### ISSUE TITLE
Occurrence records page link to species page broken

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#101]
When on an occurrence record page e.g. http://records.als.scot/occurrences/search?q=lsid:NBNSYS0000000013#tab_mapView and select the species name link at the top, next to the drop down (113 results for  SPECIES: Fratercula arctica), you are taken to a page with a load of code on it, not the species page as expected http://species-ws.als.scot/species/NBNSYS0000000013

**Comment by djtfmartin** [comment]
This has now been fixed.

**Comment by RachelStroud** [comment]
Great, thanks Dave

@EllaVogel @CEJohnston  Updated in Project Plan
