### ISSUE TITLE
Add species action framework documentation to species pages

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#102]
Can we add Species Action Framework documents http://species-ws.als.scot/species/NBNSYS0000000013 to the pages for those species? Below the map on the species page it could be good to have a box that includes a link to these pdf's, or perhaps a new tab would be better?

**Comment by djtfmartin** [comment]
This is probably information that can be added through the list tool.

**Comment by EllaVogel** [comment]
If that is something that I am able to do, I'll happily do so

**Comment by sophiathirza** [comment]
@EllaVogel is this still ongoing?
