### ISSUE TITLE
HTML tags not rendering correctly in dataset descriptions on Data Partner pages

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#103]
[http://registry.als.scot/public/show/dp0](url)

Example is the RSPB page - see dataset 11.  The italics in species names have not rendered properly. we have tried to fix manually but without success.

**Comment by djtfmartin** [comment]
This app doesnt support html tags in these fields. This support could be added though.

**Comment by RachelStroud** [comment]
If this could be added that would be great!

**Comment by djtfmartin** [comment]
this needs a priority
