### ISSUE TITLE
National Parks layer in AoLS spatial portal is showing the whole of the UK

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#104]
All the layers should show for Scotland only.
Also - it is curious that it contains Forest Parks which are not National Parks. Do you know the source for this layer?

**Comment by djtfmartin** [comment]
We need to source a layer which just contains Scottish National Parks.

**Comment by CEJohnston** [comment]
Okay.  This is another layer that was up early on but I think a Scottish one could be sourced from SNH.  I shall go and investigate and get back to you.

**Comment by CEJohnston** [comment]
Have done some research and there is no single layer for the two Scottish NPs - have uploaded to S3 the two files you need (Cairngorms and Loch Lomond sourced from Scottish Govt) to replace the existing single file. This matches the way that SEWeb handles NPs.

Have also uploaded three more layers from the Scottish Govt that need to be added to the portal: Environmentally Sensitive Areas; Nitrate Vulnerable Zones and National Scenic Areas.

**Comment by djtfmartin** [comment]
Fixed
