### ISSUE TITLE
'Visit data partner's website' link not working

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#105]
When on the Grasshopper Recording Scheme data partner page [http://registry.als.scot/public/show/dp86], and I select the 'visit data partner's website' link, it takes me to the list of data partners on the atlas, not to their URL. I think I've completed the data partner page correctly, so not sure why this is happening.

**Comment by djtfmartin** [comment]
The entered website URL was just missing a "http://", and was then treated as a relative link.
