### ISSUE TITLE
Replace UK countries layer

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#106]
I searched for occurrences in the SAC Isle of May via the Search by pre-defined area window. It returned 1273 records.  When I went to View Records via the button at bottom of page it returned only 4 records.

[http://regions.als.scot/Special%20Area%20of%20Conservation/Isle%2520of%2520May#group=ALL_SPECIES&subgroup=&from=1850&to=2016&tab=speciesTab](url)

I tried a similar search in the Cairngorms National Park and it returned 153191 records and that was the same number that came up under View Records.

**Comment by djtfmartin** [comment]
I think we need a better layer that specifies the extent of Scotland and includes all Marine areas.

**Comment by CEJohnston** [comment]
Where did this layer come from in the first place? It was one of the first layers that went up but was not by me.  A layer could be sourced from SNH - but did it come from them originally?

**Comment by djtfmartin** [comment]
This layer wasn't sourced from SNH.

**Comment by CEJohnston** [comment]
OK - I'll get these boundary layers resourced from SNH.

**Comment by CEJohnston** [comment]
Hi - have just uploaded SNH's version of the SAC layer to the S3 server - could the layer be uploaded to the Atlas and tested to see if it will work?

**Comment by CEJohnston** [comment]
Have just uploaded a layer called 'Countries with sea areas' for masking by  country - maps the country areas out to the EEZ - one polygon per country.  Can you test it and see if it works? Thanks.

**Comment by djtfmartin** [comment]
The layer looks great Christine. Thanks a stack !!

I'll do more testing with it and try and get it into the Atlas.

**Comment by CEJohnston** [comment]
Brilliant - glad to have got it done before the holidays - if it does need
tweaking let me know.

Christine Johnston
NBN Scottish Liaison Officer
tel: 07342254589
email: c.johnston@nbn.org.uk

NBN website: www.nbn.org.uk
NBN Gateway: http://data.nbn.org.uk
NBN Atlas Scotland: www.als.scot

*NBN Trust *- Registered in England and Wales - Company no. 3963387 -
Registered charity no. 1082163
Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL

**Comment by djtfmartin** [comment]
This is done
