### ISSUE TITLE
Enable the grid display in the spatial portal

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#107]
Would be good to be able to map site boundaries (protected areas and admin) with mapping of species styled by Ordnance Survey grid ref.

**Comment by djtfmartin** [comment]
If i follow correctly, this is possible in the spatial portal. Perhaps need more explanation.

<img width="1402" alt="screenshot 2016-06-22 16 02 06" src="https://cloud.githubusercontent.com/assets/444897/16271629/b16a444c-3892-11e6-9d3e-ee25192c42e4.png">

**Comment by CEJohnston** [comment]
I didn't know we could do that! Your map is aggregating by 10k square and mapping by point.  What I was thinking of was showing the records mapped by actual grid ref, as you can on the interactive map, but enabling the site boundary to be shown as well.  So if the grid ref of a set of records was NT123123 you would see the square rather than a point.

![image](https://cloud.githubusercontent.com/assets/18594564/16273241/c7fa6934-3898-11e6-8eaf-afa5b21801df.png)

**Comment by djtfmartin** [comment]
OK. So i think the requirement is to enable the grid display in the spatial portal. The tool above is a simple mapping tool with more advanced functionality being served by spatial portal (spatial.als.scot). The spatial portal allows the loading of regions etc

**Comment by CEJohnston** [comment]
Yes - I thought so - is that doable and will it take a long time? 

Users do like to see records mapped by grid square rather than point as a point implies a false precision. Being able to combine this with at least the boundary and admin layers would be good.

**Comment by djtfmartin** [comment]
Added an estimate of 3 days.

**Comment by EllaVogel** [comment]
#131 #119

**Comment by CEJohnston** [comment]
I think we could do with a discussion about grid mapping and what we want from it before we proceed with enhancement. The appearance of the resulting grid also relates to #117 - I think if OSGB36 was used as the base map the grid would appear straight as opposed to angled (or projected).

**Comment by djtfmartin** [comment]
thanks @CEJohnston  - might be worth doing that discussion over email. Adding the grid display to the SP and changing projections are 2 separate tasks. Switching to OSGB36 for display could be straightforward but could create quite a few issues.

**Comment by djtfmartin** [comment]
This is done and deployed to a dev server. Still requires some more testing.

**Comment by djtfmartin** [comment]
This is done and deployed to production ALS. Please test and re-open if theres issues.

**Comment by RachelStroud** [comment]
Fantastic!!  We will get testing, and get friendly testers to test too!

@CEJohnston @EllaVogel  Updated in project plan
