### ISSUE TITLE
Web services text needs editing/correcting

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#109]
Web services text - final paragraph after 'You may also use Google maps,....' does not look quite right.  How should it read? I am unclear what it should say.
Once text agreed can we update this or is it Red Paint?

**Comment by djtfmartin** [comment]
This should be editable via wordpress  - so yes you can update this.

**Comment by CEJohnston** [comment]
Thanks. Does the following wording for the final para make sense?

You may also use Google maps to embed a map in your website. Then you can map spatial layers from other sources along side data from the atlas system to tell a particular story.
All of this is coming soon, so watch this space…

**Comment by djtfmartin** [comment]
Looks good to me.
