### ISSUE TITLE
Use Ordnance Survey open source satellite data - layer

### ISSUE THREAD

**Issue by djtfmartin** [nbnuk/nbnatlas-issues#11]
Need to organise licencing

**Comment by sophiathirza** [comment]
@djtfmartin is this still required?

**Comment by djtfmartin** [comment]
its still outstanding. im not sure of the priority.

@CEJohnston has been looking into this.

**Comment by CEJohnston** [comment]
The OS does not offer open source satellite data. Suggest this is closed.
