### ISSUE TITLE
Add more fields to record downloads

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#111]
Suggestion from NBN Forum copied and pasted below. This needs discussion

"Here are two possible solutions. 
One – have two download links on the site, one giving a basic download with the following fields (those marked **\* are not available at present, but where datasets allow comment and altitude and any other fields that are currently viewable via G5 they MUST be included in ALS downloads – anything less would be yet another diminution in the quality of the accessible data):
Scientific Name
Vernacular Name
locality
OSGR***
Collector
Determiner***
Event Date - parsed
Basis Of Record - processed
Sex
Sample altitude***
Observation comment***

Kingdom - matched
Phylum - matched
Class - matched
Order - matched
Family - matched
Record ID
Match Taxon Concept GUID
Matched Scientific Name
Taxon Rank - matched
Vernacular Name – matched

Two – keep the current single link, but rearrange the fields so that folk who are only interested in basic fields do not have to select these from their current positions scattered across the 41 columns (soon I hope to be at least 45 columns) in the full download.  I suggest a suitable format here.
The two batches of fields above followed by
Genus - matched
Species - matched
Collection Code
Latitude - original
Longitude - original
geodetic Datum
Latitude - processed
Longitude - processed
Coordinate Uncertainty in Metres - parsed
Country - parsed
State - parsed
Year - parsed
Month - parsed
Taxon identification issue
Location Quality
Data Resource ID
Data Resource Name
Occurrence status assumed to be present
Country inferred from coordinates
Latitude Longitude calculated from grid reference
First of the month
First of the year
Name not in national checklists
Precision / range mismatch
"
[http://forums.nbn.org.uk/viewtopic.php?pid=25010#p25010]

**Comment by CEJohnston** [comment]
I would suggest we go for option 2.  I think option 1 is complicating matters. The fact the grid ref is not downloaded has been noted to SNH (Roddy) by some recorders - fixing it is high priority.

**Comment by djtfmartin** [comment]
Minor update to this. Ive added grid references to downloads.

Downloads now include the full reference, 100k, 10k, 2k and 1k grid references.

**Comment by RachelStroud** [comment]
Thanks Dave.  Do you need any more guidance on this one?

@EllaVogel  @CEJohnston  Minor Update added to Project Plan but not closed yet

**Comment by davidgenney** [comment]
Sorry for butting into this thread but I notice that some of the fields are still not available in download. Are you still planning to add them e.g. Identifier/Determiner? If not I'd be happy to provide some justification for adding them if this helps?

**Comment by sophiathirza** [comment]
I have written a requirements document (on Teams) for changes to the simple format spreadsheet download. There is an accompanying xlsx file listing the fields and possible order.

**Comment by sophiathirza** [comment]
The simple format download has been updated. 

Identifier/determiner has been included. I am going to close this now and we can start another issue for any further updates.
