### ISSUE TITLE
Make corrections to grammar in data quality tests table

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#114]
Received from a user: I landed on the quality report page, e.g.  http://records.als.scot/occurrences/4dd … 69c07bb4e9 .  This label ‘Show/Hide 50 tests that havent been ran’ may perhaps be Strine, but it ain’t English (or even Scots).  Please correct it.

[http://records.als.scot/occurrences/4dd58720-ddbf-4be3-9385-a869c07bb4e9](url)

Suggested correct version: Show/Hide 50 tests that have not been run

**Comment by djtfmartin** [comment]
this has been fixed

**Comment by RachelStroud** [comment]
Thanks Dave
