### ISSUE TITLE
Fix broken links in the 'Additional political boundaries information table'

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#115]
Fix links in the table 'Additional political boundaries information'. 

Change the table title to 'Additional geographical and environmental information'

[http://records.als.scot/occurrences/4dd58720-ddbf-4be3-9385-a869c07bb4e9](url)

**Comment by djtfmartin** [comment]
these are fixed. they now link to the metadata page for the layer

**Comment by RachelStroud** [comment]
Thanks Dave. 

Rachel
