### ISSUE TITLE
Does screening for sensitive species remove recorder and determiner name?

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#116]
Observation from a user: 

"This link shows both observer and determiner names, and comments: [http://records.als.scot/occurrences/50759169-1be4-4f80-8413-9af6308395fd](url) 
This one (Badger) has none: [http://records.als.scot/occurrences/96084559-d215-4688-9a55-22b7109cea07](url)
This one, reached by the same route as the one immediately above, has all: [http://records.als.scot/occurrences/a1d31a96-7961-44ca-8645-806d03120dae](url)

Both the relevant datasets should allow obs and det names and comments to be displayed.  The fact that Badger is on the SNH sensitive species list should not stop release of these three fields.  That file is at http://www.snh.gov.uk/docs/A1694903.xls  The only listed sensitivity for Badger is ‘Location of setts’ at ‘Below 1km^2’."

**Comment by djtfmartin** [comment]
The removal of the collector information for sensitive records is intentional to avoid locations being derived from other collection events involving an individual. I don't see a way around this, so Im closing this issue.

**Comment by CEJohnston** [comment]
I think we are going to have to discuss this more widely on Wednesday.  It goes with the sensitive species discussion we are having with Jo.  I think our data partners may want it to be otherwise but it's not my call!
