### ISSUE TITLE
Add support for OSGB36 projection base maps

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#117]
Comment received from a user:
If you try to define your own rectangle at http://records.als.scot/search#tab_spatialSearch, and then call up a species map on the OS grid, e.g. http://records.als.scot/occurrences/sea … ab_mapView you see that the OS grid squares are not parallel to the rectangle’s sides.  Rectangle drawn on lat/long.  Records plotted on OS grid.  

It might show you what you want, but it is not a pretty sight.  
http://records.als.scot/occurrences/search?q=*%3A*&qc=cl2%3AScotland&wkt=POLYGON((-5.100708603858948+58.62061134871613,-4.199829697608948%2058.62061134871613,-4.199829697608948%2058.055479686771335,-5.100708603858948%2058.055479686771335,-5.100708603858948%2058.62061134871613))#tab_mapView

Comment from CJ: I think this is a projection issue? Can anything be done to make it look better?

**Comment by djtfmartin** [comment]
This is a projection issue (OSGB36 projection vs Spherical mercator). I dont see want can be done, but open to ideas.

**Comment by CEJohnston** [comment]
Just a thought - if OSGB36 was adopted for the base map (using OS Open layers) I think the grid would appear straight as opposed to angled (or projected). Would that not be worthwhile as we use OSGB references as our spatial reference system? Think this might need discussion.

**Comment by sophiathirza** [comment]
@CEJohnston @djtfmartin is this still required?

**Comment by djtfmartin** [comment]
Its hasnt be done. Whether its required is a question for @JoJudge and the user groups.

**Comment by JoJudge** [comment]
This was ruled out due to cost. It may be worth us taking another look at it at a later date, but isn't currently a priority.
