### ISSUE TITLE
Downloading a grid map visualisation not working

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#119]
Downloading a grid map visualisation not working - I get a dot map when download a grid map.
For example a map of squirrels at http://records.als.scot/occurrences/search?q=lsid%3ANBNSYS0000005108&qc=cl2:Scotland&fq=year%3A%222015%22#tab_mapView downloaded as 
![grid map aug](https://cloud.githubusercontent.com/assets/18594564/17336658/16ae7b20-58d7-11e6-9531-6c319591884d.jpg)
Is the grid map enabled for download?

**Comment by djtfmartin** [comment]
Not yet. I added the grid display late on just before the launch. This is one issue along with others (e.g. grid display in SP) we need more time to tackle. Marking as an enhancement as this is new functionality and its specific to NBN/UK.

**Comment by CEJohnston** [comment]
Thanks for explaining that.

**Comment by djtfmartin** [comment]
Map downloads are now available in the Spatial portal. There is a link from the records.als.scot search to the SP

<img width="1438" alt="screenshot 2016-10-25 10 26 09" src="https://cloud.githubusercontent.com/assets/444897/19680414/775d7f72-9a9d-11e6-8be6-488e93acb8a2.png">

**Comment by RachelStroud** [comment]
Fab, thanks Dave

@CEJohnston @EllaVogel  Updated in Project Plan

**Comment by andymus** [comment]
Hi Dave, just had a go with this. On spatial portal, had mapf of Lagopus lagopus (Red Grouse) with responsive resolution. I was zoomed in to level of Scotland, showing 10km sqs. I clicked on Map Options, then download map. But the resulting jpg showed 100km sqs instead. Hope that's useful

Cheers, Andy Mus.
