### ISSUE TITLE
Sensitive data not displayed in map grid display

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#120]
A user selected records for red kite and in the species description they are mapped (probaly to 10k?) but in the interactive map they are not mapped [http://records.als.scot/occurrences/search?q=lsid:NHMSYS0000530482#tab_mapView](url). 
Is this expected behaviour?

**Comment by djtfmartin** [comment]
This is now fixed.

e.g.  http://records.als.scot/occurrences/search?q=lsid:NHMSYS0000530170#tab_mapView

**Comment by RachelStroud** [comment]
Great, you have made so much progress Dave!  Thanks!

@EllaVogel @CEJohnston  This is updated in project plan
