### ISSUE TITLE
Searching for single species in Scotland in spatial portal not working

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#122]
You can search for a species in a particular polygon - say an NNR - and for the World - and you get a layer up - but you get no returns if you define the area as Scotland.  Please can this be fixed as a priority, thanks.

**Comment by djtfmartin** [comment]
I'll probably just remove this option as the data is already restricted to Scotland (hence the filter is redundant).

**Comment by CEJohnston** [comment]
I can see you have removed the Scotland filter but I am not sure it was redundant.  It now means you need to be zoomed out to beyond Scotland to get data for all of Scotland as 'Current extent' when zoomed in clips the data to the visible area.  I think it's necessary for users to be able to make a 'Scotland' search so they know what they are getting (even when they are zoomed in) - would you need a file sourced to help with this? 

Also 'Current extent' when zoomed out means something different as it only gives you Scotland data rather than data from the whole area covered.  I think this will need to be explained to the user as in the future they may expect to see data from all the UK countries that are visible.  Has the relationship between the spatial portals for the different countries been discussed or do we still need to scope it out?

**Comment by djtfmartin** [comment]
"World" - effectively gives the Scotland filter as the data displayed is restricted to Scotland, although a rename from "World" might be a good idea.

As far as relationship between spatial portals or if we need a spatial portal for each country - needs more discussion.

**Comment by CEJohnston** [comment]
Just noticed in the spatial portal you get different spatial filtering options depending on what you want to upload.  If wanting to add 'All species' you can only choose 'Current extent' or a chosen polygon.  If wanting a single species you get the option of 'Current extent' 'Scotland' [not working] 'World ' or a chosen polygon. I suggest the options should match and that as 'World' actually gives 'Scotland' could 'World' be renamed 'Scotland'?

Have noted the need for discussion about spatial portals.

**Comment by djtfmartin** [comment]
This is now fixed. I've removed the "World" filter and "Scotland" is now working as described above.

**Comment by RachelStroud** [comment]
Thanks!
