### ISSUE TITLE
Bug in the search results sort order drop down menu

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#123]
The 'Sort by' drop down (on the screen with the results of a species search) does not work so can't sort by anything other than 'best match'

[http://species.als.scot/search?q=Cladonia&fq=&dir=&offset=0&max=10](url)

**Comment by djtfmartin** [comment]
I think this is now fixed.

**Comment by RachelStroud** [comment]
Great!
