### ISSUE TITLE
Potential bug in data released with a sensitive species record

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#124]
Potential bug in data released with a sensitive species record in the Additional political boundaries information at the bottom of the screen. Reported by RSPB - please could it be looked in to ASAP?

Eg Common scoter breeding records are sensitive. If you view a record a 1km grid ref and sometimes the name of a SSSI will be included. I am not sure if the grid ref is the record ref but together with the SSSI name the location of the nest is narrowed down. I think all the location information and the 1km grid ref needs to be removed for a sensitive record.

[http://records.als.scot/occurrences/4b77dd16-e966-4272-ab87-fe6e9428d2a5](url)

**Comment by djtfmartin** [comment]
Sampling is done the generalised version of the coordinates, so this should be ok. Failing that, perhaps the rule needs to be more restrictive that 0.1

**Comment by CEJohnston** [comment]
Sorry - not sure I quite understand. Does that mean that the location information given is in fact based on a centroid (or similar) of the 10k square and the location names are not relevant?

**Comment by djtfmartin** [comment]
correct, they are potentially not relevant dependent on the polygon size, and the position within that polygon

**Comment by CEJohnston** [comment]
Thanks. Will pass that on to the RSPB.

**Comment by djtfmartin** [comment]
im closing this. please re-open if you think there is still a problem.
