### ISSUE TITLE
Integration status > how to change from Identified to Data Available

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#125]
Hi Dave, 

How do we change the Integration status from Identified to Data Available.

The dataset page http://registry.als.scot/datasets# has 163 Identified datasets and I believe these should be Available.

Happy to make the required changes if you could let us know the process. 
Thanks!

**Comment by djtfmartin** [comment]
Email sent to 7th Sept with instructions.
