### ISSUE TITLE
Advanced Search button

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#127]
Add advanced search button to every search page (e.g. species, location etc) this should then take you to the same advanced search page (see link)

http://records.als.scot/search#tab_advanceSearch

**Comment by djtfmartin** [comment]
Could this be an menu option in the top navigation menu ?

**Comment by EllaVogel** [comment]
Yes, I think adding an advanced search button to the top navigation bar would be a good idea

**Comment by EllaVogel** [comment]
#142

**Comment by djtfmartin** [comment]
If we are going with the navigation bar solution, this is something for the RedPaint guys.

**Comment by EllaVogel** [comment]
I've forwarded this onto Andy Watson

**Comment by djtfmartin** [comment]
i think we still need to follow up on this with Andy.

**Comment by djtfmartin** [comment]
@EllaVogel 
@JoJudge 
this is easy to add in Wordpress, we just need to give the link a name.
What do you want call it ?

**Comment by djtfmartin** [comment]
Done

<img width="1413" alt="screenshot 2017-05-07 18 51 58" src="https://cloud.githubusercontent.com/assets/444897/25783582/4e1159a2-3356-11e7-8c6f-5c36aa4429fd.png">
