### ISSUE TITLE
Make Advanced Search button Clearer

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#128]
Make advanced search button on occurence page (currently above quick search) clearer

http://records.als.scot/occurrences/search?q=puffin#tab_mapView

**Comment by sophiathirza** [comment]
@djtfmartin @EllaVogel is this still required?

**Comment by djtfmartin** [comment]
Im not sure. We added an nav menu element

<img width="1440" alt="screenshot 2017-09-13 13 50 23" src="https://user-images.githubusercontent.com/444897/30378278-95cb4980-988a-11e7-90c8-d80b45659c9a.png">

**Comment by sophiathirza** [comment]
@JoJudge is the position of the advanced search okay? If so, I will close this issue

**Comment by JoJudge** [comment]
Yes, close the issue.
