### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#129]
Improve the search to work both at genus level and full species – A user experimented using Hygrocybe

**Comment by djtfmartin** [comment]
This seems to work ok for records and species.

<img width="1440" alt="screenshot 2016-09-05 14 04 46" src="https://cloud.githubusercontent.com/assets/444897/18248695/beae684e-7371-11e6-88aa-9fe4459d5c6b.png">
<img width="1440" alt="screenshot 2016-09-05 14 04 10" src="https://cloud.githubusercontent.com/assets/444897/18248696/beb160a8-7371-11e6-80bf-44daaca08b4c.png">

**Comment by RachelStroud** [comment]
Can we close this?  @EllaVogel  @CEJohnston have you any more examples (from the Forum etc) where people were struggling with this?

**Comment by CEJohnston** [comment]
Highland reported a problem (issues 291 and 292) as did Ron McBeath in issue 281.  In the Gateway you can search quite quickly by putting in the genus and just the start of the species part and the match will come up at the top of results - as far as I can see the Atlas does not do that in quite the same way.  If you see and pick the full name from the search drop down in the Atlas it does work but for some reason I could not get Ron's example to appear at the top of the results (Puccinia vincae).

**Comment by djtfmartin** [comment]
I think we can close this now that the autocomplete is working. Thoughts ?

**Comment by RachelStroud** [comment]
@CEJohnston are you happy for this to close.  Seems ok to me now

**Comment by djtfmartin** [comment]
closed. Please reopen if required.

**Comment by RachelStroud** [comment]
@CEJohnston  @EllaVogel  if you hear people feeding back that this is still broken, we can reopen. 

Otherwise Thanks @djtfmartin
