### ISSUE TITLE
Development of simple taxon distribution Grid Map

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#131]
Below the Map on Taxon Page add another button (below 'Interactive Map' and 'View records') to say 'View 10km Grid Map'.  

Takes user to a new page which is a simple, printable Grid Map with the same functionality as the NBN Gateway 10km grid map (see link for details of functionality to be replicated)

https://data.nbn.org.uk/Taxa/NHMSYS0000530671/Grid_Map

**Comment by EllaVogel** [comment]
Following discussion, we've decided that the 'interactive map' button will now take you to the Spatial Portal, with 10km grid squares. This removes the need to add an extra link which could cause confusion (and create extra work)

**Comment by djtfmartin** [comment]
@RachelStroud @EllaVogel 

The default grid rendering is "variable grid" when a user selects to load a species layer. Should we change this so its consistent ? I think it might be confusing for the "nteractive map" link to load 10k grid squares by default and the "Add to map" to chose a different rendering.

**Comment by EllaVogel** [comment]
I'm not sure really- I think that it may potentially confuse people more to think that they can only see records at 10km resolution (if they don't play around with the buttons), but I agree that consistency is generally good.
Not sure that's helpful.
I also wonder if the text for the button needs to be something like '10km grid map' rather than 'interactive map' if it's going to the spatial portal?

**Comment by djtfmartin** [comment]
This is now done - but it linking through to the variable grid. Going to mark as closed (as we havent got a resolution to the above discussion). We can reopen if we want to change the default resolution.

**Comment by RachelStroud** [comment]
Great, happy for this to be the default for now. 

@EllaVogel  and I have written an article for the NBN Blog which introduces some of this new functionality to start educating folk
