### ISSUE TITLE
Interactive Map  > Colour by point

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#134]
Change wording of “Colour by: 'none'” to "Colour by:  'point'" in the drop down on the interactive map

![image](https://cloud.githubusercontent.com/assets/7521189/17661980/54399cd8-62da-11e6-9921-f03c22d18fb5.png)

**Comment by djtfmartin** [comment]
Done. I changed to include option groups for grids and points, to (hopefully) make it all a bit clearer.

<img width="798" alt="screenshot 2016-10-24 17 12 22" src="https://cloud.githubusercontent.com/assets/444897/19653631/269ec22a-9a0d-11e6-86e3-dc3b85940f00.png">

**Comment by RachelStroud** [comment]
This looks brilliant Dave. 

I especially love the Display as Licence.... What great progress! Thanks

@EllaVogel @CEJohnston  Updated in Project Plan
