### ISSUE TITLE
Explore > Regions > Site Report > remove download option 'Field Guide'

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#135]
Remove option to download 'Field Guide' from dropdown option in 'Download Records' wizard when on a Site report. 

http://regions.als.scot/Special%20Area%20of%20Conservation/Achnahaird#group=ALL_SPECIES&subgroup=&from=1850&to=2016&tab=speciesTab

![image](https://cloud.githubusercontent.com/assets/7521189/17662030/9df14df8-62da-11e6-9419-34d33f94bd2e.png)

**Comment by djtfmartin** [comment]
this is fixed. the link now goes through to the download wizard
