### ISSUE TITLE
Enable search for Grid Ref in Explore your Area search box,

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#136]
Enable search for Grid Ref in Explore your Area search box,

Add text to say this is possible to the right of the search box where it currently says "E.g. a street address, place name, postcode or GPS coordinates (as lat, long)"

![image](https://cloud.githubusercontent.com/assets/7521189/17662813/3a5d0268-62e0-11e6-90d0-8cf2f5f0868e.png)

**Comment by djtfmartin** [comment]
This is now done and deployed

<img width="1236" alt="screenshot 2016-10-26 16 30 09" src="https://cloud.githubusercontent.com/assets/444897/19732708/89cf1b82-9b99-11e6-895d-6515d19261ce.png">

**Comment by RachelStroud** [comment]
Excellent, this is a great development Dave. 

Nice one! 

@EllaVogel @CEJohnston  I have updated project plan
