### ISSUE TITLE
Data and Partners > Search Atlas Datasets > 'Sort by' dropdown not working

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#137]
'Sort by' drop down not working 

http://registry.als.scot/datasets#sort=type  

![image](https://cloud.githubusercontent.com/assets/7521189/17662891/b1b512f6-62e0-11e6-8714-df9b49c29427.png)

**Comment by djtfmartin** [comment]
this is fixed.
