### ISSUE TITLE
Search for Atlas Dataset > enhance sort functionality

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#139]
Enable datasets to also be sorted by 'Date last updated' and 'Data partner' name.

http://registry.als.scot/datasets

![image](https://cloud.githubusercontent.com/assets/7521189/17663188/9dc3be9e-62e2-11e6-93bd-2d5b99e94d0b.png)

**Comment by sophiathirza** [comment]
Linked to #140 and #141

**Comment by c-van-dierkson** [comment]
ok to close
