### ISSUE TITLE
Search for Atlas Dataset > add extra column showing 'date last updated'

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#140]
Add an extra column in the list of Atlas datasets showing 'date last updated' next to each Dataset

http://registry.als.scot/datasets

![image](https://cloud.githubusercontent.com/assets/7521189/17663222/db56a226-62e2-11e6-9d94-061bdf8a988d.png)

**Comment by c-van-dierkson** [comment]
ok to close
