### ISSUE TITLE
Search for Atlas Dataset > add extra column showing 'Data Partner' name

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#141]
Add an extra column showing 'Data Partner' name next to each Dataset

http://registry.als.scot/datasets

![image](https://cloud.githubusercontent.com/assets/7521189/17663477/9f1b13c6-62e4-11e6-8d71-3d4ebe706f78.png)

**Comment by sophiathirza** [comment]
@djtfmartin this is correct on the Atlas, can I close this issue?

**Comment by sophiathirza** [comment]
sorry, just found the correct search. This is still outstanding.

**Comment by c-van-dierkson** [comment]
ok to close
