### ISSUE TITLE
Interactive Map  > Add multiple years

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#145]
Develop functionality to be able to select multiple years on the Interactive Map so that you could select multiple distribution maps with either selected years or selected date periods e.g. 2005-2010, 2010-2015 etc. 

At the minute you appear to be only able to look at one year, one decade or everything at once.  

[RS Comment - this functionality is very similar to the NBN GatewayV grid map Issue: #131 ]

![image](https://cloud.githubusercontent.com/assets/7521189/17664346/4c2fe716-62eb-11e6-8f6b-5cc6e2a6ae83.png)

**Comment by djtfmartin** [comment]
Perhaps we need some help materials on this, but users can do this with the current system.

Click "Choose more"

<img width="1208" alt="screenshot 2016-09-05 14 34 19" src="https://cloud.githubusercontent.com/assets/444897/18249414/efd67638-7375-11e6-9543-7bf03c73c7b1.png">

and then

<img width="648" alt="screenshot 2016-09-05 14 34 30" src="https://cloud.githubusercontent.com/assets/444897/18249421/0292fa8a-7376-11e6-9795-5d431d3de2cd.png">

Closing. Please reopen if i've misunderstood the requirement.

**Comment by djtfmartin** [comment]
More detail required here.

**Comment by djtfmartin** [comment]
Closed. Another issue  about prioritising the year filter is here #155.

**Comment by RachelStroud** [comment]
Can the year filter also have the option to have multiple years as well as just one year?
