### ISSUE TITLE
Dataset metadata > Link to a temporal distribution graph

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#147]
Include a graph on the dataset metadata showing the temporal distribution of the data holdings within the dataset such as on the NBN Gateway here: https://data.nbn.org.uk/Datasets/GA001194

http://registry.als.scot/public/showDataResource/dr454

**Comment by sophiathirza** [comment]
@djtfmartin is this still required? I know that there are date graphs on the species pages.

**Comment by c-van-dierkson** [comment]
Jo confirms to close.
