### ISSUE TITLE
Locations > Explore by predefined area > add a search box

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#152]
Add a search box to the 'Search by Pre-defined area' page to search from the pre-defined search names

http://regions.als.scot/#rt=Special+Area+of+Conservation

**Comment by djtfmartin** [comment]
Nice idea. Wonder if this is necessary in short term. The general site search will cover all regions.

e.g. http://species.als.scot/search?q=Airds+Moss
