### ISSUE TITLE
Locations > Search by Polygon > Add a user defined buffer to boundary

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#153]
Add a function for the user to decide if they want records 'completely within' the boundary or 'within and overlapping'. 

This should apply to the polygon tool, and also the predefined areas and features on the NBN Gateway V site reports (https://data.nbn.org.uk/Reports/Sites/GA000346GA000346BAD2640303/Groups)

![image](https://cloud.githubusercontent.com/assets/7521189/17667145/89b9b4bc-62fb-11e6-8463-1e8d9d894bee.png)

http://records.als.scot/occurrences/search?q=*%3A*&qc=cl2%3AScotland&wkt=POLYGON((-4.0491485595703125+57.124314084296195,-4.5325469970703125%2056.8729956637964,-3.961257934570312%2056.77680831656842,-4.0491485595703125%2057.124314084296195))#tab_mapView

**Comment by djtfmartin** [comment]
This is a major enhancement.

**Comment by c-van-dierkson** [comment]
@sophiathirza Do we have any more information on this do you know?

**Comment by sophiathirza** [comment]
@c-van-dierkson this relates to the polygon to polygon searches that Reuben has been looking at the feasibility of adding to the Atlas. This issue could probably be closed as there is a trello card for it.
