### ISSUE TITLE
Occurrence records > customise filters - default facets

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#155]
We need to make 'customise filters' more obvious and intuitive for a user to access and use.  

I suggest that we have 'Year', 'Species' and 'Licence' as standard filters which are always visible on the left hand panel. 

In addition, when you select “year” from the “customise filters”, the left hand panel should appear expanded as currently it looks like nothing has happened because, before you can select the specific year from the layer list you first have to select the arrow next to “occurrence” to see this.  

![image](https://cloud.githubusercontent.com/assets/7521189/17667326/651cc6a2-62fc-11e6-85d3-832641013428.png)

http://records.als.scot/occurrences/search?q=*%3A*&qc=cl2%3AScotland&wkt=POLYGON((-4.0491485595703125+57.124314084296195,-4.5325469970703125%2056.8729956637964,-3.961257934570312%2056.77680831656842,-4.0491485595703125%2057.124314084296195))#tab_recordsView

**Comment by djtfmartin** [comment]
this is done for nbnatlas.org
