### ISSUE TITLE
Update species groups for NBN Atlas

### ISSUE THREAD

**Issue by djtfmartin** [nbnuk/nbnatlas-issues#16]

**Comment by CEJohnston** [comment]
What help is needed?

**Comment by RachelStroud** [comment]
@djtfmartin is this now done or do you still need help from @CEJohnston

**Comment by djtfmartin** [comment]
No - nothing has been done on this.

This was discussed with @EllaVogel and @CEJohnston in Nottingham back in July.

**Comment by CEJohnston** [comment]
Sorry Dave - have looked at my notes and can't find any reference.  Can't remember either. @EllaVogel can you?

**Comment by EllaVogel** [comment]
No, I'm not quite sure. What about the species groups needed updating?

**Comment by djtfmartin** [comment]
Heres the document

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/biocache-properties/files/subgroups.json

**Comment by sophiathirza** [comment]
@djtfmartin @EllaVogel what needs to be done here?

**Comment by djtfmartin** [comment]
this has been started by @CEJohnston who has made some amendments to a google spreadsheet.

**Comment by djtfmartin** [comment]
Im going to close this  - as im not aware of any required updates or ongoing work.

**Comment by CEJohnston** [comment]
I think this needs to stay open.  @EllaVogel and I worked on the list but we did not get through it completely.  We got stuck on marine species in particular. Would be good to understand more about where and how the list is used in the Atlas so we can check if there are any 'odd-looking' results from it.

**Comment by sophiathirza** [comment]
These are the taxon group from the UKSI:
[taxon_groups.txt](https://github.com/nbnuk/nbnatlas-issues/files/1531195/taxon_groups.txt)

**Comment by sophiathirza** [comment]
We have done quite a bit of work on this now, so I am going to close this issue and we can open new issues for specific problems.
