### ISSUE TITLE
Enable shapefile upload to and download from the Interactive Map

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#160]
The requested .WKT format for upload to interactive map is not easily generated from .SHP and is not familiar. Or users could be more clearly directed to spatial portal for shapefile upload

**Comment by djtfmartin** [comment]
Users can upload (import) and download (export) shapefiles already.

**Comment by sophiathirza** [comment]
@EllaVogel is this still required?
