### ISSUE TITLE
Enable user to have two tabs open to the spatial portal at one time

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#161]
Users have requested to be able to have two separate maps open in the spatial portal at one time. Currently, if you open a new tab or new browser window and open the spatial portal, your current map is replicated.

**Comment by djtfmartin** [comment]
We are currently working on a re-write on the SP. We wont be able to support this until this is done.

**Comment by EllaVogel** [comment]
OK, it's good to know that it'll be possible in the future
