### ISSUE TITLE
Shapefile import into spatial portal: the loading box doesn’t disappear

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#162]
When you import a shapefile to the spatial portal, the loading box doesn’t seem to disappear until you press hide, it still looks like it’s loading when it’s not, it actually loads really quickly.

**Comment by djtfmartin** [comment]
is this still the case ?

**Comment by sophiathirza** [comment]
@EllaVogel is this still a problem?

**Comment by djtfmartin** [comment]
closing.  please reopen if its still a bug
