### ISSUE TITLE
Infinite loop of suggested species options triggered when using report a sighting.

### ISSUE THREAD

**Issue by studio4** [nbnuk/nbnatlas-issues#169]
An infinite loop of suggested species options triggered when using report a sighting.

How to reproduce:

Visit Report a Sighting (http://sightings.als.scot) then set location, click on "species suggestion tool" (after location is set) then on a "species group" e.g. "mammals" the panel underneath then enters an infinite loop of lazy load AJAX requests to http://records-ws.als.scot/occurrences/search.json?callback=[...]

**Comment by EllaVogel** [comment]
I see the issue here. However, we have disable all links to the 'report a sighting' page for now, so this issue should be low priority for now.

Good to have it logged though, thanks for the comment

**Comment by djtfmartin** [comment]
the function has been removed.
