### ISSUE TITLE
Bug in Search Box: 'Blackbird'

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#172]
If I type "Fox" or "Red Fox" into the search boxes, I can't get to information about this species. I can only get to it if I know it's Vulpes vulpes, or one of 10 Gaelic (?) names. 

The name "Red Fox"  is in the UKSI, but for some reason it doesn't seem to be being picked up.

**Comment by djtfmartin** [comment]
this is fixed in nbnatlas.org

**Comment by EllaVogel** [comment]
Hi Dave, You can now search by common name 'fox' but the English name doesn't appear under the 'names' tab on the fox species page https://species.nbnatlas.org/species/NHMSYS0000080188#names

**Comment by GiselleSterry** [comment]
Here's another. Blackbird
Do a species search on Blackbird and you won't find the common one.
https://forums.nbn.org.uk/viewtopic.php?id=6823

**Comment by djtfmartin** [comment]
@GiselleSterry  Can we reproduce ?

**Comment by GiselleSterry** [comment]
@djtfmartin 
[no blackbirds.docx](https://github.com/nbnuk/nbnatlas-issues/files/933263/no.blackbirds.docx)
Just done search in species - screen shot attached - no common blackbirds.

**Comment by DuncanRowland** [comment]
All the common names appear to be Welsh.
https://species.nbnatlas.org/species/NHMSYS0000530674#names

**Comment by sophiathirza** [comment]
Blackbird and Common Blackbird have been added to the UKSI as common names, so this should be corrected when we update the species inventory.

**Comment by sophiathirza** [comment]
Blackbird and common blackbird are now searchable in the Atlas. But the common name, as shown on the Atlas, are often not the English version. This is another issue, so I am going to close this issue.
