### ISSUE TITLE
Contributing Organisations need to be clearly flagged/acknowledged

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#173]
Develop functionality for 'contributing' organisations to be flagged up/attributed appropriately when data provider is a coordinating organisation supplying data on behalf of others (such as BRC)

http://forums.nbn.org.uk/viewtopic.php?pid=25903#p25903

**Comment by sophiathirza** [comment]
@GiselleSterry is this still to be done?

**Comment by GiselleSterry** [comment]
Sorry @sophiathirza not sure what this is about. @EllaVogel may be able to assist.

**Comment by CEJohnston** [comment]
I think this is about dataset metadata - the information is there in BRC metadata - but our metadata template is not structured in a searchable way.

**Comment by c-van-dierkson** [comment]
Jo confirms to close. Details merged with 512.
