### ISSUE TITLE
Taxonomy web service incorrect common names for Oethanthe

### ISSUE THREAD

**Issue by burkmarr** [nbnuk/nbnatlas-issues#176]
Oenanthe is both a genus of flowering plants and a genus of birds. The common name for the plant genus has been incorrectly assigned to the bird. Easy to fix if it's a one-off but worth considering how this arose in case it reflects a more general problem in the assignment of common names in the web service or the underlying DB.

Plant: https://species-ws.nbnatlas.org/search?q=&fq=guid:NHMSYS0000461141

Bird:  https://species-ws.nbnatlas.org/search?q=&fq=guid:NHMSYS0000066915

**Comment by djtfmartin** [comment]
This is fixed.
