### ISSUE TITLE
Visability issue between IE and Chrome

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#177]
![ie chrome comparison](https://cloud.githubusercontent.com/assets/26628372/24253224/9dc93f48-0fd7-11e7-98a1-fd48f18d49d4.png)

![biodiversity screenshot](https://cloud.githubusercontent.com/assets/26628372/24253909/7664521a-0fd9-11e7-8dad-62449bda2718.png)

Feedback from a user; I just wanted to mention that there seem to be some display issues when using Internet Explorer (which happens to be the Council’s preferred browser as it’s what certain internal things have to be run on).  Unlikely to be a priority, but just mentioning in case you weren’t aware   

Seems to affect display quality - some of the logos of data partners in scrolling banner are impossible to read and even the NBN Atlas logo at the top appears pixelated, rather than the lovely smooth clear display you get in Chrome for example.

Also, a very minor thing, but the enclosed area in the B of Biodiversity on the homepage (screenshot below) is set to opaque white rather than transparent like the rest   

It’s a little hard to see the NBN National Biodiversity Network text against certain parts of the background too, but again, not exactly a disaster!

**Comment by sophiathirza** [comment]
@SarahHyslop is this still a problem?

**Comment by SarahHyslop** [comment]
@sophiathirza I think this is now sorted, nobody esle has mentioned this since as far as I am aware.  I have tried on my PC and cant see any visibility issues with Chrome.  I cant seem to get IE to work on my PC, have you got this browser? Is the B in Biodiversity okay (see photo above)

**Comment by sophiathirza** [comment]
I checked on Microsoft Edge and it looks okay. I don't have IE. I will close and we can reopen if needs be.
