### ISSUE TITLE
Searching Area in Spatial Portal not working

### ISSUE THREAD

**Issue by JoJudge** [nbnuk/nbnatlas-issues#178]
Working through Spatial Portal user guides if Add area to map and try to use one of the options under "Searching" get this error message

![image](https://cloud.githubusercontent.com/assets/26632543/24262053/c8354330-0ff0-11e7-8aa1-60bc80518b3b.png)

**Comment by djtfmartin** [comment]
Thanks @JoJudge . This is expected behaviour if we havent indexed the records to the polygon (and the polygon is complex, lots of vertices). We have now (as of last night).

Can you remember which area you used ?

**Comment by JoJudge** [comment]
@djtfmartin I used the office address 32 Stoney Street Nottingham

**Comment by djtfmartin** [comment]
This is working, its lacking an auto zoom to selected new area - a feature of the spatial portal.
