### ISSUE TITLE
WMS - no way to produce maps for sub-species?

### ISSUE THREAD

**Issue by burkmarr** [nbnuk/nbnatlas-issues#179]
There doesn't appear to be a way to produced a distribution map via the WMS for sub-species, e.g. Luperina nickerlii subsp. gueneei (NBNSYS0000006458).

**Comment by djtfmartin** [comment]
Thanks @burkmarr 

Suggest using the taxon version key like so q=lsid:NBNSYS0000006458

https://records-ws.nbnatlas.org/mapping/wms/reflect?q=lsid%3ANBNSYS0000006458&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&BGCOLOR=0x000000&OUTLINE=true&ENV=colormode%3Aosgrid%3Bgridlabels%3Atrue%3Bgridres%3Avariablegrid%3Bopacity%3A1%3Bcolor%3Adf4a21&GRIDDETAIL=32&STYLE=opacity%3A0.8&SRS=EPSG%3A3857&BBOX=-2504688.5428486555,6261721.35712164,-1252344.2714243277,7514065.628545966

cc @DuncanRowland

**Comment by burkmarr** [comment]
Thanks @djtfmartin (cc @DuncanRowland). That looked like the answer to my needs, but I'm not able to use it in QGIS. QGIS' GUI interface to WMS only lists layers reported by the getCapabilities call. A user must select one of these to use in the getMap call. So although I can use q=lsid:NBNSYS0000006458 in the getCapabilities call that doesn't return the layer 'ALA:occurrences' - I can only select from the returned layers and these only go down 'species:#species-name#' (i.e. not subspecies). Neither can I get round it by coding the calls in python (my ultimate aim) because the QGIS python API to WMS also seems to insist that the layers parameter refers to a layer specified in the XML returned by getCapabilities.
