### ISSUE TITLE
WMS getCapabilities doesn't return expected layers for some taxa

### ISSUE THREAD

**Issue by burkmarr** [nbnuk/nbnatlas-issues#180]
Normally a getCapabilities request for a genus returns layers for all major taxonomic levels down to and including the genus, and beyond to species. For example the one below does that.

https://records-ws.nbnatlas.org/ogc/ows?q=genus:oxalis&SERVICE=WMS&REQUEST=GetCapabilities

But I noticed that for some plant genera only layers down to the phyllum were returned - nothing further, making it impossible to generate WMS layers for species in those genera. 

I've done a little testing and I found four genera where this failure occurs: Plantago, Silene, Veronica and Digitalis. These are all in the family Plantaginaceae, but I didn't test all other families.

**Comment by burkmarr** [comment]
Seems to work for Oxalis now, but not Plantago, Silene, Veronica or Digitalis.

**Comment by djtfmartin** [comment]
This is looks ok to me. Closing. @burkmarr please let us know if theres still an issue
