### ISSUE TITLE
Download CSV fieldname for Species Checklist don't match content

### ISSUE THREAD

**Issue by JoJudge** [nbnuk/nbnatlas-issues#181]
When downloading results of the Species Checklist from the Spatial Portal get this

![image](https://cloud.githubusercontent.com/assets/26632543/24299349/db3eb7f8-10a0-11e7-94f8-d690199352a7.png)

Fieldnames don't match info in the columns

**Comment by sophiathirza** [comment]
This is still a problem.

**Comment by djtfmartin** [comment]
this is fixed
