### ISSUE TITLE
BAP species list not loading in spatial portal

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#185]
I want for all species listed on the BAP list to be shown on an area of map.

In the spatial portal, I go to 'Add to map'>'species' then select 'use existing species list' and select 'Biodiversity action plan uk list of priority species'. No matter how small an area I try to apply this list to, I get an error message telling me that there are too many records in my area and to try a smaller area.

**Comment by djtfmartin** [comment]
This is now fixed.
