### ISSUE TITLE
WMS points not displayed in correct locations

### ISSUE THREAD

**Issue by burkmarr** [nbnuk/nbnatlas-issues#187]
The image below is a screenshot from QGIS showing three layers:

1. A 10 km grid
2. Green points showing the record observations downloaded from the Atlas for Peregrine Falcon (vector data).
3. The red dots are a WMS map for Peregrine Falcon generated from the Atlas web service (https://records-ws.nbnatlas.org/ogc/ows?q=genus:Falco&&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&BBOX=-595920.41243130015209317,7044496.68046787939965725,-168124.59823433827841654,7414557.44982199929654598&SRS=EPSG:3857&WIDTH=615&HEIGHT=532&LAYERS=species:Falco_peregrinus&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE)

The map in the image is projected in EPSG:3857.

The vector data appear in the correct locations, but the red dots displayed by the WMS are not in the correct locations (except on the Ilse of Man for some reason). This is a general problem - i.e. not just for Peregrine.

Rich

**Comment by burkmarr** [comment]
Sorry - i forgot to add the image. Here it is.
![atlas-wms](https://cloud.githubusercontent.com/assets/9275178/24401544/bd86c2d2-13ac-11e7-8c0b-dee10c8c2b43.png)

**Comment by djtfmartin** [comment]
i think this is an artefact of the way we deal with blurring of sensitive records.
We remove decimal places of latitude /  longitude, and its these coordinates that are used to render points. Do you see the same with a non-sensitive taxon ?

**Comment by burkmarr** [comment]
Hi David. I didn't consider that and in retrospect I used raptors in all my tests for this! That does seem to be the case - the image below for Whinchat WMS against the raw vector data looks okay.  With the NBN Gateway, where the OS grid reference system had primacy, sensitive records were 'blurred' to lower levels of precision within the national grid, so people will not be used to seeing this mismatch between blurred records and the underlying OS grid. It may take some getting used to.

![whinchat](https://cloud.githubusercontent.com/assets/9275178/24450601/61c61de0-1473-11e7-8286-2a2941db6598.png)

**Comment by djtfmartin** [comment]
Thanks @burkmarr I'll close this for now, but pass this on to as something we should include in the FAQ - somehow :)

**Comment by djtfmartin** [comment]
@CEJohnston @EllaVogel this might be worth mentioning in the FAQ or here https://nbnatlas.org/help/sensitive-species/
