### ISSUE TITLE
CSV download "Tachina fera"

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#188]
Reported  on NBN Forum http://forums.nbn.org.uk/viewtopic.php?pid=26522#p26522
By C Raper and Charlie Barnes. 

Giselle tested and got same result.

C Raper reported:
Just noticed that the CSV download option on the Search results seems to generate an enormous file (53MB) that bombs out when you try to load it into Excel. I searched for "Tachina fera" and then hit the Download button. The file seems to contain genuine search results but then just lists lots of numbers in column A.

 C Barnes:
This is by clicking the download button at the top of https://scotland-species.nbnatlas.org/s … na+fera%22
FYI - the CSV contains 3,103,979 lines all but the top 28 of which are like:

**Comment by djtfmartin** [comment]
@GiselleSterry apologies - i only tested UK Atlas.

This is now fixed on NBN Atlas Scotland
