### ISSUE TITLE
Datasets not displaying

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#189]
Records from OHBR datasets seem to have disappeared. (using NBN Atlas)

7 datasets are listed https://registry.nbnatlas.org/public/show/dp3 but only the top dataset link leads to any data. Other 6 produce no records.

**Comment by djtfmartin** [comment]
ive started the load. should be there next week

**Comment by sophiathirza** [comment]
Can this be closed now? All 7 datasets have records.

**Comment by djtfmartin** [comment]
i think so. closing
