### ISSUE TITLE
Occurrence Date Range Unsupported

### ISSUE THREAD

**Issue by DuncanRowland** [nbnuk/nbnatlas-issues#190]
Regarding forum thread: http://forums.nbn.org.uk/viewtopic.php?pid=26533

The new atlas does not support the old 'vague' notion of a recordings time stamp. In the previous version it was possible to say that a reading occurred sometime within a range of two dates, since the new version requires a single date, this data is lost.

I wonder, if it is central to the database design to have a single date for each recording, whether the old range might be calculate to a +/- Error (and the single date used to record the center of the range)?
e.g.
[Start: 2017-01-01, End:2017-01-31] -> [Date: 2017-01-16, Error: 15] (i.e. +/- days)

**Comment by djtfmartin** [comment]
We store a start and end date, and we've recently added a date precision field.
We do need to look into indexing these fields better. Apparently the newer versions of SOLR has some support built in.

So there isnt anything inherent about the Atlas that prevents it, its just something to add at some stage.

**Comment by djtfmartin** [comment]
FYI - i enabled a date precision filter yesterday, and date precision in downloads.
This is currently just the raw value provided in the original data, no parsing or interpretation.

<img width="586" alt="screenshot 2017-03-30 09 34 43" src="https://cloud.githubusercontent.com/assets/444897/24495135/26e34bee-152c-11e7-8bd7-2ed0e7faf568.png">
<img width="390" alt="screenshot 2017-03-30 09 34 49" src="https://cloud.githubusercontent.com/assets/444897/24495134/26df7e10-152c-11e7-8820-9550a3f6e5bc.png">

**Comment by sophiathirza** [comment]
There is a forum message that suggests that some records have incorrect dates after being transferred from the Gateway: https://forums.nbn.org.uk/viewtopic.php?id=6962. If only the month or year is supplied then the Atlas sets the date as the first of the month or first of January. This then incorrectly reports occurrences in January.

@djtfmartin  could this be happening?

**Comment by sophiathirza** [comment]
The graphs on the species pages do not take account for the precision of the date: https://species.nbnatlas.org/species/NHMSYS0000516186#records, thus many records with a year precision are appearing in January.

**Comment by sophiathirza** [comment]
can this be closed as we do support date ranges?

**Comment by djtfmartin** [comment]
closed. we support date ranges
