### ISSUE TITLE
Menu navigation to my profile

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#191]
I cant see a way to get to my profile. When I log in I cant get to the admin menu page which has following options. The only way is to keep logging in and out and it suddenly appears! I then have the atlas open 3 or 4 times. 
Hello Giselle !
Update your profile
View your uploaded species lists
Manage your alerts
Reset my password
Admin tools
Logout

**Comment by djtfmartin** [comment]
fixed. Separate link added.

<img width="1440" alt="screenshot 2017-03-31 16 48 04" src="https://cloud.githubusercontent.com/assets/444897/24558074/d9114ad6-1631-11e7-9ee8-d1a5c3d79ed4.png">
