### ISSUE TITLE
Text box on create account page refers to ALA

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#193]
replace reference to ALA with NBN Atlas

**Comment by GiselleSterry** [comment]
[create account ALA text.docx](https://github.com/nbnuk/nbnatlas-issues/files/910161/create.account.ALA.text.docx)

**Comment by GiselleSterry** [comment]
the privacy policy hyperlink is going to ALA's policy and not NBN Atlas terms and conditions. This needs to be changed.
Wording needs changing to 
For the NBN Atlas' policy on the collection and use of personal information see our Privacy Policy contained within the Terms and Conditions. 
Your email address will be your NBN Atlas account id. An account activation link will be emailed to the address provided. Please check your spam account or add @nbnatlas.org to your safe list.

**Comment by sophiathirza** [comment]
@ #231
