### ISSUE TITLE
Add hyperlinks to descriptions data partner pages

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#194]
would like ability to add hyper links to free text on data partner pages e.g. for further info.

**Comment by GiselleSterry** [comment]
We also want to use hyperlinks to link to NBN members page on our website. Member benefit.

**Comment by GiselleSterry** [comment]
hi @sophiathirza do you know if this is possible. Want to also add in link to data sharing certificates.

**Comment by sophiathirza** [comment]
No, it's not possible to add nicely formattted hyperlinks to these free text boxes. It's only possible to simply copy in the link, which doesn't look good.

**Comment by GiselleSterry** [comment]
Do you know if this function could be added with some programming work? Either to existing or a new box?

**Comment by sophiathirza** [comment]
Yes, it just needs a different input control and perhaps rendering of the text on the page.

**Comment by sophiathirza** [comment]
Duplicate of #103
