### ISSUE TITLE
Add Northern Ireland to Vice County Maps?

### ISSUE THREAD

**Issue by DuncanRowland** [nbnuk/nbnatlas-issues#196]
Northern Ireland is missing from the vc maps is it possible to add for these layers?
e.g.
https://layers.nbnatlas.org/geoserver/ALA/wms?service=WMS&version=1.1.0&request=GetMap&layers=ALA:county_coastal_terrestrial_region&styles=&bbox=-8.65000656908486,49.8646362819958,1.76309498389649,60.8607664486924&width=727&height=768&srs=EPSG:4326&format=image%2Fjpeg

**Comment by CEJohnston** [comment]
I have been talking to Martin Harvey at BRC about handing over management of the current VC file to to them - I shall ask him if he can supply a file for Ireland. Th British Bryological Society suggests there are Irish vice counties [http://rbg-web2.rbge.org.uk/bbs/Recording/vcmappage.htm](url)

**Comment by japonicus** [comment]
The most accurate Irish VC boundary digitisation that I'm aware of is the set compiled by Jerry Clough ( https://github.com/SK53/Irish-Vice-Counties ) which are derived from OpenStreetMap township boundaries.

**Comment by sophiathirza** [comment]
Irish VCs: https://github.com/SK53/Irish-Vice-Counties/blob/master/vice_counties/All_Irish_Vice_Counties_irish_grid.shp

**Comment by sophiathirza** [comment]
Linked to #553

**Comment by CEJohnston** [comment]
This is the only source I have found for Ireland vice-counties: [https://github.com/SK53/Irish-Vice-Counties/tree/master/vice_counties](url). 
Download zip files directly from this index - for WGS84  use file: vice_counties_wgs.zip.  There is also a version on the Irish grid if that is needed (vice_counties_osie.zip).
Before defining the other details you need can I confirm we can apply an Open Database Licence (ODbL) to it (as specified in the LICENCE file at [https://github.com/SK53/Irish-Vice-Counties](url)? This licence is not directly comparable with any CC licence.

**Comment by CEJohnston** [comment]
I think we are OK to show layers with an Open Database Licence (ODbL) as it is an open licence.  Please download the shapefiles from GitHub (as above).  The other info you need is:

Unique ID field is: guid 
Field for the county name in the key: name 

For the metadata:
Categories: Ireland; Boundaries 
Layer name: Vice Counties (Ireland) 
Licence: ODbL (Open Data Commons Open Database Licence) 
Link to licence website: https://opendatacommons.org/licenses/odbl/ 
Attribution: © 2015 Open Street Map contributors 

Link to source download and metadata page: https://github.com/SK53/Irish-Vice-Counties/tree/master/vice_counties 

Licence type ODbL is not one of the licence filters for searching - can it be added to the filters?

**Comment by sophiathirza** [comment]
Zip file name: vice_counties_wgs.zip
Shape file name: All_Irish_Vice_Counties_wgs84.shp
Layer name: Vice Counties (Ireland)
ID field: guid
Name field: name

**Comment by reupost** [comment]
Loaded as layer 133. Please add metadata as needed

**Comment by CEJohnston** [comment]
All metadata added.
