### ISSUE TITLE
UK provinces layer - needs correcting to cover all UK

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#197]
This layer is currently only covering GB - sorry did not notice until #196 started.  Please rename it 'GB countries' in the first instance.  @djtfmartin what was the original source and do you need me to source a replacement?

**Comment by CEJohnston** [comment]
Note: the layer short name is uk_state_province

**Comment by djtfmartin** [comment]
this layer has been removed and super ceded by the countries with seas layer
