### ISSUE TITLE
Duplicate Dataset

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#199]
Notified in email 31/3/17
"https://records.nbnatlas.org/occurrences/search?q=lsid:NHMSYS0020481233#tab_recordsView
It seems, on the face of it, that records are being duplicated.
Here, closer, in the Scottish Atlas
https://scotland-records.nbnatlas.org/occurrences/search?q=lsid:NHMSYS0020481233#tab_recordsView
there are really only two records

 Closer look - https://registry.nbnatlas.org/public/show/dp7 - HBRG Insect database loaded twice - appears as 5 and 6 in the list.

Not sure if this is a wider issue or a one off.

**Comment by GiselleSterry** [comment]
see also forum thread https://forums.nbn.org.uk/viewtopic.php?id=6842

**Comment by MandyHenshall** [comment]
Email dated 18.04.17 raises this again:
1)	Our Insects dataset appears twice, as https://registry.nbnatlas.org/public/show/dr965 and https://registry.nbnatlas.org/public/show/dr806.  Both appear to be identical, with 136,262 records in each.  Please delete one of them.

**Comment by djtfmartin** [comment]
This is now fixed. dr806 was deleted.
