### ISSUE TITLE
odd nomenclature associations in the species lists

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#201]
Email received - "I notice quite a lot of odd nomenclature associations in the species lists.  For example for the ground beetle Bembidion articulatum it has "accepted name Autostichidae" which is a family of moths. 

When do a search top result - 
species: Bembidion articulatum (Panzer, 1795) (accepted name Autostichidae)
Bembidion articulatum
Bembidion articulatum (Panzer, 1795)

However second result gives occurrences and clicking through to the records the taxon appears correct.

**Comment by sophiathirza** [comment]
This looks like it has been corrected. @GiselleSterry do you have the original email so that I can contact the person, thanks?
