### ISSUE TITLE
Local authority name is missing from the Atlas registration page drop down menu

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#202]
Please add 'Comhairle nan Eilean Siar' to the local authority drop down menu in the registration page  - this is the Outer Hebrides local authority name and it is missing.  

Please also check for and remove the name 'Nah-Eileanan Siar' which was included in error.

**Comment by GiselleSterry** [comment]
Also seem to be missing 'Yorkshire' counties.

**Comment by CEJohnston** [comment]
@GiselleSterry do you know which ones are missing? Just checked the supplied list and it does include Yorkshire counties.

**Comment by GiselleSterry** [comment]
@CEJohnston - this is on the create an account page 
South Yorkshire
West Yorkshire
not listed

North Yorks and East Riding are listed.

**Comment by CEJohnston** [comment]
Thanks @GiselleSterry - looks like I have missed off the Metropolitan Counties so @djtfmartin please ALSO add: Greater Manchester, Merseyside, South Yorkshire, Tyne and Wear, West Midlands and West Yorkshire

**Comment by djtfmartin** [comment]
done
