### ISSUE TITLE
Incorrect logo & black ribbon on an NBN Atlas page

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#203]
From the NBN Atlas home page if you go to 'Explore by pre-defined area' (in the 'LOCATIONS' drop down) the page you get to is correct [https://regions.nbnatlas.org/#rt=National+parks](url) but it shows the NBN Atlas Scotland logo in the top corner, along with the Scotland versions of the drop downs on the black ribbon - it should show the NBN Atlas versions.

**Comment by sophiathirza** [comment]
@CEJohnston is this still a problem? I didn't see the Scotland logo, thanks.

**Comment by CEJohnston** [comment]
This is now correct. Issue closed.
