### ISSUE TITLE
Citation information not showing on dataset pages

### ISSUE THREAD

**Issue by JoJudge** [nbnuk/nbnatlas-issues#205]
When you download data you get the citation, but its not showing on the dataset page.

Also in the citation csv file it says "...accessed through the ALA" - needs changing to NBN Atlas

![image](https://cloud.githubusercontent.com/assets/26632543/24649035/90d5526e-191d-11e7-8b81-7bc43b83b47c.png)

**Comment by EllaVogel** [comment]
Also, in the citation csv file, some of the rows have the 'rights' column blank. This seems to be where the 'More information' column is linking to a data partner page, not a data resource page (data resource links populate the 'rights' column correctly). Is there a reason that some link to data partner pages, and some to data resources?
![screenshot](https://cloud.githubusercontent.com/assets/14979912/24859547/f73854fa-1de8-11e7-902e-9976d759edd9.png)

**Comment by djtfmartin** [comment]
This is fixed.

The CSV just includes both data partners and data resources.
