### ISSUE TITLE
Some spatial layers are unavailable in the spatial portal

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#206]
When accessing the following layers in the spatial portal I am getting the 'Layer Unavailable' screen.  Layers affected are:
- [x] RSPB reserve boundary layer - RSPBreserves_UK_polygon
- [x] Priority Habitat Inventory (South) - PHI_v2_1_South
- [x] Priority Habitat Inventory (North) - PHI_v2_1_North
- [ ] Priority Habitat Inventory (Central) - PHI_v2_1_Central
- [x] Nature Conservation Marine Protected Areas - MPA_SCOTLAND

![image](https://cloud.githubusercontent.com/assets/18594564/24659439/93419130-1944-11e7-8824-98e8094dd2e7.png)

**Comment by djtfmartin** [comment]
There where problems loading these layers. Needs more investigation.

Ive disabled them for now so they arent visible in the portal

**Comment by CEJohnston** [comment]
I have sourced revised RSPB files as it is thought they are old.  I will add them to a future batch of layers for upload so pls ignore the RSPB layers that had problems.

**Comment by djtfmartin** [comment]
MPA_SCOTLAND consists of the following fields in the DBF file:
```
  Column  |            Type             |                     Modifiers                      
----------+-----------------------------+----------------------------------------------------
 gid      | integer                     | not null default nextval('"72_gid_seq"'::regclass)
 fid      | double precision            | 
 the_geom | geometry(MultiPolygon,4326) | 
```

Here are values for GID and FID

```
layersdb-# ;
 gid | fid 
-----+-----
   1 |   0
   2 |   1
   3 |   2
   4 |   3
   5 |   4
   6 |   5
   7 |   6
```

The original spreadsheet suggested using a field PA_CODE which doesn't exist in the layer. 
Hence the layer hasn't loaded properly.

@CEJohnston can you look into what data should be used with this layer ?

**Comment by CEJohnston** [comment]
Strange....these are the attributes from the attribute table viewed in QGIS.....PA_CODE appears there...

![image](https://user-images.githubusercontent.com/18594564/28831718-513747ee-76d2-11e7-94ab-0f54a753bf87.png)

**Comment by djtfmartin** [comment]
Looks like the DBF file wasnt uploaded to S3.

@CEJohnston can you upload it ?

**Comment by CEJohnston** [comment]
Done - should be there.

**Comment by djtfmartin** [comment]
MPA_SCOTLAND is now loaded.

**Comment by CEJohnston** [comment]
Thank you - its looking good!

**Comment by djtfmartin** [comment]
@CEJohnston there are some issues with the PH Central layer. Seems to be corrupt.

```
ERROR 1: Corrupted .shp file : shape 430622 : panPartStart[0] = 10252032, nVertices = 1355
ERROR 1: Corrupted .shp file : shape 430634, nPoints=3204059, nParts=1, nEntitySize=15288.
ERROR 1: Corrupted .shp file : shape 430636, nPoints=-748069785, nParts=1.
ERROR 1: Corrupted .shp file : shape 430637, nPoints=1296957473, nParts=1.
ERROR 1: Corrupted .shp file : shape 430640 : panPartStart[0] = -1230664428, nVertices = 5
ERROR 1: Corrupted .shp file : shape 430642, nPoints=1523908642, nParts=1.
ERROR 1: Corrupted .shp file : shape 430644, nPoints=49, nParts=-205586431.
ERROR 1: Corrupted .shp file : shape 430646, nPoints=397583, nParts=1962934273.
ERROR 1: Corrupted .shp file : shape 430648, nPoints=45549, nParts=-822149118.
ERROR 1: Corrupted .shp file : shape 430669, nPoints=33387, nParts=13369345.
ERROR 1: Corrupted .shp file : shape 430671, nPoints=15, nParts=1454899201.
ERROR 1: Corrupted .shp file : shape 430672, nPoints=13693445, nParts=1, nEntitySize=248.
ERROR 1: Corrupted .shp file : shape 430674, nPoints=28846, nParts=463994881.
ERROR 1: Corrupted .shp file : shape 430675 : panPartStart[0] = -2093744128, nVertices = 13
ERROR 1: Corrupted .shp file : shape 430677, nPoints=-2147418107, nParts=1.
ERROR 1: Corrupted .shp file : shape 430678, nPoints=14, nParts=58426, nEntitySize=536.
ERROR 1: Corrupted .shp file : shape 430679, nPoints=5765135, nParts=1, nEntitySize=568.
ERROR 1: Corrupted .shp file : shape 430681, nPoints=9, nParts=1589700365.
ERROR 1: Corrupted .shp file : shape 430682, nPoints=135856146, nParts=1.
ERROR 1: Corrupted .shp file : shape 430723, nPoints=-2008620712, nParts=2.
ERROR 1: Corrupted .shp file : shape 430726, nPoints=-764253120, nParts=1.
ERROR 1: Corrupted .shp file : shape 430727, nPoints=1811939439, nParts=1.
ERROR 1: Corrupted .shp file : shape 430728, nPoints=29, nParts=-555764507.
ERROR 1: Corrupted .shp file : shape 430729, nPoints=1379926087, nParts=2.
ERROR 1: Full reprojection failed, but partial is possible if you define OGR_ENABLE_PARTIAL_REPROJECTION configuration option to TRUE
Failed to reproject feature 430754 (geometry probably out of source or destination SRS).
ERROR 1: Terminating translation prematurely after failed
translation of layer PHI_v2_1_Central (use -skipfailures to skip errors)
```

**Comment by djtfmartin** [comment]
Priority Habitat North & South are now loaded.

Central has issues.

**Comment by CEJohnston** [comment]
North and South are looking good - much appreciated.  For Central perhaps it got corrupted during download and upload?  I shall re-source and re-upload to S3 and let you know when it is ready to try again.

**Comment by CEJohnston** [comment]
I have uploaded a freshly sourced copy of the Central layer to S3.  Please note: different file name -  PHI_v2_1_Central2.shp.
Please use the same variables for ingest as the original PHI_v2_1_Central.shp
I hope this copy is not corrupted.  
Thanks!

**Comment by sophiathirza** [comment]
@djtfmartin could you have another go at loading the Central Priority Habitat spatial layer that Christine uploaded, please? I have had a request for it from Reading Uni. They would like to use the spatial portal in a practical but need the missing central region. 

Message from the lecturer: I am anxious to have this data-set as it is critical to Year 2 University level practical I am running based on the NBN data. Previously we have used MAGIC but the NBN provides really great resource for teaching, packaged into one, but missing data-sets are a problem!

**Comment by sophiathirza** [comment]
I tried to run the script to ingest the Central file and got the following error:
Reprojecting shapefile to WGS 84
ERROR 1: /data/ala/data/layers/ready/shape/PHI_v2_1_Central.shp is not a directory.
 
ESRI Shapefile driver failed to create /data/ala/data/layers/ready/shape/PHI_v2_1_Central.shp

Could it be because the updated file name is the same as the original?

**Comment by CEJohnston** [comment]
Is it because the file name is PHI_v2_1_Central2 and the script is not looking for that name?  Also the file name includes capital letters that I now know can sometimes lead to it falling over.
