### ISSUE TITLE
Adding NVC_SCOTLAND layer in spatial portal gives an Internal Error message

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#207]
When accessing the National Vegetation Classification layer (NVC_SCOTLAND) in the spatial portal I get an Internal Error message.

![image](https://cloud.githubusercontent.com/assets/18594564/24659708/63569b2c-1945-11e7-95d2-7f6673b37753.png)

**Comment by djtfmartin** [comment]
ive disabled this layer for now.

**Comment by djtfmartin** [comment]
I think the problem stems from the number of polygons in the layer 200k which where all being treated as separate features (we where using the polygon ID as the unique field - not useful).

Heres the data in the shapefile:

  gid  | polygon_id | survey_id |           desc_text            | commun_cat | status | poly_src 
-------+------------+-----------+--------------------------------+------------+--------+----------
 74128 |   20064786 |  10000281 | M6c/M23a/U5a                   | Mosaic     |        | 
 74129 |   20064754 |  10000281 | M17a/M23a/M25a                 | M          |        | 
 74130 |   20064755 |  10000281 | U4d/U5a                        | U          |        | 
 74131 |   20064756 |  10000281 | M15b/M17a/H12b/U5a             | Mosaic     |        | 
 74132 |   20064969 |  10000281 | M15a/M15d/M19a/M17a/H12b/H21a  | Mosaic     |        | 
 74133 |   20064970 |  10000281 | H12b/H21a                      | H          |        | 
 74134 |   20064971 |  10000281 | H12b                           | H          |        | 
 74135 |   20064972 |  10000281 | H12b/H21a                      | H          |        | 
 74136 |   20064973 |  10000281 | H12b/H21a                      | H          |        | 
 74137 |   20064974 |  10000281 | H12b/H21a                      | H          |        | 
 74138 |   20064975 |  10000281 | CG11b                          | CG         |        | 
 74143 |   20064843 |  10000281 | M15a/M15b/M16d/M17a            | M          |        | 
 74139 |   20065061 |  10000281 | M32b/H18b/U5a/U13a/R1a/R/B/R2a | Mosaic     |        | 
 74140 |   20065062 |  10000281 | M20/H19c/U13a/U7b/BP           | Mosaic     |        | 
 74141 |   20064861 |  10000281 | H12b/U4a/U5d/R/B               | Mosaic     |        | 
 74142 |   20064842 |  10000281 | M19b/H12b/H22a                 | Mosaic     |        | 
 74162 |   20064202 |  10000280 | H12c/H12b                      | H          |        | 
 83405 |   20084105 |  10000383 | W11                            | W          |        | 
 74144 |   20065158 |  10000281 | M19b/M32b/H12b/U5a/U6c         | Mosaic     |        | 
 74145 |   20065159 |  10000281 | U7b                            | U          |        | 
(20 rows)

**Comment by djtfmartin** [comment]
For notes, using this SQL in import

https://gist.github.com/djtfmartin/89538df7421d9214d39459e17a2a81d3

**Comment by djtfmartin** [comment]
Ive hit this problems with the NVC layer

```
org.postgresql.util.PSQLException: ERROR: GEOSUnaryUnion: TopologyException: Input geom 0 is invalid: Self-intersection at or near point -4.6136957122931301 56.292468695318675 at -4.6136957122931301 56.292468695318675
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:410)
	at au.org.ala.layers.ingestion.contextual.ContextualObjectCreator.create(ContextualObjectCreator.java:62)
	at au.org.ala.layers.ingestion.contextual.ContextualObjectCreator.main(ContextualObjectCreator.java:24)
```

**Comment by djtfmartin** [comment]
https://gis.stackexchange.com/questions/229367/st-union-fails-with-topologyexception-despite-valid-polygons-and-using-st-snapto

**Comment by djtfmartin** [comment]
There have been quite a few issues with this layer. Just for notes i have done the following:

* Imported into PostGIS the raw SHP file without re-projecting (polygons are in OSGB36) with the following command:
```
java -Xmx10G -cp "${JAVA_CLASSPATH}" au.org.ala.layers.ingestion.contextual.ContextualFromShapefileDatabaseLoader "${LAYERID}" "${LAYER_SHORT_NAME}" "${LAYER_DISPLAY_NAME}" "${FIELDSSID}" "${FIELDSSNAME}" "${FIELDSSDESCRIPTION}" "${NAME_SEARCH}" "${INTERSECT}" /data/ala/data/layers/raw/NVC_SCOTLAND.shp "${DBUSERNAME}" "${DBPASSWORD}" "${DBJDBCURL}" "${DBHOST}" "${DBNAME}" 
```
* Performed the Union on the original features with a select into temporary table:
 ```
create table nvc_scotland (pid integer, name varchar(255), the_geom geometry, the_geom_4326 geometry);
```
* i was unable to perform the required union for all habitat types. This error was thrown:
```
Hole lies outside shell at or near point
```
This seemed to be a problem features in the "U, Calcifugous Grasslands and Montane Communities" habitat only.
Loaded the habitat types individually with this script:

https://gist.github.com/djtfmartin/a4f1a4a421231a7df4cd2ce8d5d23e19

Explicitly set the SRID on the geometry

```
SELECT UpdateGeometrySRID('nvc_scotland','the_geom',27700);
```
Reprojected the polygons
```
update nvc_scotland set the_geom_4326 = ST_Transform(the_geom, '4326');
```
* Loaded the ```objects``` table with this command:

```
insert into objects (pid, id, "desc", name, fid, the_geom, name_id, namesearch) 
select pid, name, name, name, 'cl65', the_geom_4326, null, false from nvc_scotland;
```
Set BBOXes

```
update objects set bbox = ST_AsText(Box2D(the_geom)) where bbox is null and fid='cl65';
```

Update stats for objects:
```
echo "Create objects from layer"
java -Xmx10G -cp "${JAVA_CLASSPATH}" au.org.ala.layers.stats.ObjectsStatsGenerator 1  "${DBJDBCURL}" "${DBUSERNAME}" "${DBPASSWORD}" cl65
```
Alter the underlying original table to 4326 projection

```
# change the underlying "65" table.....
alter table "65" add the_geom_4326 geometry;
SELECT UpdateGeometrySRID('65','the_geom',27700);
update "65" set the_geom_4326 = ST_Transform(the_geom, '4326');
ALTER TABLE "65" DROP COLUMN the_geom;
ALTER TABLE "65" RENAME COLUMN the_geom_4326 TO the_geom;

```

Load in to geoserver

```
java -Xmx10G -cp "${JAVA_CLASSPATH}" au.org.ala.layers.ingestion.PostgisTableGeoserverLoader "${GEOSERVERBASEURL}" "${GEOSERVERUSERNAME}" "${GEOSERVERPASSWORD}" "${LAYERID}" "${LAYER_SHORT_NAME}" "${LAYER_DISPLAY_NAME}"
```

**Comment by djtfmartin** [comment]
This layer is now available.

**Comment by CEJohnston** [comment]
Thanks Dave - and thanks for leaving the notes above.
