### ISSUE TITLE
Marine Conservation Zone (Wales) layer: zone name is incorrect

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#208]
This layer should have used the field 'NMR_Name' for the name of the zone (as per variable list) - instead the zone name showing in the legend is the same as the layer name.

**Comment by djtfmartin** [comment]
Fixed. This layer only contains one feature.

<img width="1440" alt="screenshot 2017-07-27 18 12 06" src="https://user-images.githubusercontent.com/444897/28683094-2aab6fbc-72f7-11e7-9ec5-2b673f874fd3.png">
