### ISSUE TITLE
Contact curator button at record level not returning the email address

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#210]
A user wanted to report an issue with this record:
https://records.nbnatlas.org/occurrences/b87ac6d5-cd6b-498e-b568-4c36ce475fb0

.... if pressed the Contact Curator button it returns a Name but email address is blank.  You can access an email address at dataset level.

![image](https://cloud.githubusercontent.com/assets/18594564/24661437/4972d482-194a-11e7-80da-c98dc0af455a.png)

**Comment by djtfmartin** [comment]
fixed
