### ISSUE TITLE
Species search issue (Buxbaumia viridis)

### ISSUE THREAD

**Issue by davidgenney** [nbnuk/nbnatlas-issues#211]
If I search for the moss Buxbaumia viridis the species is not found (filter by 'Moss') - only Buxbaumia or Buxbaumia aphylla are returned.
https://species.nbnatlas.org/search/?q=Buxbuamia+viridis&fq=taxonGroup_s:%22moss%22

However, if I select Buxbaumia and then View Records I can filter by taxon and this allows me to select and view records for Buxbaumia viridis 
(https://records.nbnatlas.org/occurrences/search?q=lsid%3ANHMSYS0000309523&fq=taxon_name%3A%22Buxbaumia+viridis%22)

I assume this is a problem with the search function rather than the taxon dictionary?

**Comment by djtfmartin** [comment]
There is a bit of problem with some unattached synonyms. We are still working on this with the UKSI folks. 

Buxbaumia viridis has a TVK of NBNSYS0000036154, and points at NHMSYS0000309525 which is missing from the export that we produce.

Still investigating...

**Comment by davidgenney** [comment]
Thanks Dave, good to know it's a known issue. At least I have a work around for now so will be able to complete the EU Article 17 report using the Atlas.

**Comment by CEJohnston** [comment]
Another related example just reported: 

I’ve been testing the search function on the new Atlas and encountered a problem with Arran Carpet (Dysstroma truncata concinnata).
If I enter the vernacular name I get no occurrences either for the name or the entry in the list which is Dysstroma truncata subsp. concinnata
 
If I enter Dysstroma truncata concinnata in the search box I get a listing for Chloroclysta truncata (Common Marbled Carpet).
The current scientific name as advocated by the current Lepidoptera checklist (Agassiz 2013) for Common Marbled Carpet is Dysstroma truncata with Arran carpet listed as a subspecies Dysstroma truncata concinnata.
If I look at the record details submitted in the OHBR Insect Dataset it shows that the record was submitted as Dysstroma truncata concinnata but has been processed as Chloroclysta truncata.

**Comment by djtfmartin** [comment]
@davidgenney i think this is resolved now. Can you confirm ?

**Comment by davidgenney** [comment]
@djtfmartin thanks David, that's working fine now. Is this a different issue to #232 then? Answer when you have time because I know you're flat out just now.

**Comment by djtfmartin** [comment]
closing
