### ISSUE TITLE
Format of "Identified by" and "Collector/Observer "

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#212]
See Forum Post https://forums.nbn.org.uk/viewtopic.php?id=6816

As an example consider https://records.nbnatlas.org/occurrence … dc9a0419cc
This gives 'Identified by' as 'Stuart Warrington' but the 'Collector/Observer' as 'Warrington, S. Stuart
Supplied as "Stuart Warrington"'.
Why two different formats for the two fields? I can't see that this helps anyone.
Is 'Warrington, S. Stuart' actually correct? I can see that 'Warrington, S. ' would be okay, as would, 'Warrington, Stuart' but 'Warrington, S. Stuart' suggests the original name was 'S. Stuart Warrington' doesn't it?

**Comment by djtfmartin** [comment]
We parse collector names and some records contain multiple collectors.

The parsed versions are using in duplicate record detection.

**Comment by japonicus** [comment]
In case it's useful, a few more examples of the parser mangling names:

organisation name parsed as 'null'
https://records.nbnatlas.org/occurrences/ca28b9ce-12fc-47a8-a0ae-e872e01cff65

reversal of initials for source names expressed as 'Surname, Forename Middle-Initial'
https://records.nbnatlas.org/occurrences/7ff7daf4-778c-45d4-9c19-f29de21358bb

another example similar to Keith's forum example, but with multiple names this time
https://records.nbnatlas.org/occurrences/be23e74e-4e6d-430d-97fa-ca5d3ebe06ba
