### ISSUE TITLE
Incorrect email given to report a problem - needs changing to NBN Atlas

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#213]
[NBN Atlas Time Out error message.docx](https://github.com/nbnuk/nbnatlas-issues/files/902208/NBN.Atlas.Time.Out.error.message.docx)
https://forums.nbn.org.uk/viewtopic.php?id=6815

Email needs changing to support@nbnatlas.org

(Dave - please can you advise how we can edit these messages ourselves. Thanks.)

I have twice tried a search for Larch Ladybird (https://species.nbnatlas.org/search/?q=Larch+Ladybird). They both timed out with the following error message:
An error has occurred
    Timed out calling web service. URL= https://species-ws.nbnatlas.org/search? … %3ACOMMON.
If this problem persists, please send an email to support@ala.org.au.

**Comment by GiselleSterry** [comment]
[NBN Atlas Time Out error message.docx](https://github.com/nbnuk/nbnatlas-issues/files/902210/NBN.Atlas.Time.Out.error.message.docx)

**Comment by GiselleSterry** [comment]
Spatial layer - internal error refers to ALA
[Spatial layer area screen shot.docx](https://github.com/nbnuk/nbnatlas-issues/files/928155/Spatial.layer.area.screen.shot.docx)

**Comment by GiselleSterry** [comment]
Email address also wrong for deactivating account. Needs to be changed from ALA to NBN address
[pop up box says ALA disable account.docx](https://github.com/nbnuk/nbnatlas-issues/files/1155684/pop.up.box.says.ALA.disable.account.docx)

**Comment by sophiathirza** [comment]
@djtfmartin can you change the ALA email address to NBN please?

**Comment by reupost** [comment]
The issue on the disable account popup should be fixed; the other two (spatial portal and species) have been fixed in code and these will reflect the next time these modules are deployed.
