### ISSUE TITLE
GetCapabilities missing layers

### ISSUE THREAD

**Issue by DuncanRowland** [nbnuk/nbnatlas-issues#217]
The following map works fine on the Atlas
https://records.nbnatlas.org/occurrences/search?q=&fq=taxon_name:%22Najas+flexilis%22#tab_mapView

However, a similar WMS GetCapabilities call only returns one layer, and it's for the entire phylum.
"<Name>phylum:Tracheophyta</Name>"
e.g. https://records-ws.nbnatlas.org/ogc/ows?SERVICE=WMS&REQUEST=GetCapabilities&q=*:*&fq=taxon_name:"Najas flexilis"

Hence, it does not currently seem possible to see this species level layers in wms clients (e.g. ArcGIS etc) even though this is visible on the website.
-D

**Comment by djtfmartin** [comment]
This isnt actually a bug (or maybe its not fixed). The returned XML looks valid and has a layer for Najas flexilis as expected.
