### ISSUE TITLE
metadata for EoL images may not be crediting owner on NBN Atlas

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#218]
Hello,
I was just looking thru the new NBN and noticed there was an image gallery. I was quite surprised to see one of my own photographs, especially as it said “Rights holder      no rights holder”.
https://images.nbnatlas.org/image/details/2058

You’ve presumably downloaded this image (as you’re entitled to do under the CC licence) from either EOL (not a very good source – their harvesting has been offline for two years so they’re well behind on corrections/name changes etc) or from DiscoverLife (a more uptodate source).

Either site would have credited the image. You’re in violation of the “BY” clause.

And incidentally the image does belong to an occurrence record in the BMS-FRDBI data which was previously submitted to NBN.
http://www.bioimages.org.uk/html/r160815.htm

**Comment by sophiathirza** [comment]
@EllaVogel can you help me with this one please?

**Comment by sophiathirza** [comment]
All images from EoL without a rights holder have been deleted.
