### ISSUE TITLE
Search timeout

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#219]
https://forums.nbn.org.uk/viewtopic.php?id=6815

Please investigate cause for slow speed / timeout issues for some users.

**Comment by CEJohnston** [comment]
I have just started to see the same performance problems today - using Chrome on Windows 10. All my species and location searches  are timing out.

**Comment by djtfmartin** [comment]
closing. Assume this was the performance problems we've worked through in April
