### ISSUE TITLE
Registration issues

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#221]
A few people have contacted us to advise that they when try to set an account up it takes them to an error message and they think that their account hasn't been created when in fact is has and has been activated.  They can then login okay.  Could this be investigated?
Thanks

**Comment by djtfmartin** [comment]
Can someone in the team try to reproduce the problem ?

**Comment by SarahHyslop** [comment]
Hi Dave

 

I have tried and it results in the error message below; also the new user Mango Chutney is not in the user list so not sure if this has worked….I used my email address for the account 

 

Thanks

 

Sarah



 

Sarah Hyslop

National Biodiversity Network Finance and Business Officer

T: 0115 924 7132

E:  <mailto:s.hyslop@nbn.org.uk> s.hyslop@nbn.org.uk  

 

Please note that my working days in the office are Monday, Tuesday, Thursday and working from home on a Friday  

 

National Biodiversity Network website: www.nbn.org.uk <http://www.nbn.org.uk/>   

NBN Atlas: www.nbnatlas.org <http://www.nbnatlas.org/> 

 

 

NBN Trust - Registered in England and Wales - Company no.3963387 - Registered charity no. 1082163.  

Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney Street, Lace Market, Nottingham NG1 1LL

 

   

 <https://www.facebook.com/pages/National-Biodiversity-Network/117818225374?fref=ts>         <https://twitter.com/NBNTrust>  @NBNTrust <https://twitter.com/NBNTrust>         <https://twitter.com/NBNTrust>  @NBNAtlas <https://twitter.com/NBNAtlas>         <https://www.linkedin.com/groups/National-Biodiversity-Network-148939/about>

**Comment by djtfmartin** [comment]
Whats the error message ?

**Comment by SarahHyslop** [comment]
Sarah Hyslop

National Biodiversity Network Finance and Business Officer

T: 0115 924 7132

E:  <mailto:s.hyslop@nbn.org.uk> s.hyslop@nbn.org.uk  

 

Please note that my working days in the office are Monday, Tuesday, Thursday and working from home on a Friday  

 

National Biodiversity Network website: www.nbn.org.uk <http://www.nbn.org.uk/>   

NBN Atlas: www.nbnatlas.org <http://www.nbnatlas.org/> 

 

 

NBN Trust - Registered in England and Wales - Company no.3963387 - Registered charity no. 1082163.  

Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney Street, Lace Market, Nottingham NG1 1LL

 

   

 <https://www.facebook.com/pages/National-Biodiversity-Network/117818225374?fref=ts>         <https://twitter.com/NBNTrust>  @NBNTrust <https://twitter.com/NBNTrust>         <https://twitter.com/NBNTrust>  @NBNAtlas <https://twitter.com/NBNAtlas>         <https://www.linkedin.com/groups/National-Biodiversity-Network-148939/about>

**Comment by SarahHyslop** [comment]
Sorry Dave, I can see now that the error message doesn't show up here, I've
[Error message.docx](https://github.com/nbnuk/nbnatlas-issues/files/910197/Error.message.docx)
 attached this now! Thanks, Sarah

**Comment by djtfmartin** [comment]
Sorry  - i cant reproduce. 

If you can, or theres more detail then please re-open.
