### ISSUE TITLE
Front page headline stats not correct

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#225]
On all NBN Atlas platforms the headline stats of species, data sets and data partners not correct. Data totally missing on NBN Atlas Wales for species.
(This is the content block under data partners carousel)

**Comment by djtfmartin** [comment]
They look fine to me. Can you provide more detail ?

@GiselleSterry

**Comment by GiselleSterry** [comment]
Example - on main NBN Atlas says 710 datasets - click on link goes to data set page - states 'showing 853 datasets'
For data partner says 96 partners - click on box 131 collections / partners in list

Species now showing on NBN Atlas Wales. 
All Atlas's going back to main NBN Atlas registry so will show different figures?
@djtfmartin

**Comment by djtfmartin** [comment]
This is expected behaviour. 

We have a shared registry for all Atlases (so that the datasets are registered once).

Im not sure theres anything to do here so I'll close this issue.
