### ISSUE TITLE
Navigation taking you away from country atlases

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#226]
If you go onto a data partner page from any of the country atlases, it takes you to the NBN Atlas, and away from your country. E.g. if you're on NBN Atlas Wales, and search for BSBI, select their data partner page from the search returns, you are then taken away from the Welsh atlas and onto the core Atlas, and it's hard to get back to the Welsh one without starting again. Is there any way of having these data partner pages within the Welsh and Scottish Atlases too?

**Comment by djtfmartin** [comment]
There isnt and this is by design - so not a bug as such.

The Atlases "share" a number of front end components including the registry, lists, alerts.
