### ISSUE TITLE
Changes to species pages when viewing synonym page

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#228]
See forum thread re synonym pages on the Atlas.
https://forums.nbn.org.uk/viewtopic.php?id=6830

Add facility to link back to page with datasets.
eg to https://species.nbnatlas.org/species/NHMSYS0000875481

**Comment by sophiathirza** [comment]
@GiselleSterry is this two separate issues? The first relating to showing records for synonyms and the second to add additional navigation? thanks.

**Comment by GiselleSterry** [comment]
@sophiathirza - one issue I think. See forum thread - relates to link to data - see text from forum thread....

Picking up on this - I would expect this page:
https://species.nbnatlas.org/species/NHMSYS0000875588
to show records even though it is a synonym? It would be very easy to find yourself on that page and think that there were no records of Bombus soroeensis. Doubly so as it has a bar code, description, map etc.
Or, alternatively to show a more user friendly message saying "click here to go the accepted name".
Or, perhaps like wikipedia does, automatically redirect to the accepted name? (and show a message saying say)

**Comment by sophiathirza** [comment]
I didn't understand the 'link back to page with datasets', it means to have a link to view the accepted name of the species, which should have any occurrence data.

**Comment by sophiathirza** [comment]
An example of a synonym species page is here: https://species.nbnatlas.org/species/NHMSYS0000460095

Could we make it more clear (somehow) that the name is a synonym and include the records from the accepted name on the synonym page. i.e. on the map and on the records tab.

Could the text 'synonym' be highlighted in red and text added to say, click on the link to view the species page for the accepted name?

**Comment by sophiathirza** [comment]
When viewing a species page where the TVK is of a non-preferred name, the page should display as if you were viewing the preferred name.

1. the species name at the top should be the preferred name
2. the matched non-preferred name should also be in the header but smaller text
3. the text 'synonym' be highlighted in red and text added to say, click on the link to view the species page for the preferred name
4. the map should show the records attached the preferred name
5. the buttons under the map should link to the page for the preferred name
6. the records and data partner tabs should have a link to the same tab on the page for the preferred name

**Comment by sophiathirza** [comment]
This has been done.
