### ISSUE TITLE
Create Account Page

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#231]
Fields need updating to reflect UK usage. Amendments also needed to field choices e.g. use of dropdowns and if all still relevant.

**Comment by sophiathirza** [comment]
@GiselleSterry is this still outstanding? There is the text: 'Your email address will be your ALA account id' which should be removed

**Comment by GiselleSterry** [comment]
Still relevant. References to ALA need to be removed so instead should say '...will be your NBN Atlas id'
Is it possible to remove the telephone number box on the create account page. We dont use this info so we should not collect it. @sophiathirza

**Comment by sophiathirza** [comment]
Please remove the telephone number box and change ALA to NBN (NBN Atlas ID).
