### ISSUE TITLE
Issues adding species to lists

### ISSUE THREAD

**Issue by davidgenney** [nbnuk/nbnatlas-issues#232]
There's an issue uploading current species to a list (perhaps related to issues 211?). For example, here are the issues related to the list _'Riparian lichens - Nationally Rare and Scarce species_ ':

Adding some species results in the attached error:

- Hydropunctaria scabra
- Gyalidea diaphana (But note below the old synonym Biatora diaphana is accepted but not recognized as a species)
- Gyalidea fritzei

[Species List error - 17 April 2017.docx](https://github.com/nbnuk/nbnatlas-issues/files/925208/Species.List.error.-.17.April.2017.docx)

The following species are accepted but not recognized as a species:

- Aspicilia zonata 
- Biatora diaphana (I tried this because the current name resulted in the above error. The taxon code also produces this result).

**Comment by djtfmartin** [comment]
I think this is fixed now (Aspicilia zonata and Hydropunctaria scabra both match now).

Note you can add species to an existing list.
