### ISSUE TITLE
Fuzzy Search - refinements required to search results

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#233]
https://forums.nbn.org.uk/viewtopic.php?id=6799

Selected comment:
 search for in Tachina fera on the main Atlas screen still asks you to chose from 5 results, and when you essentially reselect "Tachina fera" from the resulting list you still have 294 results to chose from, most of which have absolutely no relevance to the species being searched for. 
Doing the same search from the "Species" screen returns 293 results!

If a user types Tachina then trust that they know what they are doing and give them what matches in the database, ranked by the most likely/popular result. Searching for "Tachina" should NOT list junior synonyms higher than recommended names, just as searching for "Sparrow" shouldn't list rare vagrants before the House Sparrow. The UKSI contains the flags needed to do this already and it worked perfectly well on the Gateway.

**Comment by CEJohnston** [comment]
Latest post from the Forum - same topic:

Is there any news on a fix for this problem? Everything seems to have gone quiet but this is a significant problem, in my books.
For instance, when you search for "Tachina magnicornis" why should a junior synonym precede a recommended name? 
[https://species.nbnatlas.org/search/?q=tachina+magnicornis](url)
Why does a search for "Sparrow" still list rare vagrants above the common House Sparrow? 
[https://species.nbnatlas.org/search?fq=idxtype%3ATAXON&q=sparrow](url)

This problem doesn't create an error message but it is a significant loss of credibility with users when the primary search routine gives back misleading or poor results. As I said, the NBN Gateway listed things very well and I have my own scripts that give much more logical search results than this.

**Comment by djtfmartin** [comment]
I just deployed a boost to results based on occurrence count. Seems to have done the job.

**Comment by CEJohnston** [comment]
Thanks very much @djtfmartin - does look better - I have posted a response on the Forum.
