### ISSUE TITLE
Broken Link - 'Explore' when searching predefined area

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#234]
https://regions.nbnatlas.org/#rt=Ordnance+survey+100km+grids

On this page the 'Explore' hyperlink on he left side of page below the logo is not working. When click on it returns 'page not found'.

**Comment by sophiathirza** [comment]
This is still a problem.

**Comment by sophiathirza** [comment]
Where should the 'Explore' link take the user? Perhaps the hyperlink could just be removed?

**Comment by sophiathirza** [comment]
Please remove the 'explore' link.

**Comment by reupost** [comment]
Done
