### ISSUE TITLE
Explore by species - sub division of groups under ' Explore by predefined area'

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#235]
https://regions.nbnatlas.org/Ordnance%20survey%20100km%20grids/NT#group=Plants&subgroup=&from=1850&to=2017&tab=speciesTab

When searching can plants be subdivided further. Other groups eg mammals are split into further groups.

**Comment by davidgenney** [comment]
It would also be very useful to be able to view lichens as a sub-group of fungi. There must be a list of lichenised fungi somewhere because iRecord differentiates them.

**Comment by sophiathirza** [comment]
#506

**Comment by sophiathirza** [comment]
The two lichenised fungi phyla under Fungi are Ascomycota and Basidiomycota, so we should be able to list Lichens as a subgroup of Fungi based on these two phyla.

**Comment by davidgenney** [comment]
It should be easy to provide a lichen subset using the BLS taxon dictionary. The full list of accepted names can be downloaded via the CSV link at the bottom of this page:
http://www.britishlichensociety.org.uk/resources/lichen-taxon-database
At the moment I have to filter by the BLS dataset so I miss all the local records centre lichen records.

**Comment by sophiathirza** [comment]
Both phyla contain non-lichenised fungi, so we can't use them as a subgroup. The UKSI has a taxon group for lichens. I would prefer that we use a single dictionary and use the UKSI rather than adding the BLS as well.

**Comment by sophiathirza** [comment]
We now have three species lists for the different lichen groups.
