### ISSUE TITLE
SSSI layer no longer listed

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#239]
https://forums.nbn.org.uk/viewtopic.php?pid=26810#p26810

SSI layer not visible via Explore predefined area. 
https://regions.nbnatlas.org/#rt=National+parks

**Comment by djtfmartin** [comment]
They are for Scotland.

https://scotland-regions.nbnatlas.org

We just need to identify a list of layers to include (from the ones we have already loaded) in this tool.

cc @CEJohnston @JoJudge

**Comment by djtfmartin** [comment]
Im closing this. If there are new layers to be loaded and included then we can raise issues for these.

Currently we have a SSSI layer for Wales and separate one for England. We dont have a combined layer of SSSIs for UK.
