### ISSUE TITLE
Orphan datasets?

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#240]
https://forums.nbn.org.uk/viewtopic.php?id=6847

When filtering occurrence records by dataset I am sometimes presented with un-named options like dr752, dr759, dr235, ...
If I look at these records I see datasets 'BLS Lichen Database: English churchyards', 'BLS Lichen Database: England', 'BLS Lichen Database: Scotland', ...
However, datasets by these exact names cannot be found. There are almost identical datasets with different data resource ids.
It looks as if the original dataset entries have been deleted but not their occurrences, leaving the occurrences orphaned. (And duplicated by the replacement datasets, I wonder?)

**Comment by djtfmartin** [comment]
this has been fixed. Please verify.
