### ISSUE TITLE
Isle of Man - the unknown country

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#241]
I know the Isle of Man is special but I wouldn't have called it unknown. However the 595k records I find there from a polygon search on the Atlas all come back with the country field set to Unknown. Actually, the results are similar for the Republic of Ireland. What is the geographical scope of the Atlas? Are they within or without it?

**Comment by djtfmartin** [comment]
this is now fixed
thanks @CEJohnston for updating the layer

<img width="371" alt="screen shot 2017-06-30 at 3 22 01 pm" src="https://user-images.githubusercontent.com/444897/27739872-fa5ef176-5da7-11e7-9092-3cd2a0bba3fb.png">
