### ISSUE TITLE
Link to ALA via taxon groups

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#242]
https://forums.nbn.org.uk/viewtopic.php?id=6849

In the same area, if you click on one of the higher taxonomic groups, e.g. Animalia, and select Show Information, you are taken to an error page on the Atlas of Living Australia. If you drill down to a species, e.g. Fringilla coelebs and select Show Information you do get a result but for Chaffinch in Australia.

**Comment by djtfmartin** [comment]
this is fixed
