### ISSUE TITLE
Duplication under Digitised Records?

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#243]
https://forums.nbn.org.uk/viewtopic.php?id=6849

Using one of Cofnods datasets as an example (https://registry.nbnatlas.org/public/show/dr1420), there appears to be some duplication of the taxonomic hierarchy under 'DIGITISED RECORDS' - a picture shows this better (attached). However these duplicates appear under a 'blank' Kingdom?

**Comment by djtfmartin** [comment]
this is fixed
