### ISSUE TITLE
dataset mis-count?

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#244]
https://forums.nbn.org.uk/viewtopic.php?id=6850
I think this probably applies in all cases but, take for example Tamias sibiricus, a species chosen for being in very few datasets. "2 datasets have provided data for this species" says the overview page but, when you browse the list, there is always one fewer than stated.

**Comment by DuncanRowland** [comment]
For reference, I'm thinking this is the exact same issue that caused 'Unknown' to appear as a data source on EasyMaps (which I fixed there by ignoring data sets with a count of 0)...

https://records-ws.nbnatlas.org/occurrences/search?q=*:*&fq=lsid:NHMSYS0021109804&facets=data_resource_uid&pageSize=0

Shows a total of two records from two data sources, "dr671" has two, and "Unknown" has none.
I'm not sure why Unknown is being returned here if it's got no records , but that's the nub of it.

Atb, -D.

**Comment by djtfmartin** [comment]
this is fixed (and @DuncanRowland was right :)).
