### ISSUE TITLE
Scottish Biodiversity List

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#249]
Post from the forum;

If I search for Scottish Biodiversity List, although results are returned the SBL is missing. Similarly if I try a search using Species Lists or Conservation Lists, still no SBL.

If I search under Atlas Datasets with the species list filter, SBL is missing.

If I look at the overview page for an SBL species, there is information derived from the SBL and also a link to the provider which takes me to the desired SBL (https://lists.nbnatlas.org/speciesListI … /dr34#list).

The SBL and other conservation lists can be found at https://lists.nbnatlas.org/public/speciesLists but I have been unable to find a direct link to this page and not all the lists on this page can be located using the global search e.g Scottish Rural Development Programme. 

Can you add this to "matters requiring attention" please.

**Comment by sophiathirza** [comment]
@EllaVogel can you help me with this one?

**Comment by sophiathirza** [comment]
I was able to search for the SBL in the dataset search and I haven't heard anymore problems about this. So I will close.
