### ISSUE TITLE
AoLS Terms and Conditions page

### ISSUE THREAD

**Issue by djtfmartin** [nbnuk/nbnatlas-issues#25]
There's a link in this popup in the download that has a link to a terms and conditions page. 
We need a place to link to. In the short term it could be:

https://data.nbn.org.uk/Terms

But it might make sense for AoLS to have its own (particularly if the licencing arrangements have changed around data).

cc @EllaVogel

**Comment by CEJohnston** [comment]
I can't see where this appears.  I have downloaded a species list from inside the spatial portal and received no warning or pop-up box.

**Comment by djtfmartin** [comment]
This appears when users download records from here:

http://records.als.scot/occurrences/search?q=data_resource_uid:dr222

**Comment by CEJohnston** [comment]
We have Terms of Use (http://www.als.scot/terms-of-use/) on the site so need to link this to the pop up box - think that should fix it.

**Comment by djtfmartin** [comment]
Done

**Comment by CEJohnston** [comment]
Just been checking and the link is still going to https://data.nbn.org.uk/Terms.  It needs to go to http://www.als.scot/terms-of-use/ - can you fix it? Thanks.

**Comment by djtfmartin** [comment]
this is fixed.
