### ISSUE TITLE
Adding download detail to data provider logs

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#250]
Not sure if this has been raised before but there is a thread on the NBN Forum regarding adding detail of who has downloaded records so that the data providers can see this information, in particular names and details of who has downloaded the records; https://forums.nbn.org.uk/viewtopic.php?id=6839 

Can you let me know if this is possible as this was something that was available on the Gateway and it would be helpful to be able to update the forum and users if we can reinstate this on the Atlas.

Thanks

**Comment by DuncanRowland** [comment]
I saw this thread. Perhaps this is an aside, but I think it's incorrect to use an email address to verify a user's identity (it's easy to register for a temporary email address). If this was used by the Gateway then it was still essentially an honesty based system.

**Comment by djtfmartin** [comment]
We have CSV exports available on data resource and data partner admin pages.
this is done.
