### ISSUE TITLE
What are Asco's?  Showing on home page

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#251]
Under the Making the most of biodiversity data on the home page there is (intermittently) a link to Asco's.  When you click on the link it says "No records found for species_subgroup:"Asco".  This has also been raised in the NBN Forum.

**Comment by djtfmartin** [comment]
This related to the species subgroups. This is an ongoing task
cc @EllaVogel @CEJohnston

**Comment by djtfmartin** [comment]
see https://github.com/nbnuk/nbnatlas-issues/issues/16
and https://github.com/nbnuk/nbnatlas-issues/issues/61
