### ISSUE TITLE
Absence / presence enhancement

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#252]
Suggestions from MBA:

2)	The number of occurrences is still showing the number of presence + absence records which I think will be very confusing for users, either this should be reworded to number of presences & absences, or the number changed to only include presence records.
•  species: Didemnum vexillum Kott, 2002 
Didemnum vexillum Kott, 2002
Didemnum vexillum
Occurrences: 144 

4)	The absences are not displayed on the detail map, NBNGateway used to show these in a different colour and you could choose to display them.

**Comment by sophiathirza** [comment]
I had another email about this today. The species list and map on the 'Explore your area' should not include absence records.

**Comment by djtfmartin** [comment]
What is the species list in this context ?

**Comment by sophiathirza** [comment]
The two lists on the page: far left, the species count in the different taxon groups, and middle of the page, the list of scientific names.

**Comment by djtfmartin** [comment]
I think this fixed, difficult to reproduce based on the description provided.
By EYA filters absence data now.
