### ISSUE TITLE
Discrepancy on FoE dataset images

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#253]
There is a Forum post following the removal of the 3 datasets from the FoE Great British Bee Count datasets:
https://registry.nbnatlas.org/public/show/dr1416 and
https://registry.nbnatlas.org/public/show/dr1244
both say over X 1000 photos submitted and verified - but the dataset/record pages show less than 100 records. Is this correct or have lots of records gone astray somewhere?

**Comment by djtfmartin** [comment]
this is the data as supplied by JNCC

**Comment by sophiathirza** [comment]
I will close this as the datasets have been removed.
