### ISSUE TITLE
Quick way to sort species by date

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#255]
"The mapping function on last version on NBN gateway, had really nice and easy way to sort grid records of species by date. i.e.  say easily map post 2000 records of a species, the new atlas doesnt, this is very crucial feature for most recorders, dont understand why the new NBN atlas either doesnt have this or you have to go through a help file to find it embeded somewhere".

We explained how to do this via occurence records, but the following reply came in:

"Did work, but still think recorders would benefit from clicking a pre and post 1999 button in main window"

**Comment by c-van-dierkson** [comment]
@sophiathirza Can this be closed? #334 has been completed and we also have #511 open which is for the Map on species page toggle to show last 10 years/last 20 years/ all records. I'd rather add anything additional to 511 and then close this if possible?

**Comment by sophiathirza** [comment]
@c-van-dierkson yes, it sounds like it is duplicated.
