### ISSUE TITLE
Downloading child taxa for a division broken

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#256]
Text below copied from a forum [post:](https://forums.nbn.org.uk/viewtopic.php?pid=26980#p26980)

I assume it should be possible to see the classification at all levels for all British species (whether or not there are presently records in the Atlas) based on the current UK Species Dictionary.
If that assumption is correct, the classification feature seems to be a helpful way of producing taxon lists, not least in being able to download files in a handy .CSV file format. [As an aside, it would be useful if they also included a field for e.g Insects-Dragonflies type groupings.]

There appear to be some issues, however...
There are currently hornwort species included in the Atlas database (e.g. Anthoceros agrestis) and it is possible to search for and find these. However, downloads of the species or child taxa names of the Anthocerophyta seem to produce only empty lists. There seems to be a fault or some missing information here (or the proper step just isn't obvious enough for me!).

There are genera listed under Plantae (e.g  Pleurococcus) which appear to lack any intermediate taxonomic relationship. This, I assume, is a reflection of the records rather than the taxon key, but it would presumably be more useful to have all levels the hierarchy and a taxons relationship to these..

[As a further aside, based on just a few records from a particular dataset I ended up drilling into, Water Rat appears to be the preferred common name for Water Vole. This appears to be applied by the Atlas system in preference to the supplied name. This also seemed something of an oddity]

**Comment by djtfmartin** [comment]
There appears to a problem with downloading child taxa for a division. Other higher taxa seems to working e.g. Phylum, Class

**Comment by sophiathirza** [comment]
This appears now to be working with the latest UKSI.
