### ISSUE TITLE
Images on filter buttons on 'search for a data partner' are Australian species

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#257]
https://registry.nbnatlas.org/ 
When searching for a data partner, the image for 'Fauna' is an Australian bird species. Can we change this to a British species?

**Comment by djtfmartin** [comment]
yes. We just need to source the images...
Also the groups can be changed if there is a more appropriate set for NBN

**Comment by sophiathirza** [comment]
#506

**Comment by reupost** [comment]
Can anyone provide me with appropriate images please? They need to be clear at about 80px height, and ideally would be on a plain background. I can do the resizing and cleaning up of the background if necessary. We need an image for:
All collections / partners (optional)
Vertebrates
Invertebrates
Microorganisms
Plants and bryophytes

**Comment by reupost** [comment]
And fungi :)

**Comment by reupost** [comment]
Done
