### ISSUE TITLE
New users - activation emails are not being sent??

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#258]
Two new users have contacted support@nbn today to advise that they have set up an account but haven't had the activation email through.  The emails are not in spam and they are listed on the Atlas as users - I have manually activated them at this end.  Can you check to see if we are having an issue with sending the activation email?  I have tried to replicate this but I get the attached error message; 

![error message](https://cloud.githubusercontent.com/assets/26628372/25948608/33505430-364c-11e7-84fc-b91f04663e7d.jpg)

**Comment by SarahHyslop** [comment]
Just had this undeliverable email come through for one of the new accounts

**Comment by SarahHyslop** [comment]
This is the mail system at host ip-172-31-26-1.eu-central-1.compute.internal.

I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can delete your own text from the attached returned message.

                   The mail system

<k.callcutt@newcastle.ac.uk>: host mailhub-mx3.ncl.ac.uk[128.240.234.83] said:
    550 HELO host name invalid (in reply to RCPT TO command)

**Comment by sophiathirza** [comment]
@SarahHyslop can this be closed?

**Comment by SarahHyslop** [comment]
Hi @sophiathirza yes I think this can be closed as its quite old and we dont seem to have an issue at present with the activation emails.  Thanks!
