### ISSUE TITLE
Old vernacular names are being used

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#259]
Sent from British Dragonfly Society on 12.05.17; email in support@nbn

Old vernacular names are being used, e.g. "Banded Agrion" instead of the preferred "Banded Demoiselle", even though the taxon page for Calopteryx splendens (Harris, 1782) at https://species.nbnatlas.org/species/NBNSYS0000005617#names clearly shows which name is preferred and it was changed in the 1960s, I believe. This is only one example of many for dragonflies.

Detail of this example: Species ID: NBNSYS0000005617 - example records are shown on this page: https://records.nbnatlas.org/occurrences/search?taxa=&q=banded+demoiselle&offset=900&max=100&sort=occurrence_date
and the one I looked at in detail is Occurrence record 459070444 > https://records.nbnatlas.org/occurrences/6dfa605e-b663-4279-b4b5-8243bf8adbbb
where for field Vernacular name: Processed Value = "Banded Agrion", whereas Original Value = "Banded Demoiselle".

**Comment by sophiathirza** [comment]
Notes:
Banded Demoiselle is the preferred form
Banded Agrion is well formed

We need to select the preferred form to display but also consider what to display when the dataset already contains a common name.

**Comment by SarahHyslop** [comment]
Thanks for looking at this one.  Is there plaything I need to do here?

**Comment by sophiathirza** [comment]
No, thanks. It was a note for when we get the latest UKSI to work out how to choose which common name to show.

**Comment by SarahHyslop** [comment]
Okay, great thanks!

**Comment by sophiathirza** [comment]
I've added a field to the taxa table to include the preferred common English name.

Note: I have done this is R rather than in the groovy application.

**Comment by sophiathirza** [comment]
The preferred common name is correctly displayed on the species page but on the records pages are still using the a non-preferred name

e.g. https://records.nbnatlas.org/occurrences/search?taxa=&q=banded+demoiselle&offset=900&max=100&sort=occurrence_date and https://records.nbnatlas.org/occurrences/b2baaaf6-b359-443a-bdec-115b8400d9cc

**Comment by sophiathirza** [comment]
Records pages are now using the preferred common name.
