### ISSUE TITLE
MBA presence/absence issues

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#260]
Email from MBA:
We would like to access Sabellaria alveolata records from the Marlin Shore Thing dataset and ‘DASSH’ datasets. At the moment it still looks like The Shore Thing dataset records are all given as presence. When I download the dataset it does not appear to give any heading containing information on presence/absence/abundance.
 
The DASSH datasets below have the column header ‘Occurrence status assumed to be present’, but all are set to TRUE
·          DASSH Data Archive Centre Academic Surveys
·         DASSH Data Archive Centre - Statutory Surveys
·         DASSH Data Archive Centre volunteer sightings records
·         DASSH Data Archive Centre volunteer survey data)

**Comment by djtfmartin** [comment]
i think these are resolved
