### ISSUE TITLE
Species description is incorrect

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#261]
Post from the Forum: 

_Just looking at the page for Goldfinch (https://species.nbnatlas.org/species/NHMSYS0000530247)
Interested to see the following description brought in automatically.....

"Depth range based on 3 specimens in 1 taxon.
Water temperature and chemistry ranges based on 1 sample.
Environmental ranges
  Depth range (m): 0 - 0
  Temperature range (°C): 11.811 - 11.811
  Nitrate (umol/L): 6.342 - 6.342
  Salinity (PPS): 34.953 - 34.953
  Oxygen (ml/l): 6.391 - 6.391
  Phosphate (umol/l): 0.377 - 0.377
  Silicate (umol/l): 3.584 - 3.584"

Now I'm not sure what the concentrate of nitrate in a Goldfinch is, but something tells me there might be a problem here.... ;)
Flippancy aside, the bottom of the box has a link to says "http://www.iobis.org/mapper/?taxon_id=740955" - which goes to the Ocean Biogeographic Information System. I presume something in the NBN system is incorrectly assigning this code 740955 ??_

Dave - can you advise if is this a bug at our end?

**Comment by djtfmartin** [comment]
This is just pulled from EOL

http://eol.org/pages/1051079/details

not a bug, but perhaps a data issue to be discussed with EOL.
