### ISSUE TITLE
Species list - taxon matching issue

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#262]
A user has noticed that crossbill, parrot crossbill and Scottish crossbill do not have Wildlife & Countryside Act Sch1.1 on their information [species] page, but the Schedule includes all crossbill species.

I have checked the schedule in the Atlas and it defines Loxia (crossbill) at genus level only rather than species level.  So, if you look at the Loxia page on the Atlas it does say they are protected by the schedule, but if you look at the particular species pages, eg Loxia scotica (Scottish crossbill), there is no mention of the schedule. 

Is it possible to match the schedule (genus) name to the individual Loxia species names (as all of them are covered) so that the status on the schedule appears within each of the species pages?

**Comment by sophiathirza** [comment]
@EllaVogel could you help me with this? thanks.

**Comment by sophiathirza** [comment]
I think the only way to do this to manually add the individual Loxia species to the species list

**Comment by sophiathirza** [comment]
I have added the four Loxia species to the Wildlife & Countryside Act Sch1.1  species list.

**Comment by CEJohnston** [comment]
Thanks @sophiathirza - I have advised the person who raised the query that it has been fixed.  I guess this is not actually ideal as each time the list is updated from source this change will need to be made again? Although I am not sure how often that will happen so it may not be a problem.
