### ISSUE TITLE
Updated sea areas mask to include Isle of Man

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#263]
Have just uploaded to S3 an updated shapefile for the sea areas to replace the existing:

LAYER_SHORT_NAME = countries_with_sea_areas_may2017
FIELDSSID = id
FIELDSSNAME = Name
FIELDSSDESCRIPTION = Name

Can you update the reference date in the metadata to May 2017? No need to change any other source information.

Hope it is OK.  @EllaVogel for info.

**Comment by djtfmartin** [comment]
ive updated the layer

**Comment by CEJohnston** [comment]
Thanks very much!
