### ISSUE TITLE
Service unavailable - search by location / map

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#264]
Error message when trying to search by location or when on a species search and then select 'view map'

![image](https://cloud.githubusercontent.com/assets/26628372/26302818/65f495f6-3edd-11e7-825d-c9a8579da02d.png)

**Comment by djtfmartin** [comment]
its backup.

**Comment by SarahHyslop** [comment]
Thanks Dave, what was the matter with it?

**Comment by djtfmartin** [comment]
The front end server went down. Im still looking into the reasons.

**Comment by SarahHyslop** [comment]
Thanks Dave.  Also a few people last week have mentioned that they were having trouble registering and someone today has said the same.  I can see some email activation emails bounce back to admin@nbnatlas.org <mailto:admin@nbnatlas.org> 

 

Can you let me know if there are any issues and if I should raise this on GitHub?

 

Sarah Hyslop

National Biodiversity Network Finance and Business Officer

T: 0115 924 7132

E:  <mailto:s.hyslop@nbn.org.uk> s.hyslop@nbn.org.uk  

 

Please note that my working days in the office are Monday, Tuesday, Thursday and working from home on a Friday  

 

Nominate your unsung biological recording heroes for the UK Awards for Biological Recording and Information Sharing 2017 – closes 31 July!

 

National Biodiversity Network website: www.nbn.org.uk <http://www.nbn.org.uk/>   

NBN Atlas: www.nbnatlas.org <http://www.nbnatlas.org/> 

 

 

NBN Trust - Registered in England and Wales - Company no.3963387 - Registered charity no. 1082163.  

Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney Street, Lace Market, Nottingham NG1 1LL

 

   

 <https://www.facebook.com/pages/National-Biodiversity-Network/117818225374?fref=ts>         <https://twitter.com/NBNTrust>  @NBNTrust <https://twitter.com/NBNTrust>         <https://twitter.com/NBNTrust>  @NBNAtlas <https://twitter.com/NBNAtlas>         <https://www.linkedin.com/groups/National-Biodiversity-Network-148939/about>
