### ISSUE TITLE
Spatial Portal - Area Report

### ISSUE THREAD

**Issue by JonathanFenn** [nbnuk/nbnatlas-issues#265]
I'm currently making some FAQ videos for the spatial portal on the Atlas. When I bring up an area report to look at the number of records  for each taxonomic group (Mammals, Birds etc.), the number of records is identical for each group, and is the same as the total number of records.

![area report](https://cloud.githubusercontent.com/assets/28703497/26352142/6cc28944-3fb2-11e7-9082-533f1c1fccec.jpg)

**Comment by sophiathirza** [comment]
I have been able to recreate this, on a report where the number of species is the same for each classification.

**Comment by djtfmartin** [comment]
This specifically affects user drawn polygons / bounding boxes.

**Comment by djtfmartin** [comment]
This is now fixed
