### ISSUE TITLE
Log in failure

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#267]
User tried signing up but keeps getting same error message. I can see that he has acccount is live and activated but he is unable to log in. (User 11570). Already deleted account once and tried again. Error message attached
[NBN Login error.docx](https://github.com/nbnuk/nbnatlas-issues/files/1057370/NBN.Login.error.docx)

**Comment by sophiathirza** [comment]
@GiselleSterry is this still a problem? can I close it?

**Comment by GiselleSterry** [comment]
Are you able to see details on when user last logged in? If not will be a case of us emailing user to see if they can access NBN Atlas. @sophiathirza

**Comment by sophiathirza** [comment]
I have written to the user.

**Comment by sophiathirza** [comment]
The user is completely unable to log in. I can log in with his user name and password. Unfortunately, he does not want to continue trying.
