### ISSUE TITLE
Links to dataset via partner page not working

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#268]
See attached document. Relates to link under Digitised Records above the pie chart.

[Bug re login.docx](https://github.com/nbnuk/nbnatlas-issues/files/1057700/Bug.re.login.docx)

**Comment by sophiathirza** [comment]
@GiselleSterry would you send me a link to where this is happening, please?

**Comment by GiselleSterry** [comment]
Not sure if still relevant may have been a bug that is fixed - see attached document on original post. Reported by a user - just tried myself on a random dataset and it worked ok. @sophiathirza

**Comment by sophiathirza** [comment]
I tried to follow the document but didn't understand it. I will close for now and we can reopen if the problem is reported again.
