### ISSUE TITLE
Sightings - indicate the licence for records

### ISSUE THREAD

**Issue by djtfmartin** [nbnuk/nbnatlas-issues#27]
Indicate the licence for records and link to the metadata page for the dataset.

**Comment by CEJohnston** [comment]
We have User feedback that suggests we: Make licenses clear on data search and add searchable option to filter on licenses. 
I think this belongs in this heading.

**Comment by djtfmartin** [comment]
Closing. We are removing the "record a sighting" option from the Atlas. There are separate issues for downloading licence information and search via licence. See #157 and #155

**Comment by RachelStroud** [comment]
Ok thanks Dave
