### ISSUE TITLE
Bug when uploading own species list into spatial portal

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#271]
Attempting to load a species list into the spatial portal. Only the 1st species on my list gets added, not the whole list.

**Comment by EllaVogel** [comment]
update from user who has been trying to add lists: I have had some success, but it is really struggling with longer lists. If I load up a .txt with a long string of names separated by commas, without line separators, it will load more than one name. (CSV's still not working)

**Comment by djtfmartin** [comment]
The required format is a CSV where the first column is the scientific name. Any additional columns can be added too.

A single line of scientific names comma separated wont load.

Something for the help documentation .....

**Comment by EllaVogel** [comment]
The one that I tried was a CSV with scientific names listed down the 1st column, with no other columns present. This is the example where only the 1st species would load.

**Comment by djtfmartin** [comment]
I see it now too.

**Comment by EllaVogel** [comment]
Further update from a user who is trying to work out a work-around:
"Unfortunately I haven’t been able to progress my data extract. I can get my species list into the box but no further, is there any guidance on how to proceed from this point?"

**Comment by djtfmartin** [comment]
I suggest in the meantime just using the lists tool directly

https://lists.nbnatlas.org

there is a link from the list view to the spatial portal

**Comment by EllaVogel** [comment]
Good work-around. I'll pass the message on. Thanks.
