### ISSUE TITLE
Wrong info on species page

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#273]
Species page for Tetrastemma https://species.nbnatlas.org/species/NHMSYS0021056997 gives a key on the left hand side, but this is for  Pacific Tetrastemma which is inappropriate in this instance. 

Issue reported by David Fenwick

**Comment by sophiathirza** [comment]
The infoSourceURL for the record is pointing to the ALA:
[1] "http://collections.ala.org.au/public/show/null"

could this be the problem? I can't see anything else in the information on the taxon from the web service that looks incorrect.

**Comment by djtfmartin** [comment]
no. We should remove/fix that URL but its not in use in UI.

We get all species info from EOL and some pages are problematic. I think we need some sort of black list mechanism for eol pages which are problematic.

**Comment by sophiathirza** [comment]
No information about the species is being displayed now.
