### ISSUE TITLE
NBN Atlas Wales - Datasets not showing for Squatina Squatina

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#274]
When searching for Squatina Squatina on NBN Atlas Wales, beneath the map it says that there are 3 datasets, but when you click the link to "Browse the list of datasets" nothing is shown: https://wales-species.nbnatlas.org/species/NBNSYS0000188592

**Comment by djtfmartin** [comment]
this is fixed
