### ISSUE TITLE
Date Precision

### ISSUE THREAD

**Issue by JonathanFenn** [nbnuk/nbnatlas-issues#275]
When searching for records, the filter for date precision lists most of the records as 'Unknown'.

When I've actually looked at a sample of these records, they all have supplied dates.

A question from support has asked if they can look at specific temporal resolutions, so it would be useful to be able to accurately filter by date precision.

![date precision](https://user-images.githubusercontent.com/28703497/27375464-310fa79e-5667-11e7-834f-dcc576eb5bcd.jpg)
![date precision2](https://user-images.githubusercontent.com/28703497/27375465-3113e98a-5667-11e7-9ea5-e0416b67d7ac.jpg)

**Comment by djtfmartin** [comment]
Date precision is an optional supplied field and currently we only parse interpret when its been supplied by the data provider. An enhancement would be to provide a interpreted date precision field based on the date supplied when a separate date precision field isn't supplied.

**Comment by djtfmartin** [comment]
We now generate a date precision where we dont have one supplied

<img width="632" alt="screenshot 2017-11-02 13 39 37" src="https://user-images.githubusercontent.com/444897/32328907-515c3c62-bfd3-11e7-826d-8e250898c59f.png">
