### ISSUE TITLE
Contact curator not working on species page?

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#277]
A user contacted us to inform that the contact curator doesn't work on this particular page; https://records.nbnatlas.org/occurrences/5720b3fd-8381-4ca5-867f-345d3fdd99f3 

Is this feature set up yet?

![contact curator](https://user-images.githubusercontent.com/26628372/27588615-acd17aaa-5b40-11e7-9a6a-9f11c83a52dc.jpg)

We have got round this by finding the data partner and referring the user to their contact details on their page and to email outside of the Atlas.

**Comment by SarahHyslop** [comment]
I have just realised that if you click the contact curator and then click on the email address (even though it says null) it does actually start a draft email to secretary@british-dragonflies.org.uk so maybe this is working but perhaps not quite so clearly?

**Comment by djtfmartin** [comment]
thats right @SarahHyslop 

Ive made the link more obvious now

<img width="753" alt="screen shot 2017-07-04 at 1 10 15 pm" src="https://user-images.githubusercontent.com/444897/27829590-3044947a-60ba-11e7-9a44-3f3179c52f5f.png">

**Comment by CEJohnston** [comment]
Thanks very much @djtfmartin - that is now much clearer - and really good to be able to demonstrate this to our users!
