### ISSUE TITLE
Interpretation of multiple observer names in a record

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#281]
A post on the Forum [https://forums.nbn.org.uk/viewtopic.php?pid=27230#p27230](url)  is asking about the translation of multiple observer names within a record using this example:

Wood, C. Chris|null
Supplied as "Chris Wood, Anna Yunnie and John Bishop"

Is this interpretation of the three names working as expected and is there any guidance for users on supplying names in order to improve the way the names are interpreted?

**Comment by djtfmartin** [comment]
This is just a display issue. We should be presenting the names which are pipe separated in a better manner.

**Comment by GiselleSterry** [comment]
Received following by email
I noticed that the collector/observer names have been reformatted.

They seem to have been reformatted as “Surname, Initial [of firstname]. Firstname” which is rather misleading, as it looks like the person’s name is, in this example, “R. Robert Edgar”, which it isn’t. 

Edgar, R. Robert
Supplied as 'Robert Edgar'

**Comment by djtfmartin** [comment]
this is fixed. The raw recordedBy value is now displayed
