### ISSUE TITLE
Unable to retrieve details of records when using NBN Scotland Atlas - 16th June

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#282]
Was there a problem on the 16th June - this is a message from the Forum:

Unable to retrieve details of records when using NBN Scotland Atlas.
Failed to get json from web service (https://records-ws.nbnatlas.org/occurre … 73f125c85e). class java.io.IOException Server returned HTTP response code: 500 for URL: https://records-ws.nbnatlas.org/occurre … 3f125c85e, java.io.IOException: Server returned HTTP response code: 500 for URL: https://records-ws.nbnatlas.org/occurre … 3f125c85e.
Deja-vu? Just like the gateway on a Friday afternoon!

Forum link (for the actual urls):  [https://forums.nbn.org.uk/viewtopic.php?id=6922](url)

**Comment by djtfmartin** [comment]
I think this was a momentary bit of downtime. Closing. We can reopen if we think its an intermittent problem.
