### ISSUE TITLE
Explore by location error

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#284]
The location search doesn't appear to be showing any results today;

See example; 

https://records.nbnatlas.org/explore/your-area#51.50613042214491|-0.12544148740232686|11|ALL_SPECIES

Also a user has been searching for dormouse and there seem to be records showing in the species search for postcode GU10 4DW but when they search by this postcode nothing comes up - could be related to a wider search by location issue?

**Comment by djtfmartin** [comment]
thanks @SarahHyslop this is now fixed.

**Comment by SarahHyslop** [comment]
Thanks Dave, seems all sorted now :-)

Do you know what the issue was?

**Comment by djtfmartin** [comment]
Radius queries where not working
