### ISSUE TITLE
data upload - no species names

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#285]
I notice that the dataset has now gone up, however, something seems to have gone wrong with the upload as there are no species names for the records. 

This is the dataset page: 
https://registry.nbnatlas.org/public/show/dr1473

When you look at the records, the names are all 'not recognised' / 'not matched'.

**Comment by GiselleSterry** [comment]
Data provider has requested an update on timescale for resolution. thanks

**Comment by djtfmartin** [comment]
The data was supplied with the following headings (which are a little garbled or truncated)

RecordKey,UpdatedOn,TaxonVersi,SurveyKey,SampleKey,StartDate,EndDate,DateType,GridRefere,Projection,Precision,SeFsitive,ZeroAbunda,SiteKey,SiteName,SampleMeth,Recorder,Determiner,Abundance,Comment

"TaxonVersi" wasnt recognised. 

@sophiathirza @EllaVogel

**Comment by sophiathirza** [comment]
So what needs to happen? Do we correct the heading and reupload?

**Comment by sophiathirza** [comment]
I have updated the headers, except for SampleMeth. I can't find any documentation on what it should be.

**Comment by sophiathirza** [comment]
The dataset has been upload and the updates should appear on the Atlas over the weekend.

**Comment by GiselleSterry** [comment]
Checked this morning and still not showing up. Has the update been run?

**Comment by sophiathirza** [comment]
No, it was not possible to run the updates. As soon as I have more information I will let you know

**Comment by sophiathirza** [comment]
The update will be run today.

**Comment by djtfmartin** [comment]
this dataset import has now been fixed

**Comment by sophiathirza** [comment]
sorry to reopen.

The record dates have not been recognised. Is it because the year was not supplied with 4 digits?

**Comment by GiselleSterry** [comment]
@djtfmartin is there an update on this? Thank you.

**Comment by djtfmartin** [comment]
This is with @sophiathirza i think. We planned to reformat the dates.

**Comment by sophiathirza** [comment]
yes, we have to re-upload the data after reformatting the dates. I will re-upload this week.

@djtfmartin should I also add a year column to the dataset?

**Comment by djtfmartin** [comment]
i dont think so. Just dd/MM/yyyy will suffice

**Comment by GiselleSterry** [comment]
thanks.

**Comment by sophiathirza** [comment]
I have re-uploaded the dataset, after reformatting the dates. 

@djtfmartin would you import the data please? There are over 92,000 records in the dataset but only 91,000 in the current dataset online. So it looks like not all of the records imported.

**Comment by MandyHenshall** [comment]
There's still an issue with the dates...
"something still not quite right with the dates. I’m seeing 69,936 records with Year = “Unknown”. Also a bit odd that there are 55 records with licence = “Unknown”. All records should be licenced as CC-BY".
Can you please re-look at this @djtfmartin Thanks.

**Comment by djtfmartin** [comment]
All records have a licence and the dates seems to be parsed ok. closing

**Comment by GiselleSterry** [comment]
Hi @sophiathirza @djtfmartin Still not right. Showing records collected between 2019 and 2029!
Example
https://records.nbnatlas.org/occurrences/3e12f7b3-0ef7-4f48-95fd-9f5d6130ad6d

**Comment by sophiathirza** [comment]
Yes, the dates are okay on the dataset overview page but there are some invalid records dates. I will check the data.

**Comment by sophiathirza** [comment]
The dates are like that in the supplied csv file. I will contact the data providers. 

The csv file contains 92,465 records but there are 95,046 online.

**Comment by sophiathirza** [comment]
We have another copy of the data, which is ready to upload.

**Comment by sophiathirza** [comment]
Dates look perfect on now - brilliant!

Except that the csv file contains 92,465 records and there are 95,046 online, is this because there are records that should be deleted?

**Comment by djtfmartin** [comment]
now showing 92,465

**Comment by sophiathirza** [comment]
All the species names are unknown. It was correct before the records were removed.

**Comment by djtfmartin** [comment]
Looks like the data reverted to the problem with headers we've seen before

```
The data was supplied with the following headings (which are a little garbled or truncated)

RecordKey,UpdatedOn,TaxonVersi,SurveyKey,SampleKey,StartDate,EndDate,DateType,GridRefere,Projection,Precision,SeFsitive,ZeroAbunda,SiteKey,SiteName,SampleMeth,Recorder,Determiner,Abundance,Comment

"TaxonVersi" wasnt recognised.
```

**Comment by sophiathirza** [comment]
that's really strange as I checked it. I'll reupload. I guess I uploaded the wrong file.

**Comment by sophiathirza** [comment]
The data owners had another query about a TVK. Once they let me know the update I will reupload the file.

**Comment by sophiathirza** [comment]
I have reuploaded an updated csv with the updated TVKs and correct headers. @djtfmartin would you reprocess the upload please? thanks. https://registry.nbnatlas.org/dataResource/show/dr1473

**Comment by sophiathirza** [comment]
The scientific names now match for the majority of records. There are 4215 that have not matched. I will close this now. The main issues have been resolved.
