### ISSUE TITLE
Species Inventory - mapping to correct pages

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#286]
The MarLIN (Marine Life Information Network) website links its species pages directly to the NBN and now to the NBN Atlas. We’ve noticed that many of our links to NBN Atlas species pages return no map points, although they do return the relevant page. Then if we search for the same species we finds another page, with map data and images. The pages have different ‘NBN keys’.  Here are a couple of examples.
 
1)      Amphianthus dohnrii links directly to this page  https://species.nbnatlas.org/species/NBNSYS0000188416#overview which has no data or images, text etc and is labelled as “Amphianthus dohrnii (von Koch, 1878) (accepted name Amphianthus dohrnii)” But the search on your site provides (or redirects to ) this page https://species.nbnatlas.org/species/NHMSYS0021053609 which has the correct information (labelled “Amphianthus dohrnii (von Koch, 1878)”. Note the NHMSYS key endings are different.   
2)      Balanus crenatus provides the same issue with https://species.nbnatlas.org/species/NBNSYS0000174080#overview going to a page with no data and a search revealing  the correct page as https://species.nbnatlas.org/species/NHMSYS0021052696 
It affects 90/150 of our species between A and B (A-Z).  Clearly it is a systematic change.
 
What I need to know if the ‘correct’ ‘key’ to use to link directly to the correct species page and information. And then how best to harvest the appropriate ‘keys’ against our species list.

**Comment by sophiathirza** [comment]
Has this been corrected? 

For the two examples given, the maps on MarLIN website look correct: http://www.marlin.ac.uk/species/detail/1120 and http://www.marlin.ac.uk/species/detail/1381

**Comment by djtfmartin** [comment]
Im not sure, probably worth following up on.

Noticed that the NBN link under "Further information sources" is wrong on these pages.
its 

https://data.nbn.org.uk/Search?q=Amphianthus+dohrnii

and should be

https://species/nbnatlas.org/species/Amphianthus+dohrnii

**Comment by MandyHenshall** [comment]
Hi,
The first link goes to "page not found" and the second link doesn't work for me either.  It says "This site can’t be reached. species’s server DNS address could not be found."  Can you let me know which page the link should be on, so I can see if it's something I can change please.
Thanks,
Mandy

**Comment by sophiathirza** [comment]
The second link goes to another version of the name (i.e. https://species.nbnatlas.org/species/NBNSYS0000188416). I think the link should be (using the taxon key): https://species.nbnatlas.org/species/NHMSYS0021053609

**Comment by sophiathirza** [comment]
or should the search without the taxonkey be: https://species.nbnatlas.org/search?fq=idxtype%3ATAXON&q=Amphianthus+dohrnii so it finds all the species names?

**Comment by djtfmartin** [comment]
the former IMO

**Comment by MandyHenshall** [comment]
Now I can see the pages, I'm just confirming that I can't change these links.

**Comment by sophiathirza** [comment]
I have sent a csv of taxon key of the accepted name of each species on the MarLIN website to the website managers. Hopefully they will be able to update their website with the corrected keys.

**Comment by sophiathirza** [comment]
I am going to close this as I have not heard back from the website managers, so I assume that it is all okay.
