### ISSUE TITLE
Vice-county filter not visible in interactive map in NBN Atlas Scotland

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#288]
Reported on Forum: https://forums.nbn.org.uk/viewtopic.php?id=6934

Is working on NBN Atlas - see also our Skype conversation on Friday 7th July.

**Comment by djtfmartin** [comment]
this is resolved.

<img width="1440" alt="screenshot 2017-07-20 10 22 57" src="https://user-images.githubusercontent.com/444897/28410388-75af72e6-6d35-11e7-899d-7f86103b1bd0.png">

**Comment by CEJohnston** [comment]
Thanks very much!
