### ISSUE TITLE
Remove GBIF species data

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#29]

**Comment by djtfmartin** [comment]
This is been done. Data resource pages have also been removed.
cc @EllaVogel @CEJohnston

**Comment by CEJohnston** [comment]
Thanks!

Christine Johnston
NBN Scottish Liaison Officer
tel: 07342254589
email: c.johnston@nbn.org.uk

NBN website: www.nbn.org.uk
NBN Gateway: http://data.nbn.org.uk
Atlas of Living Scotland: www.als.scot

*NBN Trust *- Registered in England and Wales - Company no. 3963387 -
Registered charity no. 1082163
Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL
