### ISSUE TITLE
Facebook log-in for download reporting an error

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#290]
Reported on the Forum:

https://forums.nbn.org.uk/viewtopic.php?id=6934

So I thought I would try to download all the records for the species using my facebook account as the login. This just gives me the error message "
CAS is Unavailable
There was an error trying to complete your request. Please notify your support desk or try again.
"

**Comment by djtfmartin** [comment]
this is now fixed
