### ISSUE TITLE
Searching by Area not working

### ISSUE THREAD

**Issue by JonathanFenn** [nbnuk/nbnatlas-issues#291]
When displaying records from a species list in the atlas, then drawing an area and selecting 'search by area', an error message is returned -  seems to be true of any selection that uses the 'Data Resource' filter.

![searching species list 1](https://user-images.githubusercontent.com/28703497/28015801-909d66ae-6569-11e7-8cbc-55641a3f5297.JPG)
![searching species list 2](https://user-images.githubusercontent.com/28703497/28015802-909d9e1c-6569-11e7-9562-463d6fa3a42d.JPG)

**Comment by djtfmartin** [comment]
this is fixed
