### ISSUE TITLE
Site polygons in three spatial layers displaying as multiple parts

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#294]
Site polygons are displaying as multiple parts in the following layers:

Local_Nature_Reserves_England - eg Ackroyd Drive is showing as four polygons
National_Nature_Reserves_England - eg Ashford Hangars is showing as four polygons
SG_EnvironmentallySensitiveAreas_1996 - eg Argyll Islands is showing as 332 polygons

Can you group each site into a single polygon?  To avoid this problem in the future would ensuring that multi part polygons are grouped in a shapefile be the answer?

**Comment by djtfmartin** [comment]
I looks liked we used the "OBJECTID" as the identifier in these cases. 

Local_Nature_Reserves_England has a LNR_NAME that we should have used to group the polygons.

**Comment by djtfmartin** [comment]
Ive fixed these three layers. To answer the original question:

"To avoid this problem in the future would ensuring that multi part polygons are grouped in a shapefile be the answer?"

no. we just need to select the right field as the identifier within the shape file.
