### ISSUE TITLE
Server unavailable message

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#296]
screen shot attached. Processing for a while and then get server temporarily unavailable message. Unable to cancel / shut down / go back. Greys out the buttons and only way to escape is to shut down the tab.
[server out of service.docx](https://github.com/nbnuk/nbnatlas-issues/files/1141666/server.out.of.service.docx)

**Comment by sophiathirza** [comment]
@GiselleSterry is this still an issue? can we close it?

**Comment by GiselleSterry** [comment]
@sophiathirza - please close.
