### ISSUE TITLE
Something went wrong message

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#297]
When clicking View record on this page, get a "something went wrong" message on the next page https://records.nbnatlas.org/occurrences/search;jsessionid=259EB2A2B5E0E5BEAC3BC1E43A731B06?q=lsid:NBNSYS0000041957&fq=data_resource_uid:%22dr867%22 
![atlas something went wrong](https://user-images.githubusercontent.com/27201815/28113682-7716ca62-66f5-11e7-8088-b5540fc9fc2f.jpg)

The same issue with this record - Species:  Clathrus archeri |  Devil's Fingers Date: 2005-11-12 England OSGR: TQ6835 on https://records.nbnatlas.org/occurrences/search?q=lsid:NBNSYS0000041957&fq=data_resource_uid:%22dr1236%22

And with some in the 53 records on this page: https://records.nbnatlas.org/occurrences/search?q=lsid:NBNSYS0000041957&fq=data_resource_uid:%22dr880%22

**Comment by djtfmartin** [comment]
thanks @MandyHenshall 

there is an issue with viewing records today. im looking into it.

**Comment by djtfmartin** [comment]
this is fixed. there was an issue with the database thats now resolved.
