### ISSUE TITLE
Maps not displaying on GB Non Native Species Secretariat site

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#298]
Hi Dave,
There is an issue with our maps not displaying on the GB Non Native Species website.  For instance, there should be one showing at this page: http://www.nonnativespecies.org/factsheet/factsheet.cfm?speciesId=1668 but there are many other pages, which should have maps.
We had a similar issue when we launched the NBN Atlas with iSpot (e.g from this link, which now works: https://www.ispotnature.org/communities/uk-and-ireland/view/observation/732884/herring-gull-2cy) and I think Duncan did something really quickly to resolve it, but I can't remember what!  Can you help with this please?
Thanks,
Mandy

**Comment by sophiathirza** [comment]
The problem is due to the change in url of the web service. They would like to use EasyMaps but are holding off from adding the maps to their site until the problem with absence records displaying on the map is resolved.

**Comment by sophiathirza** [comment]
The change to the EasyMap shim code has been made (see #280), the update needs to be copied to production.

**Comment by sophiathirza** [comment]
The GB Non Native Species website will now start using EasyMaps on their website.
