### ISSUE TITLE
Create edit search button to amend spelling mistakes etc in a search

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#30]
[http://species.als.scot/search?q=barn+ow%3B](url)

**Comment by djtfmartin** [comment]
This is now achieved by setting the search value in the navbar search.

<img width="886" alt="screenshot 2016-05-04 17 15 49" src="https://cloud.githubusercontent.com/assets/444897/15020899/fc10eda4-121b-11e6-893d-8385ed5e5e82.png">
