### ISSUE TITLE
Error 500: Internal Server Error

### ISSUE THREAD

**Issue by PurbaChoudhury** [nbnuk/nbnatlas-issues#301]
A new user, Janet Khan at SEPA has alerted me to this error she received when trying to register for the NBN Atlas for the first time.  

Is there some internal server issue with the Atlas today (Friday 14 July) or is it something that the new user is doing incorrectly?

![unable to open my account](https://user-images.githubusercontent.com/27347854/28217217-4bb6d714-68ac-11e7-8613-aef8c9276c0d.JPG)

**Comment by GiselleSterry** [comment]
@djtfmartin please close - user error.
