### ISSUE TITLE
Occurrence status not shown in a download

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#302]
Email received from the MBA:
For the Shore Thing dataset (https://registry.nbnatlas.org/public/show/dr1366) the occurrence status is not shown in the download. If you view individual records on the atlas you can see whether they are recorded as presence of absence, but on download one might assume that all records are presence.
 
Please can you add OccurrenceStatus for this dataset?

Sorry, not sure if this is a bug or enhancement, so I've selected both!

**Comment by djtfmartin** [comment]
done.
