### ISSUE TITLE
Download of shapefiles not including grid refs

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#303]
"I have recently tried to download the location for Fairy Shrimp from the NBN Gateway, and when I click on Darwin Core download as a csv file it doesn’t contain the location (grid reference) of the data? I was hoping to be able to map it in ArcGIS. I have also tried to download as a shapefile and it won’t work. Not sure how to get it to download the location."

I tested and got the following fro csv file.
[records-2017-07-20.zip](https://github.com/nbnuk/nbnatlas-issues/files/1161693/records-2017-07-20.zip)

**Comment by djtfmartin** [comment]
Grid references arent in darwin core as such.

For now, if the user downloads the default "simple spreadsheet" this contains grid references.

**Comment by GiselleSterry** [comment]
Ok - thanks.

**Comment by GiselleSterry** [comment]
Extra comment from user.
"Thanks very much for sending through the data. I just tired downloading the data as a shapefile and it looks like it works fine.  However when you download the data it looks as if there is a zip file within a zip file. So you have to unzip the file twice.. I’m not sure if that is intentional but just thought I would flag it up."

**Comment by djtfmartin** [comment]
its intentional.

**Comment by GiselleSterry** [comment]
update from user: I selected simple spreadsheet format and shapefile. Then clicked on the email to download the shape file – unzipped both folders and the shape file was empty.

**Comment by djtfmartin** [comment]
There was a problem with generating shapefiles for less than 10k records.  This is now fixed.
