### ISSUE TITLE
Shape files empty when downloading data from NBN Atlas

### ISSUE THREAD

**Issue by PurbaChoudhury** [nbnuk/nbnatlas-issues#305]
James Memory rang today as he was downloading shape files of the species Arctica Islandica and all the shape files he downloaded were empty.  Is this a bug we are aware of?

If it is a bug, or if he is using the NBN Atlas incorrectly, and he should be able to access the data he has tried to download, please could someone phone James back to inform him on 0207-6349910?

Thanks, Purba

**Comment by djtfmartin** [comment]
Thanks @PurbaChoudhury 

Yes. We have an issue with shapefiles currently.

**Comment by djtfmartin** [comment]
There was a problem with generating shape files for less than 10k records.  This is now fixed.

**Comment by djtfmartin** [comment]
<img width="1439" alt="screenshot 2017-07-22 10 40 37" src="https://user-images.githubusercontent.com/444897/28490142-4fa07a32-6eca-11e7-94f4-55462d96f006.png">
