### ISSUE TITLE
no data showing on Atlas as at 11.09 on 25 July

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#306]
email sent - no datasets / records showing on NBN Atlas

**Comment by djtfmartin** [comment]
back up. there was a problem with index generation. We've reverted to a backup.
@SarahHyslop

**Comment by SarahHyslop** [comment]
Thanks Dave.  I have informed someone that its back up but they have advised they are still having issues; 'The records are now on the NBN atlas but their position on the map still isn't showing, I have tried a few different species. I think there is still some sort of problem'
![atlas screen shot](https://user-images.githubusercontent.com/26628372/28576105-ccaea1c0-714a-11e7-900e-00a76a163926.png)

**Comment by djtfmartin** [comment]
thanks @SarahHyslop . can you include a link ?

**Comment by SarahHyslop** [comment]
Ive gone back to the user to ask for this, will put it here once they reply 

Thanks

**Comment by SarahHyslop** [comment]
Here is an example: https://species.nbnatlas.org/species/NBNSYS0000005135 This shows there are 4,439 records of Harbour Seals but no representation on the map. For some species it is working and some not.
