### ISSUE TITLE
Unable to log in to the Atlas

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#308]
I have a couple of people who are unable to log into the Atlas who previous could log in. They are logging in with their username rather than email address.

**Comment by GiselleSterry** [comment]
Are they trying to use their old Gateway log in - do you know where to find the list of registered users? @sophiathirza

**Comment by sophiathirza** [comment]
I don't know whether they have Gateway logins, just that they use a username rather than their email address.  No, could you let me know where the list of registered accounts is? thanks.

**Comment by GiselleSterry** [comment]
do you want to skype me?

**Comment by sophiathirza** [comment]
I think that they were using old Gateway accounts
