### ISSUE TITLE
issue with download of shapefile

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#312]
From a user;

I tried to download a shapefile of Funiculina quadrangularis records and get the following download failure notification from data@nbnatlas.org Any ideas?

The download has failed. uniqueId:a350ac1f-6d70-3c0c-b8cb-ed52ec443bc1-1501239913983 path:/a350ac1f-6d70-3c0c-b8cb-ed52ec443bc1/1501239913983/records-2017-07-28.zip

**Comment by djtfmartin** [comment]
Ive just done this with no problems....

**Comment by djtfmartin** [comment]
Theres seems to be a problem for some queries if users select "Full darwin core" and "shapefile". If they select "Simple spreadsheet format" - which is the default,  with shapefile then theres no problems.

@SarahHyslop Can you suggest this to the user as a workaround ?

**Comment by SarahHyslop** [comment]
Thanks Dave, I've gone back to the user with this information.

**Comment by CEJohnston** [comment]
@sophiathirza @djtfmartin  A natterjack toad download has the same problem - do we know why this is happening and when the Full Darwin Core download will work?

**Comment by sophiathirza** [comment]
We've done a lot of work on the downloads. Closing for now
