### ISSUE TITLE
Tidy up National Plant Monitoring Scheme (NPMS) datasets

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#314]
It looks like the NPMS datasets were originally uploaded to the BRC provider. Now NPMS have their own page.

1. Is it possible to move https://registry.nbnatlas.org/public/show/dr1290 to under NPMS: https://registry.nbnatlas.org/public/show/dp192? Or does it have to be re-uploaded?

2. https://registry.nbnatlas.org/public/showDataResource/dr1519. Is this an older version of the new dataset under https://registry.nbnatlas.org/public/show/dp192 (dr1485)? If so, we must delete it. If it is deleted can the LSID be added to dataset dr1485?

3. Dataset https://registry.nbnatlas.org/public/show/dr1290 does not have an LSID, should it have one?

**Comment by djtfmartin** [comment]
thanks @sophiathirza. Quick answers.

1. This is done through the collectory. We need to show you how. No reload required.
2. I dont know.
3. no.

**Comment by sophiathirza** [comment]
Can you explain the LSIDs to me please?

**Comment by sophiathirza** [comment]
Point 1 has been done. I need to check that the original dataset (dr1519) can be deleted.

**Comment by EllaVogel** [comment]
I've checked with David Roy about whether one of them can be deleted. I'll keep you both posted on how we need to proceed.

**Comment by EllaVogel** [comment]
We can delete dr1519 (https://registry.nbnatlas.org/public/showDataResource/dr1519) as it is an old version of dr1485 (https://registry.nbnatlas.org/public/show/dr1485). The old version has a LSID (GA001431) associated with it (which I assume got carried over from the Gateway) that is useful to the BRC and National Plant Monitoring Scheme, can we link this LSID with the new version of the dataset once the old is removed? @djtfmartin

**Comment by EllaVogel** [comment]
Additionally, a question from Oli Pescott: Presumably if you can’t move the LSID then it is fulfilling the same function as a unique DOI for a dataset version, suggesting that you will probably be getting rid of them at some point?

Is he correct in thinking that the LSID and the DOI are fulfilling the same function, and therefore the LSID may be irrelevant?

**Comment by sophiathirza** [comment]
Yes, my understand is that LSID and DOI are fulfilling the same function.

@djtfmartin please would you delete dr1519?

**Comment by sophiathirza** [comment]
Both NPMS datasets are now shareable with GBif.
