### ISSUE TITLE
Precision range mismatch under data assertions

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#315]
Records are being flagged as having precision range mismatch, even when the coordinates are correct.

**Comment by sophiathirza** [comment]
@reupost  an you investigate what the problem here is please?

**Comment by reupost** [comment]
Could you give me an example please?

**Comment by sophiathirza** [comment]
Here are quite a few: https://records.nbnatlas.org/occurrences/search?q=spider&fq=assertions%3A%22precisionRangeMismatch%22

**Comment by sophiathirza** [comment]
Resolved.
