### ISSUE TITLE
Records upload with lat/long coordinates do not appear on the grid map

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#316]
They only appear as points on the maps.

**Comment by sophiathirza** [comment]
Most of the recent new data resources use lat-long coordinates rather than grid references and so the records are not visible on the grid map. I have another 12 datasets from a data provider all with lat-long coordinates. Could you have a look at this as soon as possible, please?

**Comment by reupost** [comment]
I'll look at this today.

**Comment by reupost** [comment]
This looks to be a biocache processing issue, I don't think its a problem with the records module per se.  I'll see what I can do, but is it possible to populate the grid reference before loading these datasets?

**Comment by sophiathirza** [comment]
We are getting more and more records with lat-long coordinates. I would prefer not to have to process all of them each time to add GRs, it will be too much.

**Comment by reupost** [comment]
dr864 is good example of this. Need to add gridreference_p to cassandra schema, and make changes to biocache-store processing to populate this field and indexing to index it. The grid reference resolution (cell size) will need to depend on coordinateUncertaintyInMeters. If this is not provided then assume highest resolution(?). If geodeticDatum is not provided assume WGS84(?). JS code to convert lat/lon to grid can be found here: https://cdn.rawgit.com/chrisveness/geodesy/v1.1.3/osgridref.js

**Comment by sophiathirza** [comment]
Records are now displaying on the grid map - thanks.
