### ISSUE TITLE
Records not showing on map

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#318]
Email received 3/8/17 from MSC

I see that our Basking Shark dataset has now been uploaded, however there appears to be a problem with the data as nothing is showing on the map. https://records.nbnatlas.org/occurrence/search?q=data_resource_uid:dr1488#tab_chartsView

**Comment by sophiathirza** [comment]
The data only shows when the map is viewed as points rather than grid. I reported the issue: #316. I will contact the MSC directly.

**Comment by sophiathirza** [comment]
I have emailed Charlotte, letting her know about the problem. I will close this issue as we have it logged already.
