### ISSUE TITLE
Mismatch between common species names in search results and records

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#319]
Comment from the Forum:
I had to think twice when I just saw "Green Plover" in a set of records before recalling that this is another name for Lapwing. I was just wondering why this was the common name given. I haven't used Recorder 6 for a while but I don't recall it ever being the recommended common name? Possibly a quirk, or to do with the other remaining taxonomy/Species Inventory issues? What makes me think this is an atlas bug is that if you *search* for Vanellus, the common name given is Lapwing not Green Plover. but all the records say Green Plover.
e.g. 
[https://records.nbnatlas.org/occurrences/322e39af-b5c3-4815-aef4-447e73165a7f](url)
Common name    Green Plover 
Supplied common name "Lapwing"

compared with
[https://species.nbnatlas.org/search/?q=vanellus](url)
species: Vanellus vanellus (Linnaeus, 1758)  – Lapwing
Lapwing, Peewit, Northern Lapwing, Green Plover
Taxon group: bird
Vanellus vanellus
Vanellus vanellus (Linnaeus, 1758)

see also [https://records.nbnatlas.org/occurrences/search?q=lsid:NBNSYS0000000027#tab_mapView](url)

And from a 2nd post:
...... the same issue is occurring with "Continental Goldcrest" (in records) and "Goldcrest" (taxon page)

@djtfmartin - can the preferred common name - such as Lapwing, Goldcrest - be applied to both the species pages and the records?

**Comment by sophiathirza** [comment]
In the latest DwC-A based on the UKSI, Lapwing is the preferred common name. We should display the preferred common name on records pages.

**Comment by sophiathirza** [comment]
This is the same problem: #259

**Comment by CEJohnston** [comment]
Green Plover is still showing as the common name.

**Comment by sophiathirza** [comment]
The preferred common name is now showing in both the species and records components - thank you!
