### ISSUE TITLE
Advanced search - vice counties and other menus drop downs are not working

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#320]
We have been notified that the vice counties drop down menu doesnt work within the advanced search - https://records.nbnatlas.org/search#tab_advanceSearch 

This did work at first for me but now doesnt work at all.  Some of the other drop down menus are also not working.

**Comment by djtfmartin** [comment]
This is now fixed.

<img width="1440" alt="screenshot 2017-09-10 10 08 21" src="https://user-images.githubusercontent.com/444897/30247597-07158d3a-9610-11e7-8a57-ae30f23c9c54.png">
