### ISSUE TITLE
Search feedback for Odiellus spinosus

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#321]
Feedback from a user;

I am not impressed by the new search facility - I searched for 'Odiellus spinosus' and with the default settings Odiellus is not even on the first page! Odiellus does not appear until the 4th page, this does not, even setting order to 'best match' and 'ascending' it is on the second page!

Note from Sarah;

Is there a way to reorder / solve this issue?

Thanks

**Comment by djtfmartin** [comment]
Ive removed the boost by occurrence count as it has an adverse affect on exact matches.
