### ISSUE TITLE
"Best match" results issue

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#322]
Email from a user:
I just searched NBN for the bat-fly: Basilia nana.
It found 139 results. It claimed to present the results in descending order of “best match” but the first match was Betula nana. Basilia nana was at the foot of page 6. I clicked on it and it said “0 records” and showed me a map of Africa (presumably centred on lat/lon 0,0).
You’ve got a lot more development to do to make the new NBN work properly!

Sorry Dave.

**Comment by djtfmartin** [comment]
Ive removed the boost by occurrence count for now as it appears to problematic.

https://species.nbnatlas.org/search/?q=Basilia+nana

is now performing better.
