### ISSUE TITLE
Fallopia japonica | Janapese Knotweed

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#325]
Spelling error on NBN Atlas for 'Common Name'. When create list of record spelling error shows up but not on the overview page.

We were featured in a BBC article over the weekend about this so would be good to correct spelling asap.

http://www.bbc.co.uk/news/business-40899108

**Comment by sophiathirza** [comment]
@djtfmartin does this text come from the UKSI? Is it possible to correct the spelling error?

**Comment by djtfmartin** [comment]
it comes from UKSI. UKSI has several variants for the name. We need a mechanism for prioritising the common names which is missing from our name matching indexes. Something to tackle with the new UKSI export.

**Comment by sophiathirza** [comment]
Notes:
Japanese knotweed is the preferred name
Janapese Knotweed is a recommended name - but is has been crossed out in the UKSI search. We need to check the next version of the UKSI to see if it is included.

**Comment by sophiathirza** [comment]
Janapese Knotweed is still a recommended name in the latest version of the UKSI.

@djtfmartin what is the best way of selecting the preferred common name. Should I add a field to the taxa table for it?

**Comment by djtfmartin** [comment]
for the namematching, we dont have a mechanism. quickest thing might be to just blacklist it in the script thats producing the DwCA

**Comment by sophiathirza** [comment]
Include water rat as well. The preferred common name for Arvicola amphibius is water vole.

**Comment by sophiathirza** [comment]
Added common name black list to the UKSI import script. Janapese Knotweed  and Water Rat are no longer in the vernacular csv file.

**Comment by JoJudge** [comment]
@sophiathirza Can this be closed now?

**Comment by sophiathirza** [comment]
No, we still need to update the UKSI on the Atlas.

**Comment by sophiathirza** [comment]
Janapese Knotweed and Water Rat have been removed from the Atlas.
