### ISSUE TITLE
Cylindrocystis gracilis and other species list order

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#326]
Apologies if this has already been posted, but I can't see it on here.  Posts from the NBN Forum on 6th August by Chris Johnson at https://forums.nbn.org.uk/viewtopic.php?id=6799 
>> Today, when I search for the species it appears top of the list, so looks as though something has been done to correct the listing, but there are no records for all of the Cylindrocystis on the first page and the map defaults to Africa, e.g.: https://species.nbnatlas.org/species/NHMSYS0000601978

**Comment by djtfmartin** [comment]
As far as I can see this is all expected behaviour. We dont have records for Cylindrocystis gracilis.

The map should centre on UK when theres no records, but this is minor issue.

**Comment by MandyHenshall** [comment]
I have posted to update the Forum, but this response has now been posted.  I'm not sure how it should be appearing so need advice regarding our response please:
>> I'm a little puzzled by this one as well - why are there two entries for Cylindrocystis gracilis in the search results, both of which link to the same key - and why is there two entries for Cylindrocystis obesa (as C. gracilis) but one appears at position 4 and another appears at position 10 in the list rather than next to each other as C. gracilis?

**Comment by djtfmartin** [comment]
https://species.nbnatlas.org/species/NHMSYS0000601978#names

the species inventory has provided a synonym "Cylindrocystis gracilis" for Cylindrocystis gracilis. Im not sure why. Could be a taxonomic synonym.

**Comment by sophiathirza** [comment]
Notes:
The current DwC-A has a single entry in the taxon file for both of these as synonyms. In the UKSI they are both accepted names. The tvk from the UKSI is in the acceptedNameUsageId field of the taxon file.

**Comment by sophiathirza** [comment]
This is consistent with the UKSI online search: Cylindrocystis gracilis I.Hirn, 1953 has the synonym Cylindrocystis gracilis (which is flagged as being ill-formed). The Atlas search looks correct but I will leave this open until after we have updated the species inventory.

**Comment by sophiathirza** [comment]
This looks okay with the new UKSI. There are two records for Cylindrocystis gracilis.
