### ISSUE TITLE
Downloads taking too long

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#327]
Post on the NBN Forum from Charlie Barnes:
I initiated a large download on the 9th, and due to it's size (and expected duration) closed the browser and waited for the email with the link. This hasn't arrived yet and there doesn't seem to be a way view pending or previous downloads.
Should downloads take this long (two days?) or has the email got lost in the post?

**Comment by MandyHenshall** [comment]
Follow up post today from Charlie:
There seems to be a delay from a dataset appearing on the NBN Atlas to records actually being visible. This is fine - I assume there is some data propagation going on - but how long should we be expecting to wait before the dataset is "usable"?
(as an example, I can't see any records for datasets with metadata last updated on 2017-08-09)
Might be worth considering altering the "new datasets" logic when sending out alerts if this ~week delay is standard?

**Comment by djtfmartin** [comment]
There was a couple problematic downloads that blocked the queue of the weekend. Still investigating the cause, but its now working properly.
