### ISSUE TITLE
Apply bootstrap3 template for data partners

### ISSUE THREAD

**Issue by djtfmartin** [nbnuk/nbnatlas-issues#33]
Apply bootstrap3 template for data partners - template was provided by RedPaint in bootstrap3.
Requires updating collectory app to use bootstrap3 (2 weeks work).

**Comment by EllaVogel** [comment]
#144

**Comment by djtfmartin** [comment]
Still to be done. The registry is now in bootstrap3, so applying the template should be relatively straightforward

**Comment by c-van-dierkson** [comment]
@reupost Do we still need this?

**Comment by c-van-dierkson** [comment]
RR confirms this has been done.
