### ISSUE TITLE
Cladonia chlorophaea - large number of matches for same binomial

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#330]
See posts below, but please note the comment "about the lack of progress on this issue?" These posts are from yesterday and today. https://forums.nbn.org.uk/viewtopic.php?id=6971

> This is a continuation of a thread started in March this year on NBN Atlas Scotland which I have now moved because there appears to be no progress at all on sorting out the confusing and misleading search results.
My latest example is as follows, how can you expect the general public to use the Atlas when presented with the following!
If you search for Cladonia chlorophaea the following appears:
Cladonia chlorophaea (Florke ex Sommerf.) Spreng. (accepted name Cladonia chlorophaea)
Cladonia chlorophaea (accepted name Cladonia chlorophaea)
Cladonia chlorophaea (Flörke ex Sommerf.) Spreng. Occurences 31
Cladonia chlorophaea (Flörke ex Sommerf.) Spreng. Occurences 86
Cladonia chlorophaea agg. (accepted name Cladonia) (this gives 50,111 records of all Cladonia species)
Cladonia chlorophaea Occurences 2008
Cladonia chlorophaea Occurences 685
If you search for Cladonia chlorophaea agg the following appears:
Cladonia chlorophaea agg. (accepted name Cladonia) (this gives 50,111 records of all Cladonia species)
Cladonia chlorophaea (Florke ex Sommerf.) Spreng. (accepted name Cladonia chlorophaea)
Cladonia chlorophaea (accepted name Cladonia chlorophaea)
Cladonia chlorophaea (Flörke ex Sommerf.) Spreng.Occurences 12
Cladonia chlorophaea (Flörke ex Sommerf.) Spreng. Occurences 31
Cladonia chlorophaea (Flörke ex Sommerf.) Spreng. Occurences 86
Surely, I'm not the only one get hot under the collar about the lack of progress on this issue?

Separate post on same thread:
> I'm gutted as well. I came back to record centre life in June this year after a 9 month stint working for the Co-op. Previously I used the Gateway on a regular basis because of how useful the species search, hierarchy and synonyms were and how easy they were to digest and navigate. I just can't get on with the new version. Perhaps I will feel differently after more exposure.

**Comment by djtfmartin** [comment]
This is a bit of mess but i think its specific to this name. There are 3 taxa with the same binomial "Cladonia chlorophaea" and i think this is causing the issues.

https://species.nbnatlas.org/species/NHMSYS0001477591#classification

Im down grading it as i dont think its that widespread.

**Comment by MandyHenshall** [comment]
There are a number of other examples on the NBN Forum though relating to different species, which I think you have been speaking to Chris Raper about: https://forums.nbn.org.uk/viewtopic.php?id=6799
A further message from Chris Johnson from 6th Aug:

>I have been getting some strange results, the occurrence weighting is biasing the search so that occurrence number overides the name matching.
E.g. Search for Carsia sororiata  produces the following:
Physcia caesia (Hoffm.) Fürnr. (1567)
Postia caesia (Schrad.) P. Karst. (152)
Carsia sororiata (Hübner, 1813) (330)
Rosa canina x caesia = R. x dumalis Bechst. (326)
Rosa caesia subsp. caesia Sm. (647)
Carsia sororiata subsp. anglica Prout, 1937 (42)
Not sure why caesia should come before carsia? The fuzzy matching is producing gibberish.
Ideally the search should produce Carsia sororiata (Hübner, 1813) (330) followed by Carsia sororiata subsp. anglica Prout, 1937 (42) before any of the others, particularly as my search term was Carsia sororiata.
This is not an isolated example, try searching for Caryocolum alsinella.
The top of the list is  Platytes alpinella (Hübner, [1813]) and Caryocolum alsinella is 7th in the list after other Caryocolum species.
It is really important that the search function is sorted as a matter of priority. If you want the Atlas to be accessible to everyone, the search has to be robust and produce the expected results; so that the name I type in the search box appears at the top, followed by the various synonymns, varieties etc. It should not be necessary to scroll down the list to find it.
>

**Comment by djtfmartin** [comment]
These problems where fixed last week - ive removed the ranking based on occurrence count for now as its problematic.

See 

https://species.nbnatlas.org/search/?q=Caryocolum+alsinella

and

https://species.nbnatlas.org/search/?q=Carsia+sororiata

**Comment by japonicus** [comment]
For both of those example searches a non-accepted name comes first on the results list (the accepted name is the third or fourth entry on the list).

**Comment by djtfmartin** [comment]
Thanks @japonicus. Yes you are right, but the forum post was describing quite a different result.

**Comment by sophiathirza** [comment]
Lichen taxonomy in the UKSI is being updated at the moment, hopeful these problems will be corrected in the new version, which we should receive after the update.

**Comment by sophiathirza** [comment]
The UKSI has been updated. The search results look to be in a sensible order, so I am going to close this issue now.
