### ISSUE TITLE
Delay in Records Appearing

### ISSUE THREAD

**Issue by PurbaChoudhury** [nbnuk/nbnatlas-issues#332]
A comment has been left on the NBN Forum about a download taking 9 days to complete.
Please see: https://forums.nbn.org.uk/viewtopic.php?id=6968

Thanks.

Purba

**Comment by djtfmartin** [comment]
There was a couple problematic downloads that blocked the queue of the weekend. Still investigating the cause, but its now working properly.

This was also reported here by @MandyHenshall #327
