### ISSUE TITLE
Bombus sylvestris incorrect image?

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#333]
Feedback from user;

Just trying to be helpful.  You illustrate this map (Bombus sylvestris) with an image but the bee in the picture is not that species.  Bombus sylvestris is a cuckoo bee and does not collect pollen.  I suspect that the photo is B. pratorum.

https://species.nbnatlas.org/species/NHMSYS0000875498

**Comment by CEJohnston** [comment]
No images for this species are showing now. Issue closed.
