### ISSUE TITLE
Adding the species name to an image which is currently missing 

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#335]
A comment to images from a user: https://images.nbnatlas.org/image/details/5880889

In this image, not species/taxon name is given, which seems to be the most relevant bit of information in a site about biodiversity?
<img width="760" alt="nbn_network" src="https://user-images.githubusercontent.com/26628372/29404757-d006df9a-8333-11e7-8568-59675cf37bf1.PNG">

**Comment by CEJohnston** [comment]
@sophiathirza this image is still showing without a name.

**Comment by sophiathirza** [comment]
Requirements have been written to improve the image presentation on the Atlases.

**Comment by c-van-dierkson** [comment]
ok to close
