### ISSUE TITLE
Spatial portal not working?

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#338]
Hi Dave,

Is there an issue with the portal at the moment?  However I try and get to "analyse", the website is just whirring and not going anywhere....

Mandy

**Comment by MandyHenshall** [comment]
After the 3 minutes since I posted I got this error message:
![image](https://user-images.githubusercontent.com/27201815/29515545-bedab622-8664-11e7-8af4-14533c5ba1a5.png)
If this server error comes up, we need to change this to relate to the NBN Atlas and the support@nbnatlas.org email address rather than ALA.

**Comment by djtfmartin** [comment]
its back up.
