### ISSUE TITLE
New download tool is offline

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#341]
I've just downloaded all of the Japanese Knotweed data as a test, and the new download wizard didn't come up. I was able to download, but using the old system. Is this intentional?

**Comment by djtfmartin** [comment]
Not intentional. What tool did you use to download the data ?

**Comment by EllaVogel** [comment]
It was just the old tool where the download is direct from the Atlas, not queued and then emailed. I think I just downloaded direct from the records list.

**Comment by djtfmartin** [comment]
I cant reproduce this. Please reopen if you know the source of the download.
