### ISSUE TITLE
Licence information isn't downloading for all of the records.

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#342]
I downloaded all of the Japanese knotweed records, and in the 'citation' file, column E 'Rights' doesn't always have a licence listed, and on these rows, column B 'Name' has the data partner name, not the dataset name (and the 'more info' link (column F) takes you to the whole data partner page, not the dataset page for the specific dataset that the records came from). Therefore, data users will have a hard time finding the licence info for the whole download.

**Comment by djtfmartin** [comment]
this information comes (and can be changed using the admin UI) from the registry.nbnatlas.org. So we need to update the "Rights" field for datasets.

**Comment by EllaVogel** [comment]
I'm not sure this is the issue (or I'm not understanding properly).

For example, in the citation download, we are given 'Derbyshire Wildlife Trust' instead of the dataset that the info comes from. Looking at their page, I can make an assumption which dataset holds the Japanese knotweed data, but for other data partners it wont be so obvious. Also, the dataset that holds the Japanese Knotweed data is licensed and does have the licence under the 'rights' sections, so there is nothing for me to update.

The issue is that it's pulling the dp info for 'name' column, not the dr info

**Comment by djtfmartin** [comment]
Im not sure i follow either, but hopefully this helps:

The citation.csv should have both the data partner as a line and the dataset (ive just tested and this looks ok).
The data partners don't have a "rights" field, so this is always blank.

**Comment by djtfmartin** [comment]
> The issue is that it's pulling the dp info for 'name' column, not the dr info

Im not seeing this behaviour in the downloads ive tested.

<img width="1424" alt="screenshot 2017-08-29 14 02 11" src="https://user-images.githubusercontent.com/444897/29822239-b0bc6216-8cc2-11e7-847f-67f1b6f0e652.png">

**Comment by EllaVogel** [comment]
I'll email you the download that I have. It's not letting me upload here.

**Comment by djtfmartin** [comment]
closing as there doesnt seem to be an issue. Perhaps we should raise enhancements to separate the citations or add additional columns to help sorting.
