### ISSUE TITLE
Issue with viewing Prionocera turcica record

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#343]
A user reported trying to get some information from the Atlas earlier today - details of two taxon records for Prionocera turcica - one provided the information without a problem while the other gave this error message:
Something went wrong....
•	Error: unknown
•	Failed to get json from web service (https://records-ws.nbnatlas.org/occurrence/385e2aa9-7db7-437a-966a-79f35630f7dc). class java.io.IOException Server returned HTTP response code: 500 for URL: https://records-ws.nbnatlas.org/occurrence/385e2aa9-7db7-437a-966a-79f35630f7dc, java.io.IOException: Server returned HTTP response code: 500 for URL: https://records-ws.nbnatlas.org/occurrence/385e2aa9-7db7-437a-966a-79f35630f7dc
The records were:
Species:  Prionocera turcica Date: 1969-08-02 Scotland OSGR: NF66
Data Resource: Cranefly (Diptera; Tipuloidea) Records For Britain To 2007 View record
Species:  Prionocera turcica Date: 1988-07-14 Scotland OSGR: NF7322
Data Resource: Cranefly (Diptera; Tipuloidea) Records For Britain To 2007 View record

The first (NF66) worked fine on clicking 'View record', the other - repeatedly - does not.

**Comment by djtfmartin** [comment]
this was the same as #344. Fixed
