### ISSUE TITLE
Error messages when searching

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#344]
Another issue with searching has been reported (on Sunday) and I have just tried a general search, some records are fine, but for others I am also getting this error message when clicking the grid square on occurrence records and then view records.

Message, as follows:

I have been looking at some liverwort records from Buckinghamshire and keep getting an error message as follows.  I can get without problem to the list of records of the particular species for Bucks  but when I want to see the actual record then the following appears.  Certainly I have had no problems previously

•	Error: unknown
•	Failed to get json from web service (https://records-ws.nbnatlas.org/occurrence/5848f4ae-6f5e-4f51-9cc2-a40720d70793). class java.io.IOException Server returned HTTP response code: 500 for URL: https://records-ws.nbnatlas.org/occurrence/5848f4ae-6f5e-4f51-9cc2-a40720d70793, java.io.IOException: Server returned HTTP response code: 500 for URL: https://records-ws.nbnatlas.org/occurrence/5848f4ae-6f5e-4f51-9cc2-a40720d70793

**Comment by djtfmartin** [comment]
I fixed this this morning.
