### ISSUE TITLE
No login on mobile device

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#346]
We have been alerted to the fact that there is no ‘log in’ button or sign-in link on the NBN Atlas on iPhone.  I've tried and this is correct.  Not sure whether it's just iPhone or all mobile devices.

Not sure if this is you Dave or RedPaint?

**Comment by EllaVogel** [comment]
I think this is on all devices, as even if you just shrink the internet browser right down on your computer screen the log-in button goes as well.

**Comment by GiselleSterry** [comment]
As a workaround I have added  a log in link on the top navigation menu so when you tap on the three lines box the option to log in is displayed.
