### ISSUE TITLE
Intermittent problem with Location Search

### ISSUE THREAD

**Issue by PurbaChoudhury** [nbnuk/nbnatlas-issues#347]
On some internet browsers (particularly Microsoft Edge and sometimes intermittently on Google Chrome) the Location search "Explore by address, postcode or location" is not working intermittently.

When typing in a postcode or name of a place, after pressing the "Search" button, the postcode/words  that have just been typed in the "Enter your location or address" box, DISAPPEAR, and the search doesn't work - so no species results are given and no map appears either.

This appears to be an intermittent bug - sometimes it works and other times it doesn't - with no rationale that's obvious to the Atlas user why the location search sometimes doesn't work.

**Comment by djtfmartin** [comment]
@PurbaChoudhury 

I think this is now fixed with the latest update. Can you test and confirm ?

**Comment by sophiathirza** [comment]
@djtfmartin would you give me a bit of information about what the problem was, so that I can reply to an email that reported this problem, thanks?

**Comment by djtfmartin** [comment]
I think the problem was a javascript caching issue. Can i close this ?

**Comment by sophiathirza** [comment]
thanks, I will reply to the email and ask the person to test. I'll close when I hear back, thanks.

**Comment by sophiathirza** [comment]
This is working correctly now.

**Comment by PurbaChoudhury** [comment]
Hi @djtfmartin and @sophiathirza 
I have tested this now (13 Sept) and the Location search is working when I access the NBN Atlas via the Microsoft Edge browser.  However, as it was an intermittent problem, (ie the Location search did work some of the time and not other times) even when I raised it, we will only know for sure if this is working if we never get a repeat of the postcode or name of place just typed disappearing!
