### ISSUE TITLE
Record missing from dr890

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#350]
NBN Atlas should have a record from the Isle of Raasay (NG578395) for "Clavaria fragilis Fr." (TVK=NBNSYS0000144600), recommended name "Clavaria fragilis Holmsk." (TVK=NHMSYS0001477796). 

Dataset: https://registry.nbnatlas.org/public/show/dr890

The dataset has 11 entries for NHMSYS0001477796 and none for NBNSYS0000144600.

**Comment by sophiathirza** [comment]
@djtfmartin would you give me access to download the DarwinCore zip for dr890, please?

**Comment by djtfmartin** [comment]
this is fixed. The previous index rebuild had an issue.

https://records.nbnatlas.org/occurrences/search?q=data_resource_uid%3Adr890&fq=species%3A%22Clavaria%20fragilis%22

https://records.nbnatlas.org/occurrences/d30a2888-9073-4b13-93c9-cc31df2dfa39
