### ISSUE TITLE
Species search in Explore by address, postcode, location isn't working correctly.

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#352]
If I type in fox for instance it takes me to a map of New York!  If I type in bat it takes me to Kota Batu in Indonesia.

![image](https://user-images.githubusercontent.com/27201815/30104008-41d30776-92ec-11e7-931b-3d44c864a6bc.png)

**Comment by djtfmartin** [comment]
The results are a bit silly, but im not sure what the expected behaviour is here. The search box is for an address.

**Comment by djtfmartin** [comment]
Ive added a filter to remove answers outside of UK. Not sure what else to do for this so will close.
The search box is clearly intended to take a location rather than a taxon.
