### ISSUE TITLE
Download to full Darwin Core missing occurrenceStatus field

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#353]
Testing the download for natterjack toad records (in NBN Atlas Scotland) - downloaded to the full Darwin Core but need the occurrenceStatus field in order to filter records by present or absent. It appears not to be included.

**Comment by sophiathirza** [comment]
In addition, we have had a request that the fields 'habitat' and 'comments' be added to the DwC download. These are the names from the Gateway, I need to find out what the DwC terms are.

**Comment by sophiathirza** [comment]
The request is to have the additional properties on a record included in the download file. Is this possible? I imagine that it is not so straightforward as the properties may be different depending on the record.

**Comment by sophiathirza** [comment]
#111 lists additional fields to be included in downloads.

**Comment by sophiathirza** [comment]
Request from Jo to have the NBN Exchange format equivalent term added to the darwin core downloads.

**Comment by sophiathirza** [comment]
I missed this one with the updates.. still on occurrenceStatus in the full darwin core downloads!

Please also add coordinateUncertaintyInMeters to the full darwin core download.

**Comment by sophiathirza** [comment]
brilliant - thanks.
