### ISSUE TITLE
Add species filter to location search

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#354]
After completing a search by location, the ability to filter or search on the species list would be really useful.

**Comment by sophiathirza** [comment]
The request came from an ecologist who said that 2km radius is more commonly used in consultancy.  @djtfmartin can we add 2km to the search radius dropdown? Is it very simple to do? This would help as it would mean that less species are returned.

**Comment by djtfmartin** [comment]
Ive added the 2km radius for explore your area.
