### ISSUE TITLE
Intermittent problem clicking on 100km hectad links

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#356]
Reported by email:

None of the 100km hectad links works on https://records.nbnatlas.org/occurrences/search?q=lsid:NBNSYS0000030336#tab_mapView.  Hover on, e.g. NX, and the pointer changes but no link opens.
 
This problem appears unpredictably and inconsistently.

**Comment by sophiathirza** [comment]
@djtfmartin could there by another script caching on the page? I have never had this problem but it was reported by someone who wasn't able to use the location search until the update.

**Comment by djtfmartin** [comment]
Im not sure. I suggest we ask the user for the OS and browser.

**Comment by sophiathirza** [comment]
I was able to recreate this.

I did a species search (Tinca tinca), clicked on view map and the grids were clickable. I viewed a few records and then clicked the back button on the browser. From then on the grids were no longer clickable. I had to close and reopen the browser.

**Comment by sophiathirza** [comment]
OS and browser from the user:

W10, I use Opera 47.0 as default, but have just checked in Chrome 61.0.3163.79 and Edge 40.15063.0.0.
 
The page has worked fine in all these before, and right now is failing as described in Opera and Chrome, but working in Edge.

**Comment by djtfmartin** [comment]
i think this is fixed. A bug introduced in the last update.

**Comment by sophiathirza** [comment]
I can't recreate it any more, thanks. I have asked the users to check.

**Comment by sophiathirza** [comment]
I have not heard back, so I assume all is okay now.
