### ISSUE TITLE
Error clicking on records from species overview page

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#358]
I have not been able to recreate this but Jo says that she continually gets the error.
![image](https://user-images.githubusercontent.com/1651015/30316033-1eb5a366-97a6-11e7-9bad-9a9f07290887.png)

This is on the Japanese knotweed overview page.

Is it possible to change the error message to give more details?

**Comment by djtfmartin** [comment]
it happens if the user clicks "view records" before the page has finished loading the charts.

**Comment by sophiathirza** [comment]
Is it possible for the error message to say, please wait for the charts to load?

**Comment by djtfmartin** [comment]
i think we can just fix the problem.

**Comment by sophiathirza** [comment]
that would be best, thanks.

**Comment by c-van-dierkson** [comment]
ok to close
