### ISSUE TITLE
Occurrence page links going to ALA

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#360]
Reported this morning:

on the Occurrence records page e.g.:
https://records.nbnatlas.org/occurrences/search?q=lsid:NHMSYS0020151698#tab_chartsView

If you click on one of the columns in the Vice-county map, it takes you to the Living Atlas of Australia! In fact, most of the links are to:
http://biocache.ala.org.au/occurrences/search?q=...

**Comment by MandyHenshall** [comment]
Further issue reported on the occurrence page:

https://records.nbnatlas.org/occurrences/e8a7db9d-b571-4a28-9246-5f32dfb6c4ea#

it is using the wrong character set or encoding because foreign characters are not displaying properly, see 'Name according to' in the above example page

**Comment by djtfmartin** [comment]
the original issue is fixed. can you raise a separate one for the encoding? its not related.
