### ISSUE TITLE
Add text above occurrence map on species pages

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#363]
The occurrence maps on the species pages display as points, which is confusing people when the data is at a grid scale. Please add some text above the occurrence maps to state that the records may be both point and grid-based occurrences at different resolutions.

I think this is quite important, as we are getting quite a lot of comments about it.

Slightly less important, can the link 'View map' be changed to 'View interactive map', please?

**Comment by sophiathirza** [comment]
Could this issue be squeezed into your work please? I have had some more irate emails about it.

It would also really help to change 'View map' to 'View interactive map', thanks

**Comment by sophiathirza** [comment]
These are included in the requirements document: NBNA Occurrence map enhancement requirements

**Comment by reupost** [comment]
Done, just needs to be pushed to the server.  If 'View interactive map' causes the buttons to wrap onto the next line (as it seems likely to do), would it be ok to have the text 'Interactive map'?

**Comment by sophiathirza** [comment]
Great, thanks. Yes, that would be okay. cheers.
