### ISSUE TITLE
Colour points on occurrence map by their resolution

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#364]
We have had this feedback from a few people. It would help in understanding the occurrence map on the species pages if the points could be coloured reflecting their resolution and a legend added.

**Comment by djtfmartin** [comment]
this is already there. See coordinateUncertainty.

**Comment by sophiathirza** [comment]
on the the species page, the first map the user sees after doing a species search?

**Comment by djtfmartin** [comment]
ah - sorry i missed that.

**Comment by sophiathirza** [comment]
I wonder about doing this because once we have verification at the record level one of the suggestions was to have verified and unverified records displayed in separate colours.

Perhaps we should wait on this on until we have the requirements for verification at the record level?

**Comment by JoJudge** [comment]
Results from the questionnaire at the conference suggested that most people (77% of those who responded) don't want/need colour by resolution by default.
