### ISSUE TITLE
Incorrect encoding for foreign characters

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#365]
Issue reported on the occurrence page (first reported in #360):

https://records.nbnatlas.org/occurrences/e8a7db9d-b571-4a28-9246-5f32dfb6c4ea#

it is using the wrong character set or encoding because foreign characters are not displaying properly, see 'Name according to' in the above example page.

**Comment by djtfmartin** [comment]
Can you check the encoding of the source data ?

**Comment by sophiathirza** [comment]
@reupost is this a display or underlying data issue?

**Comment by reupost** [comment]
Data issue. It will be because the source DwC dataset was not encoded correctly as UTF-8 I think

**Comment by c-van-dierkson** [comment]
ok to close
