### ISSUE TITLE
Datasets - identified but not approached includes datasets with data

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#366]
From a forum post: https://forums.nbn.org.uk/viewtopic.php?id=6985

On the dataset search there are many datasets under the identified but not approached link. It includes species lists but also active datasets. Checking one of the datasets, under data mobilisation there is a field for status, which is set to identified. Is this where the information is coming from?

I assume that none of the species lists or active datasets should appear under this list. @djtfmartin can you help? thanks.

**Comment by djtfmartin** [comment]
its just a field in the database that NBN can use to indicate the status of a resource. these need to be set appropriately. there isnt any downstream affect other than visiblility in the search.

**Comment by sophiathirza** [comment]
okay, thanks. I will change all the species lists and datasets (with data) to have the status: dataAvailable.

**Comment by sophiathirza** [comment]
is there anyway to do it in the db.. there are 719 of them.

**Comment by sophiathirza** [comment]
@djtfmartin can I change these in the database directly?

**Comment by djtfmartin** [comment]
yes. ill talk you through it

**Comment by sophiathirza** [comment]
@reupost would you update these directly in the DB please?

**Comment by sophiathirza** [comment]
It's these datasets that need identified changed to dataAvailable: https://registry.nbnatlas.org/datasets#filters=status%3Aidentified

**Comment by CEJohnston** [comment]
I think this is right.  However some of the species lists appear to be duplicates, eg A Conservation Evaluation of British Lichens and Lichenicolous Fungi (2012) - there is already one classed as 'Data Available' and an additional two that are classed as 'Identified'.  Could you run a report cross checking the names of the 'Identified' lists with the 'Data Available' lists and listing the duplicates so they can be removed before having the flags changed?

Also some 'Identified' lists have meaningless names (eg 123) - I don't know what they are as they won't list in the species list tool -  I do not think they sound useful.

**Comment by sophiathirza** [comment]
Many of the species lists that are labelled as identified are actually empty and are not attached to any species list: https://registry.nbnatlas.org/datasets#filters=status%3Aidentified%3BresourceType%3Aspecies-list

It will take me some time to go through each separately. Is there anyway to tell which datasets don't have species lists attached to them?

**Comment by sophiathirza** [comment]
There are still quite a few datasets (72) that have records but are flagged as identified: https://registry.nbnatlas.org/datasets#filters=resourceType%3Arecords%3Bstatus%3Aidentified

They seem to be the new ones - I don't know if I am doing something wrong or if I should change them manually once the records are correctly loaded. 

Can you change these in the database please? then from now on wards I will update new datasets to indicate that there are records. Thanks

**Comment by reupost** [comment]
These are record datasets, not species lists. Can you confirm that you want all of these changed? We had been discussing species lists, which was the group that I updated.

**Comment by sophiathirza** [comment]
The problem is not just with species lists - there are datasets that have records but are set as identified rather than dataAvailable. I can change them but there are 72 and if it's quick to do it in the database, that would be really helpful.

The comment with the original link is here: https://github.com/nbnuk/nbnatlas-issues/issues/366#issuecomment-407066576. We don't have any datasets/species lists that have been identified but don't have records.

**Comment by reupost** [comment]
Done. It will take 24 hours for the query cache to be refreshed, though.

**Comment by sophiathirza** [comment]
Brilliant - thanks
