### ISSUE TITLE
Missing 'Advanced record search' option in NBN Atlas Scotland

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#368]
Add 'Advanced record search' option to the 'Data and Partners' drop down on the Scottish home page

**Comment by sophiathirza** [comment]
@CEJohnston should the navigation take you to the UK site, as with other options in the dropdown?

**Comment by CEJohnston** [comment]
I think it should take you to the advanced search tab for the Scottish Atlas ie
https://scotland-records.nbnatlas.org/search#tab_spatialSearch

This tab is currently accessed via the 'Search by polygon' drop down under the Locations tab (although it would be more logical if the 'Search by polygon' link landed on https://scotland-records.nbnatlas.org/search#tab_spatialSearch in the first instance?)

**Comment by sophiathirza** [comment]
This is done now. thanks @GiselleSterry
