### ISSUE TITLE
Accessing records via 'Select a habitat to explore' generates an error

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#371]
In the NBN Atlas Scotland under 'HABITATS > Select a habitat to explore' chose Coniferous woodland and its sub-categories and tried to 'View records' via the button at top right.  Generates a Grails Runtime Exception.

![image](https://user-images.githubusercontent.com/18594564/30489114-429a54ea-9a2e-11e7-9d7e-ad0d6e2a1415.png)

**Comment by sophiathirza** [comment]
This is still a problem.

**Comment by reupost** [comment]
Fixed. We need the habitats layer loaded as a normal layer, though. At present I'm referencing another (arbitrary) layer so no records will ever be returned.

**Comment by sophiathirza** [comment]
The underlying layer should be change to Habmos, if we are able to upload the new version  (#383). Could the view records button be hidden in the meantime, please?

**Comment by CEJohnston** [comment]
I agree - thanks to you both!

**Comment by reupost** [comment]
Done.  I also hid the other left-hand button that is supposed to take you to a region-style page showing occurrence records for a particular habitat, because that was also defective.

**Comment by reupost** [comment]
Closing this for now. If we want to revisit the functionality of these buttons lets do that as part of a proper look at the regions component.
