### ISSUE TITLE
Web service is returning an error

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#376]
https://records-ws.nbnatlas.org/occurrences/search?q=Abies+alba:

{"pageSize":10,"startIndex":0,"totalRecords":0,"dir":"asc","status":"ERROR","errorMessage":"Could not load collection from ZK: biocache"}

**Comment by sophiathirza** [comment]
And a user has reported a timeout exception when doing a species search, although it worked okay for me.

**Comment by djtfmartin** [comment]
its back up.
