### ISSUE TITLE
Sorting records after a spatial search returns all records in the db

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#377]
Message from the forum (https://forums.nbn.org.uk/viewtopic.php?pid=27546#p27546):
I have been using the spatial search with a polygon to check on the number of records for an area.
This will retrieve records for me, but as soon as I try to sort the records the spatial filter is removed and I get a list of all the records on the database!

**Comment by sophiathirza** [comment]
I was able to recreate this.

**Comment by sophiathirza** [comment]
Additional forum message:
I tried the search again using a location polygon for the Outer Hebrides and chose to look only at the British Lichen Society Data. This produced a list of 10,000+ records. If I sort the list according to record date, instead of 10,000+ records I get 500,000+ records i.e. the whole of the BLS dataset.
As my polygon covered the Outer Hebrides I can apply the vice-county filter, get the 10,000 list back again and I can now sort by record date.
If I draw a new polygon covering just one island and choose the BLS dataset again I get a list of 1187 records, but when I try to sort the list by record date, once again I get the entire BLS dataset!

**Comment by djtfmartin** [comment]
this is now fixed.
