### ISSUE TITLE
https://spatial.nbnatlas.org is unavailable

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#379]

**Comment by EllaVogel** [comment]
This is working for me but it took a very long time to load. I got onto the spatial portal eventually

**Comment by GiselleSterry** [comment]
I can access and download records via Analyse but cant view the records when I click on a grid square.

**Comment by sophiathirza** [comment]
I will close this issue as the spatial domain is back up but records is still unavailable.
