### ISSUE TITLE
Remove 'Establishment Means...' on the refine results in Species Search page

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#38]
Or make this clearer as to what this means.  I presume "Native/Non native"

[http://species.als.scot/search?q=Hygrocybe](url)

**Comment by djtfmartin** [comment]
This is a darwin core term:

http://rs.tdwg.org/dwc/terms/#establishmentMeans

Producing a glossary of terms for the site might be a good idea.

**Comment by djtfmartin** [comment]
removed
