### ISSUE TITLE
https://records.nbnatlas.org is unavailable

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#380]

**Comment by sophiathirza** [comment]
https://records.nbnatlas.org is down

**Comment by sophiathirza** [comment]
https://records.nbnatlas.org is down, also https://records-ws.nbnatlas.org and https://species-ws.nbnatlas.org

**Comment by djtfmartin** [comment]
Hmmm - all seem up to me.

**Comment by sophiathirza** [comment]
yes, they came up about 15 minutes later. I thought that you must have done something.

**Comment by djtfmartin** [comment]
I didnt do anything.
