### ISSUE TITLE
Please replace the following spatial layers

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#382]
Three layers to be replaced as they are now out of date:
uk_lercs_february_2017:  replace with uk_lercs_nbn_atlas_july_2017
NRW_SACPolygon: replace with NRW_SACPolygon2
NRW_Sites_of_special_scientific_interest_(SSSI): replace with Sites_of_special_scientific_interest

The new shapefiles are on S3. 
The variables and metadata are listed in new documents on the shared drive - will email the links separately.

**Comment by CEJohnston** [comment]
Do we have a schedule for updates to layers?  The current versions of these layers are known to be old so need replacing.

**Comment by sophiathirza** [comment]
@CEJohnston can you tell me where you got these layers from and I will contact the owners to see if there are more recent versions? thanks.

**Comment by CEJohnston** [comment]
1.  uk_lercs_nbn_atlas_july_2017 was supplied by Tom Hunt at ALERC. I shall email you his contact details.
2.  NRW_SACPolygon2 was downloaded 16/07/2017 from the NRW portal at https://libcat.naturalresources.wales/webview/?infile=details.glu&loid=98766&rs=202858&hitno=19&straight_to_details=&tiarray=full
3. Sites_of_special_scientific_interest was also downloaded 16/07/2017 from NRW portal https://libcat.naturalresources.wales/webview/?infile=details.glu&loid=98776&rs=720709&hitno=5

**Comment by sophiathirza** [comment]
I tried to replace NRW_SSSI (layer 55), after the original was deleted. I got the following error:

Reading field sid, name and description...
java.lang.RuntimeException: No fields table entry for layer, or objects have already been created for all fields table entries for layer.
	at au.org.ala.layers.ingestion.contextual.ContextualObjectCreator.create(ContextualObjectCreator.java:68)
	at au.org.ala.layers.ingestion.contextual.ContextualObjectCreator.main(ContextualObjectCreator.java:24)

**Comment by CEJohnston** [comment]
I don't really understand the process of ingest but it sounds like a table already exists? Not sure about this though.

**Comment by sophiathirza** [comment]
We have a new version of the LERC boundaries (British Isles June 2018)

**Comment by sophiathirza** [comment]
Three layers to be replaced as they are now out of date:
- [x] UK LERCs  (#588)
- [x] NRW SAC
- [x] NRW SSSI

**Comment by reupost** [comment]
Could you check the NRW SSSI layer now, please?

**Comment by reupost** [comment]
I can't find the original layer in the layer list for this (NRW_SACPolygon):
"NRW_SACPolygon: replace with NRW_SACPolygon2"

Shall I create a new layer 'NRW_SACPolygon2' from NRW_SAC_Feb18.zip?

**Comment by sophiathirza** [comment]
Yes please, the NRW_SAC_Feb18.zip is the latest version.

**Comment by sophiathirza** [comment]
But could you call it NRW_SAC_Feb18 so that we have the date?

**Comment by reupost** [comment]
Done.

**Comment by sophiathirza** [comment]
Brilliant - thanks.
