### ISSUE TITLE
Problems with overlap of OSNI and OSGB grid references

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#386]
There is an extraneous square over the N Channel.  Clicking on it does not give any info on records.  Is it the Irish Grid?  If so, why can we not get any further, as we would by clicking on an OSG square?

https://records.nbnatlas.org/occurrences/search?q=lsid:NBNSYS0000030348&fq=#tab_mapView

**Comment by djtfmartin** [comment]
It is the Irish grid. If you zoom in, it shows its D04. There seems to be an issue with clicking this grid reference though, but its selectable when you switch to points.

<img width="1078" alt="screenshot 2017-10-09 09 10 59" src="https://user-images.githubusercontent.com/444897/31339782-fef27e1e-acd1-11e7-86a2-266ad8f92d59.png">
<img width="1110" alt="screenshot 2017-10-09 09 12 04" src="https://user-images.githubusercontent.com/444897/31339783-feff51b6-acd1-11e7-8762-5e929f4f714f.png">

**Comment by CEJohnston** [comment]
Just having a quick look at this - I think this behaviour affects all records in NI that are located in the part of NI that is covered by OS grid.  I chose a different search and when selecting in grid view the interactive map seems to only interact with the OS grid and records with OSGB coordinates (but you can get to all records when you switch to points).

[https://records.nbnatlas.org/occurrences/search?q=*%3A*&qc=&radius=8.8&lat=55.26190320774934&lon=-6.1688232421875#tab_mapView](url)

![image](https://user-images.githubusercontent.com/18594564/43086085-70d11e2e-8e94-11e8-8636-f119c22994da.png)

**Comment by sophiathirza** [comment]
Now that we have more NI records, mostly supplied with OSNI this is becoming more of a problem.

A good example is here: https://northernireland-records.nbnatlas.org/occurrences/search;jsessionid=0E900D7AB9AD9D4EFF1534C4961AB6B6?q=lsid%3ANBNSYS0000005108&fq=#tab_mapView where the OSGB supplied records are displayed without a label on the yellow box.

**Comment by sophiathirza** [comment]
This will be solved by providing a OSI grid rereference to all records in NI and the Republic of Ireland. This in the 'up next' list of development tasks.

I will close this now.
