### ISSUE TITLE
Disable the image gallery

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#387]
It was agreed in the team meeting to disable the image gallery on images.nbnatlas.org until the search can be improved. The search returns many images, most of which seem unrelated to the search query. An exact match search requires the search term in quotes. 

The gallery should be replaced with a message saying that the image gallery is unavailable whilst being redeveloped.

**Comment by MandyHenshall** [comment]
I've removed the quick links to the gallery on the home pages of all three Atlases.
We can put a note on the message board on the Help pages about it being disabled, but I'm not sure where a message would go elsewhere?

**Comment by sophiathirza** [comment]
@djtfmartin would it be possible to do this before the conference? Either hide the gallery or make the search only do an exact match?

**Comment by sophiathirza** [comment]
It is not possible to disable to gallery without loosing all the images. The image gallery allows us to manage the images and is not meant as a tool for searching for images of specific species.

Dave has suggested that we extend the species occurrence search to search images rather than occurrences. This search supports taxonomy - i.e. resolving synonyms, matching to higher taxa and showing species etc.

Will close this issue.
