### ISSUE TITLE
Abundance fields not downloading

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#389]
Email received today:
I have recently downloaded a couple of datasets, and it seems as if the abundance fields aren’t downloading. It has an occurrence field for presence and absence but there doesn’t seem to be an abundance field. Is that under the assumption that each row is one occurrence? This isn’t the case for *this organisation* where one row could have multiple occurrences. I am downloading the data in a simple spreadsheet format, outputting as a CSV file.

Is this a known issue?

**Comment by sophiathirza** [comment]
linked to #111

**Comment by djtfmartin** [comment]
Abundance - called "Individual count", the darwin core term - is now in the downloads
