### ISSUE TITLE
Link to definitions of the different protections eg Wildlife Schedule

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#390]
On the NBN Gateway definitions and explanations of the different designation lists were provided. Can these be added to the NBN Atlas?
@MandyHenshall will be able to provide some screen shot examples.

**Comment by MandyHenshall** [comment]
This is how they used to appear.
![designations list more detail](https://user-images.githubusercontent.com/27201815/31444398-132a4b3c-ae94-11e7-98ce-099fcc7eeba9.jpg)
![designations list](https://user-images.githubusercontent.com/27201815/31444399-1343817e-ae94-11e7-8dd6-2b19814f8b5c.jpg)

**Comment by GiselleSterry** [comment]
http://jncc.defra.gov.uk/page-3424
http://jncc.defra.gov.uk/page-3414
http://jncc.defra.gov.uk/page-3415
 lists the definitions.

**Comment by djtfmartin** [comment]
The descriptions are with the lists that where loaded by Rachel

<img width="1440" alt="screenshot 2017-10-11 16 34 51" src="https://user-images.githubusercontent.com/444897/31450772-332a7fb6-aea2-11e7-86f8-6acae9aaf3c4.png">

**Comment by GiselleSterry** [comment]
thanks @djtfmartin - apologies that didnt know they were there.

**Comment by djtfmartin** [comment]
no worries
