### ISSUE TITLE
Do not display a full date when the precision is only M or Y

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#392]
Where the precision is month or year, do not show the full date on the occurrence page (i.e. 01-01-1989)

**Comment by djtfmartin** [comment]
Can you supply some examples ?

**Comment by sophiathirza** [comment]
I will add them as I find them.

This is not exactly the same problem. Here the date precision is Day but it says date not supplied when it does have a date: https://records.nbnatlas.org/occurrences/2cc7acaf-a6ab-4669-96d2-2900c7869e12

**Comment by djtfmartin** [comment]
id raise that as a separate issue

**Comment by djtfmartin** [comment]
I think this is fixed, and assume it was raised based on an old forum message.

Test cases written for this in May this year.
