### ISSUE TITLE
Occurrence record incorrectly flagged with no date supplied

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#393]
The date precision is Day but it says date that no date was supplied when it does have a date: https://records.nbnatlas.org/occurrences/2cc7acaf-a6ab-4669-96d2-2900c7869e12

**Comment by sophiathirza** [comment]
Here's another one: https://records.nbnatlas.org/occurrences/22626364-335a-4191-907c-492e34b538eb

**Comment by djtfmartin** [comment]
This is fixed. The second record has been removed.

The first record was for a sensitive species, so the message was only happening for sensitive records and it was due to date information being removed by the sensitive data processing
