### ISSUE TITLE
Species search - indicate synonym matches

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#394]
Where a species name is returned because of a match on a synonym, could it be made obvious in the search results that the match is on a synonym?

An example is here: https://species.nbnatlas.org/search?fq=idxtype%3ATAXON&q=Tachina+magnicornis

The first result is the accepted name Tachina magnicornis (Zetterstedt, 1844). The second result was matched because of the associated synonym Tachina magnicornis Zetterstedt, [1838].

In the search results between the taxon group and the occurrences link, usually there are three names - what do the individual names refer to? Do we need them, and if so, can they be labelled?

**Comment by djtfmartin** [comment]
In this instance, the second match is there because its matched the epithet, not because of the synonym.

**Comment by djtfmartin** [comment]
Heres an example where it has matched the synonym

<img width="1439" alt="screenshot 2017-11-16 09 26 55" src="https://user-images.githubusercontent.com/444897/32883827-5e4ba344-cab0-11e7-9c84-031269d934e4.png">

**Comment by sophiathirza** [comment]
so the problem in my example is the order of the search results, because a synonym match (which it also is) should come before matching a single part of the name.

The actual synonym match is on page 2.

**Comment by sophiathirza** [comment]
Closing this as synonym matches are correctly identified.
