### ISSUE TITLE
Log in page not working at 11.26 on 23/10/17

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#395]
Error message:

This auth.nbnatlas.org page can’t be found

No webpage was found for the web address: https://auth.nbnatlas.org/cas/login?service=https://nbnatlas.org/
HTTP ERROR 404

**Comment by djtfmartin** [comment]
this is fixed

**Comment by GiselleSterry** [comment]
thanks!
