### ISSUE TITLE
Add date of upload to the overview page of each data resource

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#396]
It needs to be clear when records were last uploaded to a data resource.

**Comment by djtfmartin** [comment]
Record page under the map:

<img width="1437" alt="screenshot 2017-10-26 09 41 36" src="https://user-images.githubusercontent.com/444897/32043196-ebb0efb2-ba31-11e7-8ca9-4a7d8079e329.png">

**Comment by sophiathirza** [comment]
thanks! I had not seen that before. What does date last processed mean?

Is it possible to have the most recent date that a record within a dataset has been uploaded/processed on the dataset page?

**Comment by djtfmartin** [comment]
processed -  this is when we interpret the raw data, matching the taxonomy to UKSI etc.

on the dataset page.
<img width="1012" alt="screenshot 2017-10-26 09 50 16" src="https://user-images.githubusercontent.com/444897/32043602-1f308f68-ba33-11e7-8512-1da7efeb435f.png">

**Comment by sophiathirza** [comment]
The text: 'This resource was last checked..' is not on every dataset. 

Could it be moved up the page? Perhaps put at the top of the right-hand panel?

**Comment by sophiathirza** [comment]
Please add date created and date last uploaded/processed to the panel on the right handside of the dataset metadata page i.e.: https://registry.nbnatlas.org/public/show/dr1313. Underneath the percentage of verified records.
