### ISSUE TITLE
In correct precision dates being applied to vague dates

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#398]
There is a forum message that suggests that some records have incorrect dates after being transferred from the Gateway: https://forums.nbn.org.uk/viewtopic.php?id=6962. If only the month or year is supplied then the Atlas sets the date as the first of the month or first of January. This then incorrectly reports occurrences in January.

@djtfmartin could this be happening?

**Comment by sophiathirza** [comment]
Example: https://records.nbnatlas.org/occurrences/fa79d823-9405-46c8-ae9a-2bd607c84587

**Comment by sophiathirza** [comment]
The year range precision is correct here: https://records.nbnatlas.org/occurrences/c96b95d5-949b-4cf8-91fa-19062c65b560 but could the start and end dates just be the year and not a full date?

and

https://records.nbnatlas.org/occurrences/3ef1e1ef-d373-4d4f-889e-4164efa5862f

**Comment by sophiathirza** [comment]
Also, in the header of the occurrence record page, next to the name the record date should just say the year: https://records.nbnatlas.org/occurrences/f215b899-0e71-43b4-8eea-e9a094b5ef62

**Comment by djtfmartin** [comment]
This now fixed. Please see

https://records.nbnatlas.org/occurrences/3ef1e1ef-d373-4d4f-889e-4164efa5862f
https://records.nbnatlas.org/occurrences/fa79d823-9405-46c8-ae9a-2bd607c84587

Theres a minor issue with day range (which doesnt affect the phenology charts).

https://records.nbnatlas.org/occurrences/062dcb17-e97e-4130-bd0e-42dd2dfcc0d5

I'll raise a separate issue for this.
