### ISSUE TITLE
User account: change title of box to 'County/Local Authority'. Please also change 'City' to 'Town/City'

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#40]

**Comment by djtfmartin** [comment]
This is now fixed. See

https://auth.als.scot/userdetails/registration/createAccount

**Comment by CEJohnston** [comment]
Could I just check the source of the list for the drop down menu of
counties? It appears to be a list of old counties - such as Berwickshire
and Roxburghshire - rather than the Local Authority name - which would be
Scottish Borders for the two given examples. It applies to Ayrshire as
well, which is split into North, South and East Ayrshire.  Do you know if
there is a local authority list?

Thanks,
Christine

Christine Johnston
NBN Scottish Liaison Officer
tel: 07342254589
email: c.johnston@nbn.org.uk

NBN website: www.nbn.org.uk
NBN Gateway: http://data.nbn.org.uk
Atlas of Living Scotland: www.als.scot

*NBN Trust *- Registered in England and Wales - Company no. 3963387 -
Registered charity no. 1082163
Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL

**\* Nominations are now open for the UK Awards for Biological Recording and
Information Sharing! ***
http://nbn.org.uk/news/uk-awards-nominations-open/

**Comment by djtfmartin** [comment]
Thanks @CEJohnston.

Its possibly not from the best source. Is there an authoritative list ?

Changing the list is simple as its loaded form config.

**Comment by CEJohnston** [comment]
I'll have a look and see what I can find and then re-open

**Comment by CEJohnston** [comment]
I have sourced a list of counties and local authorities for use in the drop down menu - link given below. I have included an N/A line.  Please also change title of box to 'County/Local Authority'.  Please also change 'City' to 'Town/City'

https://docs.google.com/spreadsheets/d/16CRCIwsxspxaZQUPTzHvcazpLNLvn4JbcRFoXkfVevM/edit?usp=sharing

**Comment by djtfmartin** [comment]
I've applied the updated list. Renaming this issue as its changed to an enhancement.

Downgraded the priority.

**Comment by CEJohnston** [comment]
OK to downgrade and thanks for updating the list.

**Comment by sophiathirza** [comment]
@CEJohnston is this still outstanding?

**Comment by sophiathirza** [comment]
The als.scot site is no longer available, so closing this issue.
