### ISSUE TITLE
Issues reported by user

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#400]
A.      Incorrect Association shown:

https://species.nbnatlas.org/species/NBNSYS0000031029
The page is for Scambus annulatus (Kiss, 1924) so why does it show
Associations

Animal / parasitoid
Scambus inanis is parasitoid of larva of Zeugophora subspinosa

I don’t think inanis and annulatus are synonyms.

 
B.      When I search for “Scambus” the exact match is near the foot of the second page. (In fact I’ve already confirmed that I’m searching “Scambus – genus” in the autocorrect pop-up)

 
C.      The back button often gives error pop-ups. It may be a timing issue. The Atlas is quite slow at the moment and it may be caused by hitting “back” before the database retrievals have completed.

**Comment by sophiathirza** [comment]
There are three issues here:

A. information coming from EoL
B. problem with the species search
C. the site is running slowing at the moment

I will make another issue of the second point and Dave is investigating the third at the moment.

**Comment by sophiathirza** [comment]
The speed of the site is much better now. I will close this issue as the first two points are in other issues.
