### ISSUE TITLE
Order of species search results

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#401]
Comment from user:

When I search for “Scambus” the exact match is near the foot of the second page. (In fact I’ve already confirmed that I’m searching “Scambus – genus” in the autocorrect pop-up)

**Comment by sophiathirza** [comment]
Exact matches should be at the top of the list (from #400). Should the species search be changed to only do an exact match?

**Comment by sophiathirza** [comment]
A user searched for Aphodius equestris, which is a synonym of Aphodius (Volinus) sticticus. Currently the synonym match is on page 3, it should be the first in the list as an exact match.

This issue is also linked to #394 where synonym matches should be more clearly identified.

**Comment by djtfmartin** [comment]
Scambus - genus should have a better boost.

**Comment by c-van-dierkson** [comment]
improved in the new species search, can be closed
