### ISSUE TITLE
Delete records from dr1179

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#403]
Adding this here so that it is not forgotten:

Would you delete records from this dataset? https://registry.nbnatlas.org/public/show/dr1179

The issue is with all records in the dataset except those in the Coccinellidae. So either delete all records or all those not in the Coccinellidae family. Whichever is easiest.

**Comment by djtfmartin** [comment]
done

**Comment by sophiathirza** [comment]
Thanks. There are still records showing, so were you able to leave the Coccinellidae records in place?

**Comment by sophiathirza** [comment]
Sorry. Just checked and they do seem to be only in the family Coccinellidae
