### ISSUE TITLE
common names in scientific name field

### ISSUE THREAD

**Issue by djtfmartin** [nbnuk/nbnatlas-issues#404]
https://registry.nbnatlas.org/public/show/dr896

This dataset has been supplied with common names in the scientific name field - hence the lack of name matching.

**Comment by sophiathirza** [comment]
The TVKs were for the common name as well.

I have uploaded the new text file. I saved the txt file with encoding as UTF8 and line endings as \r\n. In the upload form I put  \r\n in the Line Delimiter field.

**Comment by sophiathirza** [comment]
I just realised that all the text fields are in double quotes in the uploaded file - is this okay?

**Comment by sophiathirza** [comment]
@djtfmartin would you let me know if the double quotes are a problem, please? I have quite a few data resources ready for upload.

**Comment by djtfmartin** [comment]
not a problem, as long as the config is correct in the connection parameters for the data resource.

**Comment by sophiathirza** [comment]
great, thanks.

**Comment by sophiathirza** [comment]
just in case you missed it. this one still needs processing: dr896

**Comment by djtfmartin** [comment]
reloaded
