### ISSUE TITLE
Datasets not attributed correctly

### ISSUE THREAD

**Issue by djtfmartin** [nbnuk/nbnatlas-issues#405]
There are a number of datasets not correct attributed to data providers

eg https://registry.nbnatlas.org/public/show/dr1528

I suggest we review.

**Comment by sophiathirza** [comment]
There are a lot of them! Mostly from The Wildlife Information Centre and Wales Gov. I have started updating but not sure whether Wales Gov is Natural Resource Wales.

Just for notes.
EoL: https://registry.nbnatlas.org/public/show/dr0
Wales Gov: https://registry.nbnatlas.org/dataResource/show/dr1512
Wales Gov: https://registry.nbnatlas.org/dataResource/show/dr1513
Wales Gov: https://registry.nbnatlas.org/dataResource/show/dr1514
Wales Gov: https://registry.nbnatlas.org/dataResource/show/dr1517
Wales Gov: https://registry.nbnatlas.org/dataResource/show/dr1521

**Comment by sophiathirza** [comment]
These are the data resources I can't match to a data provider:

BRAG - Berkshire Reptile and Amphibian Records | dr1404
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Arable plant survey | dr1530
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Brown Hairstreak survey | dr1531
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Brown Hare Farm-scale surveys | dr1525
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Chough Field Surveys | dr1529
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Field Survey; farm-scale survey for noctule, common pipistrelle and soprano pipistrelle | dr1526
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Field-scale surveys for breeding yellowhammer | dr1524
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Field-scale winter surveys of yellowhammers | dr1521
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Grassland Fungi survey | dr1517
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Marsh Fritillary Butterfly survey | dr1514
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Small Pearl Bordered Fritillary Butterfly survey | dr1532
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Water Vole Farm-scale Surveys | dr1513
Tir Cynnal and Tir Gofal Monitoring and Evaluation Programme: Whole-farm surveys for yellowhammer and curlew | dr1512
UK casual records from members of BASC - 1980 onwards | dr1310

**Comment by djtfmartin** [comment]
probably need to create 3 data providers

**Comment by djtfmartin** [comment]
any progress on this ? would be nice to be able to sync all with GBIF prior to the conference.

Should have added, this is preventing sharing with GBIF currently....

**Comment by sophiathirza** [comment]
The BRAG dataset has been deleted. I think the Welsh dataset belongs to dp131 but I need to confirm. Ella is contacting BASC.

**Comment by sophiathirza** [comment]
BASC data provider has been created. We still need to sort out the Welsh ones.

**Comment by sophiathirza** [comment]
New data provider created for Welsh Government and the data resources added to the provider.
