### ISSUE TITLE
Ordering of Watsonian vice-counties in charts of record counts

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#408]
Forum message:
This specifically refers to the chart of record counts, but may be applicable elsewhere: e.g. https://species.nbnatlas.org/species/NB … 48#records

Would it be beneficial to order the vice-counties by their number rather than name? The numbers for vice-counties were allocated  on a rough geographic basis - it's very crude but ordering by the number would show the "distribution" of these nicely (and be more logical for those familiar with vice-counties; i.e. North and South Lincolnshire next to each other).

(I am undecided about this - a button to switch the ordering would be the perfect solution!)

**Comment by sophiathirza** [comment]
Let's wait and see what replies this suggestion gets on the forum.

**Comment by c-van-dierkson** [comment]
Jo confirms ok to close.
