### ISSUE TITLE
Loss of records when ordering by record date

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#412]
Message from forum:

When I try to sort this search: https://records.nbnatlas.org/occurrences/search?q=text:Johnson,%20M.&fq=(collector:%22Johnson,%20M.%22%20OR%20collector:%22Johnson,%20M.;Johnson,%20S.%22%20OR%20collector:%22Johnson,%20M.S.%22%20OR%20collector:%22Johnson,%20M.S.;Neale,%20E.M.%22)&sort=occurrence_date&dir=desc by record date descending

no records are returned. The URL appears to be cutoff; manually adding &dir=asc works.

Paging the results is causes the &dir=asc to drop from the url

**Comment by sophiathirza** [comment]
I was able to recreate this.

**Comment by djtfmartin** [comment]
this is now fixed.

**Comment by sophiathirza** [comment]
This is still a problem.

**Comment by djtfmartin** [comment]
I see the problem, the query URL is getting truncated after the sort

**Comment by reupost** [comment]
Semi-colons are being treated as delimiters like ampersands, so the fq clause is truncated after 'collector:%22Johnson,%20M.'. The fq parameter needs to be encoded.

**Comment by sophiathirza** [comment]
Thank you!
