### ISSUE TITLE
Tab in NBN Atlas Scotland still saying Atlas of Living Scotland

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#413]
On accessing the spatial portal at [https://scotland-spatial.nbnatlas.org/#](url) the top tab in the web browser window still says Analyse Data / Atlas of Living Scotland

**Comment by djtfmartin** [comment]
This is editable in wordpress

**Comment by GiselleSterry** [comment]
Emailed Redpaint - we are unable to access to edit the tab,

**Comment by GiselleSterry** [comment]
reply from redpaint - @djtfmartin 
"I think this is one for Dave, we aren’t providing anything to these pages. I spoke with Mandy (or you??) about the possibility of including the header and footer on these pages but this needs to go via Dave. 

I know it’s a bit confusing about lines of responsibility but this page in particular is Dave’s domain."

**Comment by djtfmartin** [comment]
Sorry - my bad, Andy is right

**Comment by sophiathirza** [comment]
@reupost has this been fixed? I can't see the fav-icon but the text looks like it has been corrected.

**Comment by CEJohnston** [comment]
This is fixed - the favicon and the text look fine to me.
