### ISSUE TITLE
Full Darwin Core download files are empty except for the header

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#418]
I had this problem a few weeks ago and I thought that perhaps I had just missed the records, as the first few columns might be empty. But we've just had an email from someone who tried it several times and had the same problem.

I just tried now to download all CCO records from the SEWBRec area to a full Darwin Core format and the file was empty (except for the header).

**Comment by djtfmartin** [comment]
This is fixed. Heres the output:

https://records-ws.nbnatlas.org/biocache-download/64a45b36-31ed-3c31-809d-55cd44948dfb/1510661119981/records-2017-11-14.zip
