### ISSUE TITLE
Absence records and GBif

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#421]
We sent https://registry.nbnatlas.org/public/show/dr873 to Gbif. It includes absence record, which NRW have told me are displaying on GBif.

All 15 records for Urosalpinx cinerea are absence: https://records.nbnatlas.org/occurrences/search?q=data_resource_uid%3Adr873&fq=taxon_name%3A%22Urosalpinx%20cinerea%22

They display on the map in GBif and in the GBif download all 15 entries on GBif have the issue individual_count_invalid and the individual count field is empty. 

[occurrence.txt](https://github.com/nbnuk/nbnatlas-issues/files/1461664/occurrence.txt) - this is the download file from GBif.

Other records in the Gbif download file have individual count as 0, which I've checked is an absence record in the Atlas.

It seems that some absence records that we sent correctly have 0 individual counts in GBif and others not.

**Comment by djtfmartin** [comment]
fixed. reexport from NBN to GBIF

**Comment by sophiathirza** [comment]
Thanks. Was the problem that 0 was not in the individual count field? - just so that I can let the data provider know.

Can I do the export from NBN to GBif?

**Comment by sophiathirza** [comment]
How long will this take to get to GBif? I can see in GBif that the dataset was updated on 11th November but the records still have individual_count_invalid in the individual count field.

**Comment by sophiathirza** [comment]
thanks. Occurrence status is correctly set in the darwin core download from Gbif.
