### ISSUE TITLE
Data resource issue and resources for processing 

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#429]
- [x] dr681 - this has too many records, it should have 147,661 rather than 188,405
- [x] dr837 - match record key with record number (from #420)
- [x] dr896 (from #404)   
- [x] dr1374 - to correct some future dates
- [x] dr1624 - to correct some future dates

**Comment by djtfmartin** [comment]
dr681 - fixed (have ids changed ???)
dr896, dr1624, dr1374 -  reloaded

dr837 - to be done

**Comment by sophiathirza** [comment]
I don't think the ids changed for dr681.

dr1374 and dr1624 both now have almost double the number of records that they should have.

**Comment by djtfmartin** [comment]
have the IDs changed for dr1374 and dr1624 ?

**Comment by sophiathirza** [comment]
No, I really don't think so. In the morning I will compare the two txt files. All I did was unzip the files from the data providers, correct the column header name (occurrence was spelt wrong in one) and save as tab delimited text file, making sure that I converted the date fields to DD/MM/YYYY before saving. The last step was the one that I forgot the first time I uploaded the file.

**Comment by djtfmartin** [comment]
I think its an issue with the indexes. The data is only loaded into the DB once, as far as i can see.

Ill start a re-index.

When i download the entire datasets for dr1624, i get the correct number of records.

**Comment by djtfmartin** [comment]
all resources (re)loaded
