### ISSUE TITLE
Add locality and recorder name to record list

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#430]
Add locality (site name) and recorder name to the record item in the list of records. 

i.e. on this page: https://records.nbnatlas.org/occurrences/search?q=data_resource_uid:dr679

**Comment by sophiathirza** [comment]
#545

**Comment by c-van-dierkson** [comment]
SR Confirms can be closed.

We've been asked for this a few times because they were included in the records list on the Gateway. But I don't think that it's necessary.

I think that we could close this and reopen if more people comment. It's not been mentioned for a long time.
