### ISSUE TITLE
Add ability to filter records by UKSI species profile

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#432]
Add ability to filter records by UKSI species profile, i.e. marine, terrestrial and freshwater

**Comment by djtfmartin** [comment]
Once we have this, and we have a suitable boundary for marine/terrestrial, we'll be able to a enable the data quality check thats tests whether there is a a mismatch for a taxon.

**Comment by sophiathirza** [comment]
Should I source a spatial layer for the boundaries between marine and terrestrial, I guess that we don't have one?

**Comment by djtfmartin** [comment]
yes, that would be great

**Comment by sophiathirza** [comment]
World Vector Shoreline: https://gcmd.nasa.gov/records/GCMD_WVS_DMA_NIMA.html, accurate to 500m

**Comment by c-van-dierkson** [comment]
Done
