### ISSUE TITLE
Source spatial layer for boundary between sea and land

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#433]
World Vector Shoreline: https://gcmd.nasa.gov/records/GCMD_WVS_DMA_NIMA.html, accurate to 500m

**Comment by CEJohnston** [comment]
Could we use one of the existing layers -  'World base layer' (short name 'world') - for this?  It may have a slightly coarser resolution than the layer above but I am not sure where it came from.  

If we need something more detailed the Office for National Statistics provides a GB outline at [http://geoportal.statistics.gov.uk/datasets/21ab94915c5342ceadf124f44fb584f8_0](url).  And ESRI's library provides an outline of Ireland at [http://www.arcgis.com/home/item.html?id=ae74a8497a1041669a9d2165a0f450b6](url)

**Comment by CEJohnston** [comment]
This will improve record cleaning.

**Comment by c-van-dierkson** [comment]
Not required
