### ISSUE TITLE
Add LERC boundaries and/or vice counties to pre-defined areas on NBN Atlas Scotland

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#435]
Request from forum post:
https://forums.nbn.org.uk/viewtopic.php?id=7067

**Comment by sophiathirza** [comment]
Add both LERC and vice-counties to pre-defined areas for NBN Atlas Scotland.

**Comment by c-van-dierkson** [comment]
Jo confirms to close. Details added to 558.
