### ISSUE TITLE
Error 500: Internal Server Error

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#442]
Error reported by user when trying to register at 10.16 today.  I've tried to replicate and got the same message.

![image](https://user-images.githubusercontent.com/27201815/33373628-b50b72b4-d4fa-11e7-8c12-b88dbb79f6e8.png)

**Comment by sophiathirza** [comment]
I think that this might be resolved as people have registered since the issue was raised.

**Comment by djtfmartin** [comment]
this is resolved. it was due to the certificate expiring
