### ISSUE TITLE
Change text when image rights holder is missing

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#443]
If the rightsholder of an image is missing replace the text  “Rights holder: no rights holder” with “Rights holder: rights holder unknown”.

Email from photographer: 
Presumably the rights holder info is taken from the EXIF data?

It’s a bit of step to say that absence of copyright entry in EXIF means here is no rights holder – a lot of websites automatically strip EXIF information (as does DiscoverLife which is where my images get uploaded).

Suggest, if the EXIF is missing, you remove the message “Rights holder: no rights holder”, or replace it by “Rights holder: rights holder unknown”.

**Comment by sophiathirza** [comment]
@reupost - could this be corrected as a matter of urgency please?

**Comment by reupost** [comment]
Ok, let me take a look

**Comment by reupost** [comment]
The existing image records have been fixed, I still need to fix the underlying code though.
