### ISSUE TITLE
Incorrect display of dates with Day range precision

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#445]
Message from the forum: https://forums.nbn.org.uk/viewtopic.php?id=7095

The day is missing from the date in this record https://records.nbnatlas.org/occurrences/d480a8e6-e583-403e-a28a-fa5c737efee6

Event date start    1912-08 Supplied  "26/08/1912"
Event date end    1912-09 Supplied as 06/09/1912

**Comment by sophiathirza** [comment]
This problem is mentioned in the closed issue #398 but I couldn't find an open issue for it.

**Comment by sophiathirza** [comment]
Here is another example of a date range not being displayed correctly: https://records.nbnatlas.org/occurrences/8e2511b3-8c0e-4dde-ae81-4dcee177268c

**Comment by reupost** [comment]
From #451 In the following dataset, which has just been updated, https://records.nbnatlas.org/occurrences/a4686257-67e4-4553-8b15-1f95d6b188e4, the record date displays as Year:2031 Month:08 Day: "" but the supplied date in the upload file was 01/08/1931. It was a darwin core formatted txt file.

**Comment by reupost** [comment]
See #576

**Comment by sophiathirza** [comment]
All okay now, thanks.
