### ISSUE TITLE
Amend user sign up form to meet GDPA guidance

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#448]
Review form to ensure collecting relevant data on users to meet GDPA guidance due to take effect from May 2018. Details to be discussed outside github.

**Comment by sophiathirza** [comment]
@GiselleSterry do we have any details for this? what changes need to be made?

**Comment by GiselleSterry** [comment]
ideally need to remove telephone number field - dont need this information. If cant remove can field name be changed and allow it to have free text. Could then use for 'profession' or similar.
