### ISSUE TITLE
Larger view of image from Overview tab on Species page doesn't cover screen in Firefox

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#45]
Clicking image in Overview tab on the Species page opens larger view in modal dialogue but grey overlay doesn’t cover screen in Firefox when scrolling down

**Comment by djtfmartin** [comment]
This is minor issue. Im not sure why a user would want to view the rest of the page with the grey mask.

**Comment by CEJohnston** [comment]
Need to look in to it.

**Comment by djtfmartin** [comment]
I managed to reproduce this on Firefox 45 on mac osx.

**Comment by djtfmartin** [comment]
Im closing this one. I dont think its an issue.
