### ISSUE TITLE
Abundance data missing from export to GBIF

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#450]
Apparently abundance information is not being included in the export to GBIF. Do we send the individual count field to GBIF? 

This was reported sometime ago, but I can't find any details about it here.

**Comment by djtfmartin** [comment]
As far as I know we do

For reference:
https://github.com/AtlasOfLivingAustralia/biocache-store/blob/2.x/src/main/scala/au/org/ala/biocache/export/DwCACreator.scala#L27

Can you provide an example ?

**Comment by sophiathirza** [comment]
I'll ask them for an example now that I know that we do send the field. Thanks.

**Comment by sophiathirza** [comment]
It was absence records that they meant - which has been corrected.
