### ISSUE TITLE
Occurrence record event date error

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#451]
In the following dataset, which has just been updated, https://records.nbnatlas.org/occurrences/a4686257-67e4-4553-8b15-1f95d6b188e4, the record date displays as Year:2031 Month:08 Day: ""  but the supplied date in the upload file was 01/08/1931. It was a darwin core formatted txt file.

I just noticed that there is a future date in the file, so if we need to reprocess could I re-upload the file first?

**Comment by reupost** [comment]
The actual value in the text file is "01/08/31".   The one that seems future dated is "19/06/27", which is possibly also intended to be 1927, but Excel might be deciding to show it as 2027 (as per https://support.office.com/en-us/article/Change-the-date-system-format-or-two-digit-year-interpretation-aaa2159b-4ae8-4651-8bce-d4707bc9fb9f). Ideally, we'd have 4-digit years for our dates to avoid any ambiguity.  The "2027" record record doesn't show up in the portal yet, so I can't tell how its been interpreted by the data loading process, though I would imagine it would also end up being future-dated.
It's fine to re-upload the file as we need to reprocess that dataset in any event.

**Comment by sophiathirza** [comment]
Thanks. I've reuploaded the csv file, after formatting the dates. 

The dates have four digits but my computer only shows two by default and then if I save without forcing it to show four digits some dates are changed (i.e. 1918 becomes 2018).

**Comment by sophiathirza** [comment]
I still have a similar problem in the updated record: the record date displays as Year:1931 Month:08 Day: "" but the supplied date in the upload file was 01/08/1931 and it correctly says that it is has a Day precision. It was a darwin core formatted txt file.

**Comment by sophiathirza** [comment]
Another date problem:

https://records.nbnatlas.org/occurrences/765d0adb-2a6a-4855-bc29-2ce874914526
A day range not displaying properly.

https://records.nbnatlas.org/occurrences/e5a0829d-be2c-4c85-b43c-28c63bc7a674
A year range not displaying properly.

https://records.nbnatlas.org/occurrences/09ef68fc-8a06-43f4-97fc-fcf21efe9906
A month range not displaying properly.

https://records.nbnatlas.org/occurrences/deb0dfb4-0de6-40c4-b9a9-3c5b1c857b90
Day range but the precision shows as Month

https://records.nbnatlas.org/occurrences/293b830a-e24b-41c6-a51b-b0cbedf060f8
Day range but the precision shows as Year

**Comment by reupost** [comment]
I can see the Event end date is not being populated correctly for the second two examples, but I'm not sure what the problem is with the first one?

**Comment by sophiathirza** [comment]
linked to #445 and #446

**Comment by sophiathirza** [comment]
Some of these may have been updated since the issue was raised.

The start and end dates here look okay now on: https://records.nbnatlas.org/occurrences/765d0adb-2a6a-4855-bc29-2ce874914526 . The date precision here says Year when it should be Month.. but that is probably because the year was included in the end date, which is not necessary.

**Comment by reupost** [comment]
The original issue for record https://records.nbnatlas.org/occurrences/a4686257-67e4-4553-8b15-1f95d6b188e4 : the loss of the day value is due to sensitive data processing. When this is disabled the record has its day information.

@sophiathirza can you confirm that we don't want to mask any date fields for sensitive species? Otherwise this is functioning correctly (except possibly a message to indicate the processing should be included on the page).

**Comment by reupost** [comment]
I'm going to move the issue to the related bug #445 and focus that one on sensitive data processing. General date processing concerns are now in #576
