### ISSUE TITLE
No dots on occurrence and interactive maps

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#453]
This afternoon the dots have stopped displaying on the species occurrence maps and on the interactive maps.

**Comment by djtfmartin** [comment]
i cant reproduce this

**Comment by reupost** [comment]
I think I've just resolved this (temporarily) by freeing up some disk space.  Hoping we can come up with a mechanism to handle some of the really huge shapefiles that users can generate.

**Comment by sophiathirza** [comment]
thanks. The interactive maps are working now but I still find some occurrence maps that are empty, e.g. https://species.nbnatlas.org/species/NBNSYS0000003214

**Comment by reupost** [comment]
Funnily enough, that map is coming up pretty well for me, but i'll look at the logs and see if i can find anything.On 18 Dec 2017 18:56, Sophia <notifications@github.com> wrote:thanks. The interactive maps are working now but I still find some occurrence maps that are empty, e.g. https://species.nbnatlas.org/species/NBNSYS0000003214

**Comment by sophiathirza** [comment]
I still have the same problem in firefox but I tried in another browser and the dots display correctly.

**Comment by reupost** [comment]
Would you mind clearing your Firefox cache and see if the problem persists?  I’ve just had a look at the example you mentioned and it looks ok on my side.

**Comment by sophiathirza** [comment]
All okay now, thanks.

**Comment by reupost** [comment]
I'm going to open two related issues: #454 and #455 to find a more permanent fix for this.
