### ISSUE TITLE
Could the occurrence record count indicate when it includes absence records?

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#457]
For example: https://species.nbnatlas.org/species/NBNSYS0000178578#tab_mapView

15 of the records are absence records and (correctly) do not appear on the map. Could the number of absence records be written somewhere, otherwise comparing the total number of records and the distribution map is misleading.

**Comment by sophiathirza** [comment]
This is included in the requirements document: 'NBNA Occurrence map enhancement requirements' on Teams

**Comment by sophiathirza** [comment]
@reupost we've lost the total count of records on the species page maps (i.e. presence plus absence records)

**Comment by reupost** [comment]
Fixed e.g. https://species.nbnatlas.org/species/NHMSYS0020475521 ; busy rolling out to all Atlases
