### ISSUE TITLE
On Species Page, 'IUCN for UK' information box - make easier for user to understand

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#46]
First task to expand Category from Acronym to long name 'i.e VU - Vulnerable'

**Comment by djtfmartin** [comment]
The lists are managed through the lists tool. This list can be re-imported by a non-dev.

**Comment by CEJohnston** [comment]
The link is [http://species.als.scot/species/NBNSYS0000000013](url)
