### ISSUE TITLE
Multiple advanced record search saying no records found

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#461]
A user has been trying to search for multiple species from the advanced record search window but it keeps saying:
No records found for (taxa:"Huperzia selago" OR taxa:"Lycopodium clavatum") 

The batch search seems to work ok but he would ideally like to use a date filter as well.

I've replicated this issue. Please advise. Thanks.

**Comment by EllaVogel** [comment]
This same issue has been raised with me today. Unable to search for multiple species via the advanced search tool https://records.nbnatlas.org/search#tab_advanceSearch
I can replicate the issue.

**Comment by sophiathirza** [comment]
This has been corrected. We are going to improve the advanced search in the next few months.
