### ISSUE TITLE
Download reason dropdown list empty on https://scotland-regions.nbnatlas.org

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#464]
On downloading records after a search in a predefined area on the Atlas Scotland the download reason dropdown list in the dialogue box is empty. This means that it is not possible to download records from this page.

**Comment by sophiathirza** [comment]
Download reason drop down is also empty in the main Atlas as well. Something must have changed recently, as it's not possible to download records at the moment.

Try to download this search: https://records.nbnatlas.org/occurrences/search?q=lsid%3ANHMSYS0000080214&fq=identification_verification_status%3A%22Accepted%22

**Comment by reupost** [comment]
It is possible the logger service (which provides the list) was inaccessible at some point and the empty results got cached. I've restarted this and it looks ok now.

**Comment by reupost** [comment]
I've checked and Scotland is ok now as well.
