### ISSUE TITLE
Back to records on Atlas Scotland sometimes returns records from a different search 

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#465]
Forum message:
Using Atlas Scotland I searched for Spermothamnion repens, which produced a set of records and I chose a record to view and then clicked "back to records" and was presented with a list of records for Eristalis nemorum.

**Comment by sophiathirza** [comment]
I tried this a couple of times with different species searches and was able to recreate it once. I was shown the results from a spatial search when I had only done a species search.

**Comment by reupost** [comment]
Is there any way to recreate this issue reliably?  Does it depend on having multiple browser tabs open?  Any more details would help a lot.

**Comment by sophiathirza** [comment]
I have just tried again and couldn't recreate it. I tried with one or more browsers open. Could we leave this open, in case I can get more details?

**Comment by c-van-dierkson** [comment]
No further details ever received.
