### ISSUE TITLE
(IOM) Country field is incorrect for Isle of Man records

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#467]
Locations: country field is incorrectly inferred from records - is returning UK not the Isle of Man (e.g.SC190) E.g. https://isleofman-records.nbnatlas.org/occurrences/d2a59660-bb48-459d-9e98-f871a7f125e8 Country field says UK, whereas it should be Isle of Man.

**Comment by sophiathirza** [comment]
@djtfmartin how is the country determined? Is it from the country spatial layer?

**Comment by djtfmartin** [comment]
it is yes.

**Comment by EllaVogel** [comment]
How easy is it to re-name this part of the country spatial layer, to say Isle of Man, instead of UK?

**Comment by djtfmartin** [comment]
Its not straightforward, as this ties in with sensitive species record processing.

**Comment by EllaVogel** [comment]
@djtfmartin @reupost can either of you comment on when this might be fixed? Its fairy fundamental to have the country information correct for each record. I need to pass this info onto the Isle of Man team today.

**Comment by reupost** [comment]
For now, the 'Country' field has been removed when viewing an individual record.  Lower down the screen one can see:

Political
--
Countries with sea areas | Isle of Man

Note that data downloads, and the comparison of original vs processed data, still include 'Country: UK'
