### ISSUE TITLE
Analyse data button not working on Isle of Man species pages 

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#468]
Analyse data button not working on species pages e.g. https://isleofman-species.nbnatlas.org/species/NBNSYS0000174820. E.g on the Species page for Lion's Mane Jellyfish: https://isleofman-species.nbnatlas.org/species/NBNSYS0000174820 Clicked on Analyse Data and error message 'This site cannot be reached'

**Comment by sophiathirza** [comment]
Same problem on Atlas Scotland. Neither isleofman-spatial.nbnatlas.org or scotland-spatial.nbnatlas.org are available at the moment.

* On the species page, the Analyse data link points to the country specific spatial portal

* Analyse link in the header points to the main spatial portal for IoM and the country portal for Scotland

* On the interactive map, the Analyse data link points to the main spatial port for IoM and there is no link on the Scottish Atlas

The welsh spatial portal is working okay, but there is no link to it above the interactive map (as with Scotland)

**Comment by sophiathirza** [comment]
isleofman-spatial.nbnatlas.org has not been set up yet.

**Comment by EllaVogel** [comment]
Do you know when these will be set up? Is it worth re-directing the links to the main spatial portal (but carrying through the search terms from the previous page?) in the meantime, so that we don't get an error message?

**Comment by reupost** [comment]
I've redirected the links to the main spatial portal (they are already set like this for other 'Analyse' links, e.g. the 'Analyse data' button on the Map tab of the Occurrence records page)

**Comment by reupost** [comment]
Fixed
