### ISSUE TITLE
Species search doesn't generate predictive list on Atlases

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#469]
The https://isleofman-species.nbnatlas.org/ searchbox does not generate a predictive list of species as you type, unlike the main searchbox on the homepage
(Low priority?)

**Comment by sophiathirza** [comment]
This is the same as the main Atlas, species.nbnatlas.org but it would be good to have on all Atlases.

**Comment by reupost** [comment]
The main species page doesn't give predictive species at this point.  Maybe it did in the past.  https://records.nbnatlas.org does.

**Comment by sophiathirza** [comment]
Done.
