### ISSUE TITLE
'Colour by year' years are not in order (IOM)

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#470]
Search for species and look at 'View Map'.  When selecting Colour By…Display Points by Year, the points display okay but the years are not in order. (Issue raised against Isle of Man Atlas, but I think this is an issue with all of the Atlases?)

**Comment by sophiathirza** [comment]
Yes, this is the same on all Atlases.

**Comment by sophiathirza** [comment]
#52

**Comment by sophiathirza** [comment]
Duplicate, so will close.
