### ISSUE TITLE
Mismatch between records showing on Isle of Man Atlas and core Atlas

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#472]
Compared 2 exact polygons - 1 using https://isleofman-records.nbnatlas.org/search#tab_spatialSearch and 1 using https://records.nbnatlas.org/search#tab_spatialSearch  Error in that NBN Atlas Isle of Man showed '0' records whilst NBN Atlas showed '80' records.

**Comment by sophiathirza** [comment]
I have tried several spatial searches in the IoM Atlas and no records have been returned.

**Comment by sophiathirza** [comment]
The polygon search doesn't seem to be working at all on the IoM Atlas.

**Comment by reupost** [comment]
As per #477
