### ISSUE TITLE
Interactive map: Records only accessible when viewing as point data (IOM)

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#473]
https://isleofman-records.nbnatlas.org/occurrences/search?q=lsid:NHMSYS0000530739#tab_mapView - none of the records return when clicking on the Variable grids.  Can only open records in point data view - this is true of all records.

**Comment by sophiathirza** [comment]
It looks like the url is being truncated so that the querystring is missing the grid reference on the records page.

**Comment by sophiathirza** [comment]
@EllaVogel this looks okay now. Would you confirm that it is still a problem?

**Comment by EllaVogel** [comment]
@sophiathirza I'm not seeing it as an issue any more either. I'll close for now
