### ISSUE TITLE
Text not displaying properly when looking at charts (IOM)

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#474]
https://isleofman-species.nbnatlas.org/species/NHMSYS0000530739#records - the legend to the charts appear 'cut off', e.g. 'anx Biological Recording Partnership' instead of 'Manx Biological Recording Partnership'
(I think this is an issue with all atlases, not just Isle of Man)

**Comment by EllaVogel** [comment]
Similar issue reported here: https://isleofman-records.nbnatlas.org/occurrences/search?q=lsid:NHMSYS0000530739#tab_chartsView - the '1800' is obscured on the vertical axis of the By month chart

**Comment by EllaVogel** [comment]
Is it possible to get an update on this issue please? I'm sending an updated log over to Isle of Man today, and they're keen to see at least a comment on each issue. Will this be easy to fix?

**Comment by reupost** [comment]
It should be something we can configure, we'd just need to be careful how it might affect other charts, since its a pretty generic component.  The charts are generated as images.  Let me take a closer look and get a more substantive comment to you in a while.

**Comment by reupost** [comment]
There's a semi-fix on e.g. https://species-dev.nbnatlas.org/species/NHMSYS0000530739#records (I've set the species-dev site to filter like the IoM one, so the charts should be similar).

Maybe have a play and see what you think.  It doesn't update dynamically, so if you shrink the screen after it's loaded you can still get truncation on the left of the text, but if you refresh the (now smaller) screen it shortens the text and puts ellipses on the right as it should.

I see there is another issue with the labels being bunched up on e.g. https://species.nbnatlas.org/species/NHMSYS0000080188#records , so it might be an idea to try to fix these (and any other) chart issues together

**Comment by EllaVogel** [comment]
This is looking really great, and definitely an improvement. Being not dynamic isn't too problematic, I'd say.

Is there a similar fix for the bunching of the labels, or is this a trickier one?

**Comment by reupost** [comment]
Take a look at https://species-dev.nbnatlas.org/species/NHMSYS0000080188#records .  This 'unbunches' the labels, but if two charts are next to each other they could slip out of alignment because one could grow taller than the other.
