### ISSUE TITLE
Additional names in Names tab

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#475]
Someone has asked: https://isleofman-species.nbnatlas.org/species/NBNSYS0000003194#names - can we supply Manx Gaelic as Common names in Names and Sources?
If they supply the names can we add them in, or do they need to go via the UK species inventory list?

**Comment by sophiathirza** [comment]
It has to go via the UK species inventory. If they can supply the names, I will send them to Chris.
