### ISSUE TITLE
IOM: Refine results option 'Recorded in Australia'

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#476]
https://isleofman-species.nbnatlas.org/search/?q=mountain+hare - Refine Results includes 'Recorded in Australia' - this is confusing in an NBN Atlas Isle of Man context.

**Comment by sophiathirza** [comment]
This section is not on any of the other Atlases (even under a different name). It should be removed from the available filters.

**Comment by sophiathirza** [comment]
Its quite a nice filter to have on the species lists of the smaller Atlases, to return those species recorded in the hub country (locatedInHubCountry=true), if it could be renamed to the hub country.

**Comment by reupost** [comment]
Fixed
