### ISSUE TITLE
User defined polygon not showing records on Isle of Man atlas.

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#477]
I got 6270 results for spatial validity within user defined polygon.  But when I changed the sort order from Ascending to Descending I got 'No records found' although using the back arrow it then said it was showing in Descending order (although I couldn't see that the order of the records had actually changed).
https://isleofman-records.nbnatlas.org/search#tab_spatialSearch

**Comment by sophiathirza** [comment]
This also sounds like the url is being truncated on changing the sort order. I have tried several polygon searches and no records are being returned.

**Comment by reupost** [comment]
The issue was bad encoding of the quote marks around "Isle of Man" in the query. Fixed in dev.

**Comment by EllaVogel** [comment]
Thanks @reupost

**Comment by reupost** [comment]
Fix deployed
