### ISSUE TITLE
Isle of Man missing from 'Choose Atlas' drop-down

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#478]

**Comment by reupost** [comment]
I think this might be for Red Paint.  The options displayed on the dropdown are simply retrieved from https://isleofman.nbnatlas.org/shared/header-bs2/ .  As far as I know, Red Paint manage that server, and/or the options could be set in WordPress.  Let me know if you want me to follow up with Giselle or Red Paint directly.

**Comment by EllaVogel** [comment]
Thanks Reuben, I'll get in touch with Giselle/Mandy and see if they know how first. Otherwise I'll mention it to Red Paint.
