### ISSUE TITLE
ALA reference on Create your account page and ALA links

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#480]
I can't seem to get into this page of the CMS desk, so wonder if this has to be done within the NBN Atlas?

The following needs amending with the bold text added or amended:
For the **NBN** Atlas' policy on the collection and use of personal information see our **Privacy Policy** (this need to be updated to NBN Atlas link to the Terms of Use, not ALA).

Your email address will be your ALA(delete and add) **NBN Atlas** account id.

**Comment by sophiathirza** [comment]
Associated issues:
#441 #231 and #193

**Comment by reupost** [comment]
Fixed the link, the 'email address will be your NBN Atlas account id' text needs the component to be redeployed

**Comment by MandyHenshall** [comment]
The NBN Atlas Help and Documentation site should be going live next week.  As there will be much clearer signposting to "Create your account" it would be great to get the "ALA" text changed to NBN Atlas, especially the "Your email address will be your NBN Atlas account id".  Is this possible @reupost ? Thanks

**Comment by reupost** [comment]
Hi @MandyHenshall - yes, I hope to deploy all the recent changes next week, which will include the 'In progress' items, e.g. the changes to the registration page

**Comment by MandyHenshall** [comment]
Brilliant!  Thanks @reupost
