### ISSUE TITLE
Don't blur the date on records of sensitive species

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#483]
The day has been removed from the event date for this sensitive species record but there is no message to indicate why: https://records.nbnatlas.org/occurrences/a3fb8b2c-01ab-41fb-a0a5-44780e449775

Some records do have the message: https://records.nbnatlas.org/occurrences/0c4671cb-4db7-4eba-94fe-ff39efb5b513

**Comment by EllaVogel** [comment]
The sensitive species steering group have decided that it's unnecessary to be altering date info for sensitive species, just the reduced location is enough. So, is it possible to remove the feature that reduces date precision please?

**Comment by reupost** [comment]
Fixed in dev; need to test on live (need to reprocess datasets with new biocache and deploy updated nbn-hub to records servers)

**Comment by sophiathirza** [comment]
Were you able to make this change live? In the recently updated mammal dataset, the day has been removed from the start date but the end date is complete: https://records.nbnatlas.org/occurrences/4dc6d378-80a6-4075-b9cc-d6aa65a6b71d

**Comment by reupost** [comment]
Please review on records-dev.

**Comment by sophiathirza** [comment]
Looks great, thanks.
