### ISSUE TITLE
Links still entitled 'Atlas of Living Australia'

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#485]
I sent a link to an NBN Atlas page via skype, and the link on the skype page was named 'Atlas of Living Australia' Is there still something behind the scenes that makes the NBN Atlas think that it's stil ALA?

![image](https://user-images.githubusercontent.com/14979912/35927945-dcc9bca6-0c23-11e8-9637-15ba8f69d11f.png)

**Comment by reupost** [comment]
Fix proposed, waiting for acceptance to redeploy ALA component, rather than fork our own version

**Comment by reupost** [comment]
Fixed lists, images, regions and sds via configuration. species and species-ws still need to be fixed in code.

**Comment by reupost** [comment]
Fixed
