### ISSUE TITLE
Spatial layers for Atlas NI

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#486]
DAERA OGL Natural Heritage datasets (https://www.daera-ni.gov.uk/articles/download-digital-datasets):
- [x] Areas of Special Scientific Interest (ASSIs)
- [x] National Nature Reserves (NNRs)
- [x] Special Areas of Conservation (SACs)
- [x] Special Protection Areas (SPAs)
- [x] Ramsar Sites
- [x] Areas of Outstanding Natural Beauty (AONBs)
- [x] Landscape Character Areas
- [x] NI Regional Seascape Character Assessment
- [x] World Heritage Site
- [x] NI Regional Landscape Character Assessment

Water datasets (https://www.daera-ni.gov.uk/articles/wmu-digital-dataset-downloads):
- [x] Lakes
- [x] Rivers [river segments or river water bodies?]
- [x] River Basin Districts

- [x] MCZ data layer (provided by email)

- [ ] Geology layer (url not working, I have emailed Pauline about it): 
https://utility.arcgis.com/usrsvcs/servers/07cd6ef9c3714b8cb493527c31b6a9ed/rest/services/Geology/Geology/MapServer

Second batch:
RSPB, Ulster Wildlife, National Trust

All layers should appear together in the list of available spatial layers, which means that they probably need to be called NI - * or have the category as Nothern Ireland

**Comment by sophiathirza** [comment]
Mike has prepared the next 8 NI spatial layers for processing.

**Comment by reupost** [comment]
For the rivers, the river water bodies is quite different from the river segments.  The segments look like rivers, while the water bodies look a bit like catchment areas.  Could you confirm you want the water bodies as per the spreadsheet?

**Comment by sophiathirza** [comment]
they probably want both, I didn't realise there were two under Rivers. I'll update the spreadsheet

**Comment by reupost** [comment]
I've uploaded all the layers except the rivers, if you wouldn't mind adding the metadata on  https://layers.nbnatlas.org/ws/admin/layers

**Comment by sophiathirza** [comment]
The segments dataset doesn't have any unique ids. So let's just stick with water bodies for now

**Comment by reupost** [comment]
Ok, done

**Comment by sophiathirza** [comment]
I've added the metadata and asked Pauline for the details on the second batch. I will close this issue once the layers are sampled.

**Comment by sophiathirza** [comment]
The geology layer that we were given doesn't have unique ids.
