### ISSUE TITLE
Citation format for downloads from many sources - could a condensed version be developed?

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#487]
Received the following comment re using citations: 

Regarding the citation document you get with the Atlas download - This is helpful if you only are using data from one or a small number of datasets, but if like me you were downloading data for all of the UK for one species, the citation list is very long. See attached for Harlequin Ladybird records for UK. I am still not sure how I would include a credit on a map sensibly. I looked at the Atlas page “Guidance for using data” (https://nbnatlas.org/help/guidance-using-data/) to see if there was any further advice on crediting long lists of data providers in maps etc. but could not find anything. My only solution is to use the brief credit “NBN Atlas occurrence download at https://nbnatlas.org accessed on Tue Feb 20 16:26:32 UTC 2018. List of data providers given in Annex 1”. Annex 1 would be 5 pages long to include all the information given in the READ ME file. So, it would be nice if there was a condensed citation available that people can use in reports/ maps?

[README.pdf](https://github.com/nbnuk/nbnatlas-issues/files/1748384/README.pdf)

**Comment by sophiathirza** [comment]
I think what the person suggested is okay, to give a brief credit and list the data providers or datasets in an appendix. I am not sure what a condensed citation could be.

The list of citations, when you download records, includes both entries for both the data provider and the individual datasets. Is it necessary to have both? I would have thought that only the dataset citation is required, thought it is good to have data providers as well.

Our guidance on using the citations should be improved, I'll take a look.

**Comment by CEJohnston** [comment]
Thanks @sophiathirza - in due course as not high priority. I agree it is difficult to think of a condensed version unless there is some way of facilitating the saving of a search or the downloads so that they could be accessed online.

**Comment by sophiathirza** [comment]
We now have a page on the help site for citation help: https://docs.nbnatlas.org/cite-nbn-atlas-data/

**Comment by CEJohnston** [comment]
Thanks @sophiathirza - this is useful.  I think retaining both dataset and data provider name in the citation list is important as sometimes the data provider name is not clear from the dataset name.
