### ISSUE TITLE
Change Thumbnail on 'add layer' box in Spatial Portal to be outline of Scotland, not Australia

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#49]
Small issue but high priority as it will be annoying to users!

**Comment by djtfmartin** [comment]
Well spotted ! This will require some design help

**Comment by CEJohnston** [comment]
We have requested an image from the designer - thought we could use the small letter a with the leaf from the logo in black and white.

**Comment by CEJohnston** [comment]
Have sourced an image as .png from the designer - will email.

**Comment by djtfmartin** [comment]
Thanks Christine. Just spoke with Rachel and seen the image. Im not sure its the best choice.
The icon is intended to indicate to the user if they are loading a raster or vector layer (we currently only have vector layers in ALS).

See screenshot from ALA

<img width="852" alt="screenshot 2016-05-06 10 38 56" src="https://cloud.githubusercontent.com/assets/444897/15069779/dc89a144-1377-11e6-8146-e7730c16c28a.png">

**Comment by CEJohnston** [comment]
OK - will discuss with the others. Not sure we want a country specific outline as its UK wide!

**Comment by djtfmartin** [comment]
something generic makes good sense.

**Comment by djtfmartin** [comment]
Ive used one of the icons Will has provided.

**Comment by CEJohnston** [comment]
Which one? I have looked on the spatial portal and it's still showing as Australia.

**Comment by djtfmartin** [comment]
It requires a browser cache clear im afraid. Heres a screenshot:

<img width="894" alt="screenshot 2016-05-06 14 54 26" src="https://cloud.githubusercontent.com/assets/444897/15075099/8575e8d6-139a-11e6-91ce-c61915c27a2f.png">

**Comment by EllaVogel** [comment]
Looks good Dave, thanks.

Christine, if you're using google chrome, hold ctrl+shift+r to refresh the
webpage and refresh the cache. That worked at my end.

Ella

On 6 May 2016 at 14:55, Dave Martin notifications@github.com wrote:

> It requires a browser cache clear im afraid. Heres a screenshot:
> 
> [image: screenshot 2016-05-06 14 54 26]
> https://cloud.githubusercontent.com/assets/444897/15075099/8575e8d6-139a-11e6-91ce-c61915c27a2f.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/nbnuk/als-issues/issues/49#issuecomment-217446863

## 

Ella Vogel

NBN Trust Project Development Officer

M: 07506 863 980

E: ellavogel.nbn@gmail.com

NBN website: www.nbn.org.uk

NBN Gateway: http://data.nbn.org.uk

 [image: NBN-Logo-153x80]

_NBN Trust_ - Registered in England and Wales - Company no.3963387 -
Registered charity no. 1082163.

Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL

**Comment by CEJohnston** [comment]
Thanks both - it's exactly the icon that I would have chosen! Christine

Christine Johnston
NBN Scottish Liaison Officer
tel: 07342254589
email: c.johnston@nbn.org.uk

NBN website: www.nbn.org.uk
NBN Gateway: http://data.nbn.org.uk
Atlas of Living Scotland: www.als.scot

*NBN Trust *- Registered in England and Wales - Company no. 3963387 -
Registered charity no. 1082163
Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL

**\* Nominations are now open for the UK Awards for Biological Recording and
Information Sharing! ***
http://nbn.org.uk/news/uk-awards-nominations-open/
