### ISSUE TITLE
Record list from map grid

### ISSUE THREAD

**Issue by reupost** [nbnuk/nbnatlas-issues#490]
If you are one grid references on the map, not points, and try to follow through to 'view record', no records are returned!

**Comment by reupost** [comment]
Fixed in dev

**Comment by EllaVogel** [comment]
This is still an issue for me

**Comment by reupost** [comment]
I haven't deployed the fix yet :)  That's the 'in progress' tag

**Comment by EllaVogel** [comment]
Right! I'm with you now :)
Can you drop a message when it's deployed, then I can update the issues log spreadsheet log?

**Comment by reupost** [comment]
Fix deployed
