### ISSUE TITLE
Grammatical error in the species pages text

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#492]
In the species pages text there is either a missing word or too many words in the text box that describes the number of datasets that have provided data for the species map.

Eg after a search for peregrine falcon in the NBN Atlas Scotland, under Datasets it says '31 datasets have provided data to the for this species'.   I think 'to the' could be removed so that it just says '31 datasets have provided data for this species' or the word 'Atlas' is added after 'to the' but my preference would be the former.

**Comment by reupost** [comment]
Fixed.  The latter option keeps consistency with the main code, so I've used that, hope that's ok.

**Comment by CEJohnston** [comment]
That looks OK to me - thanks @reupost
