### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by acclivity2** [nbnuk/nbnatlas-issues#493]
on page   https://species.nbnatlas.org/search/?q=Salicornia+europaea

"Glassowrt"  is a typo

Common Glasswort, Common Glassowrt

**Comment by sophiathirza** [comment]
Thank you for letting us know. 

The name comes from the UK species inventory and we can't change it directly on the Atlas. I have updated our export to ensure that the next time we update the species names 'Common Glassowrt' will not be included.
