### ISSUE TITLE
No records returned when viewing second page of a record list

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#496]
I did a search  by location, selected bird and viewed the records (I also sorted by taxon_name):

https://records.nbnatlas.org/occurrences/search?q=*:*&fq=species_group:Birds&sort=taxon_name&lat=57.34421&lon=-6.065360000000055&radius=5

Clicking on the second page returns no results. The url for the second page is below. It includes a taxa query element, which is missing from the url of the first page:
https://records.nbnatlas.org/occurrences/search?taxa=&q=*%3A*&fq=species_group%3ABirds&wkt=&lat=57.34421&lon=-6.065360000000055&radius=5&dir=&sort=taxon_name&offset=20&max=20

**Comment by reupost** [comment]
Fixed in dev, will be deployed next week
