### ISSUE TITLE
Species counts on spatial queries

### ISSUE THREAD

**Issue by reupost** [nbnuk/nbnatlas-issues#500]
The pop-up 'species count' for a spatial search is not actually a count of species.  For example, on the Northern Ireland portal, a bounding box encompassing the entire area gives 9933 species. 

This is derived from a WS call to https://records-ws.nbnatlas.org/occurrence/facets.json?q=*%3A*&qc=cl28%3A%22Northern+Ireland%22&facets=taxon_name .  But taxon_name is just one possible facet to group by. Using facet 'species_guid' gives 8582 'species', while using 'names_and_lsid' gives 9978. A manual count of the species occurring in cl28:Northern Ireland, taking synonymous names and mapping them to accepted names to determine distinct taxon concepts, gives 7136.  

For the entire NBN Atlas, the front page gives 71 327 species.  A spatial query gives 55 800.

**Comment by sophiathirza** [comment]
Part of the difference might be that for a spatial query the coordinates of the occurrence are needed and we don't have them for all records.

Are occurrence records linked to synonym names?

taxon_name is not unique; many have the same name but different authorships and/or attributes (see #426) 

I think that names_and_lsid is better but it will include all taxon ranks not just species. If you only want species than you should filter by rank=species.

**Comment by sophiathirza** [comment]
This has been corrected.
