### ISSUE TITLE
Unable to download registered users again

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#502]
Hi Reuben,
I'm getting the same issue that I seem to get every time when I try to download a csv of registered users.  Please can you add my IP address again - 81.140.254.96?  Thanks in advance!
Mandy

**Comment by reupost** [comment]
Should work now @MandyHenshall, could you check?

**Comment by MandyHenshall** [comment]
Yes, that worked.  Thank you @reupost !
