### ISSUE TITLE
Image pop-up refers to ALA

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#503]
The image dialogue box that opens when you click on an image refers to ALA in the bottom right-hand corner.
![screen shot 2018-03-27 at 12 54 17](https://user-images.githubusercontent.com/1651015/37963364-554413c4-31be-11e8-888d-8ad6aa32fbcb.png)

**Comment by reupost** [comment]
Fixed in dev

**Comment by c-van-dierkson** [comment]
reviewed 11/12/2019 - is now OK (says NBN Atlas) - close
