### ISSUE TITLE
Remove: 'Recorded on the isle of man' filter

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#508]
Comment below emailed thorugh:

https://isleofman-species.nbnatlas.org/search?fq=idxtype%3ATAXON&q=woodpecker

Please can we remove the words in the left hand box ‘Recorder in the Isle of Man Yes (5)’. I’m using the search term Woodpeckers as an example, so on this page it implies there are 5 species of Woodpecker on the IOM (what it actually means is there are 5 species in the list on the right, taken from the taxonomic dictionary). In fact if you look at the main list on the right, you can see in red, ‘Occurrences: 186 for Great Spotted Woodpecker’ but no occurrences for the others listed. (except the family Picidae which has the same number 186 ie the same records, so doesn’t count).  I have looked at the other country Atlases and they do not have the ‘Recorded on…’ piece. So I guess it got left on ours by mistake.

**Comment by reupost** [comment]
Done
