### ISSUE TITLE
Explore your area, no records found

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#510]
Using ‘Explore your area’, I searched location 'Ayres' and filtered Birds, selected European White-fronted Goose, for which two records were found yet on clicking on the dot on the map it stated “No records found”

**Comment by sophiathirza** [comment]
The link has this url: https://isleofman-records.nbnatlas.org/occurrences/search?q=*:*&fq=species_guid:NHMSYS0000532791&lat=54.417&lon=-4.39&radius=0.05

Records are returned when species_guid query parameter is replaced with lsid:

https://isleofman-records.nbnatlas.org/occurrences/search?q=*:*&fq=lsid:NHMSYS0000532791&lat=54.417&lon=-4.39&radius=0.05

**Comment by EllaVogel** [comment]
Thanks Sophie, you beat me to it! I've just tried for other species on this list and records are returned fine, so it's possibly just an issue with European white-fronted goose

**Comment by reupost** [comment]
Would you mind seeing if there are any other species with this problem, or if there's something 'funny' about that goose record?

**Comment by EllaVogel** [comment]
I've just tried for other species on this list and records are returned fine, so it's possibly just an issue with European white-fronted goose

**Comment by reupost** [comment]
Here's another one: Search for 'Calf', select birds, 

27. | Anser albifrons subsp. flavirostris : Greenland White-fronted Goose
-- | --

Clicking on the list of records returns them correctly (searching by species name) but the map point click does not.

**Comment by reupost** [comment]
Fixed in dev, using the same taxon_name criterion as the 'list of records' links in the species list concertina.  Note that this criterion is not ideal, since two taxa could have the same name, excluding taxonomic authority

**Comment by sophiathirza** [comment]
Two taxa can have the same name including taxonomic authority: #426

**Comment by reupost** [comment]
Agreed. Based on the logic of the page, using the name makes it consistent. There is a call to records-ws to get the original list of species which needs to be looked into.
