### ISSUE TITLE
Zoom out from country view to whole NBN Atlas view

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#517]
Enhancement from Jo: Zoom out from country view to whole NBN Atlas view

**Comment by sophiathirza** [comment]
@JoJudge, from which page? Do you mean from the map on the species pages?

**Comment by JoJudge** [comment]
I was thinking more for the interactive map and spatial portal

**Comment by sophiathirza** [comment]
Would you expect to stay on the country Atlas, rather than being directed to the UK Atlas?

**Comment by JoJudge** [comment]
I think if looking at a UK scale it would be fine to be directed to the UK Atlas.

**Comment by c-van-dierkson** [comment]
Jo confirms to close
