### ISSUE TITLE
Download wizard bypassed on spatial portal

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#518]
When trying to download records through the 'quick links' box on the spatial portal (load species occurrences and use quick links box to select 'download all records of this species'), you are not taken via the download wizard, but instead are able to download a csv without all of the extra info about CC BY-NC licensing etc.

Also, there is a reference to the Atlas of Living Australia when you download via this route on the Welsh Atlas
![image](https://user-images.githubusercontent.com/14979912/39198209-66d8b1ea-47de-11e8-93bd-9d616846d558.png)

**Comment by reupost** [comment]
See #509 as well

**Comment by reupost** [comment]
Fixed
