### ISSUE TITLE
Add licence field to citation.csv file in downloads

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#521]

**Comment by sophiathirza** [comment]
Even better.... would it be possible to include the contact email for the dataset in citation.csv file (as well as the licence)?

**Comment by reupost** [comment]
The license is included in the citation.csv file as far as I can see:

UID | Name | DOI | Citation | Rights | More Information | Data generalisations | Information withheld | Download limit | Number of Records in Download
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
dr909 | BRERC species records within last 15 years | doi:10.15468/vntgox | Records provided by BRERC species records within last 15 years, accessed   through NBN Atlas website. | **Creative Commons, with Attribution, Non-commercial v4.0 (CC-BY-NC)   CC-BY-NC** | For more information:   https://registry.nbnatlas.org/public/show/dr909 |   | 5956

**Comment by sophiathirza** [comment]
that's the Rights free text field, which is not always populated (I will start adding it). It would be better to have the licence field as well.

**Comment by reupost** [comment]
From the code, it looks like this is based on the actual licence, its just replacing it with the full name for it instead of the abbreviation. All the datasets have a licence.  Could you send me an example where its not filled in, and then I can either update the lookup list, or amend the code?

**Comment by sophiathirza** [comment]
sorry, my mistake. I was looking at data partners. If the email address could be added to more information, that would be really great.
