### ISSUE TITLE
'Choose more' option not available for licences on interactive map

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#524]
When on interactive map (https://records.nbnatlas.org/occurrences/search?q=pine+marten#tab_mapView) the is not the 'choose more' option underneath the licence filters, so you are unable to select more than one licence to view. This option does appear beneath most other filters
![image](https://user-images.githubusercontent.com/14979912/39817368-e2223444-5395-11e8-8acc-6df22fe108a7.png)

**Comment by sophiathirza** [comment]
It's because there are no other licences in the list of records.

**Comment by EllaVogel** [comment]
The choose more button opens up a new window where you can select multiple attributes from the same category (e.g. datasets, or licences) and then choose to include or exclude the selection. If I wanted to exclude NC licences, I can't do this without the 'choose more' option, as I can only choose to see either CC BY or OGL, not both together

**Comment by sophiathirza** [comment]
sorry, yes, that's true.

**Comment by sophiathirza** [comment]
@reupost I think that this is a bug...

**Comment by sophiathirza** [comment]
This is working now, thanks.
