### ISSUE TITLE
NC records sometimes re-appear once they've been excluded

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#525]
A worked example of how to replicate this error is below:

1. Log into main Atlas
2. From 'Locations' tab choose 'Explore by Pre-defined area'
3. National Parks, select Brecon Beacons NP.
4. Zoom to region and click the Brecon Beacons NP 'button' 
5. Click the button.
6. Click the Map tab
7. Drop down the 'Attribution' menu and click on 
8. Click on CC-BY-NC and then on 'EXCLUDE selected items'
9. Use the rectangle tool ()on the map window to drag a small box covering a few 1km squares .
and click on 'Search for records in this area'.
10. You will now see that the NC records have all reappeared.

**Comment by reupost** [comment]
For step 5, do you mean click the 'Occurrences' button? I'm actually having trouble replicating this issue.

**Comment by EllaVogel** [comment]
Apologies, the text didn't copy properly from the email that reported the issue. Step 5 is 'select the 'view records' button.

I followed the steps through and could replicate

**Comment by sophiathirza** [comment]
I think that Jo said that the exclude doesn't work at all.

**Comment by c-van-dierkson** [comment]
Unable to replicate. Jo confirms to close.
