### ISSUE TITLE
Incorrect "related links" on occurrence records list of species

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#526]
When searching for Badger at the top right of the page of returned results, the Related Links aren't right.  The BHL link goes to no results and the Occurrence records shows (0). When you click on the Occurrence records link it goes to a page saying: No records found for UNRANKED: Badger Face Welsh Sheep
https://species.nbnatlas.org/search?q=badger
This rings a bell, so sorry if it's been reported before.

**Comment by sophiathirza** [comment]
I've tried a few different searches and this only seems to be a problem when searching for badger.

**Comment by c-van-dierkson** [comment]
close, will be corrected with the new species search
