### ISSUE TITLE
Error when clear filters

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#528]
Email received: I am searching in a pre-defined area (BIS) and using the filters to exclude CC-BY-NC data and data provided by BIS. I am then choosing one data resource at a time to include and view. If I try to remove one of the filters, so for example remove the data resource so that I can select an alternative one, I always get an error message 'no records in cl84:"Biodiversity Information Service for Powys & Brecon Beacons National Park"  

https://records.nbnatlas.org/occurrences/search?q=cl84%3A%22Biodiversity+Information+Service+for+Powys+%26+Brecon+Beacons+National+Park%22&fq=rank%3A%28species+OR+subspecies%29&fq=%28license%3A%22OGL%22+OR+license%3A%22CC-BY%22+OR+license%3A%22CC0%22%29&fq=data_resource_uid%3A%22dr1212%22

**Comment by sophiathirza** [comment]
I have been able to recreate this.

**Comment by c-van-dierkson** [comment]
ok to close
