### ISSUE TITLE
Add establishmentMeans and establishmentStatus to all species pages

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#532]
Please add establishmentMeans and establishmentStatus to the species pages in all the Atlases, as in the INNS portal.

**Comment by reupost** [comment]
Do you mean in the species header text, where 'Name authority' is, and/or as a facet for searching, and/ or to include in the species results listing? To include it in the header text I would need to deploy the new species component, which is still under development, so I'd rather wait on that for a little while.

**Comment by sophiathirza** [comment]
In the species header, next to Name authority.

No rush for this, just something that would be great to have once the INNS portal has been launched.

**Comment by sophiathirza** [comment]
This has been done.
