### ISSUE TITLE
Sensitive species blurring

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#533]
An excerpt from the Sensitive Species Policy:

_Seasonal Sensitivity   
Many species are only sensitive at certain times of the year or during specific life cycle stages e.g. breeding. The sensitive species lists may therefore define a date range within which the species’ location must be blurred. All records for species outside of that date range will be available at the full supplied resolution._  

So, at some point we'll need to look at developing the functionality to blur records depending on date, as well as species name. These dates are supplied in the new sensitive species lists. People have been told that this development isn't one of the top priority jobs though.

**Comment by sophiathirza** [comment]
I think we should close this and reopen on Trello once we have the complete requirements.
