### ISSUE TITLE
Review download reasons

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#534]
We should review the different download reasons as there are several that are very similar.

Also, add an LERC option.

**Comment by sophiathirza** [comment]
We had a suggestion to include the sectors (from the SBIF review, https://nbn.org.uk/about-us/where-we-are/in-scotland/the-sbif-review/stage-2-gather-understand-stakeholder-requirements/) in an additional drop down:

Roles and Sectors defined in the Review
Roles:

    Recorder or Data Collector
    Verifier or County Recorder
    Collection Curator
    Recording Group Operator
    Recording Scheme Operator
    Data Provider
    Data Developer
    Data User
    Service Provider
    Service User
    Funder
    Facilitator

Sectors:

    Recorders or Recording Groups
    National Recording Schemes
    Environmental/conservation Non-Governmental Organisations
    Local Environmental Records Centres
    Commercial companies and environmental consultancies
    Museums, zoos and botanic gardens
    Academia and education
    Local authorities and national park authorities
    National or central government
    Cross-sectoral partnership or secretariat organisations

**Comment by sophiathirza** [comment]
Additional suggestion: the user also has to check a box to indicate whether THEY regard the current usage as commercial

**Comment by sophiathirza** [comment]
Comments:

I think the sectors list is fine, however the Roles needs some work. I would like to see “Policy Maker/Advisor” included and somehow be able to capture Student usage (both secondary and tertiary levels, MRes/PhD etc). This could be implied from the Academia/Education Sector but the granularity would be welcome.

**Comment by CEJohnston** [comment]
Happy to review / create a suitable list of sectors and roles with @sophiathirza

**Comment by sophiathirza** [comment]
In the interim, could a LERC option be added to the list of download reasons: #610, please?

**Comment by sophiathirza** [comment]
more comments on using SBIF roles and sectors:

Does it make sense to have two lists? Or better to combine into one? Are there too many options? Yes, some of these roles/sectors made sense in context of the SBIF review, but are they all relevant regarding downloading data from NBNA? I wonder if it might be better to boil it down further to a smaller number of options. For example (and these are off the top of my head now and could well be improved):

a) Public - download is for personal use only
b) Volunteer researcher/publisher - download may lead to amateur (non-funded) publication - maybe this would include National or Local scheme collators and verifiers.
c) Professional researcher/publisher - download may lead to professional publication (including universities, NGOs etc - anything where people are being paid to research and publish)
d) Commercial - download is for purposes of fulfilling a commercial contract (?)
e) Statutory - download is by a government-linked body for their statutory work

In this model, LERCs are perhaps tricky (as is often the case!) as they can mix elements of b, c, d and e, depending on the LERC itself and the task being undertaken.

Education use (e.g. in schools) is perhaps another case. Nice to encourage, but at the same time, perhaps having it recorded that NBN data were being used in such a way could be useful justification for funding from Dept of Education?

**Comment by sophiathirza** [comment]
Please replace the download reasons with the following:

a) Public - download is for personal use only
b) Volunteer researcher/publisher - download may lead to amateur (non-funded) publication - maybe this would include National or Local scheme collators and verifiers.
c) Professional researcher/publisher - download may lead to professional publication (including universities, NGOs etc - anything where people are being paid to research and publish)
d) Commercial - download is for purposes of fulfilling a commercial contract
e) Statutory - download is by a government-linked body for their statutory work
f) Education – download is for use by primary, secondary and tertiary educational purposes

I guess the text after the hyphen should be added as help on the page. Could we have a dialogue box that displays the descriptions?

I need to check where LERC downloads fit in this scheme.

**Comment by sophiathirza** [comment]
Final list:

a) Public - download is for personal use only
b) Volunteer researcher/publisher - download may lead to amateur (non-funded) publication - maybe this would include National or Local scheme collators and verifiers.
c) Professional researcher/publisher - download may lead to professional publication (including universities, NGOs etc - anything where people are being paid to research and publish)
d) Commercial - download is for purposes of fulfilling a commercial contract
e) Statutory - download is by a government-linked body for their statutory work
f) Education – download is for use by primary, secondary and tertiary educational purposes
g) LERC work

**Comment by CEJohnston** [comment]
I think the list is good.  It is hard to define LERC work as they all do so many different things.  Perhaps it could be explained along the lines of 'LERC - download is for use by a local environmental records centre to support provision of its services'
Just a couple of extra thoughts:
1. Under Statutory: specify also local authorities? [Statutory - download is by a government-linked body or local authority for their statutory work.]
2. Just thinking about a collection curator (for a museum or herbarium) - perhaps in c) add the word collections after NGOs?
I like the idea of a dialogue box that displays the descriptions.

**Comment by reupost** [comment]
For the purposes of deriving consistent ongoing statistics on user downloads, is it possible to match up all or some of the old reasons to the new reasons, or are these a completely new set (i.e. not directly comparable)? 

Here is the old list with my best guess at the corresponding entry on the new list:

1. conservation management/planning
2. biosecurity management/planning
3. environmental assessment
4. education == f) Education – download is for use by primary, secondary and tertiary educational purposes
5. scientific research
6. collection management
7. ecological research
8. systematic research/taxonomy
9. testing == h) testing
10. citizen science
11. restoration/remediation
12. statutory work == e) Statutory - download is by a government-linked body or local authority for their statutory work
13. LERC work == g) LERC work - download is for use by a local environmental records centre to support provision of its services

Here are the unmatched new entries (with Christine's amendments where applicable):

a) Public   - download is for personal use only
b) Volunteer researcher/publisher - download may lead to amateur (non-funded) publication   - maybe this would include National or Local scheme collators and verifiers.
c) Professional researcher/publisher - download may lead to professional   publication (including universities, NGOs, collections, etc. - anything where   people are being paid to research and publish)
d) Commercial - download is for purposes of fulfilling a commercial contract

@sophiathirza  could you advise if there are any other matches? Once I've implemented the change, the unmatched terms from the old list will be deprecated, so we will stop gathering statistics on them.

**Comment by sophiathirza** [comment]
The terms and conditions text at the bottom of the download page: https://records.nbnatlas.org/download?searchParams=%3Fq%3D*%253A*%26fq%3Didentification_verification_status%253A%2522478%2522&targetUri=/occurrences/search&totalRecords=2

refer to the ALA: By downloading this content you are agreeing to use it in accordance with the Atlas of Living Australia Terms of Use and any Data Provider Terms associated with the data download. 

Can this be changed to NBN Atlas?

Could the description of each download reason be included on the page, please?

**Comment by reupost** [comment]
Hi Sophie

Yes, I'll fix that.

The descriptions of the reasons are visible when you pick an item from the
list, it is displayed below in italic text. Let me know if that doesn't
work for you, I didn't want to make a pop-up which would need another click
to get rid of, but I'm open to suggestions.

Cheers

Reuben

**Comment by sophiathirza** [comment]
Hi Reuben,
Ah, I see the description now. Let's leave it for now and see what people
think,

thanks, Sophie

**Comment by reupost** [comment]
ALA link at the foot of the downloads page is now corrected

**Comment by sophiathirza** [comment]
brilliant - thanks.
