### ISSUE TITLE
Download page no longer refreshes to download zip file

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#536]
Once a download is ready for downloading the Atlas page used to refresh and provide the URL to the zip file for the user.

Now the page no longer refreshes automatically, so there is no indication to the user that the download is finished (other than the email which people don't always get).

A hard return on the Atlas page, once the email has been received, shows the message  Thank you for your download

Your download has completed

The download has already been run. Click the button below to start over. 

Would it be possible to refresh the page automatically and give the user URL to the zip file, please?

**Comment by reupost** [comment]
Should be fixed now

**Comment by sophiathirza** [comment]
I've tested several times up to 150k records and the page automatically refreshes with the download now link each time, thanks!
