### ISSUE TITLE
Map tools: expand their availability

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#54]
Comment in full: The map can’t be resized and there are limited interactive tools. It would be good if the map tools from the other interactive map were available so you can interrogate the records (making spatial selections etc.).

[http://records.als.scot/explore/your-area#55.94576711058396|-3.219697273366478|12|ALL_SPECIES](url)

**Comment by djtfmartin** [comment]
This is a major enhancement. Requires re-working of EYA tool.

**Comment by djtfmartin** [comment]
Im going to remove the "high-priority" flag  as its a bit of a distraction. 

The Atlas contains multiple mapping tools, with resizing etc. This is a comment on EYA which is fixed intentionally for simplicity.
