### ISSUE TITLE
Date accuracy - record with year date defaults to 1st January

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#541]
Accuracy of phenology / climate change data [a record with a year date defaults to 1st January].  If old record only has a year on it, ie 2003, the record defaults to 1st January - there needs to be more explanation on the record itself otherwise it will show up as inaccurate - swifts flying on 1st January, arrivals of cuckoo, etc

**Comment by sophiathirza** [comment]
We need to assess is this is still a problem as Dave had corrected the original problems that we had with the dates and said that the phenology charts were okay.

**Comment by sophiathirza** [comment]
Linked to #451

**Comment by sophiathirza** [comment]
@reupost what requirements do you need?

Dates entered as years or months should not default to the first day of the year or the first day of the month, as was happening previously. I thought that this was corrected, so we just need to check that it isn't still a problem.

**Comment by reupost** [comment]
"there needs to be more explanation on the record itself otherwise it will show up as inaccurate" - do we need anything here?

From #451, I can't see what is wrong with this one: https://records.nbnatlas.org/occurrences/765d0adb-2a6a-4855-bc29-2ce874914526

**Comment by sophiathirza** [comment]
It shouldn't display as first of the month anyway. As long as it only displays as a year and the phenology charts are correct, I don't think that any explanation is needed.

**Comment by sophiathirza** [comment]
I think that this is corrected. Any problems are due to the data and not the code. e.g.:https://records.nbnatlas.org/occurrences/d66263f4-ce2a-4c45-af63-7a719d3c2f51
