### ISSUE TITLE
Develop ability to create species list for multiple criteria

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#542]
Make it possible (or easier if it already exists) to make a species list (for a particular taxonomic group, or all groups) for a 10km square, tetrad, monad etc. If you are going out to record it is useful to what has been recorded already and know where to target recording effort.

Develop through the Advanced Search?

**Comment by sophiathirza** [comment]
Requirements need to improve the advanced search.

**Comment by c-van-dierkson** [comment]
Is this just download a species list for an area? Already possible, but maybe need better instructions? @CEJohnston @sophiathirza

**Comment by sophiathirza** [comment]
@c-van-dierkson this might be a duplicate. The new advanced search will allow searching by grid reference.

**Comment by c-van-dierkson** [comment]
Hi Sohpie.

This one? https://trello.com/c/h71rrqHp/278-advanced-records-search-design

**Comment by sophiathirza** [comment]
@c-van-dierkson yes, that's it.

**Comment by c-van-dierkson** [comment]
Closing as captured https://trello.com/c/h71rrqHp/278-advanced-records-search-design
