### ISSUE TITLE
Know age of the harvest rates 

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#546]
Dataset metadata requirements.

**Comment by CEJohnston** [comment]
Comment from the Welsh stakeholder group: Show data profile (how old is data) in metadata for each dataset.

**Comment by c-van-dierkson** [comment]
Is this a duplicate of #396? @CEJohnston @sophiathirza

**Comment by sophiathirza** [comment]
@c-van-dierkson yes.
