### ISSUE TITLE
Make the interactive map positive records only

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#550]
Make the default display map positive records only. Displaying absence records on the map, undistinguished from presence records, is confusing to everybody.  An Atlas of species distributions should show you where the species is, not where it isn't. 

Currently the species map displays presence only but the interactive map displays presence and absence with the ability to switch off absence.

**Comment by CEJohnston** [comment]
Welsh stakeholder group comment: Need to display negative records. Further requirements: 1) Species not found, but habitat looks ok so worth another visit, 2) species not found, habitat unsuitable, 3) species not found, wrong time of year- for phenological studies

**Comment by c-van-dierkson** [comment]
This is covered by the improvements to the overview page and already captured in Trello.
