### ISSUE TITLE
Source local authority and vice county boundaries

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#553]
Being able to see the local authority / vice county boundaries on search maps (cf. Grab a Grid Reference). To be able to check where a record comes form when close to the boundaries - especially useful in relation to LBAPS.

Source and add local authority boundary layer in the first instance. Can then be added to the spatial portal but not interactive map.

**Comment by CEJohnston** [comment]
Re Northern Ireland county boundary layer file - good to see it in the layer chooser but I get a Layer Unavailable message on the map when try to upload.  A legend appears but it is a habitat legend.
![image](https://user-images.githubusercontent.com/18594564/46948155-f3363580-d074-11e8-9254-817734162e75.png)

**Comment by CEJohnston** [comment]
Reference #603  The import script seems to be assigning habitat information from somewhere else to the importing of this layer hence the error message ...... objects have already been created for all fields table entries for layer?

**Comment by CEJohnston** [comment]
I have local authority boundaries ready for Wales, England, Scotland and GB.  File sizes are large - Wales only 2MB, but England 7MB and 21MB; Scotland 19MB; GB 43MB even when zipped.  Emailing Scotland failed - can I upload the files to S3 to transfer them @reupost please?  The rest of the info about the layers is ready to go.

**Comment by CEJohnston** [comment]
Just to clarify - the county boundary layer for Northern Ireland needs to be enabled to complete local authority boundaries across the whole of the UK.  The original source is: [https://www.opendatani.gov.uk/dataset/osni-open-data-largescale-boundaries-county-boundaries1 ](url)

**Comment by sophiathirza** [comment]
NI county boundary:
Zip file name: OSNI_County_Boundaries.zip
Shape file name: OSNI_County_Boundaries.shp
Layer name: County Boundaries (Northern Ireland)
ID field: COUNTY_ID
Name field: COUNTYNAME

**Comment by CEJohnston** [comment]
@sophiathirza - will start sending over the spatial files you need, as requested.  Just attaching is a document I wrote about the files while I was creating them and it includes layer names and field names for import  - should be useful.
[LA sources for NBN Atlas 2.docx](https://github.com/nbnuk/nbnatlas-issues/files/2740406/LA.sources.for.NBN.Atlas.2.docx)

**Comment by CEJohnston** [comment]
@sophiathirza - have created a new channel in the NBN Atlas Teams group called 'Spatial layer upload' - can you see it and download the file for Wales - the smallest file?

**Comment by sophiathirza** [comment]
- [x] NI county boundary:
Zip file name: OSNI_County_Boundaries.zip
Shape file name: OSNI_County_Boundaries.shp
Layer name: County Boundaries (Northern Ireland)
ID field: COUNTY_ID
Name field: COUNTYNAME

- [x] Local Authorities (Scotland)
Zip file name:  local_authorities_scotland.zip
Shape file name: local_authorities_scotland.shp
Layer name: Local Authorities (Scotland)
ID field: CODE
Name field: NAME

- [x] Local Authorities (Wales)
Zip file name:  local_authorities_wales.zip
Shape file name: local_authorities_wales.shp
Layer name: Local Authorities (Wales)
ID field: CODE
Name field: NAME

- [x] Districts, Boroughs and Unitary Authorities (England)
Zip file name: district_borough_ua_england.zip
Shape file name: district_borough_ua_england.shp
Layer name: Districts, Boroughs and Unitary Authorities (England)
ID field: CODE
Name field: NAME

- [x] Non-Metropolitan Counties and Greater London (England)
Zip file name: county_region_england.zip
Shape file name: county_region_england.shp
Layer name: Non-Metropolitan Counties and Greater London (England)
ID field: CODE
Name field: NAME

- [x] Districts, Boroughs and Unitary Authorities (Great Britain)
Zip file name: district_borough_ua_gb.zip
Shape file name: district_borough_ua_gb.shp
Layer name: Districts, Boroughs and Unitary Authorities (Great Britain)
ID field: CODE
Name field: NAME

**Comment by reupost** [comment]
NI county boundaries = layer 127
Local authorities Scotland = layer 128
Local authorities Wales = layer 129
Districts, Boroughs and Unitary Authorities (England) = layer 130
Districts, Boroughs and Unitary Authorities (Great Britain) = layer 131
Non-Metropolitan Counties and Greater London (England) = layer 132

**Comment by reupost** [comment]
Not sure if these replace any existing layers. All new layers need metadata captured.

**Comment by CEJohnston** [comment]
These layers are all new and I have the metadata info ready to copy across to the layer list.  The GB layer was created as a straight duplicate of 128 + 129 + 130 combined - it is needed for the 'Search by pre-defined area' in the main NBN Atlas but strictly speaking does not need to be visible in the layer chooser of the spatial portal - what do you think @sophiathirza ?  Refer also to #618
