### ISSUE TITLE
Add Marine protected areas (MPAs) and SAC polygons to the maps

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#556]
MPAs - to be sourced for the whole of the UK.  SACs to be sourced for Wales.

**Comment by CEJohnston** [comment]
We require two layers published by JNCC - these show the offshore and inshore SACs and SPAs around the UK.  There is some overlap with the detail on the SAC and SPA layers from the country Agencies that are already uploaded but in order to have the offshore areas this overlap cannot be avoided.  The layers we need are:

1. Officially submitted version SACs with marine components (Special Areas of Conservation)
2. Officially submitted version SPAs with marine components (Special Protection Area)

Can be downloaded from JNCC's website: [http://jncc.defra.gov.uk/protectedsites/SACselection/gis_data/terms_conditions.asp](url)

The layers are displayed on the JNCC interactive map: http://jncc.defra.gov.uk/page-5201

Layer names for use in the NBN Atlas: 
1.  Special Areas of Conservation with marine components (UK)
2.  Special Protection Areas with marine components (UK)

Atlas categories:  UK; Protected Areas

**Comment by sophiathirza** [comment]
- [x] SACs with marine components
Zip file name: c20181212_UKSACswithMarineComponents.zip
Shape file name: c20181212_UKSPAswithMarineComponents_WGS84.shp [assumed c20181212_UKSACswithMarineComponents_WGS84.shp]
Layer name: Special Areas of Conservation with marine components (UK)
ID field: SITE_CODE
Name field: SITE_NAME

- [x] SPAs with marine components
Zip file name: c20181212_UKSPAswithMarineComponents.zip
Shape file name: c20181212_UKSPAswithMarineComponents_WGS84
Layer name: Special Protection Areas with marine components (UK)
ID field: SITE_CODE
Name field: SITE_NAME

**Comment by reupost** [comment]
Special Areas of Conservation with marine components (UK) = layer 141
Special Protection Areas with marine components (UK) = layer 142

Note an error when loading 142 "java.lang.RuntimeException: Error setting layer border in geoserver" - please check this one.

Please add metadata as needed.

**Comment by CEJohnston** [comment]
@reupost - have selected and viewed 142 without problems.  It contains the correct number of polygons.  Have been able to select from it without error.
