### ISSUE TITLE
Better signposting of deeper data sources

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#561]
Flag to say there are more/higher resolution data available. Shop window to data. Enable data users to find the data that are most useful.

**Comment by c-van-dierkson** [comment]
Closed as captured with TT whitelisting improvements

**Comment by sophiathirza** [comment]
@c-van-dierkson I'm not sure it is entirely.

**Comment by CEJohnston** [comment]
@c-van-dierkson this suggestion originated from some organisations that hold higher resolution datasets that are not available on the Atlas - specifically some LERCs and national schemes.  Generally organisations that provide a paid-for search service.  They wanted the Atlas user to be guided to providers of datasets of greater detail for the local area.   The suggestion pre-dates our plans for a Two-Tier system which is not the same but perhaps our preferred way forward now?

**Comment by JoJudge** [comment]
@CEJohnston @sophiathirza @c-van-dierkson Better signposting will be provided through the two-tier system when it is completed as people will be able to see both from the maps and record pages when higher resolution data is available. We probably need to add an information page anyway about where the data on the NBN Atlas comes from and include in there that schemes and societies may have data we don't, but that is not an NBN Atlas development issue.
