### ISSUE TITLE
List known datasets that are not on the NBN Atlas

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#562]
List of known datasets that are not on the NBN Atlas to help defuse the assumption that everything is on the Atlas (thinking specifically about commercial use here).  

Reason: It is wrongly assumed that everything is on the Atlas, and data that aren't there are invisible to this primary data resource. Would also encourage data partners to engage as a shop window.

**Comment by sophiathirza** [comment]
Could we use the 'identified' flag on the dataset? 

All datasets and species lists that have records have the flag 'dataAvailable'. The alternative is 'identified', i.e. datasets that would be great to have on the NBN Atlas but we don't have any records for yet.

**Comment by c-van-dierkson** [comment]
Jo confirms to close - Will never get a complete list of datasets so would not address the problem.
