### ISSUE TITLE
Include history of changes to a record in record annotation function

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#563]
The original stakeholder comment was: [Develop a] Database of wrong records. Once a record has been released to databases, if it proves to be incorrect, it is impossible to be sure that all copies have been deleted or corrected. If the wrong version has been published, it is impossible to withdraw. So, it would be very useful to have a database of wrong records. Anyone doing a county flora or an atlas could then check this database of wrong records to clean their data.

**Comment by c-van-dierkson** [comment]
@sophiathirza @CEJohnston Could this be done outside of the Atlas?

**Comment by sophiathirza** [comment]
@c-van-dierkson not sure what you mean. I was asked about this again recently by another group. I don't think it's something that we can really do, either in the Atlas or outside.

**Comment by CEJohnston** [comment]
@c-van-dierkson @sophiathirza this suggestion pre-dates the ability to add a comment / annotate a record.  Data partners can now be made aware of erroneous records and OUGHT to take steps to rectify, in time.   Users can now also filter out records with assertions.  I would think we have done enough to help address the underlying problem of users being made aware of incorrect records.  I'd suggest closing this issue.

**Comment by sophiathirza** [comment]
The initial question was about creating a database of incorrect records. I don't think that we can address it but it's not the same as providing an annotation function for the records.

I have been asked recently about keeping incorrect records so that there is a history of them. I said that we couldn't.
