### ISSUE TITLE
Investigate where WKT format is used in the Atlas

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#568]
Allow ESRI shapefile upload for polygon searches.  ESRI shapefiles are an industry standard, used by many people.  WKT format is not supported by ArcGIS without advanced scripting.

**Comment by sophiathirza** [comment]
WKT format is used in the spatial search: https://records.nbnatlas.org/search#tab_spatialSearch

**Comment by c-van-dierkson** [comment]
Ok to close
