### ISSUE TITLE
Footer: remove the option to select 'Locations, Get Involved and Data Partners' top level menu

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#57]
Full text: At bottom of page remove the option to select 'Locations, Get Involved and Data Partners' top level menu as these do not go anywhere .  Leave these but let them appear to turn into a button when hover over

**Comment by djtfmartin** [comment]
These links are all now live. I assume this was an issue raised early on (Sept 2015).

**Comment by CEJohnston** [comment]
The links are live but the header doesn't take you anywhere.  When you
hover on it it acts like it should be a link.

Christine Johnston
NBN Scottish Liaison Officer
tel: 07342254589
email: c.johnston@nbn.org.uk

NBN website: www.nbn.org.uk
NBN Gateway: http://data.nbn.org.uk
Atlas of Living Scotland: www.als.scot

*NBN Trust *- Registered in England and Wales - Company no. 3963387 -
Registered charity no. 1082163
Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL

**Comment by djtfmartin** [comment]
This is the expected behaviour as its a menu with drop downs.

Might be worth discussing with RedPaint.
