### ISSUE TITLE
Add ability to link records to other species

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#575]
Linking records to other species e.g. host plants, species feeding on japanese knotweed etc.. Improves biological knowledge and ecological understanding. Field recording best practice.  

This would need to be recorded by the recorder and supplied by the data partner at record level but requirements are needed.

**Comment by c-van-dierkson** [comment]
Jo confirms to close.

**Comment by sophiathirza** [comment]
@c-van-dierkson why close this one? We can do it, if the correct information is supplied.

**Comment by c-van-dierkson** [comment]
Jo's comment: Records cannot be easily linked to associated species (this is counter to field recording best practice).
If you'd like it to be reopened can you confirm with Jo please?
