### ISSUE TITLE
Record date processing errors

### ISSUE THREAD

**Issue by reupost** [nbnuk/nbnatlas-issues#576]
Gathered from #451 and #445:

1. https://records.nbnatlas.org/occurrences/8e2511b3-8c0e-4dde-ae81-4dcee177268c
Here is another example of a date range not being displayed correctly: 

2. https://records.nbnatlas.org/occurrences/765d0adb-2a6a-4855-bc29-2ce874914526
A day range not displaying properly.

3. https://records.nbnatlas.org/occurrences/e5a0829d-be2c-4c85-b43c-28c63bc7a674
A year range not displaying properly.

4. https://records.nbnatlas.org/occurrences/09ef68fc-8a06-43f4-97fc-fcf21efe9906
A month range not displaying properly.

5. https://records.nbnatlas.org/occurrences/deb0dfb4-0de6-40c4-b9a9-3c5b1c857b90
Day range but the precision shows as Month

6. https://records.nbnatlas.org/occurrences/293b830a-e24b-41c6-a51b-b0cbedf060f8
Day range but the precision shows as Year

7. https://records.nbnatlas.org/occurrences/3dbeefc0-d599-4522-9c8b-d1eaee3273b2
Date precision not supplied

8. https://records.nbnatlas.org/occurrences/d5d61dc3-99cc-462a-9c57-1d38461d4a78
Year provided but date precision not identified

**Comment by reupost** [comment]
The precision of date ranges is calculated as follows:
If the start and end dates fall on the same day, then the precision is Day
Otherwise, if the start and end dates are in the same month, then the precision is Month
Otherwise, if the start and end dates are in the same year, then the precision is Year.

There will be specific circumstances where this could give odd precisions, e.g. a date range of 30/6 to 1/7 gives Year precision despite being only 2 days, while 1/6 - 30/6 gives Month precision despite being 30 days.

@sophiathirza how should this be adjusted? This applies to 2, 5 and 6 above.

**Comment by reupost** [comment]
1. has now been resolved, though a complete reprocessing of the data is required to fix any similar records (month-day range ending on a leap year Feb 29).

**Comment by sophiathirza** [comment]
Message from the forum: https://forums.nbn.org.uk/viewtopic.php?pid=28627#p28627

This record: https://records.nbnatlas.org/occurrences/ff4f626d-1787-4517-8279-120068383bbd/ is correctly displaying a year range but the start and end date are empty in the simple download.

**Comment by reupost** [comment]
The start and end date in the download are only populated with actual dates. Because the record was stipulated as having Year range, the dates are reduced to '2003' and '2008', which won't appear. We would need to include the individual fields for start Y/M/D and end Y/M/D in the download.

**Comment by sophiathirza** [comment]
Sorry, I wasn't thinking - what I meant to say is that the start year is missing. Are you going to add an end date year as well to the downloads?

**Comment by reupost** [comment]
Yes, I will. The code for some reason blanks out the processed year month and day values when the start and end year are not the same, or if a 'Year range' precision is stipulated, so I'll review that as well.

**Comment by reupost** [comment]
These examples should be correct now (bar some refinements to the actual display, which will be made to the records component). All records need to be reprocessed to apply this fix.

**Comment by sophiathirza** [comment]
These are all correct now - thank you!
