### ISSUE TITLE
"0 records" showing in text when there are records

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#577]
Above the map is displaying "0 records (5,601 in total)" which doesn't make sense.

https://species.nbnatlas.org/species/NHMSYS0000504085

**Comment by reupost** [comment]
When I visit that page I see "5,599 records (5,601 in total)". The count of presence records (the "0" in the issue above) is loaded from a webservice which might have been a bit slow. I'm not sure what we should do about this issue.

**Comment by MandyHenshall** [comment]
I've just refreshed it and it now says: 38,465 records (5,601 in total)  This doesn't make sense either does it?  Why are there two different figures? I could understand if it was something like "5601 absence records (38465 in total)", but having a lower total figure than the first figure, as it now shows for me, seems quite odd.

**Comment by reupost** [comment]
I don't know why you are seeing that. It looks fine from my side, but I could dig through the SOLR and species portal logs to see if I can find anything. Would you mind doing a hard refresh on the page, and sending through your browser details (type, version)? It's hard to debug unless I can replicate the issue.

**Comment by MandyHenshall** [comment]
It's now showing as it did for you!  I'm using Chrome 67 apparently. All details should be on this link: whatsmybrowser.org/b/VSTPKKX I only looked at this species as I want to add the map link to a story for Network News, so sorry it's not a quick one!  Thanks Reuben.

**Comment by JoJudge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/6KXhmkmn/1-test)

**Comment by sophiathirza** [comment]
I am seeing this a lot now, for example: https://species.nbnatlas.org/species/NHMSYS0020194826 says 529 records (45,701 in total), but there are only 286 absence records.

**Comment by JoJudge** [comment]
Searching through some species for a good screenshot to use, this seems to be a very common issue.

**Comment by reupost** [comment]
@JoJudge could you give some examples? I'm not seeing this at all.

**Comment by JoJudge** [comment]
I've just tried them again and they now all seem to be OK!

**Comment by reupost** [comment]
@JoJudge I did find some issues. It was the webservice call to the records server timing out occasionally and giving inconsistent results. I've added some checks and improved the efficiency a bit; hopefully it will work better now.

**Comment by sophiathirza** [comment]
I haven't found the problem again, so I will close for now. We can reopen if we find it again.
