### ISSUE TITLE
Multi-word entries in the lifeStage field appear in the facet search as separate entries

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#579]
Multi-word entries in the lifeStage field are appearing in the facet search as separate entries for each word.

https://records-ws.nbnatlas.org/occurrence/facets?facets=life_stage - there are almost the same number of entries in lifeStage for 'not' and 'recorded'. I looked for example records and I get the same number whether I search for 'recorded' (https://records-ws.nbnatlas.org/occurrences/search?fq=data_resource_uid:dr1842&fq=life_stage:%22recorded%22) or 'not recorded' (https://records-ws.nbnatlas.org/occurrences/search?fq=data_resource_uid:dr1842&fq=life_stage:%22not%20recorded%22)

lifeStage is not returned in the web service, so I can't see how it looks there. On the occurrence page the entry looks okay:https://records.nbnatlas.org/occurrences/9b490972-223a-4ed1-94d0-bc1a59a8a3e0

Should the entries be single words?

**Comment by reupost** [comment]
This should be fixable within the SOLR schema to prevent this field being parsed

**Comment by sophiathirza** [comment]
Done.
