### ISSUE TITLE
Add warning about point to polygon searches

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#581]
Add text to the following pages to advise users that a spatial search will only match a record supplied with a grid reference if the centre of the grid reference is within the boundary.

https://records.nbnatlas.org/search#tab_spatialSearch
https://regions.nbnatlas.org
https://records.nbnatlas.org/explore/your-area

**Comment by sophiathirza** [comment]
#548

**Comment by sophiathirza** [comment]
We can decide on the text once we know exactly how it works.

**Comment by reupost** [comment]
Done

**Comment by sophiathirza** [comment]
I couldn't see the text on the regions page (https://regions.nbnatlas.org)

**Comment by reupost** [comment]
Its visible below the map when viewing a specific region.

**Comment by sophiathirza** [comment]
ah.. thanks. Could it also go below the text:
'Click the region button to explore occurrence records, images and documents associated with the region. '
on the home page?

**Comment by sophiathirza** [comment]
thanks.
