### ISSUE TITLE
Add marine/freshwater/terrestrial status to occurrence record

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#583]
At the moment the marine/freshwater/terrestrial status for a taxa is only on the species search in the habitat term. Please could it be added to the occurrence records as well.

- The value should come from the species, i.e. it will not be supplied with the data
- It should be possible to search/filter for occurrence records by habitat.
- Habitat should be included on the occurrence record page
- Less important - habitat could be included in the occurrence record downloads

Could be done at the same time as #582.

**Comment by sophiathirza** [comment]
Habitat is a single value field on the species component. Ideally it should be changed to multi-value to make searching easier.

**Comment by c-van-dierkson** [comment]
Ok to close - will be monitored on Trello
