### ISSUE TITLE
Error uploading UK lakes spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#587]
Layer id: 106
Script name: UK_Lakes

Error:
Reading line 2399, statement 2394
Checking row count of shape geometry table
Creating layers table entry...
Creating fields table entry...
Create objects from layer
Connecting to database
Reading field sid, name and description...
java.lang.RuntimeException: No fields table entry for layer, or objects have already been created for all fields table entries for layer.
	at au.org.ala.layers.ingestion.contextual.ContextualObjectCreator.create(ContextualObjectCreator.java:68)
	at au.org.ala.layers.ingestion.contextual.ContextualObjectCreator.main(ContextualObjectCreator.java:24)

**Comment by sophiathirza** [comment]
It could be that ID 106 has previously been used for a layer that failed to load.

ID 106 was not in the list on layers admin page.

**Comment by sophiathirza** [comment]
I tried to rerun the script using ID 111, which I am sure has not been using before, but I get the error:

Reprojecting shapefile to WGS 84
ERROR 1: /data/ala/data/layers/ready/shape/UK_Lakes_10ha.shp is not a directory.

ESRI Shapefile driver failed to create /data/ala/data/layers/ready/shape/UK_Lakes_10ha.shp

Perhaps because UK_Lakes_10ha.shp already exists?

**Comment by reupost** [comment]
Yes, you need to delete the reprojected shapefile.

There is still an issue with this layer, geoserver throws an 'operation on mixed SRID geometries' error. I've reprojected it to WGS84 and removed a couple of invalid geometries, and (I think) filtered out any shapes with NULL geometry, but its unchanged.

**Comment by reupost** [comment]
Manually republished in geoserver.

**Comment by sophiathirza** [comment]
The UK Lakes layer is displaying habitat types rather than lakes.

**Comment by reupost** [comment]
I see that, yes. I think we need to ensure we don't reuse any IDs when uploading layers, and to not attempt to replace layers. The priority habitats layer was loaded as 106 previously, and it seems it leaves some vestiges in geoserver, e.g. for layer keywords, that aren't replaced. I'll need to investigate, but for now I'm going to delete the broken layers.

**Comment by sophiathirza** [comment]
yes, I don't remember which ids I tried when layers fail. Sorry, that was my fault. Can you re-upload the Lakes layer or send it to me and I will upload with a new ID, thanks.

**Comment by reupost** [comment]
Its now loaded ok with ID 109

**Comment by sophiathirza** [comment]
Brilliant - thanks.
