### ISSUE TITLE
Species search filter for has/doesn't have occurrence records

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#594]
Would be good to be able to filter the taxa by whether they have occurrence records or do not have occurrence records.

I tried this query: https://wales-species-inns.nbnatlas.org/search?q=*%3A*&fq=-occurrenceCount:[1%20TO%20100000] but it returns some species with occurrence records.

**Comment by c-van-dierkson** [comment]
From the query you used above, there's a link 'View Occurrence Records' on the right-hand side. Does that fix this or does this still need to be done? @sophiathirza

**Comment by sophiathirza** [comment]
@c-van-dierkson We needed to have the correct occurrence count on the BIE index in order to be able to filter by occurrence count. Reuben added it last week, so now this should be possible.

**Comment by c-van-dierkson** [comment]
RR confirms this is fixed.
