### ISSUE TITLE
September datasets for processing

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#597]
- [ ] dr1887 - not indexed correctly
- [ ] dr535 - not indexed correctly
- [ ] dr536 - not indexed correctly
- [x] dr1890
- [x] dr1891
- [x] dr1892
- [x] dr1893
- [x] dr1128
- [x] dr875
- [x] dr1143

delete first:
- [ ] dr1313
- [x] dr1842 - duplicates from last processing run
- [ ] dr1647 - duplicates from last processing run

**Comment by reupost** [comment]
dr1892 and dr1893 had rows missing the primary key; otherwise all loaded, processed and sampled without incident.
