### ISSUE TITLE
Habitat layer: Enhance display of hedgerow data  - difficult to see at low zoom

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#60]
[http://regions.als.scot/habitats/](url)

**Comment by djtfmartin** [comment]
The hedgerows are there, but are very thin polylines that can only been seen when zoomed in. Not sure what to do with this issue at the minute.

**Comment by CEJohnston** [comment]
Yes I see the problem.  Could you add some text in the legend or on the map
page that simply explains you need to zoom in to view some categories (eg
Hedgerows)?

Christine Johnston
NBN Scottish Liaison Officer
tel: 07342254589
email: c.johnston@nbn.org.uk

NBN website: www.nbn.org.uk
NBN Gateway: http://data.nbn.org.uk
Atlas of Living Scotland: www.als.scot

*NBN Trust *- Registered in England and Wales - Company no. 3963387 -
Registered charity no. 1082163
Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL

[image: facebook logo]
https://www.facebook.com/pages/National-Biodiversity-Network/117818225374?fref=ts
National Biodiversity Network   [image: Twitter logo]
https://twitter.com/NBNTrust @NBNTrust  [image: Twitter logo]
https://twitter.com/AoLScot  @AoLScot

[image: NBN-Logo-153x80]

*\* Nominations are now open for the UK Awards for Biological Recording and
Information Sharing! ***
http://nbn.org.uk/news/uk-awards-nominations-open/
