### ISSUE TITLE
Replace LERC boundary spatial layer on predefined areas page

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#600]
The LERC boundary file as been updated, sampled and indexed. 

Please would you replace the base spatial layer for https://regions.nbnatlas.org/#rt=Local+Environmental+Records+Centre+Boundaries to ID:110 and delete layer ID:84.

**Comment by CEJohnston** [comment]
The layer supplied for ID:110 is incorrect.  It has been disabled in the spatial portal and the data partner who supplied it (ALERC) has been advised of the need to provide an updated version.

**Comment by CEJohnston** [comment]
An updated version of the layer is now available for download from the data partner's website:
[http://www.alerc.org.uk/downloads.html](url)  This replaces ID:84 and ID:110. 

We have had a request for this updated layer to be available across the interface - please prioritise over other layers.

**Comment by sophiathirza** [comment]
Zip file name: LERC_June_2018.zip
Shape file name: LERC_June_2018.shp
Layer name: Local Environmental Records Centre Boundaries of the UK
ID field: LERC_Short
Name field: LERC_Long

**Comment by reupost** [comment]
Loaded as layer 126. Obsolete layers will be deleted at end of milestone. Please add metadata for this layer.

**Comment by CEJohnston** [comment]
This layer is to replace the existing layer across the Atlas, including in the 'Search by pre-defined area' . Ref also #553 and #618
