### ISSUE TITLE
Download - formatting options unavailable

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#606]
I am trying to download these records: https://records.nbnatlas.org/download?searchParams=%3Fq%3Ddata_resource_uid%253Adr731%26fq%3Dcl16%253A%2522Dorset%2522%26fq%3Dyear%253A%25222010%2522&targetUri=/occurrences/search&totalRecords=1993

The formatting options are not shown on the screen, i.e. Full DwC, simple spreadsheet and customised spreadsheet. The text box to change the name of the download file shows briefly and then disappears. 

I've tried on both Firefox and Chrome.

**Comment by reupost** [comment]
Should be fixed now

**Comment by sophiathirza** [comment]
brilliant - thanks.
