### ISSUE TITLE
By decade charts are unavailable

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#608]
The by decade chart on the species page and the records page says 'No data to display',

e.g. https://records.nbnatlas.org/occurrences/search?q=data_resource_uid:dr731#tab_chartsView
and https://species.nbnatlas.org/species/NHMSYS0000544773#records

The decade filter is okay.

**Comment by reupost** [comment]
The charts.json entry needs to be updated to use occurrence_decade_i, but this triggers an error on the current records-ws instance (but not the new one). When we update records-ws I'll fix this as well.

**Comment by c-van-dierkson** [comment]
Ok to close
