### ISSUE TITLE
Custom downloads are failing

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#609]
Custom downloads are not working.

I've tried with all the options (one at a time) and with no options selected. Each one fails.

Full darwin core and simple downloads are working.

**Comment by reupost** [comment]
CSV-format custom and full darwin core downloads are working now (TSV or shapefile format still fail). Please re-prioritise if appropriate.

**Comment by sophiathirza** [comment]
Brilliant - thanks.

**Comment by sophiathirza** [comment]
Custom downloads have started failing again. At least when I set miscellaneous fields.
