### ISSUE TITLE
Taxonomy: Split out Fungi from Plants 

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#61]

**Comment by djtfmartin** [comment]
Closing. Are taxonomy is provided by species inventory and there isnt any plans to diverge away from this.

**Comment by EllaVogel** [comment]
Hope you don't mind me re-opening. We've had an email saying that fungi and lichens can't be differentiated. Is this likely to be a similar issue?

'The Location link takes me to Fungi for that location but does not seem to
permit differentiation between lichens and other fungi.'

**Comment by djtfmartin** [comment]
this is related subgroups and the classification used by EYA.

**Comment by sophiathirza** [comment]
#506

**Comment by sophiathirza** [comment]
I've added species lists for the different lichen groups and at the moment that's all we can do. Lichen groups are being added to the UKSI, once that is complete then we can use the UKSI for the groupings.
