### ISSUE TITLE
Add field for organismStatus

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#612]
Please add organismStatus so that we can store (and filter) on alive/dead organisms. For now, just having the field in the database is sufficient - but when possible, could the filter we added to the list of available record filters?

**Comment by sallystewartmoore** [comment]
Is this going to be fulfilled? I have a particular problem with marine mollusc records. It is not clear if they are alive or dead from the record pages, but this is vital information. Perhaps it would be easier if all alive species are tagged as alive and all dead species are tagged as dead (as opposed to leaving alive blank).

**Comment by sophiathirza** [comment]
I did wonder about having default of Alive. Most of the records we receive do not indicate whether the organism was alive - only whether they were dead, and I wasn't sure about assuming that they were alive. Perhaps it's okay to.

Yes, this will be scheduled.

**Comment by sallystewartmoore** [comment]
I suppose the priority is to ensure that dead records are flagged. But I think it would also be useful to flag all other records as alive, which adds an extra element of confidence. I suppose the only way to do this is to include it as a field at the data submission stage. Dead records certainly need to be included as a field for data download.

**Comment by reupost** [comment]
It has been suggested that we apply to TDWG to have this field added to the DarwinCore. There is a precedent here http://semanticscience.org/resource/SIO_010057

**Comment by sophiathirza** [comment]
Yes, we discussed asking for it to be added, I found out how to do it - I just hadn't applied yet.
