### ISSUE TITLE
Some spatial layers need to be replaced

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#614]
The following layers need to be replaced as updated versions have been published (there have been site deletions, additions and/or boundary re-alignments):

Scottish layers: shapefiles to be downloaded from Scottish Natural Heritage at  https://gateway.snh.gov.uk/natural-spaces/ 

ID: 6  sssi_scotland
ID: 7  spa_scotland
ID: 9  sac_scotland
ID: 10  lnr_scotland
ID: 11  nnr_scotland
ID: 65 NVC_SCOTLAND
ID: 72  MPA_SCOTLAND

English layers:
ID: 57 Special_Areas_of_Conservation_England  (http://naturalengland-defra.opendata.arcgis.com/datasets/special-areas-of-conservation-england)

Field information for ingesting the layers and for the metadata table are to be collated - will do so once  timing of the upload is known.

**Comment by sophiathirza** [comment]
- [x] ID: 6 sssi_scotland
Zip file name: sssi_scot_edited.zip
Shape file name: sssi_scot_edited.shp
Layer name: Sites of Special Scientific Interest (Scotland)
ID field: PA_CODE
Name field: NAME

- [x] ID: 7 spa_scotland
Zip file name: spa_scot_edited.zip
Shape file name: spa_scot_edited.shp
Layer name: Special Protection Areas (Scotland)
ID field: PA_CODE
Name field: NAME

- [x] ID: 9 sac_scotland
Zip file name: sac_scot_edited.zip
Shape file name: sac_scot_edited.shp
Layer name: Special Areas of Conservation (Scotland)
ID field: PA_CODE
Name field: NAME

- [x] ID: 10 lnr_scotland
Zip file name: lnr_scot_edited.zip
Shape file name: lnr_scot_edited.shp
Layer name: Local Nature Reserves (Scotland)
ID field: PA_CODE
Name field: NAME

- [x] ID: 11 nnr_scotland
Zip file name: nnr_scot_edited.zip
Shape file name: nnr_scot_edited.shp
Layer name: National Nature Reserves (Scotland)
ID field: PA_CODE
Name field: NAME 

- [x] ID: 65 NVC_SCOTLAND
Zip file name: nvc_scot_edited.zip
Shape file name: nvc_scot_edited.shp
Layer name: National Vegetation Classification (Scotland)
ID field: POLYGON_ID
Name field: COMMUN_CAT

- [x] ID: 72 MPA_SCOTLAND
Zip file name: mpa_scot_edited.zip
Shape file name: mpa_scot_edited.shp
Layer name: Nature Conservation Marine Protected Areas (Scotland)
ID field: PA_CODE
Name field: NAME

- [x] ID: 57 Special_Areas_of_Conservation_England
Zip file name: sac_england_edited.zip
Shape file name: sac_england_edited.shp
Layer name: Special Areas of Conservation (England)
ID field: OBJECTID
Name field: SAC_NAME

**Comment by CEJohnston** [comment]
Zip files for two files sac_england_edited.zip and sssi_scot_edited.zip have been uploaded to Teams.  I have not been able to access SNH's Natural Spaces today so cannot progress any of the other files at the moment.  Have emailed them to establish what the problem is.

**Comment by sophiathirza** [comment]
@CEJohnston, if you still can't access the site, I have all the zip files downloaded and can upload them to Teams.

**Comment by CEJohnston** [comment]
@sophiathirza thanks but its OK - I did get access to the site and have all of them downloaded.  Have edited them all and will complete upload to Teams today hopefully.

**Comment by CEJohnston** [comment]
@sophiathirza  All the above files except the NVC file have been edited and uploaded to Teams. The NVC file just needs a bit of finishing off in QGIS - will do that next but may not get it finished til Thursday morning as it takes a while to save.

**Comment by sophiathirza** [comment]
All zip files (except NVC) are uploaded to the layers server

**Comment by CEJohnston** [comment]
NVC is ready to be uploaded to TEAMS - will start it off now.

**Comment by sophiathirza** [comment]
NVC zip file is now on the layers server. All layers in this issue are ready now.

**Comment by reupost** [comment]
Layer 6 to be replaced with layer 118
Layer 7 to be replaced with layer 119
Layer 9 to be replaced with layer 120
Layer 10 to be replaced with layer 121
Layer 11 to be replaced with layer 122
Layer 65 to be replaced with layer 123
Layer 72 to be replaced with layer 124
Layer 57 to be replaced with layer 125

**Comment by reupost** [comment]
All new layers need metadata; the obsolete layers will be bulk-deleted at the end of the milestone

**Comment by CEJohnston** [comment]
All looks fine except ID124 Nature Conservation Marine Protected Areas (Scotland) as one area is missing - we have 34 rather than 35 as supplied. It is Loch Carron (Emergency ncMPA). Below is image of Atlas legend and QGIS attribute table - any thoughts? Its the only one with brackets in its name (other areas have blank EUR_CODE but it was imported on PA_CODE):
![image](https://user-images.githubusercontent.com/18594564/51623255-3172a900-1f30-11e9-8b2e-b845eb6720f1.png)
