### ISSUE TITLE
Change layer name in spatial portal Add Layer dialogue box

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#615]
The layer name in this dialogue box does not update automatically if changed in the metadata table.  the following layers need a name change:

ID: 8  cntrypk_scotland:  update name to: Country Parks (Scotland)
ID: 13 ramsar_scotland: update name to: RAMSAR Wetlands of International Importance (Scotland)
ID: 2  uk_state_province: update name to: GB countries
ID: 23 awi_scotland: update name to: Ancient woodland inventory (Scotland)

**Comment by reupost** [comment]
e.g. 13 is showing up on the layer list on spatial.nbnatlas.org as "Wetlands of International Importance (Ramsar)" while the information for the layer is correctly picking up "RAMSAR Wetlands of International Importance (Scotland)".
https://layers.nbnatlas.org/ws/field/cl13 gives the old incorrect name (fieldname for each object), while https://layers.nbnatlas.org/ws/layer/13 has the correct name (displayname), as does https://layers.nbnatlas.org/ws/layers. Refreshing the cache (/data/webportal/cache/commondata) on the spatial portal is still picking up the old name.

**Comment by reupost** [comment]
Fix manually with edit in layersdb as per e.g. 
update fields set name = 'Ancient woodland inventory (Scotland)', "desc" = 'Ancient woodland inventory (Scotland)' where id = 'cl23';
Then refresh caches on spatial portals
