### ISSUE TITLE
Duplicate records created when dr1852 was updated

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#617]
dr1852 was updated via an Archive file. I can't see any problems with the file, the occurrence ids have not changed.

Most of the records in the dataset have been duplicated. BRC are going to provide an updated file and we can delete the current records and reupload but it would be useful to know why this happened.

**Comment by reupost** [comment]
I can't replicate this locally. Without knowing more history its going to be tricky to debug this - can I suggest we delete and reload this dataset, and then review?

**Comment by sophiathirza** [comment]
resolved.
