### ISSUE TITLE
Create a National Park spatial layer for UK

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#618]
For use in the NBN Atlas search by pre-defined area.  Layer to be created by combining the individual country national park layers (note there are no national parks in Northern Ireland): 

ID 39: CombinedScottishNPs
ID 70: NRW_NATIONAL_PARKPolygon
ID 69: National_Parks

Once this layer is made please delete the current UK layer ID 5: national_park and layer ID 3: magnatpk (the source of both these layer is unknown).

Note that ID39 is to be used in the Scottish Atlas search by pre-defined area and ID70 in the Welsh Atlas search by pre-defined area.  These should also be retained for the spatial portal layer list.

**Comment by sophiathirza** [comment]
@reupost are you able to combine the three spatial layers as detailed above?

**Comment by reupost** [comment]
Done as layer 117. Bulk-deletion of superseded layers to follow at end of milestone. This layer needs metadata.

**Comment by CEJohnston** [comment]
ID 5: national_park and layer ID 3: magnatpk can be deleted.

Layer ID 117: to be used in the NBN Atlas 'Search by pre-defined area'.  It is not actually needed in the spatial portal as is a duplicate of ID 39, 69 and 70 - do you agree?

Note that ID39 is to be used in the Scottish Atlas 'Search by pre-defined area' and ID70 in the Welsh Atlas search by pre-defined area. These two layers should also be retained for the spatial portal.

Shall we create a new GitHub issue for the changes required to the 'Search by pre-defined area' function in each Atlas?
