### ISSUE TITLE
When viewing Records in a list, change State: to 'Country'.  

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#62]
When viewing Records in a list ("Species:  Fratercula arctica |  Puffin Date: 2009-04-06 State: Scotland")  change State: to 'Country'.

**Comment by djtfmartin** [comment]
"State" has been removed. Internally the country is "United Kingdom" due to the ISO country list that we currently use (which doesnt include Scotland separately).
