### ISSUE TITLE
Data processing no longer matching on vernacular name

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#620]
In the latest processing run four datasets only provide the common name for some records (in the vernacularName field) and the name matching routine as failed to find a match for them. I have checked some of the common names and they are in the Atlas.

dr1569
dr719
dr736
dr671

**Comment by reupost** [comment]
Could you let me know which of these only have common names? They all seem to have scientific names now, so its a bit tricky to test the issue (they process fine).

**Comment by sophiathirza** [comment]
dr671 and dr736 have a mix of common names and scientific names. 

https://records.nbnatlas.org/occurrences/search?q=data_resource_uid%3Adr671&fq=assertions%3A%22nameNotRecognised%22
https://records.nbnatlas.org/occurrences/search?q=data_resource_uid%3Adr736&fq=assertions%3A%22nameNotRecognised%22

Sorry, I replaced the common names in the first two in the reupload - as they were supplied with all common names.

**Comment by reupost** [comment]
Propose leaving scientificName blank (and in particular, not filling it with vernacular names) if there are authoritative entries in the vernacularName field. Records like this are correctly matched to taxa.

**Comment by sophiathirza** [comment]
thanks for investigating. I will updated our documentation.
