### ISSUE TITLE
Occurrence ID on records page hyperlink

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#621]
We have two datasets where the occurrence id is a hyperlink to the records on the data provider's own website. 

Could the records page detect when the occurrence id contains a hyper link and make the id a link?

e.g.: https://records.nbnatlas.org/occurrences/ff5c102f-57e5-4fcd-a49e-1e6acdd41055
and
https://records.nbnatlas.org/occurrences/d3a7b9c9-e9e7-44c2-8dc4-d7b38ac3457d

**Comment by reupost** [comment]
Done

**Comment by sophiathirza** [comment]
thanks.
