### ISSUE TITLE
December datasets for processing

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#624]
- [x] dr1939 - one unmatched name, although it looks correct
- [x] dr506
- [x] dr1725 - missing 2k records
- [x] dr1180
- [x] dr953
- [x] dr227
- [x] dr1941 - 506 names not recognised
- [x] dr1942
- [x] dr1944
- [ ] dr1225 - a few too many records
- [x] dr1943
- [x] dr1945
- [x] dr1953 - 51 unmatched names
- [x] dr1954

Delete first:
- [ ] dr1842 - DwCA, could be used for testing duplicates #617 
- [x] dr1284
- [x] dr681 - we had problem loading this one previously, so the records will need to be deleted first. I have cleaned it and exported it as UTF-8 but R threw a couple of warnings on saving the file. I can't see any problem with it.
- [x] dr864
- [ ] dr859 - this is the big 2.7m dataset that we struggled with last time.
- [x] dr671
- [x] dr855

**Comment by reupost** [comment]
dr859 is again only loading about 2.1m records. 
ip-172-31-19-101 2019-01-19 09:12:01,609 INFO : [DataLoader] - 2163000, >> last key : dr859|8674630, records per sec: 543.4783

There are a two points where it gives errors :
Skipping line: 1360589 incorrect number of columns (20)...headers (39)
Skipping line: 2163861 incorrect number of columns (27)...headers (39)

**Comment by sophiathirza** [comment]
Couldn't re-import it into R until I deleted the # symbols. I will re-upload the new version and we can try again in two weeks, thanks.
