### ISSUE TITLE
Source and upload RAMSAR sites layer for Wales

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#625]
The following layer is required to complete RAMSAR information for the UK:

Source: http://lle.gov.wales/catalogue/item/ProtectedSitesRamsarWetlandsOfInternationalImportance/?lang=en 
Layer name:  RAMSAR (Wetlands of International Importance) (Wales)
Classification: Wales; Protected Areas
The rest of the metadata can be completed when uploaded.  

The layers for Scotland, England and Northern Ireland are already uploaded so once Wales is uploaded, delete the layer ID 4: ramsar (this layer is currently disabled; its provenance is unknown and is superseded by the country layers)

**Comment by sophiathirza** [comment]
Zip file name: Ramsar.zip
Shape file name: NRW_RAMSARPolygon.shp
Layer name: RAMSAR (Wetlands of International Importance) (Wales)
ID field: OBJECTID
Name field: RAM_name

**Comment by reupost** [comment]
There is a problem with this shapefile:
java.lang.RuntimeException: shp2pgsql failed: Shapefile type: Polygon
Postgis type: MULTIPOLYGON[2]
Unable to convert data value to UTF-8 (iconv reports "Invalid or incomplete multibyte or wide character"). Current encoding is "UTF-8". Try "LATIN1" (Western European), or one of the values described at http://www.postgresql.org/docs/current/static/multibyte.html.

**Comment by reupost** [comment]
Ok, fixed. This is loaded as layer 116. I'll bulk-delete all superceded layers at the end of the milestone. This layer needs metadata.
