### ISSUE TITLE
Show only the titles of the designations on species pages 

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#626]
Show only the titles of the species designations on the lower right of the species pages, which expand to display the details when clicked on.

This was suggested for the Atlas NI but I think it's appropriate for all the Atlases

**Comment by reupost** [comment]
Sorry, what tab is this on? Could you take a screenshot, I'm battling to find where this is.

**Comment by sophiathirza** [comment]
On the species pages, eg: https://northernireland-species.nbnatlas.org/species/NHMSYS0000080191

![image](https://user-images.githubusercontent.com/1651015/51604622-a1236c80-1f0d-11e9-9b83-37bd6041b116.png)

**Comment by sophiathirza** [comment]
I think it's appropriate for all the hubs - not just NI.

**Comment by reupost** [comment]
Done e.g. https://northernireland-species.nbnatlas.org/species/NHMSYS0001706186#

**Comment by sophiathirza** [comment]
This looks much better - thanks.
