### ISSUE TITLE
Order of designations on species pages

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#627]
Could the NI species designations be at the top of the list and if possible with a purple coloured bar?

**Comment by reupost** [comment]
Do you mean the list memberships shown under the 'Datasets' section under the map on the 'Overview' tab?

**Comment by sophiathirza** [comment]
Yes, that's it. We will need to go through the lists and make sure that they have a region defined.

**Comment by reupost** [comment]
Done. The lists need to have region set correctly to 'Northern Ireland' (not 'NI' ).

**Comment by sophiathirza** [comment]
Great, thanks.
