### ISSUE TITLE
Replacement for layer ID73 - RSPB reserve boundaries

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#628]
Layer ID73 (currently disabled) to be replaced.  
Download new shapefile from: [https://opendata-rspb.opendata.arcgis.com/datasets/rspb-reserves]
Layer name:  RSPB reserve boundaries (UK)
Categories: UK; Boundaries

**Comment by sophiathirza** [comment]
Zip file name: RSPB_Reserves.zip
Shape file name: RSPB_Reserves.shp
Layer name: RSPB nature reserve boundaries (UK)
ID field: OBJECTID
Name field: Name

**Comment by reupost** [comment]
Created as layer 115. I'll bulk-delete replaced layers at the end of the milestone. We need metadata for this layer.
