### ISSUE TITLE
Add new Greenspace spatial layer for GB

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#631]
This OS Open Greenspace layer is available for download from: [https://www.ordnancesurvey.co.uk/opendatadownload/products.html](url)
Download the single file for Great Britain (29 Mb)

Layer name: Greenspace (GB)
Categories: GB; Boundaries

**Comment by sophiathirza** [comment]
I don't think that we will be able to use this layer. 

The layer has a field for function (playing field, religious grounds (I now know where the BBG boundaries have come from), etc., but the field is not unique. There is a field for distname but it is not unique and often empty.

**Comment by CEJohnston** [comment]
The layer would be classified by function or type of greenspace - so not many categories - like was done for NVC.  This is the key from the Greenspace Map viewer - so similar to this:
![image](https://user-images.githubusercontent.com/18594564/51973826-7342a880-2476-11e9-82c2-7f5f610e64d9.png)
I think the file needs its multipart polygons made and a Unigue ID assigned to each (like I did for NVC).

**Comment by sophiathirza** [comment]
okay, thanks. Would you be able to do that? Doesn't have to be for this month.

**Comment by CEJohnston** [comment]
Yes - will have a look at it - have just sourced the file.

**Comment by CEJohnston** [comment]
An edited version is now available in Teams folder:

Zip file name: greenspace_GB_edited.zip
Shape file name: greenspace_GB_edited.shp
Layer name: Greenspace (GB)
ID field: function_i
Name field: function

Date of file (for metadata): October 2018
This file could be uploaded this month if there is space.  The legend will have these 10 categories (this is from the view of the layer in QGIS): 
![image](https://user-images.githubusercontent.com/18594564/51982595-574b0100-248e-11e9-945a-67c1017f0cd3.png)

**Comment by sophiathirza** [comment]
Zip file name: greenspace_GB_edited.zip
Shape file name: greenspace_GB_edited.shp
Layer name: Greenspace (GB)
ID field: function_i
Name field: function

**Comment by reupost** [comment]
Greenspace (GB) = layer 140

Please add metadata as needed.
