### ISSUE TITLE
Upload World Heritage Site boundary layers to spatial portal

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#632]
Upload World Heritage Sites layers for each country:
1. Scotland: download from Historic Environment Scotland at: [http://portal.historicenvironment.scot/downloads/worldheritagesites](url)

2. England: download from Historic England: [https://data.gov.uk/dataset/3ac5c299-6805-476b-af9b-90aadec5e7b4/world-heritage-sites-gis-data](url)

3. Wales: download from Historic Environment Service (CADW): [http://lle.gov.wales/catalogue/item/WorldHeritageSites/?lang=en](url)

Each of the layers is named in the Atlas as 'World Heritage Sites' followed by the country_name in brackets.
Each layer is categorised by 'country_name; Protected Areas'

The Northern Ireland layer is already uploaded but the site name (there is only one) is not appearing in the key for the layer - could that be fixed?

Once the layers are uploaded please remove layer ID12: whs_scotland.  I don't know its origin and it should be replaced by the country layers.

**Comment by sophiathirza** [comment]
- [ ] World Heritage Sites (Scotland)
Zip file name: WHS.zip
Shape file name: World_Heritage_Sites.shp
Layer name: World Heritage Sites (Scotland)
ID field: DES_REF
Name field: DES_TITLE

- [ ] The Northern Ireland layer is already uploaded but the site name (there is only one) is not appearing in the key for the layer - could that be fixed?

**Comment by CEJohnston** [comment]
Edited and renamed files for England and Wales are now uploaded to Teams.

 - [x] World Heritage Sites (England)
Zip file name: whs_england.zip
Shape file name: whs_england.shp
Layer name: World Heritage Sites (England)
ID field: key
Name field: full_name

 - [x] World Heritage Sites (Wales)
Zip file name: whs_wales.zip
Shape file name: whs_wales.shp
Layer name: World Heritage Sites (Wales)
ID field: RecordNumb
Name field: Name

Each layer is categorised as ''country_name'; Protected Areas'

**Comment by reupost** [comment]
WHS England = layer 147, WHS Wales = layer 148. Please add metadata as needed.

Note WHS Wales was not encoded in UTF8, so I needed to resave this in the appropriate format.

**Comment by sophiathirza** [comment]
England and Wales are great, but the layer in the previous comment was missed. 

- [ ] World Heritage Sites (Scotland)
Zip file name: WHS.zip
Shape file name: World_Heritage_Sites.shp
Layer name: World Heritage Sites (Scotland)
ID field: DES_REF
Name field: DES_TITLE

- [ ] The Northern Ireland layer is already uploaded but the site name (there is only one) is not appearing in the key for the layer - could that be fixed?

**Comment by reupost** [comment]
I can't see the problem with the NI WHS layer. Could you send a screenshot please?

**Comment by sophiathirza** [comment]
I imagine the layer didn't have a name attribute as there is only one polygon. The boundary should have the name: 'Giant's Causeway and Causeway Coast'. 

![image](https://user-images.githubusercontent.com/1651015/53726096-90033f00-3e6d-11e9-9ab8-dbba40f15414.png)

**Comment by sophiathirza** [comment]
Can you change this manually - or shall we reupload the layer?

**Comment by reupost** [comment]
Re-upload the layer, please.

**Comment by reupost** [comment]
WHS Scotland created as layer 151, please add metadata as needed

**Comment by CEJohnston** [comment]
The missing name for the legend to layer ID: 96  NI_WHS is contained in attribute field: AREANAME.
All the metadata is complete.

**Comment by sophiathirza** [comment]
@CEJohnston is this issue complete?

**Comment by CEJohnston** [comment]
Not yet - the name in the legend for layer ID: 96 NI_WHS is still incorrect - it should be 'Giant's Causeway and Causeway Coast' - it is contained in attribute field: AREANAME.

**Comment by sophiathirza** [comment]
@CEJohnston have you sent me the layer for upload?

**Comment by CEJohnston** [comment]
No changes to the file were required so I assumed the original would just be re-uploaded.  I have now uploaded to Teams a zip file copy of the required shapefile (I have changed its name so it is now unique):

- [ ] World Heritage Site (Northern Ireland)
Zip file name: World_Heritage_Site_NI.zip
Shape file name: World_Heritage_Site_NI.shp
Layer name: World Heritage Site (Northern Ireland))
ID field: OBJECTID
Name field: AREANAME

This replaces layer ID: 96 NI_WHS.  The metadata has not changed.

**Comment by reupost** [comment]
World Heritage Site (Northern Ireland) loaded as layer 161. I've copied the metadata across from layer 96.

**Comment by CEJohnston** [comment]
This is strange - the site name is still not rendering correctly in the interface legend.  I am still seeing the name 'World Heritage Site (Northern Ireland)'.  
![image](https://user-images.githubusercontent.com/18594564/57287564-b5037080-70af-11e9-9aff-6e25681939ba.png)
There is no field with that name in the attribute table - this is what the table looks like in QGIS:
![image](https://user-images.githubusercontent.com/18594564/57287265-12e38880-70af-11e9-972c-a2dabccaef28.png)
Is it worth making me creating a pared down shapefile with just the ID and AREANAME fields as attributes for re-upload? The name of the site is given in the metadata.

**Comment by CEJohnston** [comment]
There is now a Trello card for this issue: [https://trello.com/c/OREjsbZp/342-fix-the-name-of-the-northern-ireland-world-heritage-site-in-layer-id-161](url).  Please keep this card open until issue is fixed.

**Comment by sophiathirza** [comment]
Close because on Trello.
