### ISSUE TITLE
Source and upload Local Nature Reserves layer for Wales

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#636]
Please upload the Local Nature Reserves layer from NRW's website:

http://lle.gov.wales/catalogue/item/LocalNatureReserves/?lang=en

Layer name in spatial portal: Local Nature Reserves (Wales)
Categories: Wales; Protected Areas

This layer is required so that LNRs are mapped for all the countries of the UK (England, Scotland and NI are already uploaded)

**Comment by sophiathirza** [comment]
Zip file name: LocalNatureReservesLNR.zip
Shape file name: NRW_LNRPolygon.shp
Layer name: Local Nature Reserves (Wales)
ID field: OBJECTID
Name field: LNR_Name

**Comment by reupost** [comment]
Re-encoded as NRW_LNRPolygonUTF8.shp 

Local Nature Reserves (Wales) = layer 139.

Please add metadata as needed.
