### ISSUE TITLE
Replace Local Nature Reserves (England) spatial layer (ID49)

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#637]
Replace the following layers:

1. ID49: Local_Nature_Reserves_England  (layer name is Local Nature Reserves (England)) - was updated by Natural England 30/11/2018.  Download from: [https://naturalengland-defra.opendata.arcgis.com/datasets/local-nature-reserves-england](url)

**Comment by sophiathirza** [comment]
@CEJohnston can you work your magic on this one, please? The ids are unique but the names aren't. I don't think that there are the same name for different LNRs.

**Comment by CEJohnston** [comment]
An edited version is now available in Teams folder:

Zip file name: lnr_england_edited.zip
Shape file name: lnr_england_edited.shp
Layer name: Local Nature Reserves (England)
ID field: OBJECTID
Name field: LNR_NAME

Date of file (for metadata) 19/12/2018

**Comment by reupost** [comment]
Local Nature Reserves (England) = layer 138

Please add metadata as needed. I will disable layer 49 when this new layer is confirmed ok

**Comment by sophiathirza** [comment]
All okay, please disable layer 49

**Comment by sophiathirza** [comment]
@reupost how do we disable a layer? is in on the edit page or is it something that you have to do?

**Comment by reupost** [comment]
You can uncheck the 'Enabled' box on the edit page https://layers.nbnatlas.org/ws/admin/layers/edit/49 but I think I must have already done it because it is already not enabled. Are you seeing it coming up somewhere it shouldn't?

**Comment by sophiathirza** [comment]
No, I'm just cleaning up github. Thanks.
