### ISSUE TITLE
Source and upload Biosphere Reserve spatial layers

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#638]
The following layers are to be uploaded (the Scottish reserve boundaries were available on the Gateway):

1. Biospheric Reserves (Wales) - download from: [http://lle.gov.wales/catalogue/item/ProtectedSitesBiosphericReserves/?lang=en](url)

2. Biosphere Reserves (Scotland) - download from: [https://gateway.snh.gov.uk/natural-spaces/dataset.jsp?dsid=BIOSPH](url)

3. Biosphere Reserves (England) - download from: [https://naturalengland-defra.opendata.arcgis.com/datasets/biosphere-reserves-england](url)

Layer names to be used in the Atlas are as listed above.  
Categories for each layer: [country name]; Designated Areas 

There are no Biosphere Reserves in Northern Ireland.

Note: the whole of the Isle of Man is a Biosphere Reserve so if needed the user can create the outline from the World Map layer.  I think that this should suffice (unless we are advised otherwise).

**Comment by sophiathirza** [comment]
1. Wales: there is only one reserve but three categories (core, buffer..). We can't upload as is, as the name isn't unique. Could we combine the name and the category?

2. There are two reserves: each with three polygons - can you combine them into multipart polygons?

3. This one is okay as is for upload.

**Comment by sophiathirza** [comment]
- [x] 1. Biospheric Reserves (Wales) 
Zip file name: biosphere_wales_edited.zip
Shape file name: biosphere_wales_edited.shp
Layer name: Biospheric Reserves (Wales) [Do you mean 'Biosphere' as per the other layers?]
ID field: ogc_field [does not exist: do you mean ogc_fid?]
Name field: bios_zone
Date (for metadata); 09/02/2010

- [x] 2. Biosphere Reserves (Scotland)
Zip file name: biosphere_scotland_edited.zip
Shape file name: biosphere_scotland_edited.shp
Layer name: Biosphere Reserves (Scotland) 
ID field: PA_CODE
Name field: NAME
Date (for metadata); 15/06/2016

- [x] 3. Biosphere Reserves (England) 
Zip file name: Biosphere_Reserves_England.zip
Shape file name: Biosphere_Reserves_England.shp
Layer name: Biosphere Reserves (England)
ID field: OBJECTID
Name field: NAME

**Comment by CEJohnston** [comment]
Files for 1 and 2 now available in Teams

**Comment by reupost** [comment]
Biospheric Reserves (Wales) = layer 135
Biosphere Reserves (Scotland) = layer 136
Biosphere Reserves (England) = layer 137

Please add metadata as necessary

**Comment by CEJohnston** [comment]
@reupost at zoomed in scales the Wester Ross biosphere reserve polygon (in layer 136) does not fill correctly.  Is it the same for your view?

![image](https://user-images.githubusercontent.com/18594564/52216691-be055b80-288e-11e9-8f30-48b2a75aba6a.png)

All metadata for the three layers has been added.

**Comment by CEJohnston** [comment]
@reupost I have created a replacement file for Biosphere Reserves (Scotland) (layer 136) and uploaded a zip file to Teams:
  Zip file name: biosphere_scot_edited2.zip
  Shape file name: biosphere_scot_edited2.shp
  Layer name: Biosphere Reserves (Scotland)
  ID field: PA_CODE
  Name field: NAME
  Date (for metadata); 15/06/2016
For info: the polygons needed to be processed in QGIS by the 'Dissolve' toolbox rather than 'Collect geometries'.

**Comment by sophiathirza** [comment]
@CEJohnston does the Biosphere Reserves (Scotland) layer need to be added to this months layers for processing?

**Comment by CEJohnston** [comment]
Yes please - would be good to get it fixed.

**Comment by sophiathirza** [comment]
Zip file name: biosphere_scot_edited2.zip
Shape file name: biosphere_scot_edited2.shp
Layer name: Biosphere Reserves (Scotland)
ID field: PA_CODE
Name field: NAME

**Comment by reupost** [comment]
Loaded as layer 146. Please add metadata as needed.
