### ISSUE TITLE
Upload Local Wildlife Site boundaries from Merseyside Biobank

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#639]
Please upload the two layers supplied by Merseyside BioBank - both are on the external drive held by Sophie:
1. Liverpool Local Wildlife Sites (proposed)
2. North Merseyside Local Wildlife Sites

Suggested layer names for the Atlas:
1. Local Wildlife Sites (proposed) (Liverpool)
2. Local Wildlife Sites (North Merseyside)

Categories for both: England; Designated Areas

Merseyside BioBank has confirmed they are eligible to share under 'Presumption to Publish' (ie with an OGL licence) - guidance is at [https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/public-sector/guidance/derived-data.html#moduleAccordion117220132917-5](url)  
Please prioritise under the February milestone as both layers were available on the Gateway.

**Comment by sophiathirza** [comment]
@CEJohnston These are in a folder called 'Not to be used', is that because of the question over the licences?

**Comment by CEJohnston** [comment]
Yes - they were placed there initially but then Ben confirmed by email that he had received a presumption to publish from the OS.  Is it worth checking with Ben that this file is still current?

**Comment by sophiathirza** [comment]
If you would like to.. let me know.

**Comment by CEJohnston** [comment]
Yes I think we should - just in case.  I'll drop him a line.

**Comment by sophiathirza** [comment]
Waiting for the latest version, which is only a single layer.

**Comment by CEJohnston** [comment]
This issue can be closed.  We are still awaiting the latest version - will be managed and re-prioritised via the master spatial layer list once we receive the file.

**Comment by c-van-dierkson** [comment]
CJ is monitoring via her master spreadsheet.
