### ISSUE TITLE
Add NI 10km OS grid spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#641]
Available from here: http://osni-spatial-ni.opendata.arcgis.com/datasets/de0116be5fe5499f921c112568218a39_1

**Comment by sophiathirza** [comment]
Zip file name: OSNI_Open_Data_10k_Grid.zip
Shape file name: OSNI_Open_Data_10k_Grid.shp
Layer name: Ordnance NI Survey Grids - 10km
ID field: FID
Name field: NAME

**Comment by reupost** [comment]
This has been loaded as layer 114, but we need metadata captured on layers.nbnatlas.org. Thereafter I'll make it visible on the spatial portals.

**Comment by CEJohnston** [comment]
I think it might be more appropriate to name this layer as either 'Ordnance Survey of Northern Ireland Grid - 10km  Grid' or 'OSNI Grid - 10km' - what do you think @sophiathirza ? The 'NI' ought to come after 'Ordnance Survey' text.

**Comment by sophiathirza** [comment]
Yes, sorry, I wrote it too quickly. OSNI Grid - 10km sounds good.

**Comment by CEJohnston** [comment]
@reupost please also change the name of this layer to: OSNI Grid - 10km

**Comment by CEJohnston** [comment]
I get an internal error message when I load this layer though it fixes itself if I press continue then zoom to layer:
![image](https://user-images.githubusercontent.com/18594564/51618972-2f581c80-1f27-11e9-920e-9051b1815d94.png)
The first line of the legend is looking odd containing a coding message.

**Comment by reupost** [comment]
Should be fixed now. There was a tiny triangular shape with a null name (FID=1056) which I have removed and uploaded a new layer.

**Comment by CEJohnston** [comment]
Working fine now.  Have closed this issue.
