### ISSUE TITLE
Add SWT reserves spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#642]
(issue replaces #603) 

Zip file name: SWT_reserves.zip
Shape file name: scottishwildlifetrust_reserves_20180924.shp
Layer name: Scottish Wildlife Trust reserve boundaries
ID field: SWT_Code
Name field: SITE_NAME

Then delete layers 27 and 112

**Comment by reupost** [comment]
Loaded as layer 113. I'll bulk-delete all replaced layers at the end of the milestone.
