### ISSUE TITLE
Change Customise filters button colour to purple on Atlas NI

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#644]
To better signpost the 'Customise filter' button on the records page of the Atlas NI, please change the colour to purple.

**Comment by reupost** [comment]
Should this apply across all the Atlases (changing the button colour to that of the theme banner)? It seems odd to just do it for one Atlas.

**Comment by sophiathirza** [comment]
@JoJudge and @CEJohnston NMNI have asked that the Customise filter button be coloured purple to signpost it better - should we apply this to all the Atlases - i.e. change the button colour to the theme banner?

**Comment by JoJudge** [comment]
I agree having it as a more prominent colour would be useful. Not sure we should have them in different colours on the different country portals though. Can we pick one colour and go with that?

**Comment by CEJohnston** [comment]
I also agree to it being more prominent.  For balance would be good for colour to match the Download button - it might be nice to match the colour of both to theme banner but if not I'd suggest the blue of the Download button.

**Comment by reupost** [comment]
Please review, its live on the NI records atlas at this point. I've gone with the same colour as the downloads button, though its easy to change.

**Comment by JoJudge** [comment]
Looks good! I think using the same colour as the downloads button is the way to go.

**Comment by sophiathirza** [comment]
The button is more prominent. For me the text on the button looks a bit blurred. Is it okay for everyone else?

**Comment by CEJohnston** [comment]
The button looks good but I also think the text is a bit blurred - it makes the 'Customise filters' type look bolder than 'Download'.  Also are the buttons the same depth - the Customise filters button appears looks to be not as deep?

**Comment by reupost** [comment]
Please review

**Comment by sophiathirza** [comment]
Much better - thanks.

**Comment by CEJohnston** [comment]
Looks perfect - thanks v much!
