### ISSUE TITLE
Square brackets in species groups names in explore your area pages

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#645]
Some species group names are displaying in square brackets: https://records.nbnatlas.org/explore/your-area#53.426037|-2.3535518999999567|12|Reptiles

**Comment by c-van-dierkson** [comment]
@sophiathirza This looks fixed. Can we close?

**Comment by sophiathirza** [comment]
@c-van-dierkson not sure, I've seen it fairly recently. I don't know whether @reupost resolved it or not.

**Comment by c-van-dierkson** [comment]
I've gone through various postcodes and can't find an example. @reupost did you do a fix for this?

**Comment by c-van-dierkson** [comment]
RR confirms this is fixed.
