### ISSUE TITLE
Add NI header to records component

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#646]
The NI records component still has the Scottish header: https://northernireland-records.nbnatlas.org

**Comment by Lorsom** [comment]
screen ![locations search by polygon](https://user-images.githubusercontent.com/36696917/51532267-94344980-1e37-11e9-8b01-394e25f1379b.PNG)
https://northernireland-records.nbnatlas.org/search#tab_spatialSearch

Locations tab - Search by polygon & Explore by address, postcode or location defaults to NBN Scotland.

**Comment by reupost** [comment]
Fixed

**Comment by sophiathirza** [comment]
Terrific, thanks.
