### ISSUE TITLE
Incorrect dataset count on species page on country hubs

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#647]
It looks like there are 5 Orca whale records in NI: https://northernireland-species.nbnatlas.org/species/NBNSYS0000005173#overview

However, under the map it says 19 datasets have submitted records to Atlas NI for this species. This is the same as the main Atlas - so I think it's not excluding non-NI records.

**Comment by reupost** [comment]
Is this an NI-specific issue?

**Comment by sophiathirza** [comment]
good point. No, it looks like it's a problem with Scotland as well. It is likely to be a problem with all of the hubs.

**Comment by reupost** [comment]
Fixed on NI portal, fix will be rolled-out to all once we've finished up all the general adjustments.

**Comment by sophiathirza** [comment]
brilliant - thanks.
