### ISSUE TITLE
Changes to Explore by pre-defined area

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#648]
Change the layers displayed in regions component for each version of the Atlas:

1. To display on NBN Atlas at https://regions.nbnatlas.org/ - in this order:
LOCAL AUTHORITIES (GB) - ID131
COUNTIES (NORTHERN IRELAND) - ID127
LOCAL ENVIRONMENTAL RECORDS CENTRES - ID126
WATSONIAN VICE COUNTIES - ID14
VICE COUNTIES (IRELAND) - ID133
NATIONAL PARKS - ID117

2. To display on NBN Atlas Scotland at https://scotland-regions.nbnatlas.org/ - in this order:
LOCAL AUTHORITIES - ID128
ENVIRONMENTALLY SENSITIVE AREAS - ID35
NATIONAL NATURE RESERVES - ID122
NATIONAL PARKS - ID39
NATIONAL SCENIC AREAS - ID36
NATURE CONSERVATION MARINE PROTECTED AREAS - ID124
NITRATE VULNERABLE ZONES - ID37
SITES OF SPECIAL SCIENTIFIC INTEREST - ID118
SPECIAL AREAS OF CONSERVATION - ID120
SPECIAL PROTECTION AREAS - ID119
WETLANDS OF INTERNATIONAL IMPORTANCE (RAMSAR) - ID13

The ID numbers are for reference only - they all refer to existing enabled layers.
Please also check that the layers in the regions component for Wales are the most up to date versions.  the Northern Ireland and Isle of Man components should be OK as none of these layers has been updated in January.

**Comment by reupost** [comment]
Done, please review. I notice sometimes the tiles of the more complex layers don't get loaded until you click on an individual entry. If that is an issue, could it be logged separately.

The Wales regions component doesn't refer to any of the new layers.

**Comment by CEJohnston** [comment]
This is looking good - thank you.  I think the the issue of complex layers not loading could be explained in the header text.  I'll put together some revised text and raise a new issue.

**Comment by sophiathirza** [comment]
great, I'll close this then.
