### ISSUE TITLE
Missing polygon in Nature Conservation Marine Protected Areas (Scotland)  spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#649]
ID124 Nature Conservation Marine Protected Areas (Scotland) as one area is missing - we have 34 rather than 35 as supplied. It is Loch Carron (Emergency ncMPA). 

Its the only one with brackets in its name (other areas have blank EUR_CODE but it was imported on PA_CODE):
image

**Comment by reupost** [comment]
Could you confirm? I seem to be able to see this feature without any problem.

![screen shot 2019-01-25 at 07 28 38](https://user-images.githubusercontent.com/4357196/51731459-ec0ac480-2072-11e9-8add-ba878409f159.png)

**Comment by CEJohnston** [comment]
OK - its definitely there now - and there are the correct number of polygons (35) - I shall close this issue.
