### ISSUE TITLE
February 2019 datasets for processing

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#651]
- [ ] dr1959 - problems with a few dates and possibly field names
- [ ] dr1960 - problems with a few dates and possibly field names
- [x] dr671 - this doesn't need reloading, but it had a default value set on the identificationVerificationStatus field that should have been removed before it was processed. can the dataset be reprocessed? it's a DwCA
- [x] dr855 - same as above

delete first:
- [x] dr1758
- [x] dr866
- [x] dr859
- [x] dr819
- [ ] dr1236 - many unmatched names
- [ ] dr1383 - unmatched names
- [x] dr1842
- [ ] dr1206 - unmatched names
- [ ] dr1309 - problems with a few dates and possibly field names

**Comment by reupost** [comment]
Record deletion is now in progress on Cassandra

**Comment by reupost** [comment]
Dataset loading now in progress

**Comment by reupost** [comment]
New index is live

**Comment by sophiathirza** [comment]
For reloading and processing:

dr1960
dr1959
dr1309
dr772
dr1236
