### ISSUE TITLE
Replace NTS property boundary

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#653]
Replace the NTS property boundary layer with latest version

**Comment by sophiathirza** [comment]
Have asked for an updated file as there is a duplicated name.

**Comment by sophiathirza** [comment]
Zip file name: nts_properties_opendataderived.zip
Shape file name: nts_properties_opendataderived.shp
Layer name: National Trust Scotland Properties
ID field: ID
Name field: PROPERTY

Once this is sampled, please delete layer ID 105

**Comment by reupost** [comment]
Loaded as layer 145. Please add metadata as needed.

**Comment by sophiathirza** [comment]
All good. Please delete/disable layer ID 105

**Comment by reupost** [comment]
Done

**Comment by sophiathirza** [comment]
thanks
