### ISSUE TITLE
New Isle of Man Protected Areas (Marine)

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#656]
We have the zip and metadata for the new boundary layer.

**Comment by sophiathirza** [comment]
Zip file name: Isle_of_Man_Marine_Nature_Reserves.zip
Shape file name: Isle_of_Man_Marine_Nature_Reserves.shp
Layer name: Marine Nature Reserves (Isle of Man)
ID field: OBJECTID
Name field: Name

**Comment by reupost** [comment]
Loaded as layer 144. Please add metadata as needed.
