### ISSUE TITLE
Absence records not displaying on the interactive map

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#657]
There are no records displayed as points on the following map:
https://records.nbnatlas.org/occurrences/search?q=lsid%3ANHMSYS0021056527&fq=occurrence_status%3A%22absent%22#tab_mapView

However, when you colour by occurrence status the points display.

**Comment by reupost** [comment]
I don't know how to colour by occurrence status.

It seems to make sense that the map doesn't display absence records. How would you like this to work?

**Comment by sophiathirza** [comment]
Map type > Display as points > occurrence status.

The map on the species page doesn't show absence records.. I think. But the interactive map I thought did. You can filter the records by occurrence status, so it makes sense that the map shows absence records - they are included in the list of records.

Perhaps this is something that has changed and I didn't realise, but people are getting confused when they view the list of records and download the records - suddenly they have more records than expected.

It would make more sense for there to be an automatic filter (which can be removed) to exclude absence records

**Comment by sophiathirza** [comment]
#237

**Comment by sophiathirza** [comment]
Absence records should only be excluded in the regions component and in the explore your area pages.

**Comment by sophiathirza** [comment]
I'm going to close this for now.
