### ISSUE TITLE
Searching from Species tab is returning all related names

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#658]
I think using the search box on "Species" (rather than the top left search box or central box on the home page ) used to cut out all the road names etc., but on a search for Darwin, it is giving me lots of roads and locations and just one species.

**Comment by reupost** [comment]
All species portals only include taxa in search results, except the main species portal which only excludes common names (and hence includes locations and other results). 
@sophiathirza you mentioned that some users use the species search to find things other than taxa. Could you advise if this should be changed to match the other portals? The types of data we can in/exclude are:
Locality
Taxon
Region
Common name
Data resource
Data provider
Layer

**Comment by sophiathirza** [comment]
Would it be possible that if the search is done from the species page that only taxa are included but if the search is done from the top left search box then all contexts are included?

**Comment by reupost** [comment]
Done.

**Comment by sophiathirza** [comment]
I am happy with the change - @MandyHenshall is it okay?

We will review the species search in more detail this year and get a full set of requirements, as people do find it confusing.

**Comment by MandyHenshall** [comment]
Yes, that's great. thank you
