### ISSUE TITLE
Usual licence info to accompany all types of download

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#659]
The suggestion is: Remote downloads / views to include purpose of access and under what licence and to ensure some re-iteration of Ts & Cs in Atlas accompanying any other map created from Atlas data streaming. 
The reason: Lot of potential for accidental misuse of data (eg the Tom Bio QGIS tool where currently licence info and attribution does not follow the download)

**Comment by c-van-dierkson** [comment]
Ok to close
