### ISSUE TITLE
Hide editable sections on data resource page when logged on as an editor

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#664]
Please hide the following sections in the edit view of a data resource so that Editors cannot see them:

- [x] image metadata
- [x] taxonomic range - my update isn't saved. Could this be hidden or the make the page save my selection?
- [x] attributions (I don't know what these do)
- [x] taxonomy hints
- [x] external identifiers

- [x]  I think we should also hide the check box for Is NBN member.

**Comment by reupost** [comment]
Done. There is something wrong with the taxonomic range component, but we've never used it - please raise it as a separate issue if you want me to look into it.
Attributions (there is only NBN now, not the Australian ones) is something Giselle wanted (as per email also sent to you 30 Jan 2019)

**Comment by sophiathirza** [comment]
But what is the difference between Belongs to NBN and the NBN Attribution?

**Comment by reupost** [comment]
I don't know; it wasn't relevant for the whitelisting work. If you'd like me to look into it, please raise a new issue.

**Comment by sophiathirza** [comment]
It doesn't matter. I thought that you had used the NBN Attribution to indicate an NBN member (it's what you say above) - but when I looked at the pages it seemed to be the 'belongs to NBN' that indicates a member.
