### ISSUE TITLE
When adding names to whitelist - only allow exact email matches

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#666]
I thought that we were only allowing editors to match exact email addresses when adding names to the white list, rather than a fuzzy search. On searching for 'Soph' I was able to see all accounts starting with Soph.

**Comment by reupost** [comment]
Sorry, badly capitalised configuration entry :/ Fixed now.

**Comment by sophiathirza** [comment]
thank you!
