### ISSUE TITLE
Change link text under Online resources on NI species pages

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#668]
Please change: 

- [x] NMNI Habitas link text to 'National Museums NI Habitas'
- [ ] NI Priority species link text to 'NI Priority species'

**Comment by reupost** [comment]
How do you want the NB Priority species link changed? On e.g. https://northernireland-species.nbnatlas.org/species/NHMSYS0000876090 it already appears as "NI Priority species"

**Comment by sophiathirza** [comment]
Sorry,     * NI Priority species link text to 'NI Priority Species' capital S

**Comment by reupost** [comment]
Done
