### ISSUE TITLE
Fix taxon stats on home page

### ISSUE THREAD

**Issue by djtfmartin** [nbnuk/nbnatlas-issues#67]
Currently reporting:

```
22,628
Stoneflies

3,473
Hares, Pikas, Rabbits

5,762
Mussels, Clams

2,549
Lizards, Snakes
```

Which i think are place holder stats.

<img width="743" alt="screenshot 2016-05-05 11 49 27" src="https://cloud.githubusercontent.com/assets/444897/15041939/beeca688-12b7-11e6-84ff-71f2af3f02c2.png">

**Comment by djtfmartin** [comment]
Theres a breakdown of taxon groups available from this webservice:

```
http://species-ws.als.scot/search?q=*:*&facets=taxonGroup_s&rows=0
```

**Comment by studio4** [comment]
Data is coming from //records-ws.als.scot/occurrences/search.json?q=cl2:Scotland&pageSize=0&facets=species_subgroup

Tried using //species-ws.als.scot/search?q=_:_&facets=taxonGroup_s&rows=0&callback=set_record_count3 as a direct replacement but we get:

> SyntaxError: missing ] after element list
> [Ljava.lang.Object;@4682f23

**Comment by djtfmartin** [comment]
Perhaps this isn't a issue. Will mark as a question for the NBN guys.

Cant reproduce that error (although the above URL isnt quite right - see 'q' param).

<img width="806" alt="screenshot 2016-05-11 21 51 55" src="https://cloud.githubusercontent.com/assets/444897/15196069/9ac0acb8-17c2-11e6-904f-dd2d826784f4.png">

**Comment by djtfmartin** [comment]
Closing - non issue
