### ISSUE TITLE
Has user assertions is missing from list of available filters

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#673]
Under the Customise filter  button, the option to include user assertions is missing on the live Atlas.

**Comment by reupost** [comment]
Note that this is not displayed when there are no records with different values for the facet in question. But if you click on 'Reset to defaults' then the facet will be shown even if there is no variation in record values for it. Its a little tricky. Perhaps raise another issue if we want to amend this behaviour.

**Comment by sophiathirza** [comment]
okay. It's strange as it's just reappeared without me doing anything. Although there is a new assertion.
