### ISSUE TITLE
Unable to grant access to species within a dataset as an Editor

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#674]
Logged on as an Editor, on selecting a species from the drop-down nothing happened. 

Logged on an an Admin, selecting a species highlights the datasets that contain the species and indicates the number of records of the species in the dataset. It also disables the check boxes of the other datasets.

**Comment by reupost** [comment]
Fixed

**Comment by sophiathirza** [comment]
thanks.
