### ISSUE TITLE
Remove eventdate - sensitive from simple format download

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#676]
The 'eventdate - sensitive' and 'Event end date - sensitive' fields are not required in the downloads. The event date of sensitive records should not be blurred.

**Comment by reupost** [comment]
Please review on records-dev

**Comment by sophiathirza** [comment]
thanks, it's gone.

**Comment by sophiathirza** [comment]
Sorry.. I was looking on live.

The start date month and start date day field are missing from the downloads on dev. Was that intentional?

**Comment by reupost** [comment]
If there are no records with content for a given field it is always omitted.

**Comment by sophiathirza** [comment]
Ah.. okay. So if the record has a complete start date, no value is given to start month and start day?

**Comment by reupost** [comment]
Yes, start day/month/year are only populated if the event date is incomplete (e.g. 'Mar-2012' or '2013'). It's a bit of a labyrinth...

**Comment by sophiathirza** [comment]
I see that. Thanks!
