### ISSUE TITLE
Question on the list of species that you can grant access to

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#678]
Are the species in the drop down only those whose records are sensitive in data provider's datasets, i.e. in the country that the record is in, or are they sensitive species from all countries combined?

There are quite a few species listed in dr885 that are not sensitive in Scotland and I don't think that there are many records outside of Scotland.

If not, is it possible to restrict the species listed to only those that have sensitive records in the data provider's datasets?

**Comment by reupost** [comment]
At the moment the list of species is based on the distinct species within a data providers datasets that are also found in a set of sensitive species lists (i.e. dr804, dr1536, dr805, dr52). I can't think of an inexpensive way of checking the records of each potentially sensitive species to see whether they in turn are found in any of the specific countries for which that species is declared sensitive. 

Once a particular species is selected then it would be possible to check the records for that species, but of course that defeats the purpose.

If this is important (and I'd suggest maybe we should see how much need for it there is), then I'd need to put some time into thinking whether there is a reasonable way of achieving this without bombarding  the records webservices with potentially hundreds of queries in a short space of time.

**Comment by sophiathirza** [comment]
That's okay - it was really just a question to check that I understood what was happening.

thanks
