### ISSUE TITLE
List of Users - heading link as a means of changing order not working

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#679]
When viewing list of users previously could click on ID or name etc and it would reverse the order from oldest to newest etc . When click header now says 'Page not found'

**Comment by sophiathirza** [comment]
It's missing the Admin folder in the url.

**Comment by reupost** [comment]
This should work now. Note if you have filtered the list by searching, and then click a column sort, you lose your filter. I'd need to look into that as a separate issue.

**Comment by sophiathirza** [comment]
thanks.
