### ISSUE TITLE
London BBG boundaries

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#682]
Zip file name: London.zip
Shape file name: London.shp
Layer name: Burial grounds (London)
ID field: BBG_UNIQUE
Name field: BBG_NAME

**Comment by reupost** [comment]
Loaded as layer 143. Please add metadata as needed.

**Comment by sophiathirza** [comment]
Sampling has worked - I found records in Kensal Green Cemetery
