### ISSUE TITLE
All-Ireland spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#683]

**Comment by sophiathirza** [comment]
Zip file name: All_Ireland_CoastalWaters.zip
Shape file name: All_Ireland_CoastalWaters.shp
Layer name: Ireland and coastal waters
ID field: Id
Name field: Name

**Comment by reupost** [comment]
Loaded as layer 150, please add metadata as needed.

**Comment by sophiathirza** [comment]
thanks.
