### ISSUE TITLE
Consistent column names in downloads

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#684]
The latitude and longitude columns that contain the supplied (ungeneralised) values are called latitude - ungeneralised and longitude - ungeneralised

Could the gridReference - sensitive, locality -sensitive and coordinateUncertaintyInMeters - sensitive columns be renamed to gridReference - ungeneralised, locality - ungeneralised and coordinateUncertaintyInMeters - ungeneralised, respectively, please?

This is in both the simple and full DwC downloads

**Comment by reupost** [comment]
ok

**Comment by sophiathirza** [comment]
thanks.
