### ISSUE TITLE
Create your Account interface defaults to Australian regions

### ISSUE THREAD

**Issue by arbutler90** [nbnuk/nbnatlas-issues#688]
![image](https://user-images.githubusercontent.com/46929296/53636229-5f29cc80-3c17-11e9-84a7-a50684c744e7.png)

I attempted to flag a record through my Atlas NI editor login but was prompted to create an account in the NBN Atlas. Not sure if that's an issue with the type of login that I have or if there is an interoperability issue between Atlas logins.

Real issue here is that the set-up interface defaults to Australian regions as illustrated.

**Comment by sophiathirza** [comment]
Your Atlas NI editor login is just for the WordPress site, you need to have an NBN Atlas account to flag an issue.

Thank you for reporting the problem with the region drop-down.

**Comment by reupost** [comment]
I see the component had these options hardcoded. What should our options be?

**Comment by reupost** [comment]
I've set the options as United Kingdom (i.e. non-specific), England, Isle of Man, Northern Ireland, Scotland, Wales. Let me know if you want to amend this.

**Comment by sophiathirza** [comment]
@GiselleSterry we updated the authorisation component recently and the drop-down on the create and edit account page reverted to Australian territories. Reuben has replaced it with UK and countries - do you remember what we had before, was it counties or is countries okay? thanks.

**Comment by reupost** [comment]
No, it was counties, from looking at the data. I've changed it to reflect this.

**Comment by sophiathirza** [comment]
The counties look good - but the auth website has an image saying that the website is under maintenance rather than the NBN Atlas theme.
