### ISSUE TITLE
Custom and full DwC download coordinateUncertaintyInMeters processed

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#694]
In the full and custom DwC download the 'coordinateUncertaintyInMeters processed' value should be the generalised value for sensitive records, regardless of whether the user has access or not. At the moment, if the user has access to the record the supplied value is used.

NB: the 'decimalLatitude processed' and 'decimalLongitude processed' values are the generalised values for sensitive records, regardless of the users access.

**Comment by sophiathirza** [comment]
I don't think that this is so important as the decimalLatitude and decimalLongitude values are generalised values. I have reduced the priority.

**Comment by reupost** [comment]
Fixed on 7 March

**Comment by sophiathirza** [comment]
The 'coordinateUncertaintyInMeters processed' is the generalised value for sensitive records in the full DwC download but it is still the supplied value in the custom DwC downloads

**Comment by reupost** [comment]
Ok, this should be better now. I've left the original coordinateUncertainty next to the decimalLatitude/Longitude and geodeticDatum columns, removed the misleading coordinateUncertaintyInMeters_processed value (which was displaying the unprocessed value) and made sure the sensitive columns include both.

**Comment by reupost** [comment]
Ok, I've removed both - see #695

**Comment by sophiathirza** [comment]
- [x]  DwC full and custom - locality, grid reference and coordinateUncertaintyInmeters  are called '- sensitive' rather than '- ungeneralised'
- [ ] DwC full and custom - still have coordinateUncertaintyInmeters_processed
- [ ] DwC full and custom - are missing coordinateUncertaintyInmeters

Have I understood correctly that we shouldn't have coordinateUncertaintyInmeters_processed?

**Comment by reupost** [comment]
Could you send me links to the searches you've done that show these problems please? My go-to test dataset has been deleted

**Comment by reupost** [comment]
When I do a Dwc download of https://records.nbnatlas.org/occurrences/search?q=lutra%20lutra&fq=month:%2204%22#tab_chartsView (having given myself sensitive access on some of these records) I get column headings 

decimalLatitude   processed | decimalLongitude processed | Longitude - ungeneralised | Latitude - ungeneralised | Locality - ungeneralised | Grid reference - ungeneralised | Coordinate uncertainty (m) - ungeneralised | Coordinate uncertainty - processed
-- | -- | -- | -- | -- | -- | -- | --

A custom download of the same set gives headings:

Longitude -   ungeneralised | Latitude - ungeneralised | Locality - ungeneralised | Grid reference - ungeneralised | Coordinate uncertainty (m) - ungeneralised | Coordinate uncertainty - processed
-- | -- | -- | -- | -- | --

(please note these are columns GZ - HE)

Could you advise where the problems are?

**Comment by sophiathirza** [comment]
The fields are no longer called * - generalised. 

I thought that you had removed the * - processed and kept the original names. I misunderstood - I get the same as above now.

thanks.
