### ISSUE TITLE
Custom DwC download - unnecessary fields

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#695]
The custom DwC download has additional fields decimalLatitude, decimalLongitude and coordinateUncertaintyInMeters that are not in the full DwC download.

For sensitive records, without access, the coordinates are the generalised values but the uncertainty value is the supplied uncertainty. With access, the coordinates and uncertainty are the supplied values. 

Without access, the uncertainty value should be the generalised value – otherwise it’s easy to decide that you’ve been given access to the original coordinates.

Either this should be corrected or the fields decimalLatitude, decimalLongitude and coordinateUncertaintyInMeters could be removed from the file because both the processed and ungeneralised coordinates and uncertainty are in other fields. 

Removing these three fields would make the download more consistent with the full DwC download and there is no reason to have them.

**Comment by sophiathirza** [comment]
This one I think is more confusing for the users than #694, but if it is difficult to correct then it can be left for now as well.

**Comment by reupost** [comment]
Ok, I've removed these 3. The only issue is the 'coordinateUncertaintyInMeters processed' is a long way from the processed lat/long columns, but that is not easy to change

**Comment by sophiathirza** [comment]
thanks.
