### ISSUE TITLE
Records order problems

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#698]
- [x] The default sort order of the Records tab is always Date added and Descending. Change the order to Ascending and the view is refreshed but changed to a sort by Best match.

- [x] change the default order to record date. 
 
- [ ] when ordering by Record date, the displayed records are not in date order, either ascending or descending. This could be a problem with partial record dates. If you then change the order from Ascending to Descending or vice versa then the view is properly ordered. But if you select the numbered squares at the foot of this view I have seen the order change from Ascending to Descending of its own volition.

**Comment by reupost** [comment]
Record date is not populated for some records (without collection year, month and day), so it produces some unexpected listings: see lower in the list here https://records.nbnatlas.org/occurrences/search?taxa=&q=potato&fq=&wkt=&lat=&lon=&radius=&dir=asc&offset=0&max=20

**Comment by sophiathirza** [comment]
I made a mistake - the default should be descending record date (most recent first), sorry....

**Comment by sophiathirza** [comment]
hold on.. that's what you did. sorry. too hot.

I expect that's why the default wasn't record date - but we try not to accept records without an event date, so it's okay. Let's wait for feed back. thanks.

**Comment by sophiathirza** [comment]
brilliant - thank you.
