### ISSUE TITLE
Base map missing when downloading map from the interactive map

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#699]
The base map has stopped displaying in maps downloaded from the interactive map: https://records.nbnatlas.org/occurrences/search?q=lsid%3ANBNSYS0000177880&qc=&wkt=MULTIPOLYGON(((-2.198638916015625+51.08926288673459,-2.187652587890625%2050.450042692806214,-0.457305908203125%2050.45528906660724,-0.479278564453125%2051.07718524202257,-2.198638916015625%2051.08926288673459)))#tab_mapView
 
Only the records are displayed in the download
 
I tried the same map in the spatial portal and base map (using the outline map) and it’s okay.

**Comment by reupost** [comment]
Fixed I think

**Comment by sophiathirza** [comment]
yes, it is, thanks
