### ISSUE TITLE
Missing columns in DwC downloads?

### ISSUE THREAD

**Issue by katieoli** [nbnuk/nbnatlas-issues#700]
There is no _Locality_ or _Locality - ungeneralised_ column in DwC downloads.

**Comment by sophiathirza** [comment]
The full and custom DwC downloads have a verbatimLocality field - is that the locality field? 

The locality - ungeneralised field is in both the full and the custom DwC downloads

**Comment by c-van-dierkson** [comment]
KO advised ok to close
