### ISSUE TITLE
Sensitive species list access and use - is it confusing?

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#704]
I was wanting to refer to the Combined sensitive species list that is used for screening records in the Atlas and I know that it can be accessed via the HELP webpage at [https://docs.nbnatlas.org/sensitive-species-list/](url).  
However, a search for lists that contain the word 'sensitive' in the Species List search box at [https://lists.nbnatlas.org/public/speciesLists?q=sensitive](url) results in the agency lists but not the Combined sensitive species list:
![image](https://user-images.githubusercontent.com/18594564/54702732-5d289e80-4b2f-11e9-9e53-92fb67bfea10.png)

I think the result from searching the Species Lists could be confusing as these Agency lists may be mistaken for the actual list that used for blurring, and the search does not provide a link to the Combined sensitive species list. Could this be changed? 
It might also be worth adding a note to the HELP webpage text to indicate that the Agency lists are available but are not used for the screening.  

However - I have just realised the Agency lists are used in the Species page overviews - could this lead to a species being noted as sensitive but not being blurred or will that not matter? Perhaps the Agency list names need to change to ensure the Agency names are all included?

**Comment by sophiathirza** [comment]
Yes, we are storing sensitive species in several places. The definitive one is here: https://sds.nbnatlas.org/sensitive-species-data.xml - this is the actual list that the screening is based on.

What would be great is if we could put a style sheet on this XML file so that it can be viewed easily, both in its combined form and for each country separately.

Also, could the XML file be put in github, so that we can trace any changes?

**Comment by CEJohnston** [comment]
I think the above would be a good idea and it does need to be made available to the Atlas user. Do you think it worth changing the name of the Agency lists to indicate they are different to the NBN list?

**Comment by sophiathirza** [comment]
The sensitive species lists names have been changed.
