### ISSUE TITLE
NR SE spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#706]
Zip file name: Southeast_Route_Study_Area_rev1.zip
Shape file name: Southeast_Route_Study_Area_rev1.shp
Layer name: Network Rail SE route study area
ID field: OBJECTID
Name field: Route_Name

**Comment by reupost** [comment]
Loaded as no. 152. Please add metadata as needed

**Comment by sophiathirza** [comment]
all okay, thanks.
