### ISSUE TITLE
NI District Council spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#708]
This is the link to the LPS District Council boundaries on Open Data NI:
 
https://www.opendatani.gov.uk/dataset/osni-open-data-largescale-boundaries-local-government-districts-20121

**Comment by sophiathirza** [comment]
Zip file name: OSNI_Open_Data_Largescale_Boundaries__Local_Government_Districts_2012.zip
Shape file name: OSNI_Open_Data_Largescale_Boundaries__Local_Government_Districts_2012.shp
Layer name: District Council boundaries (Northern Ireland))
ID field: OBJECTID
Name field: LGDNAME

**Comment by reupost** [comment]
Loaded as layer ID 160, please add metadata as needed

**Comment by sophiathirza** [comment]
Metadata added - thanks.
