### ISSUE TITLE
Spatial layer: change mapped categories in the Ancient Woodland Inventory map

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#71]
The polygons need to be mapped by the attribute ANTIQUITY rather than SITE_NAME.  There are only 3 categories of ancient woodland. My apologies for not picking the correct attribute.

**Comment by djtfmartin** [comment]
I've done this:

<img width="1120" alt="screenshot 2016-05-16 20 13 00" src="https://cloud.githubusercontent.com/assets/444897/15300834/a085d158-1ba2-11e6-89f5-c1d417db2f5d.png">
