### ISSUE TITLE
Problem with easymaps

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#710]
Some maps are returning an internal server error: https://easymap.nbnatlas.org/EasyMap?tvk=NHMSYS0020528110&w=332&b0fill=ff0000. The map hasn't changed and the TVK is still correct.

It looks like it is a problem with the combination of url parameters, as it works with the default yelllow fill: https://easymap.nbnatlas.org/EasyMap?tvk=NHMSYS0020528110&w=332

Removing the map projection parameter but keeping the red fill also works (just a bit squashed): https://easymap.nbnatlas.org/EasyMap?tvk=NHMSYS0020528110&b0fill=ff0000

 Here is map on the data providers page: https://www.naturespot.org.uk/species/greenhouse-slug-0

**Comment by reupost** [comment]
I just cleaned the cache and it looks ok?

**Comment by sophiathirza** [comment]
Yes it does - thanks! any ideas why?
