### ISSUE TITLE
Add Ireland Vice Counties to predefined areas on NI Atlas

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#713]
Please add layers 111 and 133 to the predefined areas in the Atlas NI

**Comment by c-van-dierkson** [comment]
Do we still need to do this? @sophiathirza

**Comment by sophiathirza** [comment]
Yes: https://northernireland-regions.nbnatlas.org/#rt=Areas+of+Special+Scientific+Interest

**Comment by c-van-dierkson** [comment]
Layer 111 has been replaced with layer 127 - RR confirms this is done

**Comment by c-van-dierkson** [comment]
@reupost  When navigating from the Home page to Regions, the vice-county menu defaults to open, which means the other menus are slightly obscured from the page. Would you be able to fix it so no menu is open and nothing is highlighted on the map please?

**Comment by c-van-dierkson** [comment]
@reupost Sally confirms she would like the default to be County Boundaries (Northern Ireland)

**Comment by c-van-dierkson** [comment]
RR fixed.
