### ISSUE TITLE
Typos and inconsistent VC names in boundary files

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#715]
There is a typo in Dumfriesshire in the VC with 3 and 12 mile boundary files. @CEJohnston also noted inconsistencies between the three VC files, which should be corrected.

**Comment by CEJohnston** [comment]
Other naming inconsistencies between VC (no buffer) and 3 and 12 mile buffer files noted so far (for reference -  listed in format _no buffer file name / 3 and 12 mile buffer files name_):

South Aberdeenshire / South Aberdeen
Angus / Forfar
East Ross and Cromarty / East Ross

We need to confirm the correct version and get the files updated.

**Comment by sophiathirza** [comment]
I think that BRC have done some work on this. I will contact them to ask.

**Comment by CEJohnston** [comment]
BRC recently reported there is now a GitHub repository for vice county mapping layers: [https://github.com/BiologicalRecordsCentre/vice-counties](url)  Hopefully the VC names will have been corrected across the board.  The VC layers in our portal will probably need updating now.

Note: we still offer a download of the VC files on the NBN Trust website at [https://nbn.org.uk/tools-and-resources/nbn-toolbox/watsonian-vice-county-boundaries/](url) - with the development of the GitHub repository our page now needs to be reviewed.  I'd suggest a link to GitHub replaces the download option to avoid version control issues.

**Comment by c-van-dierkson** [comment]
@sophiathirza @CEJohnston What's the latest on this please?

**Comment by CEJohnston** [comment]
@c-van-dierkson - I have no update.  @sophiathirza - did you manage to contact Martin (see Trello card https://trello.com/c/sA6D1Xp4/308-vice-county-information-on-the-nbn-website-to-be-updated)?

**Comment by sophiathirza** [comment]
@CEJohnston no, not yet.

**Comment by CEJohnston** [comment]
@sophiathirza I suspect Martin is pretty busy this week as he is organising the BRC's recorders' conference this coming weekend.  @c-van-dierkson we gave the Trello card a medium priority - is that still OK?

**Comment by c-van-dierkson** [comment]
Yes, I was just wondering where we were with it.

**Comment by c-van-dierkson** [comment]
As we've got a Trello card on this can we confirm this is no longer an NBN Trust issue? I'm thinking we can close this on GH? @sophiathirza

**Comment by sophiathirza** [comment]
@c-van-dierkson I haven't got to this yet, sorry.
