### ISSUE TITLE
Remaining NR route boundaries

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#716]
- [ ] Anglia
Zip file name: Anglia_route_Study_area.zip
Shape file name: Anglia_route_Study_area.shp
Layer name: Network Rail Anglia route study area
ID field: Area
Name field: Route_Name

- [ ] LNE
Zip file name: LNE_route_Study_area.zip
Shape file name: LNE_route_Study_area.shp
Layer name: Network Rail LNE route study area
ID field: Area
Name field: Route_Name

- [ ] LNW
Zip file name: LNW_route_Study_area.zip
Shape file name: LNW_route_Study_area.shp
Layer name: Network Rail LNW route study area
ID field: Area
Name field: Route_Name

- [ ] Scotland
Zip file name: Scotland_route_Study_area.zip
Shape file name: Scotland_route_Study_area.shp
Layer name: Network Rail Scotland route study area
ID field: Area
Name field: Route_Name

- [ ] Wales
Zip file name: Wales_route_Study_area.zip
Shape file name: Wales_route_Study_area.shp
Layer name: Network Rail Wales route study area
ID field: Area
Name field: Route_Name

- [ ] Wessex 
Zip file name: Wessex_route_Study_area.zip
Shape file name: Wessex_route_Study_area.shp
Layer name: Network Rail Wessex route study area
ID field: Area
Name field: Route_Name

- [ ] Western
Zip file name: Western_route_Study_area.zip
Shape file name: Western_route_Study_area.shp
Layer name: Network Rail Western route study area
ID field: Area
Name field: Route_Name

**Comment by reupost** [comment]
Loaded layers with IDs as follows, please add metadata as needed:
Anglia: 153
LNE: 154
LNW: 155
Scotland: 156
Wales: 157
Wessex: 158
Western: 159

**Comment by sophiathirza** [comment]
thanks. all looks good.
