### ISSUE TITLE
Data partners needs to be opened as a new tab!

### ISSUE THREAD

**Issue by sallystewartmoore** [nbnuk/nbnatlas-issues#720]
The data partners tab needs to be a new tab for all Atlases, to stop directing users away from their local Atlas (which often goes unnoticed initially and then you have to find your way back to your local Atlas). It makes it impossible to open the data from your chosen data partner in the Atlas you want to use.

**Comment by sophiathirza** [comment]
Sorry, I thought I had already done that. It now opens in a new window on the Atlas NI
