### ISSUE TITLE
Unable to delete a user

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#721]
Tried to delete user 11061. Still appears in the list. 
Click on edit button in user details - click delete - warning message appears - click ok - message 'User 11,061 deleted' appears at top of user list.
Go back in and user details still there. 
Also tried deleting user roles and unticking activation box.

**Comment by sophiathirza** [comment]
I wasn't able to either.

**Comment by reupost** [comment]
Should work now

**Comment by sophiathirza** [comment]
I was able to delete a user account.
