### ISSUE TITLE
Non-preferred common names in the species lists

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#724]
The non-preferred common names are still being matched in the species lists

**Comment by davidgenney** [comment]
I was just about to post about this. I'm trying, in vain, to include the moss _Campylopus subporodictyon_ into a list. It doesn't matter whether I enter by name or by the correct species code, NHMSYS0021194602, the list always interprets as _Dicranum subporodictyon_ (NHMSYS0000309770). The latter is an out of date synonym and not associated with any records. I can get around this by downloading this species separately, but it takes time to check that similar miss-matching isn't occurring elsewhere and I'll look forward to hearing if there is a solution.

**Comment by sophiathirza** [comment]
David, species names that were added in the last update of the species dictionary (like Campylopus subporodictyon) are not being matched in the species lists. New names are working as expected in the rest of the Atlas. I have asked Reuben to look into it as quickly as possible.

**Comment by davidgenney** [comment]
Thank you Sophia.

**Comment by sophiathirza** [comment]
Species names are now being correctly matched in the species list.

**Comment by sophiathirza** [comment]
@reupost, has the update also corrected the common name in the lists? I can't find any examples where the common name is not the preferred English common name in the species lists?
