### ISSUE TITLE
Incorrect link to iRecord app, submit a record

### ISSUE THREAD

**Issue by Lorsom** [nbnuk/nbnatlas-issues#725]
Incorrect link to iRecord App, on NBN Atlas Northern Ireland, submit a record https://northernireland.nbnatlas.org/submit-a-record/, 
currently links to iRecord login for online recording. Change link to  http://www.brc.ac.uk/apps

**Comment by sophiathirza** [comment]
The link has been updated.

**Comment by Lorsom** [comment]
Sophia
Have checked the link and it has not updated. I want the link to go to the App specifically not the iRecord website and online recording. Please note I am receiving security messages for the app, via below link, see screen shot iRecord security warning. Apologies for not raising through GitHub but am investigating if this is an internal network problem.
https://irecord.org.uk/app/

This link works for my work network instead… http://www.brc.ac.uk/apps
Can you please update to go directly to the App.


I have also encountered a similar problem with the following link from Home page, Report Invasive species & other threats<https://isleofman.nbnatlas.org.194-187-248-148.testcode.co.uk/contact-us/report-invasive-species/> (redirects to Isle of Man).

Are you able to check this for me as again I am getting a security warning, raised with my internal IT.  In order to report an invasive species the link should be to https://www2.habitas.org.uk/records/ISI Submit record of invasive non-native species in Northern Ireland

Thanks
Lorna


Lorna Somerville, NI Environment Agency, Klondyke Building,Cromac Avenue,Belfast,BT7 2JA
Tel. 028 90569644

**Comment by sophiathirza** [comment]
Sorry Lorna. The both links are now updated.

**Comment by Lorsom** [comment]
Many thanks Sophia, am keen to promote iRecord to encourage recording, much appreciated

Lorna

Lorna Somerville, NI Environment Agency, Klondyke Building,Cromac Avenue,Belfast,BT7 2JA
Tel. 028 90569644
