### ISSUE TITLE
NBN Atlas Documentation Portal 

### ISSUE THREAD

**Issue by Lorsom** [nbnuk/nbnatlas-issues#726]
NBN Atlas Documentation Portal does not list NBN Atlas Northern Ireland under Choose Atlas tab

**Comment by sophiathirza** [comment]
@MandyHenshall would you add NBN NI Atlas under Choose Atlas on the Documentation site, please?

**Comment by MandyHenshall** [comment]
Done.  Apologies that I'd missed that before.

**Comment by Lorsom** [comment]
Sophia
Sorry to trouble you again. I’m not able to log into the atlas to edit.

Can you please edit the link for iRecord App – it currently directs the user to the desktop  iRecord<https://www.brc.ac.uk/irecord/> page but this is not correct.
The user should be directed through to iRecord App http://www.brc.ac.uk/apps

Many thanks
Lorna

Lorna Somerville, NI Environment Agency, Klondyke Building,Cromac Avenue,Belfast,BT7 2JA
Tel. 028 90569644
