### ISSUE TITLE
Unable to verify annotation 

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#727]
Trying to set the verification status of the record as corrected, I get the response 'Forbidden': https://records.nbnatlas.org/occurrences/6438bade-d434-402f-bdd9-e1af8a1f6c7b

![image](https://user-images.githubusercontent.com/1651015/57436332-c11e3800-723f-11e9-9d33-4839fe8fd5d3.png)

The data provider has the same problem logged on as an Editor.

**Comment by sophiathirza** [comment]
This is a recently updated dataset.

**Comment by reupost** [comment]
Problems with API keys, I think
