### ISSUE TITLE
Error subscribing to alerts on the species page

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#729]
I received the following error when trying to subscribe to an alert when new records are added of a species, on the species page. Also the email address in the error is incorrect.
![image](https://user-images.githubusercontent.com/1651015/57459088-d5c7f380-7272-11e9-97de-987b603cca3f.png)

I was able to subscribe to alerts of new records of the same species on the records page:
![image](https://user-images.githubusercontent.com/1651015/57459152-f42def00-7272-11e9-9290-88d00971c4c2.png)

**Comment by sophiathirza** [comment]
I just tried again with another species and it worked...

**Comment by c-van-dierkson** [comment]
Ok to close
