### ISSUE TITLE
Explore your area defaults to wrong location

### ISSUE THREAD

**Issue by Lorsom** [nbnuk/nbnatlas-issues#730]
Northern Ireland Atlas link to explore your own area redirects to wrong location, Moffat, Scotland. Default map to be changed to Northern Ireland
![Explore your area Home Page](https://user-images.githubusercontent.com/36696917/57526076-49760900-7324-11e9-94cd-3594be8bfc67.PNG)
![Explore your area](https://user-images.githubusercontent.com/36696917/57526085-5266da80-7324-11e9-9905-524b8d903b9b.PNG)

**Comment by sophiathirza** [comment]
That's strange as the default location for me is Belfast. It does try to detect your location and use that as the default.

**Comment by Lorsom** [comment]
Sophia
I just checked and still defaults to Moffat, I will check with my IT team. It may be related to the locations settings on work network. I will check on my home PC tonight and let you know.

Lorna Somerville, NI Environment Agency, Klondyke Building,Cromac Avenue,Belfast,BT7 2JA
Tel. 028 90569644

**Comment by sophiathirza** [comment]
This was not a problem with the Atlas.
