### ISSUE TITLE
Incorrect link to report invasive species, N Ireland

### ISSUE THREAD

**Issue by Lorsom** [nbnuk/nbnatlas-issues#732]
![report invasive species and other threats](https://user-images.githubusercontent.com/36696917/57710236-66804400-7664-11e9-9e92-2cb5c3aa87bc.PNG)

Please change link to report invasive species & other threats. Default is set to Isle of Man, not N Ireland, please link to below:

https://www2.habitas.org.uk/records/ISI

**Comment by sophiathirza** [comment]
The button links to the ISI page on habitats, for me. I wonder if it has cached.

**Comment by Lorsom** [comment]
Sophia
It would appear the problems and broken links I’m encountering are caused by Google Chrome browser on my work PC. I tried the link for IIS via Internet Explorer and it directs me to the correct page. Obviously this is an issue with the internal NI Civil service network, I’ll raise with my IT team. My apologies for wasting your time and troubling you with this, I’ve been trying out the Atlas to demonstrate to colleagues.
Thanks for your patience
Lorna

Lorna Somerville, NI Environment Agency, Klondyke Building,Cromac Avenue,Belfast,BT7 2JA
Tel. 028 90569644

**Comment by sophiathirza** [comment]
Oh shame. Thanks for letting me know.
