### ISSUE TITLE
Scientific name qualifier is not included on the records page

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#734]
Could both the authority and name qualifier be added under the Taxonomy header. e.g.: https://records.nbnatlas.org/occurrences/7de41932-fd26-4675-8435-cf0f5e18e60e

and to the scientific name in the header

The full scientific name (i.e. the first link) should be Brachypterolus pulicarius sensu auct. partim not (L., 1758)

**Comment by reupost** [comment]
The example is from the records page. Could this be clarified?

**Comment by sophiathirza** [comment]
sorry, I meant the records page.

**Comment by sophiathirza** [comment]
sorry, it is done. closing.
