### ISSUE TITLE
Add navigation to record submission routes

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#737]
This is a suggestion from the NBN Atlas Scotland steering group meeting in April 2019:  could a tab or button be added to the records search results pages and species pages in the NBN Atlas (and the country Atlases) to guide users to info on submission routes for records?  

I'd suggest something like a button with text 'Submit your sightings' linking to the Record Wildlife page on the NBN website [https://nbn.org.uk/record-share-explore-data/start-recording-wildlife/](url) but other suggestions are welcome.  Would in particular help non-expert users submit their records into the data flow.

**Comment by sophiathirza** [comment]
I've been meaning to talk to @MandyHenshall about this. We need a page from the navigation for 'submit a sighting', as we now have on Atlas NI. After the NBN Atlas newsletter went out I had four different emails from individuals asking where to submit their records.

The entire navigation on the Atlas needs a rethink, perhaps we can do it all at the same time?

**Comment by MandyHenshall** [comment]
I'm happy to add this into the navigation.  I can't see where it is on the NI Atlas other than as a quick link on the home page though?  As the navigation currently is on the main Atlas, I think it sits best under Get Involved, but if you want the navigation revising, just let me know your thinking and we can discuss this further for implementation.  Thanks.

**Comment by CEJohnston** [comment]
I think it needs to be obvious - putting it under Get Involved is a bit hidden.  So adding it as a call to action (like the NI home page) would be good - would the button idea on the search results pages be difficult to implement?
Do we need a different page of info from what is written on the NBN website? 
I agree it might be worth having a discussion about the navigation in general anyway - am happy to be part of it.

**Comment by CEJohnston** [comment]
At the last meeting of the Scottish Atlas steering group on 10 Sep 2019 it was agreed (as the quickest option) to amend and re-order the call to arms boxes on the NBN Atlas Scotland home page to include a box for Submit Your Sightings.  Details are given in Trello Card [https://trello.com/c/lISJRoNs/182-amend-call-to-arms-boxes-on-nbn-atlas-scotland-home-page#](url)

**Comment by CEJohnston** [comment]
This issue can be closed - the work has been done.
