### ISSUE TITLE
Red Fox Overview

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#739]
https://species.nbnatlas.org/species/NHMSYS0000080188#overview
Is it possible to change the main photo that appears on overview so that its not the back end of the skull. Thanks

**Comment by sophiathirza** [comment]
We can delete the occurrence record: 300ae1de-d9bc-433e-8c77-ab0e61c08973

**Comment by sophiathirza** [comment]
The image has been deleted.
