### ISSUE TITLE
Point to grid menu: change suggested species in menu to Scottish species (as per #51)

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#74]
Point to grid in interactive mapping interface - when selecting a species in the menu box the suggested species is Kangaroo - make this a Scottish species

**Comment by sophiathirza** [comment]
@CEJohnston is this still required?

**Comment by CEJohnston** [comment]
Would be nice to do - this is a text change to the dialogue box in the spatial portal - suggest Osprey 'Pandion haliaetus' for Scotland - but affects all countries so possibly use Wren 'Troglodytes troglodytes' throughout?

![image](https://user-images.githubusercontent.com/18594564/42945962-adb5b60a-8b61-11e8-874c-2dd3f94489c2.png)
