### ISSUE TITLE
Replace layer Marine Conservation Zones (England)

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#743]
The layer for Marine Conservation Zones (England) needs replacing. The updated layer (dated 31/05/2019) shows 103 sites (the old layer has 118 sites).
Download from Natural England: [https://naturalengland-defra.opendata.arcgis.com/datasets/marine-conservation-zones-england](url)
This is a priority layer - add to the next spatial layer upload milestone.

**Comment by sophiathirza** [comment]
Zip file name: Marine_Conservation_Zones_England.zip
Shape file name: Marine_Conservation_Zones_England.shp
Layer name: Marine Conservation Zones (England)
ID field: OBJECTID
Name field: MCZ_NAME

**Comment by reupost** [comment]
New layer 162 to replace layer 62, which is not used in any of the regions portals. I've copied the metadata across except for the new citation date (31/5/2019), and disabled the old layer.

**Comment by CEJohnston** [comment]
This layer is OK - thanks.
