### ISSUE TITLE
Public forests (England)

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#744]
Metadata: http://data-forestry.opendata.arcgis.com/datasets/008f058c12064fe594326f9d2b49ee28_0

**Comment by sophiathirza** [comment]
This will now be a single shape file with a multi-part polygon for each region

**Comment by CEJohnston** [comment]
England (single shapefile - features converted to multipart polygons).  Zipped file now available in Teams folder.

Zip file name: forest_england.zip
Shape file name: forest_england.shp
Layer name: National Forest Estate (England)
ID field: OBJECTID
Name field: FORESTDIST

Note: quality checks on this file have detected invalid geometries in 4 of the 6 polygons.  I suspect this is related to the 16 overlaps that were detected in the source file.  The source file was downloaded 18/06/2019

**Comment by reupost** [comment]
New layer 163 added. I cleaned up the shapefile beforehand. Please add metadata as needed.

**Comment by CEJohnston** [comment]
This layer is complete.  @reupost can you advise how the layer was cleaned up?

**Comment by reupost** [comment]
Hi @CEJohnston I used GRASS v.clean (all cleaning tools selected, no snapping, default minimum area), and there was also one polygon that I needed to manually fixed the geometry of: it was twisted and had a small overlap with another area.
