### ISSUE TITLE
SEPA spatial layers

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#746]
- [ ] WFD River Basin Districts
Zip file name: SEPA_River_Basin_Districts_BNG_shp.zip
Shape file name: SEPA_RIVER_BASIN_DISTRICTS_BNG.shp
Layer name: Water Framework Directive River Basin Districts (Scotland)
ID field: OBJECTID
Name field: RB_DIST
{Note: this file has three polygons.  Topolgy checks reveal one overlap which I cannot find.  I think it is very small so file might upload OK.  Can you try?]

- [ ] WFD Sub Units
Zip file name: SEPA_Sub_Basin_Districts_BNG_shp.zip
Shape file name: SEPA_SUB_BASIN_DISTRICTS_BNG.shp
Layer name: Water Framework Directive Sub Basin Districts (Scotland)
ID field: OBJECTID
Name field: SB_DIST

Spatial portal metadata category 1 and 2 (for all) is: Scotland; Hydrography
Download date: 12/06/2019

These files have failed the topology checks and are likely to not to upload correctly - not worth trying to upload:
- [ ] Bathing water catchments
- [ ] Main river and coastal catchments

**Comment by CEJohnston** [comment]
I have downloaded them using the atom feed scripts.  I shall upload the zip files to the OneDrive folder:  
The link (for reference & metadata) is:
https://www.spatialdata.gov.scot/geonetwork/srv/eng/catalog.search#/search?resultType=details&sortBy=relevance&any=Scottish%20Environment%20Protection%20Agency%20(SEPA)&from=1&to=20&fast=index&_content_type=json

**Comment by sophiathirza** [comment]
- [x] WFD River Basin Districts
Zip file name: SEPA_River_Basin_Districts_BNG_shp.zip
Shape file name: SEPA_RIVER_BASIN_DISTRICTS_BNG.shp
Layer name: Water Framework Directive River Basin Districts (Scotland)
ID field: OBJECTID
Name field: RB_DIST
{Note: this file has three polygons. Topolgy checks reveal one overlap which I cannot find. I think it is very small so file might upload OK. Can you try?]

- [x] WFD Sub Units
Zip file name: SEPA_Sub_Basin_Districts_BNG_shp.zip
Shape file name: SEPA_SUB_BASIN_DISTRICTS_BNG.shp
Layer name: Water Framework Directive Sub Basin Districts (Scotland)
ID field: OBJECTID
Name field: SB_DIST

**Comment by reupost** [comment]
Layer 165: WFD River Basin Districts
Layer 166: WFD Sub Units

I've added the categories and citation date, please add other metadata as needed.

**Comment by CEJohnston** [comment]
These layers are complete.
