### ISSUE TITLE
Update the licences on the Atlas.

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#75]
I have given licences to each dataset now, and they are showing 'Australia' after the licence name. We also need OGL adding to the licence list. Also visible on:
[http://registry.als.scot/public/show/dr242](url)

Critical for launch

**Comment by djtfmartin** [comment]
Thanks @CEJohnston. Can you provide a list of licences (name and URLs) ? This should be quick to do...

**Comment by CEJohnston** [comment]
Hi Dave - the four licences are below.  They each have a link to the
Creative Commons webpages (the list is off the NBN website -
http://nbn.org.uk/news/data-licensing-on-the-nbn-gateway/).

Ella - can you confirm these are correct?
- Open Government Licence
  http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
  (OGL)
- Creative Commons Zero
  https://creativecommons.org/publicdomain/zero/1.0/ (CC0)
- Creative Commons with Attribution
  http://creativecommons.org/licenses/by/4.0/ (CC-BY)
- Creative Commons, with Attribution, Non-commercial
  http://creativecommons.org/licenses/by-nc/4.0 (CC-BY-NC)

Christine
Christine Johnston
NBN Scottish Liaison Officer
tel: 07342254589
email: c.johnston@nbn.org.uk

NBN website: www.nbn.org.uk
NBN Gateway: http://data.nbn.org.uk
Atlas of Living Scotland: www.als.scot

*NBN Trust *- Registered in England and Wales - Company no. 3963387 -
Registered charity no. 1082163
Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL

[image: facebook logo]
https://www.facebook.com/pages/National-Biodiversity-Network/117818225374?fref=ts
National Biodiversity Network   [image: Twitter logo]
https://twitter.com/NBNTrust @NBNTrust  [image: Twitter logo]
https://twitter.com/AoLScot  @AoLScot

[image: NBN-Logo-153x80]

*\* Nominations are now open for the UK Awards for Biological Recording and
Information Sharing! ***
http://nbn.org.uk/news/uk-awards-nominations-open/

**Comment by EllaVogel** [comment]
Hi,

Yes, those licences look correct to me.

Thanks for progressing this.

Dave, hope everything is great with baby Jim!
Ella

On 12 May 2016 at 09:24, CEJohnston notifications@github.com wrote:

> Hi Dave - the four licences are below. They each have a link to the
> Creative Commons webpages (the list is off the NBN website -
> http://nbn.org.uk/news/data-licensing-on-the-nbn-gateway/).
> 
> Ella - can you confirm these are correct?
> - Open Government Licence
>   <http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
>   >
>   (OGL)
> - Creative Commons Zero
>   https://creativecommons.org/publicdomain/zero/1.0/ (CC0)
> - Creative Commons with Attribution
>   http://creativecommons.org/licenses/by/4.0/ (CC-BY)
> - Creative Commons, with Attribution, Non-commercial
>   http://creativecommons.org/licenses/by-nc/4.0 (CC-BY-NC)
> 
> Christine
> Christine Johnston
> NBN Scottish Liaison Officer
> tel: 07342254589
> email: c.johnston@nbn.org.uk
> 
> NBN website: www.nbn.org.uk
> NBN Gateway: http://data.nbn.org.uk
> Atlas of Living Scotland: www.als.scot
> 
> *NBN Trust *- Registered in England and Wales - Company no. 3963387 -
> Registered charity no. 1082163
> Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
> Street, Lace Market, Nottingham NG1 1LL
> 
> [image: facebook logo]
> <
> https://www.facebook.com/pages/National-Biodiversity-Network/117818225374?fref=ts
> 
> > National Biodiversity Network [image: Twitter logo]
> > https://twitter.com/NBNTrust @NBNTrust [image: Twitter logo]
> > https://twitter.com/AoLScot @AoLScot
> 
> [image: NBN-Logo-153x80]
> 
> *\* Nominations are now open for the UK Awards for Biological Recording and
> Information Sharing! ***
> http://nbn.org.uk/news/uk-awards-nominations-open/
> 
> On 11 May 2016 at 20:07, Dave Martin notifications@github.com wrote:
> 
> > Thanks @CEJohnston https://github.com/CEJohnston. Can you provide a
> > list of licences (name and URLs) ? This should be quick to do...
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/nbnuk/als-issues/issues/75#issuecomment-218558672
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/nbnuk/als-issues/issues/75#issuecomment-218691649

## 

Ella Vogel

NBN Trust Project Development Officer

M: 07506 863 980

E: ellavogel.nbn@gmail.com

NBN website: www.nbn.org.uk

NBN Gateway: http://data.nbn.org.uk

 [image: NBN-Logo-153x80]

_NBN Trust_ - Registered in England and Wales - Company no.3963387 -
Registered charity no. 1082163.

Registered office of the NBN Trust: Broadway Business Centre, 32a Stoney
Street, Lace Market, Nottingham NG1 1LL

**Comment by djtfmartin** [comment]
This is done, although a check on each data resource is probably advised.

Theres a list here of resources with licence details here:

http://registry.als.scot/dataResource/list
