### ISSUE TITLE
Admins can't delete annotations

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#751]
Would you make it possible for admins to delete annotations, please?

I would like to delete this annotation: https://records.nbnatlas.org/occurrences/aeb7a5dd-1beb-434c-913a-eabfd29812d7

**Comment by reupost** [comment]
Done. Previously it was only possible for admins to delete verification entries for an annotation, so this is a specific change to the business rules.

**Comment by sophiathirza** [comment]
ah, sorry. I wasn't sure - but I think it's important that admins can delete annotations, in case of spam.

**Comment by sophiathirza** [comment]
looks good - thanks.
