### ISSUE TITLE
Error downloading facet result from records page filter

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#753]
I tried to download the list of data providers for this record search:

https://records-ws.nbnatlas.org/occurrences/facets/download?q=*%3A*&fq=geospatial_kosher%3Atrue&lat=56.70436&lon=-3.729711&radius=5.0%20AND%20geospatial_kosher:true&facets=data_provider_uid&count=true&lookup=true

using the download button in the facet dialogue box:
![image](https://user-images.githubusercontent.com/1651015/60492686-c5992700-9cab-11e9-8043-9b66d6d73ca9.png)

The error was: The request sent by the client was syntactically incorrect.

**Comment by reupost** [comment]
Could you provide the URL for the records search, please? There is something wrong with the parameters that are listed above: if you remove the '%20AND%20geospatial_kosher:true' text it works correctly (geospatial_kosher is filtered earlier in the fq clause), so I need to figure out how that parameter was included

**Comment by sophiathirza** [comment]
That is the url for the record search - it's because I did a location search first and then viewed the records. The locations search must add the geospatial_kosher bit... really don't like that parameter name

**Comment by sophiathirza** [comment]
thanks.
