### ISSUE TITLE
Error searching by supplied name in species list

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#756]
I just tried to search for Pipistrellus in the England SS list (https://lists.nbnatlas.org/speciesListItem/list/dr2047#list) and got the following error:

Unable to retrieve species list items. Please let us know if this error persists. <br>Error:<br>Hibernate operation: could not extract ResultSet; bad SQL grammar [n/a]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'specieslist.specieslis2_.item_order' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

I tried a couple of other lists and got the same error.

**Comment by reupost** [comment]
Should be fixed now.

**Comment by sophiathirza** [comment]
brilliant, thanks.
