### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#757]
I get the following error: 
![image](https://user-images.githubusercontent.com/1651015/61270667-a36ed100-a7a2-11e9-95ee-5e107ed077d3.png)

I tried a couple of custom downloads yesterday evening and the emails haven't arrived. I tried a simple format download this morning and get the error above.

**Comment by reupost** [comment]
This should be resolved now. We had failure on 2 of the Cassandra nodes, so custom and DwC downloads were failing, and had filled up the queue. We should look at better ways of monitoring Cassandra and/or review the queuing mechanism for downloads.
This may have been triggered by the extensive ad-hoc data deletes last week (the stalled downloads dated from 11 July)

**Comment by sophiathirza** [comment]
thanks.
