### ISSUE TITLE
Run Time Error in the habitat map

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#76]
Habitat map creates a Grails Run Time Error when you attempt to drill down to a habitat page from the EUNIS interactive habitat map. See attached image 

![image](https://cloud.githubusercontent.com/assets/18594564/15181916/b0da2aba-1781-11e6-883f-f837d85cd65d.png)

**Comment by djtfmartin** [comment]
This is fixed
