### ISSUE TITLE
Incorrect image displayed for Ixodes ricinus

### ISSUE THREAD

**Issue by c-van-dierkson** [nbnuk/nbnatlas-issues#761]
A user has advised the image displayed next to Ixodes ricinus is Ixodes scapularis. We will verify this is correct and either remove or replace the correct image when confirmed.

**Comment by sophiathirza** [comment]
The image comes from EoL, so there is every chance that it is incorrect and we should delete the occurrence record. Would you let me know who raised the issue please? I will add the record to the list for deletion.

**Comment by c-van-dierkson** [comment]
@sophiathirza 

The issue was raised by Chris Manning via our Support email account. 

Many thanks

Caroline
