### ISSUE TITLE
January 2020 data processing

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#766]
dr1969
dr1968
dr2121
dr2123
dr2124
dr2125
dr2126
dr2127
dr2128
dr2129
dr2130
dr1827
dr749
dr2116 - missing 54 records from last time

delete records first
dr664
dr1223
dr227
dr953
dr2088
dr1518
dr2078
dr763
dr780
dr793
dr765
dr767
dr766
dr667

**Comment by reupost** [comment]
Loading complete. No errors noted in the logs.
