### ISSUE TITLE
Simplyfy the form for users registering on Atlas

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#77]
Simplyfy the form for registering with the site by making fields such as "remove the 2 reasons for using this site" noncompulsary

**Comment by sophiathirza** [comment]
@GiselleSterry can this be closed?

**Comment by GiselleSterry** [comment]
@sophiathirza  Hi this can be closed. I think its good to have the reasons to help us monitor why people using NBN Atlas. For note new Data Protection regulations are coming in May 2018 so we will have to review the sign up page to make sure we comply. We will need to discuss outside github.
