### ISSUE TITLE
June 2020 Data processing

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#773]
dr794
dr869 - retry as missing records
dr756
dr677
dr700
dr2247
dr2248
dr855
dr1852
dr2140
dr2141
dr742
dr1570
dr1571
dr2142
dr2046
dr1851
dr1915
dr2201
dr1364
dr1572
dr1130
dr2139
dr671
dr1485
dr1290
dr1842
dr2249
dr706
dr1953
dr1158
dr2096
dr1850
dr680
dr1135
dr2250
dr2251
dr2252
dr2177
dr1916
dr2255
dr1954 - DwCA - images. May still be some missing images
dr2232 - a DwCA of 10 images. Let me know how it goes..I never seem to get them right the first time.

Delete first:
dr1929
dr1933
dr1759
dr665
dr676
dr732
dr839
dr1429
dr736
dr731

**Comment by reupost** [comment]
@sophiathirza is this list stable? I just noticed dr731 being added

**Comment by sophiathirza** [comment]
@reupost yes, it's the last dataset that I was waiting for. I just added it and added a comment to the trello card.
