### ISSUE TITLE
Easymap service stop displaying map

### ISSUE THREAD

**Issue by BirenRathod** [nbnuk/nbnatlas-issues#776]
Hello

Easymap service has stopped working. This is consistently happening. Could you please resolve this issue as soon as possible?

We use this service on number of websites at BRC, so continuity of this service is must.

**Comment by sophiathirza** [comment]
Thanks for letting us know. We had some issues yesterday with the web services. Hopefully it is resolved today and Easymaps is back up this morning.

**Comment by BirenRathod** [comment]
Thanks @sophiathirza.
Yes I checked today and it's working fine now.
