### ISSUE TITLE
Interactive map - Charts tab - charts missing

### ISSUE THREAD

**Issue by mikeashworthtech** [nbnuk/nbnatlas-issues#778]
Hi, in the last few days the charts are no longer being displayed by the Charts tab of the Interactive Map. I have tried Microsoft Edge, Google Chrome and Opera with the same result, so I don't think this is a browser issue. Screenshot attached for the query https://records.nbnatlas.org/occurrences/search?q=Argyra+leucocephala#tab_chartsView 
![NBN chart view missing 08Feb21](https://user-images.githubusercontent.com/39989188/107217520-30711f00-6a06-11eb-9034-e9fd88929272.jpg)
Thank,
Mike Ashworth

**Comment by sophiathirza** [comment]
Hi Mike,
Thank you for letting us know. It's not a browser issue, it looks like it's an error on the page. Our developer is investigating now and I will let you know when it is resolved.

Best wishes, Sophia

**Comment by mikeashworthtech** [comment]
Hi Sophia, the chart view is working again now. Thanks to you and your developer for fixing it. Best wishes, Mike

**Comment by mikeashworthtech** [comment]
Closing this now
