### ISSUE TITLE
NBN species loading Issue

### ISSUE THREAD

**Issue by Fenja222222** [nbnuk/nbnatlas-issues#779]
HI
Just using NBN and for the last 2 days cannot load any species data, it comes up with an error message of internal error. This is the only forum I could use to contact NBN. Any ideas?

Cheers

**Comment by sophiathirza** [comment]
Hello,
Thank you for letting us know. Would you send me a bit more information about what you would like to do and I will try and help. I am not sure what you mean by a species loading issue.

If you would prefer to write an email, the support address is support@nbnatlas.org

Best wishes, Sophia

**Comment by Fenja222222** [comment]
Hey Sophia,

So on the NBN Atlas, I can load an area fine but when I go to add to map, species then it loads or processes for ages and an error message comes up! See attached. It's a website issue I'm pretty sure just couldnt find an email address to a support forum so they can sort it! Will also email the email you gave me too! Thank you!

Cheers

Fenja


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by sophiathirza** [comment]
Hi Fenji,
Many thanks for letting us know. There was a problem with one of the servers, which was causing the problem.

The spatial portal is working again,

Best wishes, Sophia
