### ISSUE TITLE
Add link back from Interactive map to Species Search

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#78]
Add link back from Interactive map to Species Search

**Comment by djtfmartin** [comment]
Not sure what this means. Some example links might help.

**Comment by CEJohnston** [comment]
Sure. The request was to be able to effectively be able to press a button to get back to the species search results overview page.  So in the example here (red squirrel distribution) the user would want to be able to easily get to the overview of the red squirrel:

[http://records.als.scot/occurrences/search?q=lsid:NBNSYS0000005108#tab_mapView](url)

**Comment by djtfmartin** [comment]
I don't think this is necessary. Users can use the back button of their browser.

**Comment by CEJohnston** [comment]
Yes - I now realise that this is the case.  Thanks for explanation. @RachelStroud should we retail as a low priority enhancement or close?

**Comment by sophiathirza** [comment]
@CEJohnston can we close this?

**Comment by djtfmartin** [comment]
closing
