### ISSUE TITLE
Species pages

### ISSUE THREAD

**Issue by PeterBrash** [nbnuk/nbnatlas-issues#780]
I’m receiving a blank box where map should be and a ‘counting’ number of records when searching for species for the last two days.

**Comment by sophiathirza** [comment]
Thank you for letting us know, Peter. 

I am sorry for the problems we had with the NBN Atlas last week. The problems are now resolved, but please let me know if you have any further problems with the Atlas.

Best wishes, Sophie

**Comment by sophiathirza** [comment]
Closing, as this has been resolved.
