### ISSUE TITLE
Add functionality to seach by OS grid reference

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#80]
Add functionality to search by OS Grid Squares eg. searching NX927744 would take you to the location for that Grid Reference. 
See also http://www.gridreferencefinder.com/

**Comment by djtfmartin** [comment]
We've got this for 100km, 10km, 1km grids.

e.g.

http://species.als.scot/search?q=NX9274
http://species.als.scot/search?q=NX97

<img width="1440" alt="screenshot 2016-05-12 09 08 54" src="https://cloud.githubusercontent.com/assets/444897/15208047/89e5b032-1821-11e6-99f7-e84a0569f46d.png">

Users can also load the area in the spatial portal and do an area report.

<img width="351" alt="screenshot 2016-05-12 09 12 21" src="https://cloud.githubusercontent.com/assets/444897/15208113/c2c98e50-1821-11e6-9a5a-065ead9f39b1.png">
<img width="494" alt="screenshot 2016-05-12 09 12 43" src="https://cloud.githubusercontent.com/assets/444897/15208116/c49892a8-1821-11e6-89dc-d0a60ad8c1ec.png">
<img width="1192" alt="screenshot 2016-05-12 09 13 03" src="https://cloud.githubusercontent.com/assets/444897/15208119/c6fdd6e8-1821-11e6-9a70-166d3c3c0f03.png">

**Comment by CEJohnston** [comment]
Dave - could you email us all (Rachel, me and Ella) with the above images - I was trying to replicate  a search by grid square and failed.  Thanks.

**Comment by djtfmartin** [comment]
Theres also a facet exposed for 10km grid refs

<img width="1065" alt="screenshot 2016-05-24 15 14 58" src="https://cloud.githubusercontent.com/assets/444897/15507153/4f0b4846-21c2-11e6-9a43-532f700c5a21.png">

Im closing this issue. If there is something specific to add, please feel free to re-open.
