### ISSUE TITLE
Still says 'Atlas of Living Australia' under Digitised Records

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#82]
[http://registry.als.scot/public/show/dr219](url)

![image 1](https://cloud.githubusercontent.com/assets/18594564/15210819/f26b8eac-182f-11e6-89b4-8089dd9090e1.png)

**Comment by djtfmartin** [comment]
This is now fixed

"1,707 records can be accessed through the Atlas. This resource was last checked for updated data on 01 Apr 2016. The most recent data was published on 01 Apr 2016."
