### ISSUE TITLE
Change icon to demonstrate that a data partner cannot be mapped

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#91]
Using an icon of Australia to show that collection cant be mapped.  Change to an icon of Scotland (or other icon) 

http://registry.als.scot/

**Comment by RachelStroud** [comment]
@djtfmartin we will source a new icon for this

**Comment by RachelStroud** [comment]
I have spoken to Will about designing a little icon with a line through that indicates that a data partner cannot be mapped on the Atlas registry (see the list here: http://registry.als.scot/)  He is going to see if the little 'a' logo will work when super small.  He will send on to you Christine this pm as Ella and I are out in a meeting 1.30 -4

**Comment by djtfmartin** [comment]
I suggest something generic that can be used for all Atlases (rather than something specific to Scotland)

**Comment by djtfmartin** [comment]
Done

<img width="1115" alt="screenshot 2016-05-19 11 36 54" src="https://cloud.githubusercontent.com/assets/444897/15390851/114dbf8a-1db6-11e6-8eb2-c6e5bca40b82.png">

**Comment by RachelStroud** [comment]
Fantastic, thanks Dave!
