### ISSUE TITLE
Scotland's collections & data partners - link to collection type

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#94]
How do we tag datasets and data partners with the categories on the left hand side?

Fauna - Mammals, birds, reptiles, fish, amphibians and invertebrates.
Insects - Insects, spiders, mites and some other arthropods.
Microorganisms - Protists, bacteria, viruses, microfungi and microalgae.
Plants- Vascular plants, algae, fungi, lichens and bryophytes.

**Comment by djtfmartin** [comment]
This is done using the "keywords" field in the data partners admin page:

<img width="816" alt="screenshot 2016-05-19 11 38 39" src="https://cloud.githubusercontent.com/assets/444897/15390902/4636741c-1db6-11e6-9fd7-4f541b53194c.png">

**Comment by RachelStroud** [comment]
Fantastic, thanks Dave! 

Learning SO much this week - will sort out at this end
