### ISSUE TITLE
Explore your area predefined radius - expand radii options

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#96]
Expand the options to 'Display records in a  xx km radius' to have a user defined radius.

This will enable us to expand the options from 1, 5 and 10km  

http://records.als.scot/explore/your-area#56.998999|-4.505722999999989|11|ALL_SPECIES

**Comment by djtfmartin** [comment]
Good idea.

FWIW - Users can specify any radius in spatial portal.

**Comment by sophiathirza** [comment]
as part of #354 2 km radius has been added.

**Comment by c-van-dierkson** [comment]
Jo confirms to close.

**Comment by sophiathirza** [comment]
@c-van-dierkson we had a request recently to add more options. I added a Trello card for it.

**Comment by c-van-dierkson** [comment]
https://trello.com/c/fFWbYPTe/347-add-01km-and-or-05km-search-radius-to-location-search

For reference
