### ISSUE TITLE
Spatial layer: upload SWT reserve boundary file

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#97]
Add Scottish Wildlife Trust reserve boundary file (SWT_reserves.shp). Uploaded to S3.  The SWT are speaking at the launch - could the file be uploaded before then?

**Comment by djtfmartin** [comment]
Done.

<img width="1347" alt="screenshot 2016-05-24 16 18 12" src="https://cloud.githubusercontent.com/assets/444897/15509354/22c3b0bc-21cb-11e6-87d1-1ebba7c9b883.png">
