### ISSUE TITLE
Hyperlinks in Alert email results go to ALA

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#99]
When an email is sent out resulting from an alert being triggered the hyperlinks in the table go to the Atlas of Living Australia - recorded by Rachel

**Comment by djtfmartin** [comment]
Do we know what type of alert this was ? New dataset, new records ?

I think Ive found & fixed this bug for new datasets.

**Comment by djtfmartin** [comment]
This is fixed in nbnatlas.org
